; GOOD 6 - CELDUIN

WaterTransparency
  ReflectionPlaneZ = 77.0;
  ReflectionOn = Yes
End

; Weather
Weather

  HardwareFogColor = R:220 G:226 B:235

  HardwareFogEnable = Yes

  HardwareFogStart = 400

  HardwareFogEnd = 3000

End

;-----------------------------------------------------------------

AIData

  LowLodTreeName = TreeLowLODIronHills

END

;-----------------------------------------------------------------

Object MordorFortress
	KindOf              = PRELOAD COMMANDCENTER VITAL_FOR_BASE_SURVIVAL STRUCTURE IMMOBILE CASTLE_KEEP MP_COUNT_FOR_VICTORY SELECTABLE FS_FACTORY AUTO_RALLYPOINT MADE_OF_WOOD SCORE DOZER_FACTORY
End

;----------------------------------------------------------------

;Objectives
MissionObjectiveList

     MissionObjectiveTag         = SCRIPT:OBJECTIVE_G06_01	; Reach Dain's Army

     MissionObjectiveTag         = SCRIPT:OBJECTIVE_G06_02	; Repel Mumakil

     MissionObjectiveTag         = SCRIPT:OBJECTIVE_G06_03	; Cross Shallows

     MissionObjectiveTag         = SCRIPT:OBJECTIVE_G06_04	; Destroy Mordor Fortress

     BonusMissionObjectiveTag    = SCRIPT:OBJECTIVE_G06_B01   ; Rescue Men of Dale

     BonusMissionObjectiveTag    = SCRIPT:OBJECTIVE_G06_B02   ; Capture Tech Buildings

     BonusMissionObjectiveTag    = SCRIPT:OBJECTIVE_G06_B03   ; Dain Survives

     BonusMissionObjectiveTag    = SCRIPT:OBJECTIVE_G06_B04   ; Mordor Catapults

End

Rank 1
    SkillPointsNeededDefault        = 0
    SkillPointsNeededCampaign        = 0 
    SciencePurchasePointsGranted    = 55
End

;Evil Faction Balancing

Weapon EvilShipRangedBombardWeapon

	AttackRange				= 400
	MinimumAttackRange			= 10
	DelayBetweenShots			= 3000

End

Weapon MordorCatapultRock 

	WeaponSpeed		= 201        
	MinWeaponSpeed		= 201
	HitPercentage       	= 50
	ScatterRadius       	= 10
End

Object MordorHaradrimArcher

	VisionRange = 600;336.0

End

;Object DwarvenPorter
;	CommandSet = DwarvenPorterCommandSet_LotREra
;End

;Object DwarvenAssembly
;	CommandSet = DwarvenAssemblyCommandSetLevel1_Hobbit
	
 ; ReplaceModule ModuleTag_DwarvenArcheryRangeLevel2CommandSet	
 ; Behavior = CommandSetUpgrade ModueTag_AssemblyLevel2CommandSet
;		TriggeredBy			= Upgrade_DwarvenArcheryRangeLevel2
;		CommandSet			= DwarvenAssemblyCommandSetLevel2_Hobbit
;	End
;End	
;  ReplaceModule ModuleTag_DwarvenArcheryRangeLevel3CommandSet	
 ; Behavior = CommandSetUpgrade ModueTag_AssmblyLevel3CommandSet
;		TriggeredBy			= Upgrade_DwarvenArcheryRangeLevel3	
;		CommandSet			= DwarvenAssemblyCommandSetLevel3_Hobbit
;	End 
;End
;End


Object DwarvenBrand
ReplaceModule ModuleTag_Leadership
Behavior = AttributeModifierAuraUpdate ModuleTag_LeadershipX
		StartsActive	= No
		TriggeredBy		= Upgrade_ObjectLevel1
		BonusName		= HaldirLeadership
		RefreshDelay	= 2000
		Range			= 200
		ObjectFilter	= ANY +DaleGuard +MenofDaleSwordsman +DwarvenMenOfDale +DaleCavalry +DaleCavalry_Summoned +DaleCavalry_Brand +LaketownSpearmen +DwarvenLaketownBowmen +LaketownGuard ALLIES
	End
End
End

CommandSet CommandSetInnCelduin
	1	= Command_ConstructDaleCavalryHorde
End

Object Inn_old
	ReplaceModule ModuleTag_CommandSetDwarven
	Behavior = CommandSetUpgrade ModuleTag_CommandSetDwarven_NEW
		TriggeredBy	= Upgrade_DwarfFaction
		CommandSet	= CommandSetInnCelduin
	End
END
	ReplaceModule ModuleTag_CommandSetGondor
	Behavior = CommandSetUpgrade ModuleTag_CommandSetMen_NEW
		TriggeredBy	= Upgrade_MenFaction
		CommandSet	= CommandSetInnCelduin
	End
END
	ReplaceModule ModuleTag_CommandSetRivendell
	Behavior = CommandSetUpgrade ModuleTag_CommandSetRivendell_NEW
		TriggeredBy	= Upgrade_ArnorFaction
		CommandSet	= CommandSetInnCelduin
	End
END
	ReplaceModule ModuleTag_CommandSetElven
	Behavior = CommandSetUpgrade ModuleTag_CommandSetElven_NEW
		TriggeredBy	= Upgrade_ElfFaction
		CommandSet	= CommandSetInnCelduin
	End
END
	ReplaceModule ModuleTag_CommandSetIsengard
	Behavior = CommandSetUpgrade ModuleTag_CommandSetIsengard_NEW
		TriggeredBy	= Upgrade_IsengardFaction
		CommandSet	= CommandSetInnCelduin
	End
END
	ReplaceModule ModuleTag_CommandSetMordor
	Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_NEW
		TriggeredBy	= Upgrade_MordorFaction
		CommandSet	= CommandSetInnCelduin
	End
END
	ReplaceModule ModuleTag_CommandSetWild
	Behavior = CommandSetUpgrade ModuleTag_CommandSetWild_NEW
		TriggeredBy	= Upgrade_WildFaction
		CommandSet	= CommandSetInnCelduin
	End
END
	ReplaceModule ModuleTag_CommandSetAngmar
	Behavior = CommandSetUpgrade ModuleTag_CommandSetAngmar_NEW
		TriggeredBy	= Upgrade_AngmarFaction
		CommandSet	= CommandSetInnCelduin
	End
END
End

;-------------------------------------------------------------------------------------------------------
; BFME 2 BUILDING EDITS
;-------------------------------------------------------------------------------------------------------

CommandSet DwarvenFortressCommandSet_LotREraX
	InitialVisible = 6
	//Main Menu
	1	= Command_ConstructDwarvenPorter
	2   = Command_SelectUpgradesDwarvenFortress
	3	= Command_FireWeaponDwarvenFortressOilCasks
	4	= Command_HornsoftheGate
	5	= Command_Sell
	//Upgardes Menu
	7	= Command_PurchaseUpgradeDwarvenFortressBanners
	8	= Command_PurchaseUpgradeDwarvenHornsoftheGate
	9	= Command_PurchaseUpgradeDwarvenFortressSiegeKegs
	;10	= Command_PurchaseUpgradeDwarvenFortressOilCasks ;Command_PurchaseUpgradeDwarvenFortressSiegeKegs
	10	= Command_PurchaseUpgradeDwarvenFortressFlamingMunitions
	11	= Command_PurchaseUpgradeDwarvenFortressDwarvenStonework
	12	= Command_RadialBack
	33	= Command_RadialBack
End

Object DwarvenFortress
CommandSet = DwarvenFortressCommandSet_LotREraX
End

Object DwarvenFortressCitadel
CommandSet = DwarvenFortressCommandSet_LotREraX
RemoveModule ModueTag_LotREraCommandSet
End

;-------------------------------------------------------------------------------------------------------
; BFME 2 SPELLBOOK
;-------------------------------------------------------------------------------------------------------

;-------5 points
Science SCIENCE_ElvenGifts
  PrerequisiteSciences = SCIENCE_MEN OR SCIENCE_GOOD
  SciencePurchasePointCost = GOOD_RANK_1_COST
  SciencePurchasePointCostMP = 5
  IsGrantable = Yes
End
Science SCIENCE_Heal
  PrerequisiteSciences = SCIENCE_GOOD OR SCIENCE_MEN OR SCIENCE_ELVES OR SCIENCE_DWARVES OR SCIENCE_ARNOR
  SciencePurchasePointCost = GOOD_RANK_1_COST
  SciencePurchasePointCostMP = 5
  IsGrantable = Yes
End
Science SCIENCE_RallyingCall
  PrerequisiteSciences = SCIENCE_MEN OR SCIENCE_GOOD ;SCIENCE_EnshroudingMistSP
  SciencePurchasePointCost = GOOD_RANK_1_COST
  SciencePurchasePointCostMP = 5
  IsGrantable = Yes
End
Science SCIENCE_RallyingCallMP
  PrerequisiteSciences = SCIENCE_MEN OR SCIENCE_GOOD ;SCIENCE_EnshroudingMistSP
  SciencePurchasePointCost = GOOD_RANK_1_COST
  SciencePurchasePointCostMP = 5
  IsGrantable = Yes
End
;-------10 points
Science SCIENCE_CampaignElvenWood
  PrerequisiteSciences = SCIENCE_GOOD OR SCIENCE_ElvenGifts
  SciencePurchasePointCost = GOOD_RANK_2_COST
  SciencePurchasePointCostMP = 10
  IsGrantable = Yes
End
Science SCIENCE_CampaignRebuild
  PrerequisiteSciences = SCIENCE_GOOD OR SCIENCE_ElvenGifts OR SCIENCE_Heal
  SciencePurchasePointCost = GOOD_RANK_2_COST
  SciencePurchasePointCostMP = 10
  IsGrantable = Yes
End
Science SCIENCE_UndermineErebor
  PrerequisiteSciences = SCIENCE_GOOD SCIENCE_Heal OR SCIENCE_RallyingCall
  SciencePurchasePointCost = GOOD_RANK_2_COST
  SciencePurchasePointCostMP = 10
  IsGrantable = Yes
End
Science SCIENCE_CampaignRadagast
  PrerequisiteSciences = SCIENCE_GOOD OR SCIENCE_RallyingCall OR SCIENCE_RallyingCallMP
  SciencePurchasePointCost = GOOD_RANK_2_COST
  SciencePurchasePointCostMP = 10
  IsGrantable = Yes
End
;-------15 points
Science SCIENCE_CampaignArrowVolley
  PrerequisiteSciences = SCIENCE_GOOD OR SCIENCE_CampaignElvenWood OR SCIENCE_CampaignRebuild
  SciencePurchasePointCost = GOOD_RANK_3_COST
  SciencePurchasePointCostMP = 15
  IsGrantable = Yes
End
Science SCIENCE_CampaignCloudBreak
  PrerequisiteSciences = SCIENCE_GOOD OR SCIENCE_CampaignRebuild OR SCIENCE_UndermineErebor
  SciencePurchasePointCost = GOOD_RANK_3_COST
  SciencePurchasePointCostMP = 15
  IsGrantable = Yes
End
Science SCIENCE_CampaignEagleAllies
  PrerequisiteSciences = SCIENCE_GOOD OR SCIENCE_UndermineErebor OR SCIENCE_CampaignRadagast
  SciencePurchasePointCost = GOOD_RANK_3_COST
  SciencePurchasePointCostMP = 15
  IsGrantable = Yes
End
;-------25 points
Science SCIENCE_Earthquake
  PrerequisiteSciences = SCIENCE_GOOD OR SCIENCE_CampaignArrowVolley OR SCIENCE_CampaignCloudBreak
  SciencePurchasePointCost = GOOD_RANK_4_COST
  SciencePurchasePointCostMP = 25
  IsGrantable = Yes
End
Science SCIENCE_Flood
  PrerequisiteSciences = SCIENCE_GOOD OR SCIENCE_CampaignEagleAllies OR SCIENCE_CampaignCloudBreak
  SciencePurchasePointCost = GOOD_RANK_4_COST
  SciencePurchasePointCostMP = 25
  IsGrantable = Yes
End

CommandSet GoodSpellBookCommandSetX
	1 = Command_SpellBookElvenGifts
	2 = Command_SpellBookHeal
	3 = Command_SpellBookRallyingCall

	4 = Command_SpellBookCampaignElvenWood
	5 = Command_SpellBookCampaignRebuild
	6 = Command_SpellBookUndermineErebor
	7 = Command_SpellBookCampaignRadagast

	8 = Command_SpellBookCampaignArrowVolley
	9 = Command_SpellBookCampaignCloudBreak
	10 = Command_SpellBookCampaignEagleAllies

	11 = Command_SpellBookEarthquake
	12 = Command_SpellBookFlood
End



CommandSet GoodSpellStoreCommandSetX							; Good campaign
	1 = Command_PurchaseSpellElvenGifts
	2 = Command_PurchaseSpellHeal
	3 = Command_PurchaseSpellRallyingCallSP

	4 = Command_PurchaseSpellCampaignElvenWood
	5 = Command_PurchaseSpellCampaignRebuild
	6 = Command_PurchaseSpellUndermineErebor
	7 = Command_PurchaseSpellCampaignRadagast

	8 = Command_PurchaseSpellCampaignArrowVolley
	9 = Command_PurchaseSpellCampaignCloudBreak
	10 = Command_PurchaseSpellCampaignEagleAllies

	11 = Command_PurchaseSpellEarthquake
	12 = Command_PurchaseSpellFlood
End


Object GoodSpellBook
CommandSet = GoodSpellBookCommandSetX
End

;-------------------------------------------------------------------------------------------------
;PLAYER TEMPLATE
;-------------------------------------------------------------------------------------------------

PlayerTemplate FactionMen

StartingBuilding = NONE
StartingUnit0 = NONE
StartingUnit1 = NONE
StartingUnit2 =  NONE
StartingUnitOffset2 = X:300 Y:0 Z:0
StartingUnit3 = NONE
StartingUnitOffset3 = X:0 Y:300 Z:0
StartingUnit4 = NONE
StartingUnitOffset4 = X:-300 Y:0 Z:0
StartingUnit7 = NONE
StartingUnitOffset7 = X:0 Y:-300 Z:0
StartMoney = 0
BuildableHeroesMP		= NONE
DefaultPlayerAIType		= NONE
	IntrinsicSciences		= SCIENCE_GOOD
	IntrinsicSciencesMP 		= SCIENCE_GOOD
	SpellBook			= GoodSpellBook
	SpellBookMp			= GoodSpellBook
	PurchaseScienceCommandSet	= GoodSpellStoreCommandSetX
	PurchaseScienceCommandSetMP	= GoodSpellStoreCommandSetX
End

PlayerTemplate FactionDwarves

StartingBuilding = NONE
StartingUnit0 = NONE
StartingUnit1 = NONE
StartingUnit2 =  NONE
StartingUnitOffset2 = X:300 Y:0 Z:0
StartingUnit3 = NONE
StartingUnitOffset3 = X:0 Y:300 Z:0
StartingUnit4 = NONE
StartingUnitOffset4 = X:-300 Y:0 Z:0
StartingUnit7 = NONE
StartingUnitOffset7 = X:0 Y:-300 Z:0
StartMoney = 0
BuildableHeroesMP		= NONE
DefaultPlayerAIType		= NONE
	IntrinsicSciences		= SCIENCE_GOOD
	IntrinsicSciencesMP 		= SCIENCE_GOOD
	SpellBook			= GoodSpellBook
	SpellBookMp			= GoodSpellBook
	PurchaseScienceCommandSet	= GoodSpellStoreCommandSetX
	PurchaseScienceCommandSetMP	= GoodSpellStoreCommandSetX
End

PlayerTemplate FactionElves

StartingBuilding = NONE
StartingUnit0 = NONE
StartingUnit1 = NONE
StartingUnit2 =  NONE
StartingUnitOffset2 = X:300 Y:0 Z:0
StartingUnit3 = NONE
StartingUnitOffset3 = X:0 Y:300 Z:0
StartingUnit4 = NONE
StartingUnitOffset4 = X:-300 Y:0 Z:0
StartingUnit7 = NONE
StartingUnitOffset7 = X:0 Y:-300 Z:0
StartMoney = 0
BuildableHeroesMP		= NONE
DefaultPlayerAIType		= NONE
	IntrinsicSciences		= SCIENCE_GOOD
	IntrinsicSciencesMP 		= SCIENCE_GOOD
	SpellBook			= GoodSpellBook
	SpellBookMp			= GoodSpellBook
	PurchaseScienceCommandSet	= GoodSpellStoreCommandSetX
	PurchaseScienceCommandSetMP	= GoodSpellStoreCommandSetX
End

PlayerTemplate FactionWild

StartingBuilding = NONE
StartingUnit0 = NONE
StartingUnit1 = NONE
StartingUnit2 =  NONE
StartingUnitOffset2 = X:300 Y:0 Z:0
StartingUnit3 = NONE
StartingUnitOffset3 = X:0 Y:300 Z:0
StartingUnit4 = NONE
StartingUnitOffset4 = X:-300 Y:0 Z:0
StartingUnit7 = NONE
StartingUnitOffset7 = X:0 Y:-300 Z:0
StartMoney = 0
BuildableHeroesMP		= NONE
DefaultPlayerAIType		= NONE
	IntrinsicSciences		= SCIENCE_GOOD
	IntrinsicSciencesMP 		= SCIENCE_GOOD
	SpellBook			= GoodSpellBook
	SpellBookMp			= GoodSpellBook
	PurchaseScienceCommandSet	= GoodSpellStoreCommandSetX
	PurchaseScienceCommandSetMP	= GoodSpellStoreCommandSetX
End


PlayerTemplate FactionMordor

StartingBuilding = NONE
StartingUnit0 = NONE
StartingUnit1 = NONE
StartingUnit2 =  NONE
StartingUnitOffset2 = X:300 Y:0 Z:0
StartingUnit3 = NONE
StartingUnitOffset3 = X:0 Y:300 Z:0
StartingUnit4 = NONE
StartingUnitOffset4 = X:-300 Y:0 Z:0
StartingUnit7 = NONE
StartingUnitOffset7 = X:0 Y:-300 Z:0
StartMoney = 0
BuildableHeroesMP		= NONE
DefaultPlayerAIType		= NONE
	IntrinsicSciences		= SCIENCE_GOOD
	IntrinsicSciencesMP 		= SCIENCE_GOOD
	SpellBook			= GoodSpellBook
	SpellBookMp			= GoodSpellBook
	PurchaseScienceCommandSet	= GoodSpellStoreCommandSetX
	PurchaseScienceCommandSetMP	= GoodSpellStoreCommandSetX
End


PlayerTemplate FactionIsengard

StartingBuilding = NONE
StartingUnit0 = NONE
StartingUnit1 = NONE
StartingUnit2 =  NONE
StartingUnitOffset2 = X:300 Y:0 Z:0
StartingUnit3 = NONE
StartingUnitOffset3 = X:0 Y:300 Z:0
StartingUnit4 = NONE
StartingUnitOffset4 = X:-300 Y:0 Z:0
StartingUnit7 = NONE
StartingUnitOffset7 = X:0 Y:-300 Z:0
StartMoney = 0
BuildableHeroesMP		= NONE
DefaultPlayerAIType		= NONE
	IntrinsicSciences		= SCIENCE_GOOD
	IntrinsicSciencesMP 		= SCIENCE_GOOD
	SpellBook			= GoodSpellBook
	SpellBookMp			= GoodSpellBook
	PurchaseScienceCommandSet	= GoodSpellStoreCommandSetX
	PurchaseScienceCommandSetMP	= GoodSpellStoreCommandSetX
End

PlayerTemplate FactionArnor

StartingBuilding = NONE
StartingUnit0 = NONE
StartingUnit1 = NONE
StartingUnit2 =  NONE
StartingUnitOffset2 = X:300 Y:0 Z:0
StartingUnit3 = NONE
StartingUnitOffset3 = X:0 Y:300 Z:0
StartingUnit4 = NONE
StartingUnitOffset4 = X:-300 Y:0 Z:0
StartingUnit7 = NONE
StartingUnitOffset7 = X:0 Y:-300 Z:0
StartMoney = 0
BuildableHeroesMP		= NONE
DefaultPlayerAIType		= NONE
	IntrinsicSciences		= SCIENCE_GOOD
	IntrinsicSciencesMP 		= SCIENCE_GOOD
	SpellBook			= GoodSpellBook
	SpellBookMp			= GoodSpellBook
	PurchaseScienceCommandSet	= GoodSpellStoreCommandSetX
	PurchaseScienceCommandSetMP	= GoodSpellStoreCommandSetX
End

PlayerTemplate FactionCivilian
StartingBuilding = NONE
StartingUnit0 = NONE
StartingUnit1 = NONE
StartingUnit2 =  NONE
StartingUnitOffset2 = X:300 Y:0 Z:0
StartingUnit3 = NONE
StartingUnitOffset3 = X:0 Y:300 Z:0
StartingUnit4 = NONE
StartingUnitOffset4 = X:-300 Y:0 Z:0
StartingUnit7 = NONE
StartingUnitOffset7 = X:0 Y:-300 Z:0
StartMoney = 0
DefaultPlayerAIType		= NONE
	IntrinsicSciences		= SCIENCE_GOOD
	IntrinsicSciencesMP 		= SCIENCE_GOOD
	SpellBook			= GoodSpellBook
	SpellBookMp			= GoodSpellBook
	PurchaseScienceCommandSet	= GoodSpellStoreCommandSetX
	PurchaseScienceCommandSetMP	= GoodSpellStoreCommandSetX
End

PlayerTemplate FactionRohan

StartingBuilding = NONE
StartingUnit0 = NONE
StartingUnit1 = NONE
StartingUnit2 =  NONE
StartingUnitOffset2 = X:300 Y:0 Z:0
StartingUnit3 = NONE
StartingUnitOffset3 = X:0 Y:300 Z:0
StartingUnit4 = NONE
StartingUnitOffset4 = X:-300 Y:0 Z:0
StartingUnit7 = NONE
StartingUnitOffset7 = X:0 Y:-300 Z:0
StartMoney = 0
BuildableHeroesMP		= NONE
DefaultPlayerAIType		= NONE
	IntrinsicSciences		= SCIENCE_GOOD
	IntrinsicSciencesMP 		= SCIENCE_GOOD
	SpellBook			= GoodSpellBook
	SpellBookMp			= GoodSpellBook
	PurchaseScienceCommandSet	= GoodSpellStoreCommandSetX
	PurchaseScienceCommandSetMP	= GoodSpellStoreCommandSetX
End
