;; ---------------------------------
;;         FALLING SNOW
;; ---------------------------------
;; This code will automatically put in falling snow.  The denser the snow, the more laggy the map.

Weather
    SnowEnabled = Yes               ; enable/disable snow on the map.
    IsSnowing = Yes               ; is it snowing today?
    SnowTexture = Exraindrop.tga   ;;;GtOSnowFlake.tga    ;;;Original EA Snow Texture: EXSnowFlake2.tga;; m@tt: ExCloud02.tga
    SnowBoxHeight = 400             ; height from which snow falls
    SnowSpacing = 15             ; snow spacing -- less means more; 30
    NumberTiles = 4

    SnowAmplitude = 5              ; amount of side-to-side movement. 
    SnowFrequencyScaleX = 0.01        ; speed of side-to-side wave movement.
    SnowFrequencyScaleY = 0.005         ; speed of side-to-side wave movement. 

    SnowPointSize = 2               ; scale the size of snow particles.
    SnowMinPointSize = 4           ; min point size
    SnowMaxPointSize = 8           ; max point size

    SnowPointSprites = No           ; set to "no" for point-sprite emulation.
    SnowQuadSize = 3               ; scale the size of snow particles when using point-sprite emulation.

    SnowSpeed = 100               ; speed at which snow falls; 60
    ;;;SnowXYSpeed = X:40 Y:25



	HardwareFogColor = R:55 G:70 B:80 
	HardwareFogEnable = Yes
	HardwareFogStart = 400
	HardwareFogEnd = 6000 ;2200
	

End

;;;;


Object GondorBuildingIthilien02
 
  Geometry              = BOX
  GeometryMajorRadius   = 0.01
  GeometryMinorRadius   = 0.01
  GeometryHeight        = 0.01
  GeometryIsSmall       = No
  Shadow                = SHADOW_VOLUME
  BuildCompletion     = PLACED_BY_PLAYER
End


Object GondorBuildingIthilien03
 
  Geometry              = BOX
  GeometryMajorRadius   = 0.01
  GeometryMinorRadius   = 0.01
  GeometryHeight        = 0.01
  GeometryIsSmall       = No
  Shadow                = SHADOW_VOLUME
  BuildCompletion     = PLACED_BY_PLAYER
End


Object GondorBuildingIthilien05
 
  Geometry              = BOX
  GeometryMajorRadius   = 0.01
  GeometryMinorRadius   = 0.01
  GeometryHeight        = 0.01
  GeometryIsSmall       = No
  Shadow                = SHADOW_VOLUME
  BuildCompletion     = PLACED_BY_PLAYER
End


Object GondorBuildingIthilien13
 
  Geometry              = BOX
  GeometryMajorRadius   = 0.01
  GeometryMinorRadius   = 0.01
  GeometryHeight        = 0.01
  GeometryIsSmall       = No
  Shadow                = SHADOW_VOLUME
  BuildCompletion     = PLACED_BY_PLAYER
End


Object Object GondorBuildingIthilien14
 
  Geometry              = BOX
  GeometryMajorRadius   = 0.01
  GeometryMinorRadius   = 0.01
  GeometryHeight        = 0.01
  GeometryIsSmall       = No
  Shadow                = SHADOW_VOLUME
  BuildCompletion     = PLACED_BY_PLAYER
End


Object GondorBuildingIthilien15
 
  Geometry              = BOX
  GeometryMajorRadius   = 0.01
  GeometryMinorRadius   = 0.01
  GeometryHeight        = 0.01
  GeometryIsSmall       = No
  Shadow                = SHADOW_VOLUME
  BuildCompletion     = PLACED_BY_PLAYER
End


Object GondorBuildingIthilien17
 
  Geometry              = BOX
  GeometryMajorRadius   = 0.01
  GeometryMinorRadius   = 0.01
  GeometryHeight        = 0.01
  GeometryIsSmall       = No
  Shadow                = SHADOW_VOLUME
  BuildCompletion     = PLACED_BY_PLAYER
End


Object GondorBuildingIthilien19
 
  Geometry              = BOX
  GeometryMajorRadius   = 0.01
  GeometryMinorRadius   = 0.01
  GeometryHeight        = 0.01
  GeometryIsSmall       = No
  Shadow                = SHADOW_VOLUME
  BuildCompletion     = PLACED_BY_PLAYER
End


Object GondorBuildingIthilien21
 
  Geometry              = BOX
  GeometryMajorRadius   = 0.01
  GeometryMinorRadius   = 0.01
  GeometryHeight        = 0.01
  GeometryIsSmall       = No
  Shadow                = SHADOW_VOLUME
  BuildCompletion     = PLACED_BY_PLAYER
End


Object GondorBuildingIthilien28
 
  Geometry              = BOX
  GeometryMajorRadius   = 0.01
  GeometryMinorRadius   = 0.01
  GeometryHeight        = 0.01
  GeometryIsSmall       = No
  Shadow                = SHADOW_VOLUME
  BuildCompletion     = PLACED_BY_PLAYER
End


Object GondorBuildingIthilien30
 
  Geometry              = BOX
  GeometryMajorRadius   = 0.01
  GeometryMinorRadius   = 0.01
  GeometryHeight        = 0.01
  GeometryIsSmall       = No
  Shadow                = SHADOW_VOLUME
  BuildCompletion     = PLACED_BY_PLAYER
End


Object GondorBuildingIthilien45
 
  Geometry              = BOX
  GeometryMajorRadius   = 0.01
  GeometryMinorRadius   = 0.01
  GeometryHeight        = 0.01
  GeometryIsSmall       = No
  Shadow                = SHADOW_VOLUME
  BuildCompletion     = PLACED_BY_PLAYER
End


;;;


Object OsgiliathPlot01
 
  Geometry              = BOX
  GeometryMajorRadius   = 0.01
  GeometryMinorRadius   = 0.01
  GeometryHeight        = 0.01
  GeometryIsSmall       = No
  Shadow                = SHADOW_VOLUME
  BuildCompletion     = PLACED_BY_PLAYER
End


Object OsgiliathRubble01
 
  Geometry              = BOX
  GeometryMajorRadius   = 0.01
  GeometryMinorRadius   = 0.01
  GeometryHeight        = 0.01
  GeometryIsSmall       = No
  Shadow                = SHADOW_VOLUME
  BuildCompletion     = PLACED_BY_PLAYER
End


Object OsgiliathRubble02
 
  Geometry              = BOX
  GeometryMajorRadius   = 0.01
  GeometryMinorRadius   = 0.01
  GeometryHeight        = 0.01
  GeometryIsSmall       = No
  Shadow                = SHADOW_VOLUME
  BuildCompletion     = PLACED_BY_PLAYER
End


Object OsgiliathRubble03
 
  Geometry              = BOX
  GeometryMajorRadius   = 0.01
  GeometryMinorRadius   = 0.01
  GeometryHeight        = 0.01
  GeometryIsSmall       = No
  Shadow                = SHADOW_VOLUME
  BuildCompletion     = PLACED_BY_PLAYER
End


Object OsgiliathRuin08
 
  Geometry              = BOX
  GeometryMajorRadius   = 0.01
  GeometryMinorRadius   = 0.01
  GeometryHeight        = 0.01
  GeometryIsSmall       = No
  Shadow                = SHADOW_VOLUME
  BuildCompletion     = PLACED_BY_PLAYER
End


Object OsgiliathRuin12
 
  Geometry              = BOX
  GeometryMajorRadius   = 0.01
  GeometryMinorRadius   = 0.01
  GeometryHeight        = 0.01
  GeometryIsSmall       = No
  Shadow                = SHADOW_VOLUME
  BuildCompletion     = PLACED_BY_PLAYER
End


Object OsgiliathRuin06
 
  Geometry              = BOX
  GeometryMajorRadius   = 0.01
  GeometryMinorRadius   = 0.01
  GeometryHeight        = 0.01
  GeometryIsSmall       = No
  Shadow                = SHADOW_VOLUME
  BuildCompletion     = PLACED_BY_PLAYER
End


Object OsgiliathRuin07
 
  Geometry              = BOX
  GeometryMajorRadius   = 0.01
  GeometryMinorRadius   = 0.01
  GeometryHeight        = 0.01
  GeometryIsSmall       = No
  Shadow                = SHADOW_VOLUME
  BuildCompletion     = PLACED_BY_PLAYER
End


Object OsgiliathRuin10
 
  Geometry              = BOX
  GeometryMajorRadius   = 0.01
  GeometryMinorRadius   = 0.01
  GeometryHeight        = 0.01
  GeometryIsSmall       = No
  Shadow                = SHADOW_VOLUME
  BuildCompletion     = PLACED_BY_PLAYER
End


Object OsgiliathRuin17
 
  Geometry              = BOX
  GeometryMajorRadius   = 0.01
  GeometryMinorRadius   = 0.01
  GeometryHeight        = 0.01
  GeometryIsSmall       = No
  Shadow                = SHADOW_VOLUME
  BuildCompletion     = PLACED_BY_PLAYER
End


Object OsgiliathRuin18
 
  Geometry              = BOX
  GeometryMajorRadius   = 0.01
  GeometryMinorRadius   = 0.01
  GeometryHeight        = 0.01
  GeometryIsSmall       = No
  Shadow                = SHADOW_VOLUME
  BuildCompletion     = PLACED_BY_PLAYER
End


Object OsgiliathRuin20
 
  Geometry              = BOX
  GeometryMajorRadius   = 0.01
  GeometryMinorRadius   = 0.01
  GeometryHeight        = 0.01
  GeometryIsSmall       = No
  Shadow                = SHADOW_VOLUME
  BuildCompletion     = PLACED_BY_PLAYER
End








;startOfAuto-Generation
;------------------------------------------------------------------------;
;	  ERIADOR REGION 														 ;
;------------------------------------------------------------------------;
Object Inn
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Eriador
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Eriador
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Eriador
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Eriador
		End
	End
End
Object InnDesert
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Eriador
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Eriador
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Eriador
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Eriador
		End
	End
End
Object InnSnow
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Eriador
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Eriador
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Eriador
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Eriador
		End
	End
End
Object Inn_old
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Eriador
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Eriador
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Eriador
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Eriador
		End
	End
End
;endOfAuto-Generation


;==== Auto Generated AI Fix =====;
SkirmishAIData TheSkirmishAIData
    DisableBaseBuilding        = No
    DisableEconomyBuilding     = No
    DisableUnitBuilding        = No
    DisableScienceUpgrading    = No
    DisableUnitUpgrading       = No
    DisableTacticalAI          = No
    DisableTeamBuilding        = No
    DisableWallBuilding        = Yes ;,; No
End
