Weather

	HardwareFogColor = R:165 G:180 B:180
	HardwareFogEnable = Yes
	HardwareFogStart = 400
	HardwareFogEnd = 8000
End


Object AIBaseMarkerBase // THIS IS SPAWNED TO MAKE A TEAM EXIST, ALLOWING UNITS TO BE RECRUITED ONTO IT
RemoveModule ModuleTag_01
AddModule
	Body = ActiveBody ModuleTag_02
		MaxHealth         = 1
	End
End
End

ChildObject PrimaryAIBaseMarker AIBaseMarkerBase // DARK PRESENCE CASTER
	KindOf          = PRELOAD STRUCTURE IMMOBILE AUTO_RALLYPOINT FS_FACTORY IGNORE_FOR_VICTORY IGNORE_FOR_EVA_SPEECH_POSITION NO_COLLIDE UNATTACKABLE NOT_AUTOACQUIRABLE
AddModule
	Behavior = GrantUpgradeCreate ModuleTag_GrantUpgrade
		UpgradeToGrant	= Upgrade_GondorStableLevel2
	End
End
AddModule
	Behavior = AttributeModifierAuraUpdate ModuleTag_DarkPresence
		StartsActive	= Yes
		TriggeredBy		= Upgrade_GondorStableLevel2
		BonusName		= GuldurDarkPresence
		RefreshDelay	= 2000
		Range			= 20000
		ObjectFilter	= ANY +GuldurBrokenRabble +GuldurBrokenRabbleA +GuldurBrokenRabbleB +GuldurBrokenRabbleC +GuldurBrokenRabbleHorde +GuldurOrcArcher +GuldurOrcArcherHorde +GuldurOrcPikeman +GuldurOrcPikemanForBrokenRabble +GuldurOrcPikemanHorde +GuldurOrcArcherHorde_Summoned +GuldurOrcPikemanHorde_Summoned +GuldurBannerOrc +GuldurPikemenArcherComboHorde
	End
End
End

Object IsengardOrthancDoor
RemoveModule ModuleTage_AIGateUpdate
ReplaceModule ModuleTag_GATE
	Behavior = GateOpenAndCloseBehavior ModuleTag_GATEX
		ResetTimeInMilliseconds = 12200 ; important! this must be longer than the gates animation, ir it will twitch
		OpenByDefault = Yes
		PercentOpenForPathing = 50
		//Proxy = IsengardOrthancDoorProxy
		SoundOpeningGateLoop = GateOpenStart
		SoundClosingGateLoop = GateCloseStart
		SoundFinishedOpeningGate = GateOpenEnd
		SoundFinishedClosingGate = GateCloseEnd
		TimeBeforePlayingOpenSound = 9500
		TimeBeforePlayingClosedSound = 9500
	End
End
ArmorSet
		Conditions        = None
;		Armor             = CitadelFortressArmor
		Armor             = CastleGateArmorAttackable ; DefaultWallArmor
		DamageFX          = GateDamageFX
	End
End

; -----------------------------------------------------------------------------------------------------------------------------
; MORDOR INFANTRY SETUP
; -----------------------------------------------------------------------------------------------------------------------------

Object MordorSiegeWorks

	CommandSet = MordorSiegeWorksCommandSetLevel1_ForMP

	ReplaceModule ModuleTag_MordorSiegeWorksLevel2
		Behavior = CommandSetUpgrade ModuleTag_MordorSiegeWorksLevel2_ForMP
			TriggeredBy		= Upgrade_MordorSiegeWorksLevel2
			ConflictsWith	= Upgrade_MordorSiegeWorksLevel3
			CommandSet		= MordorSiegeWorksCommandSetLevel2_ForMP
		End
	End
	
	ReplaceModule ModuleTag_MordorSiegeWorksLevel3
		Behavior = CommandSetUpgrade ModuleTag_MordorSiegeWorksLevel3_ForMP
			TriggeredBy		= Upgrade_MordorSiegeWorksLevel3
			CommandSet		= MordorSiegeWorksCommandSetLevel3_ForMP
		End
	End
End
	
;///////////////////////////////////////////////////////////////////////////	

Object IsengardSiegeWorks
	
	CommandSet = IsengardSiegeWorksCommandSetLevel1_ForMP
	
	ReplaceModule ModuleTag_IsengardSiegeWorksLevel2CommandSet
		Behavior = CommandSetUpgrade ModuleTag_IsengardSiegeWorksLevel2CommandSet_ForMP
			TriggeredBy		= Upgrade_StructureLevel2
			ConflictsWith	= Upgrade_StructureLevel3
			CommandSet		= IsengardSiegeWorksCommandSetLevel2_ForMP
		End
	End
	
	ReplaceModule ModuleTag_IsengardSiegeWorksLevel3CommandSet
		Behavior = CommandSetUpgrade ModuleTag_IsengardSiegeWorksLevel3CommandSet_ForMP
			TriggeredBy		= Upgrade_StructureLevel3
			CommandSet		= IsengardSiegeWorksCommandSetLevel3_ForMP
		End
	End
End

Object MordorSiegeTower
	ReplaceModule ModuleTag_07
		Behavior = SiegeDeploySpecialPower ModuleTag_WallSearchDistanceLocal
	    	SpecialPowerTemplate = SpecialAbilitySiegeDeploy
            LowerDelay = 1200
            RaiseDelay = 2000
            EvacuatePassengersOnDeploy = Yes
            SkipAdjustPosition = Yes ; have to skip the path find adjust or it this will not go to the right docking position
            WallSearchDistance = 99999.0
 		End
	End
End

Armor SiegeTowerArmor
  Armor = DEFAULT          10%     ;this sets the level for all nonspecified damage types
  Armor = CRUSH           15% ;25%     ;horseman damage
  Armor = SLASH           25% ;1%     ;soldier damage
  Armor = SIEGE		  30%     ;war machine attack
  Armor = STRUCTURAL	  30%	   ;Structural damage (Ent rocks)
  Armor = FLAME            20% ;10%     ;fire attack
  Armor = PIERCE            1%     ;archer damage 
  Armor = HERO		   10%     ;hero damage
  Armor = MAGIC		  50%     ;hero damage
  Armor = HERO_RANGED       1%     ;Hero bow damage     
End
;startOfAuto-Generation
;------------------------------------------------------------------------;
;	  ROHAN REGION 														 ;
;------------------------------------------------------------------------;
Object Inn
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Rohan
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Rohan
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Rohan
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Rohan
		End
	End
End
Object InnDesert
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Rohan
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Rohan
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Rohan
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Rohan
		End
	End
End
Object InnSnow
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Rohan
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Rohan
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Rohan
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Rohan
		End
	End
End
Object Inn_old
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Rohan
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Rohan
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Rohan
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Rohan
		End
	End
End
;endOfAuto-Generation


;==== Auto Generated AI Fix =====;
SkirmishAIData TheSkirmishAIData
    DisableBaseBuilding        = No
    DisableEconomyBuilding     = No
    DisableUnitBuilding        = No
    DisableScienceUpgrading    = No
    DisableUnitUpgrading       = No
    DisableTacticalAI          = No
    DisableTeamBuilding        = No
    DisableWallBuilding        = Yes ;,; No
End
