Weather
	HardwareFogColor = R:95 G:110 B:110
	HardwareFogEnable = Yes
	HardwareFogStart = 400
	HardwareFogEnd = 8000
End



Object AIBaseMarkerBase // THIS IS SPAWNED TO MAKE A TEAM EXIST, ALLOWING UNITS TO BE RECRUITED ONTO IT
RemoveModule ModuleTag_01
AddModule
	Body = ActiveBody ModuleTag_02
		MaxHealth         = 1
	End
End
End

ChildObject PrimaryAIBaseMarker AIBaseMarkerBase // DARK PRESENCE CASTER
	KindOf          = PRELOAD STRUCTURE IMMOBILE AUTO_RALLYPOINT FS_FACTORY IGNORE_FOR_VICTORY IGNORE_FOR_EVA_SPEECH_POSITION NO_COLLIDE UNATTACKABLE NOT_AUTOACQUIRABLE
AddModule
	Behavior = GrantUpgradeCreate ModuleTag_GrantUpgrade
		UpgradeToGrant	= Upgrade_GondorStableLevel2
	End
End
AddModule
	Behavior = AttributeModifierAuraUpdate ModuleTag_DarkPresence
		StartsActive	= Yes
		TriggeredBy		= Upgrade_GondorStableLevel2
		BonusName		= GuldurDarkPresence
		RefreshDelay	= 2000
		Range			= 20000
		ObjectFilter	= ANY +GuldurBrokenRabble +GuldurBrokenRabbleA +GuldurBrokenRabbleB +GuldurBrokenRabbleC +GuldurBrokenRabbleHorde +GuldurOrcArcher +GuldurOrcArcherHorde +GuldurOrcPikeman +GuldurOrcPikemanForBrokenRabble +GuldurOrcPikemanHorde +GuldurOrcArcherHorde_Summoned +GuldurOrcPikemanHorde_Summoned +GuldurBannerOrc +GuldurPikemenArcherComboHorde
	End
End
End

Object MordorCirithUngolGateDoor
  ArmorSet
		Conditions        = None
		Armor             = CastleGateArmorAttackable ; DefaultWallArmor
		DamageFX          = GateDamageFX
	End
End 

Object AOTRBreeDoor
  ArmorSet
		Conditions        = None
		Armor             = CastleGateArmorAttackable ; DefaultWallArmor
		DamageFX          = GateDamageFX
	End
End

;-------------------------------------------------------------------------------------------------
;GEOMETRY
;-------------------------------------------------------------------------------------------------

Object HelmsDeepdoSectionA2
AddModule
    Behavior = InvisibilityUpdate ModuleTag_StealthForEscape
        InvisibilityNugget
            InvisibilityType            = CAMOUFLAGE
            ForbiddenConditions            = FIRING_ANY
            BecomeStealthedFX           = FX_ElvenCloakOn
            ExitStealthFX               = FX_ElvenCloakOff
            DetectionRange                = 0
            HintDetectableConditions    = IS_FIRING_WEAPON
        End
        StartsActive                    = Yes
        UpdatePeriod                    = 2000
    End
End
End

Object AotRAmonHenN03
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotRAmonHenN08
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotRDolGuldurStairsC2
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotRDolGuldurBridgeB01
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotRDolGuldurBridgeB03
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotRDolGuldurBridgeB04
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotRDolGuldurRuinF
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotRDolGuldurWallB01
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotRDolGuldurGateA03
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotRDolGuldurGateA06
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotRDolGuldurGateA08
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotRDolGuldurCliffB02
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotRDolGuldurCliffb03
  Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotRDolGuldurCliffb04
  Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotRDolGuldurCliffb07
  Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotRDolGuldurRock01
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotRDolGuldurRock05
  Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotRDolGuldurRock07
  Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

ShadowMap
	MapSize = 2048
	MaxViewDistance = 6000.0
	MinShadowedTerrainHeight = 0.0
End

;startOfAuto-Generation
;------------------------------------------------------------------------;
;	  RHOVANION REGION 														 ;
;------------------------------------------------------------------------;
Object Inn
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Rhovanion
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Rhovanion
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Rhovanion
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Rhovanion
		End
	End
End
Object InnDesert
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Rhovanion
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Rhovanion
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Rhovanion
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Rhovanion
		End
	End
End
Object InnSnow
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Rhovanion
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Rhovanion
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Rhovanion
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Rhovanion
		End
	End
End
Object Inn_old
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Rhovanion
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Rhovanion
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Rhovanion
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Rhovanion
		End
	End
End
;endOfAuto-Generation


;==== Auto Generated AI Fix =====;
SkirmishAIData TheSkirmishAIData
    DisableBaseBuilding        = No
    DisableEconomyBuilding     = No
    DisableUnitBuilding        = No
    DisableScienceUpgrading    = No
    DisableUnitUpgrading       = No
    DisableTacticalAI          = No
    DisableTeamBuilding        = No
    DisableWallBuilding        = Yes ;,; No
End
