Weather
  HardwareFogColor = R:220 G:185 B:140
  HardwareFogEnable = Yes
  HardwareFogStart = 500
  HardwareFogEnd = 8500
End

;-----------------------------------------------------------------

; Water Effects

WaterTransparency
  ReflectionPlaneZ = 35.0;
  ReflectionOn = Yes
End

;------------------------------------------------------------

;Wandering Townsfolk
;Object GondorTownsman
;
;	RadarPriority = INVALID
;   KindOf = PRELOAD CAN_CAST_REFLECTIONS INFANTRY PATH_THROUGH_EACH_OTHER SCORE UNATTACKABLE 
;
;AddModule
;Behavior = AnimalAIUpdate ModuleTagWanderAroun
                ;FleeRange = 10; how close enemies have to be before we panic
                ;FleeDistance = 800; how far the animal will run once spooked
                ;WanderPercentage = 5;percentage of the time we should move
                ;MaxWanderDistance = 100;maximum distance to move at once
                ;MaxWanderRadius = 200; how far to wander on our own
                ;UpdateTimer = 11; how often do we want to check for enemies
;AfraidOfCastles = Yes; are we afraid of entering castles/camps
;End
;End
;
;End


Object Celduin_FishNet01
KindOf          = STRUCTURE IMMOBILE NOT_AUTOACQUIRABLE UNATTACKABLE; CLEARED_BY_BUILD 
END

Object Celduin_FishNet02
KindOf          = STRUCTURE IMMOBILE NOT_AUTOACQUIRABLE UNATTACKABLE; CLEARED_BY_BUILD 
END

Object Celduin_FishNet03
KindOf          = STRUCTURE IMMOBILE NOT_AUTOACQUIRABLE UNATTACKABLE; CLEARED_BY_BUILD 
END

Object Celduin_LobTrap01
KindOf          = STRUCTURE IMMOBILE NOT_AUTOACQUIRABLE UNATTACKABLE; CLEARED_BY_BUILD 
END


Object Outpost

	
  ; ***DESIGN parameters ***
  DisplayName         = OBJECT:Outpost
  Description 	      = OBJECT:OutpostDescription
  
  ; *** AUDIO Parameters ***

	VoiceSelect		= GondorForbiddenPoolSelect; CivilianOutpostSelect

	;End
	

	Geometry				= BOX
  	GeometryMajorRadius		= 0.1
	GeometryMinorRadius		= 0.1
	GeometryHeight			= 0.1
	GeometryOffset			= X:6 Y:7 Z:0	

	AdditionalGeometry		= BOX
  	GeometryMajorRadius		= 0.1
	GeometryMinorRadius		= 0.1
	GeometryHeight			= 0.1
	GeometryOffset			= X:23 Y:-60 Z:0	
	
	AdditionalGeometry		= BOX
  	GeometryMajorRadius		= 0.1
	GeometryMinorRadius		= 0.1
	GeometryHeight			= 0.1
	GeometryOffset			= X:-54 Y:-40 Z:0	
	
	GeometryIsSmall			= No
	Shadow					= SHADOW_VOLUME
	BuildCompletion			= PLACED_BY_PLAYER
	
	GeometryContactPoint = X:-15.0	Y:15.0		Z:0			Repair
	GeometryContactPoint = X:15.0	Y:-15.0		Z:0			Repair
	GeometryContactPoint = X:15.0	Y:15.0		Z:0
	GeometryContactPoint = X:-15.0	Y:-15.0		Z:0
	GeometryContactPoint = X:0.0	Y:0.0		Z:50.0	Swoop

End
;startOfAuto-Generation
;------------------------------------------------------------------------;
;	  HARAD REGION 														 ;
;------------------------------------------------------------------------;
Object Inn
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Harad
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Harad
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Harad
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Harad
		End
	End	
End
Object InnDesert
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Harad
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Harad
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Harad
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Harad
		End
	End
End
Object InnSnow
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Harad
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Harad
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Harad
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Harad
		End
	End
End
Object Inn_old
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Harad
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Harad
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Harad
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Harad
		End
	End
End
;endOfAuto-Generation


;==== Auto Generated AI Fix =====;
SkirmishAIData TheSkirmishAIData
    DisableBaseBuilding        = No
    DisableEconomyBuilding     = No
    DisableUnitBuilding        = No
    DisableScienceUpgrading    = No
    DisableUnitUpgrading       = No
    DisableTacticalAI          = No
    DisableTeamBuilding        = No
    DisableWallBuilding        = Yes ;,; No
End
