WaterTransparency
  ReflectionPlaneZ = 32.0;
  ReflectionOn = Yes
End

Weather

	HardwareFogColor = R:175 G:190 B:192
	HardwareFogEnable = Yes
	HardwareFogStart = 450
	HardwareFogEnd = 8000
	
End

;-------------------------------------------------------------------------------------------------
;GEOMETRY
;-------------------------------------------------------------------------------------------------

Object AotRBreeHedge
  KindOf = PRELOAD STRUCTURE IMMOBILE NOT_AUTOACQUIRABLE SCORE
  Geometry              = BOX
  GeometryMajorRadius   = 0.1
  GeometryMinorRadius   = 0.1
  GeometryHeight        = 0.1
  GeometryIsSmall       = No
End

Object AotROsgiliathProp39
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object GondorBuildingGeneric03
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object GondorBuildingGenericNew01
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object GondorBuildingGenericNew02
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object GondorBuildingGenericNew06
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object GondorBuildingGenericNew07
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object GondorBuildingGenericNew08
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

;;;market stall reskin;;;

Object AotRBazaarProp11
	ReplaceModule ModuleTag_01
	Draw = W3DScriptedModelDraw ModuleTag_white
	RandomTexture = hbbazaarA_gondor.tga 0 hbbazaarA.tga
		DefaultModelConditionState
			Model = prbazaar11_skn
		End
	End
	End
End

Object AotRBazaarProp12
	ReplaceModule ModuleTag_01
	Draw = W3DScriptedModelDraw ModuleTag_white
	RandomTexture = hbbazaarA_gondor.tga 0 hbbazaarA.tga
		DefaultModelConditionState
			Model = prbazaar12_skn
		End
	End
	End
End

Object AotRBazaarProp13
	ReplaceModule ModuleTag_01
	Draw = W3DScriptedModelDraw ModuleTag_white
	RandomTexture = hbbazaarA_gondor.tga 0 hbbazaarA.tga
		DefaultModelConditionState
			Model = prbazaar13_skn
		End
	End
	End
End
;startOfAuto-Generation
;------------------------------------------------------------------------;
;	  GONDOR REGION 														 ;
;------------------------------------------------------------------------;
Object Inn
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Gondor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Gondor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Gondor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Gondor
		End
	End
End
Object InnDesert
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Gondor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Gondor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Gondor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Gondor
		End
	End
End
Object InnSnow
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Gondor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Gondor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Gondor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Gondor
		End
	End
End
Object Inn_old
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Gondor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Gondor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Gondor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Gondor
		End
	End
End
;endOfAuto-Generation


;==== Auto Generated AI Fix =====;
SkirmishAIData TheSkirmishAIData
    DisableBaseBuilding        = No
    DisableEconomyBuilding     = No
    DisableUnitBuilding        = No
    DisableScienceUpgrading    = No
    DisableUnitUpgrading       = No
    DisableTacticalAI          = No
    DisableTeamBuilding        = No
    DisableWallBuilding        = Yes ;,; No
End
