Weather

	HardwareFogColor = R:165 G:180 B:180
	HardwareFogEnable = Yes
	HardwareFogStart = 400
	HardwareFogEnd = 8000
End



WaterTransparency
  ReflectionPlaneZ = 189.0;
  ReflectionOn = Yes
End


 ;----------------------------------------------------------------------------------------
 
 
 ; Bear
Object Bear

	ReplaceModule ModuleTag_01
	Draw = W3DScriptedModelDraw ModuleTag_NewBear  

		RandomTexture = cubeara.tga 0 cubear.tga  

    DefaultModelConditionState
		Model               = CUBear_SKN
    End
    
   	IdleAnimationState
		StateName					=   STATE_Idle
		Animation = IdleA
			AnimationName       = CUBear_SKL.CUBear_IDLA
			AnimationPriority	= 10
			AnimationMode       = ONCE
			AnimationBlendTime	=	10
		End
		Animation = IdleB
			AnimationName       = CUBear_SKL.CUBear_IDLB
			AnimationPriority	= 10
			AnimationMode       = ONCE
			AnimationBlendTime	=	10
		End
		BeginScript
			Prev = CurDrawablePrevAnimationState()
			if Prev == "STATE_Alert" then CurDrawableSetTransitionAnimState("TRANS_AlertToIdle") end
		EndScript
    End

;	AnimationState				= MOVING WANDER
;		Animation				= WLKA
;			AnimationName		= CUBear_SKL.CUBear_WLKA
;			AnimationBlendTime	=	20
;			AnimationMustCompleteBlend = yes
;		End
;	End

	AnimationState				= MOVING PANICKING
		Animation				= RUNA
			AnimationName		= CUBear_SKL.CUBear_RUNA
			AnimationMode		= LOOP
		End
		Flags					= RANDOMSTART
	End    
	    	
	AnimationState			=	MOVING
		StateName			=	STATE_moving
		Animation			=	Moving
			AnimationName	=	CUBear_SKL.CUBear_WALKA
			AnimationBlendTime	=	10
			AnimationMustCompleteBlend = yes
		End
		
		BeginScript
			Prev = CurDrawablePrevAnimationState()
			if Prev == "STATE_Alert" then CurDrawableSetTransitionAnimState("TRANS_AlertToIdle") end
		EndScript
		
	End
	
	TransitionState					=	TRANS_AlertToIdle
		Animation					=   IDLE
			AnimationName			=	CUBear_SKL.CUBear_IDLE
			AnimationMode			=	ONCE
		End
	End	
	
	TransitionState					=	TRANS_IdleToAlert
		Animation					=   IDLC
			AnimationName			=	CUBear_SKL.CUBear_IDLC
			AnimationMode			=	ONCE
		End
	End		

;	AnimationState        = EMOTION_ALERT
;		StateName			=   STATE_Alert
;		Animation           = ALERT_1
;			AnimationName     = CUBear_SKL.CUBear_IDLD
;			AnimationMode     = ONCE
;		End
;		BeginScript
;			Prev = CurDrawablePrevAnimationState()
;			if Prev == "STATE_Idle" then CurDrawableSetTransitionAnimState("TRANS_IdleToAlert") end
;		EndScript
;		Flags               = RESTART_ANIM_WHEN_COMPLETE ; acts like an idle animation & keeps running the animations.
;	End
	
	AnimationState        = DYING DEATH_1
		Animation           = CUBear_DIEA
  			AnimationName     = CUBear_SKL.CUBear_IDLA
			AnimationMode     = LOOP
		End
	End	
	
	AnimationState        = DYING
		Animation           = CUBear_DIEA
  			AnimationName     = CUBear_SKL.CUBear_DIEA
			AnimationMode     = ONCE
		End
	End

			
 End
 End
 End
;startOfAuto-Generation
;------------------------------------------------------------------------;
;	  ROHAN REGION 														 ;
;------------------------------------------------------------------------;
Object Inn
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Rohan
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Rohan
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Rohan
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Rohan
		End
	End
End
Object InnDesert
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Rohan
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Rohan
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Rohan
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Rohan
		End
	End
End
Object InnSnow
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Rohan
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Rohan
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Rohan
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Rohan
		End
	End
End
Object Inn_old
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Rohan
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Rohan
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Rohan
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Rohan
		End
	End
End
;endOfAuto-Generation


;==== Auto Generated AI Fix =====;
SkirmishAIData TheSkirmishAIData
    DisableBaseBuilding        = No
    DisableEconomyBuilding     = No
    DisableUnitBuilding        = No
    DisableScienceUpgrading    = No
    DisableUnitUpgrading       = No
    DisableTacticalAI          = No
    DisableTeamBuilding        = No
    DisableWallBuilding        = Yes ;,; No
End
