Weather

	HardwareFogColor = R:155 G:175 B:175
	HardwareFogEnable = Yes
	HardwareFogStart = 600
	HardwareFogEnd = 8000
	
End


Object DoGoldurWallTowerSmall
 
  Geometry              = BOX
  GeometryMajorRadius   = 0.1
  GeometryMinorRadius   = 0.1
  GeometryHeight        = 0.1
  GeometryIsSmall       = Yes
  Shadow                = SHADOW_VOLUME
  BuildCompletion     = PLACED_BY_PLAYER
End

Object DolGoldurWallSegmentSmall_Damagable
 
  Geometry              = BOX
  GeometryMajorRadius   = 0.1
  GeometryMinorRadius   = 0.1
  GeometryHeight        = 0.1
  GeometryIsSmall       = Yes
  Shadow                = SHADOW_VOLUME
  BuildCompletion     = PLACED_BY_PLAYER
End

Object DoGoldurWallHubSmall
 
  Geometry              = BOX
  GeometryMajorRadius   = 0.1
  GeometryMinorRadius   = 0.1
  GeometryHeight        = 0.1
  GeometryIsSmall       = Yes
  Shadow                = SHADOW_VOLUME
  BuildCompletion     = PLACED_BY_PLAYER
End

Object DoGoldurWallCatapultSmall
 
  Geometry              = BOX
  GeometryMajorRadius   = 0.1
  GeometryMinorRadius   = 0.1
  GeometryHeight        = 0.1
  GeometryIsSmall       = Yes
  Shadow                = SHADOW_VOLUME
  BuildCompletion     = PLACED_BY_PLAYER
End
;startOfAuto-Generation
;------------------------------------------------------------------------;
;	  MISTY MOUNTAINS REGION 														 ;
;------------------------------------------------------------------------;
Object Inn
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_MM
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_MM
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_MM
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_MM
		End
	End
End
Object InnDesert
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_MM
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_MM
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_MM
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_MM
		End
	End
End
Object InnSnow
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_MM
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_MM
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_MM
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_MM
		End
	End
End
Object Inn_old
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_MM
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_MM
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_MM
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_MM
		End
	End
End
;endOfAuto-Generation


;==== Auto Generated AI Fix =====;
SkirmishAIData TheSkirmishAIData
    DisableBaseBuilding        = No
    DisableEconomyBuilding     = No
    DisableUnitBuilding        = No
    DisableScienceUpgrading    = No
    DisableUnitUpgrading       = No
    DisableTacticalAI          = No
    DisableTeamBuilding        = No
    DisableWallBuilding        = Yes ;,; No
End
