Weather

	HardwareFogColor = R:40 G:40 B:40
	HardwareFogEnable = Yes
	HardwareFogStart = 400
	HardwareFogEnd = 7000

End



Object AotREreborRock01
	ReplaceModule ModuleTag_01
	Draw = W3DScriptedModelDraw ModuleTag_green
	RandomTexture = PRCliffErebor_green.tga 0 PRCliffErebor.tga
		DefaultModelConditionState
			Model = PRErebor01
		End
	End
	End
End

Object AotREreborRock02
	ReplaceModule ModuleTag_01
	Draw = W3DScriptedModelDraw ModuleTag_green
	RandomTexture = PRCliffErebor_green.tga 0 PRCliffErebor.tga
		DefaultModelConditionState
			Model = PRErebor02
		End
	End
	End
End

Object AotREreborRock03
	ReplaceModule ModuleTag_01
	Draw = W3DScriptedModelDraw ModuleTag_green
	RandomTexture = PRCliffErebor_green.tga 0 PRCliffErebor.tga
		DefaultModelConditionState
			Model = PRErebor03
		End
	End
	End
End

Object AotREreborRock04
	ReplaceModule ModuleTag_01
	Draw = W3DScriptedModelDraw ModuleTag_green
	RandomTexture = PRCliffErebor_green.tga 0 PRCliffErebor.tga
		DefaultModelConditionState
			Model = PRErebor04
		End
	End
	End
End

Object AotREreborRock05
	ReplaceModule ModuleTag_01
	Draw = W3DScriptedModelDraw ModuleTag_green
	RandomTexture = PRCliffErebor_green.tga 0 PRCliffErebor.tga
		DefaultModelConditionState
			Model = PRErebor05
		End
	End
	End
End

Object AotREreborRock08
	ReplaceModule ModuleTag_01
	Draw = W3DScriptedModelDraw ModuleTag_green
	RandomTexture = PRCliffErebor_green.tga 0 PRCliffErebor.tga
		DefaultModelConditionState
			Model = PRErebor08
		End
	End
	End
End

Object AotREreborRock09
	ReplaceModule ModuleTag_01
	Draw = W3DScriptedModelDraw ModuleTag_green
	RandomTexture = PRCliffErebor_green.tga 0 PRCliffErebor.tga
		DefaultModelConditionState
			Model = PRErebor09
		End
	End
	End
End

Object EreborTorch
	ReplaceModule ModuleTag_01
	Draw = W3DScriptedModelDraw ModuleTag_green
	RandomTexture = eb_wall01_green.tga 0 eb_wall01.tga
		DefaultModelConditionState
			Model = EB_torch
		End
	End
	End
End



;startOfAuto-Generation
;------------------------------------------------------------------------;
;	  EREBOR REGION 														 ;
;------------------------------------------------------------------------;
Object Inn
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Erebor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Erebor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Erebor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Erebor
		End
	End
End
Object InnDesert
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Erebor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Erebor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Erebor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Erebor
		End
	End
End
Object InnSnow
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Erebor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Erebor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Erebor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Erebor
		End
	End
End
Object Inn_old
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Erebor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Erebor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Erebor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Erebor
		End
	End
End
;endOfAuto-Generation


;==== Auto Generated AI Fix =====;
SkirmishAIData TheSkirmishAIData
    DisableBaseBuilding        = No
    DisableEconomyBuilding     = No
    DisableUnitBuilding        = No
    DisableScienceUpgrading    = No
    DisableUnitUpgrading       = No
    DisableTacticalAI          = No
    DisableTeamBuilding        = No
    DisableWallBuilding        = Yes ;,; No
End
