
//-----------------------------------------------------------------------------------------------------------------------------------------------------------------
// 										ARNOR REGION - 12 TERRITORIES - 4 SUB-REGIONS
//-----------------------------------------------------------------------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------
// ARTHEDAIN SUB-REGION
//-------------------------------------------------------------------------------------------------
;////////////////////////////
;// Annuminas
;////////////////////////////

WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Fornost_1

WOTRGatherPoint_Fornost_1

WOTRSpawnPoint_Grey_Havens_1

WOTRGatherPoint_Grey_Havens_1

WOTRSpawnPoint_Hills_Evendim_1

WOTRGatherPoint_Hills_Evendim_1

WOTRSpawnPoint_North_Downs_1

WOTRGatherPoint_North_Downs_1

WOTRSpawnPoint_The_Shire_1

WOTRGatherPoint_The_Shire_1

WOTRSpawnPoint_Tower_Hills_1

WOTRGatherPoint_Tower_Hills_1			



;////////////////////////////
;// Fornost
;////////////////////////////

WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Annuminas_1

WOTRGatherPoint_Annuminas_1	

WOTRSpawnPoint_Buckland_1

WOTRGatherPoint_Buckland_1		

WOTRSpawnPoint_North_Downs_1

WOTRGatherPoint_North_Downs_1		

WOTRSpawnPoint_Weather_Hills_1

WOTRGatherPoint_Weather_Hills_1

WOTRSpawnPoint_The_Shire_1

WOTRGatherPoint_The_Shire_1		



;////////////////////////////
;// Hills of Evendim
;////////////////////////////

WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Annuminas_1

WOTRGatherPoint_Annuminas_1

WOTRSpawnPoint_Ered_Luin_Highlands_1

WOTRGatherPoint_Ered_Luin_Highlands_1		

WOTRSpawnPoint_Ettenmoors_1

WOTRGatherPoint_Ettenmoors_1		

WOTRSpawnPoint_Grey_Havens_1

WOTRGatherPoint_Grey_Havens_1		

WOTRSpawnPoint_Ice_Bay_Of_Forochel_1

WOTRGatherPoint_Ice_Bay_Of_Forochel_1

WOTRSpawnPoint_Tuli_Ma_1

WOTRGatherPoint_Tuli_Ma_1	

WOTRSpawnPoint_North_Downs_1

WOTRGatherPoint_North_Downs_1		



;////////////////////////////
;// North Downs
;////////////////////////////


WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Annuminas_1

WOTRGatherPoint_Annuminas_1	

WOTRSpawnPoint_Ettenmoors_1

WOTRGatherPoint_Ettenmoors_1		

WOTRSpawnPoint_Fornost_1

WOTRGatherPoint_Fornost_1		

WOTRSpawnPoint_Hills_Evendim_1

WOTRGatherPoint_Hills_Evendim_1	

WOTRSpawnPoint_Weather_Hills_1

WOTRGatherPoint_Weather_Hills_1		




//-------------------------------------------------------------------------------------------------
// BREE-LAND SUB-REGION
//-------------------------------------------------------------------------------------------------
;////////////////////////////
;// Barrow-downs
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Bree_1

WOTRGatherPoint_Bree_1	

WOTRSpawnPoint_Weathertop_1

WOTRGatherPoint_Weathertop_1		

WOTRSpawnPoint_Cardolan_1

WOTRGatherPoint_Cardolan_1		

WOTRSpawnPoint_Minhiriath_1

WOTRGatherPoint_Minhiriath_1	

WOTRSpawnPoint_Sarn_Ford_1

WOTRGatherPoint_Sarn_Ford_1

WOTRSpawnPoint_Old_Forest_1

WOTRGatherPoint_Old_Forest_1			


;////////////////////////////
;// Bree
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Buckland_1

WOTRGatherPoint_Buckland_1	

WOTRSpawnPoint_Weather_Hills_1

WOTRGatherPoint_Weather_Hills_1		

WOTRSpawnPoint_Weathertop_1

WOTRGatherPoint_Weathertop_1		

WOTRSpawnPoint_Barrow_Downs_1

WOTRGatherPoint_Barrow_Downs_1	

WOTRSpawnPoint_Old_Forest_1

WOTRGatherPoint_Old_Forest_1			

;////////////////////////////
;// Sarn Ford
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_The_Shire_1

WOTRGatherPoint_The_Shire_1	

WOTRSpawnPoint_Old_Forest_1

WOTRGatherPoint_Old_Forest_1		

WOTRSpawnPoint_Barrow_Downs_1

WOTRGatherPoint_Barrow_Downs_1		

WOTRSpawnPoint_Minhiriath_1

WOTRGatherPoint_Minhiriath_1	

WOTRSpawnPoint_Harlindon_1

WOTRGatherPoint_Harlindon_1

WOTRSpawnPoint_Tower_Hills_1

WOTRGatherPoint_Tower_Hills_1			


//-------------------------------------------------------------------------------------------------
// THE SHIRE SUB-REGION
//-------------------------------------------------------------------------------------------------
;////////////////////////////
;// Buckland
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Fornost_1

WOTRGatherPoint_Fornost_1	

WOTRSpawnPoint_Weather_Hills_1

WOTRGatherPoint_Weather_Hills_1		

WOTRSpawnPoint_Bree_1

WOTRGatherPoint_Bree_1		

WOTRSpawnPoint_Old_Forest_1

WOTRGatherPoint_Old_Forest_1	

WOTRSpawnPoint_The_Shire_1

WOTRGatherPoint_The_Shire_1		


;////////////////////////////
;// The Shire
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Annuminas_1

WOTRGatherPoint_Annuminas_1	

WOTRSpawnPoint_Fornost_1

WOTRGatherPoint_Fornost_1		

WOTRSpawnPoint_Buckland_1

WOTRGatherPoint_Buckland_1		

WOTRSpawnPoint_Old_Forest_1

WOTRGatherPoint_Old_Forest_1	

WOTRSpawnPoint_Sarn_Ford_1

WOTRGatherPoint_Sarn_Ford_1

WOTRSpawnPoint_Tower_Hills_1

WOTRGatherPoint_Tower_Hills_1		


;////////////////////////////
;// The Old Forest
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_The_Shire_1

WOTRGatherPoint_The_Shire_1	

WOTRSpawnPoint_Buckland_1

WOTRGatherPoint_Buckland_1		

WOTRSpawnPoint_Bree_1

WOTRGatherPoint_Bree_1		

WOTRSpawnPoint_Barrow_Downs_1

WOTRGatherPoint_Barrow_Downs_1	

WOTRSpawnPoint_Sarn_Ford_1

WOTRGatherPoint_Sarn_Ford_1	

//-------------------------------------------------------------------------------------------------
// WEATHER HILLS SUB-REGION
//-------------------------------------------------------------------------------------------------
;////////////////////////////
;// Weather Hills
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_North_Downs_1

WOTRGatherPoint_North_Downs_1	

WOTRSpawnPoint_Ettenmoors_1

WOTRGatherPoint_Ettenmoors_1		

WOTRSpawnPoint_Rhudaur_1

WOTRGatherPoint_Rhudaur_1		

WOTRSpawnPoint_Weathertop_1

WOTRGatherPoint_Weathertop_1	

WOTRSpawnPoint_Bree_1

WOTRGatherPoint_Bree_1

WOTRSpawnPoint_Buckland_1

WOTRGatherPoint_Buckland_1	

WOTRSpawnPoint_Fornost_1

WOTRGatherPoint_Fornost_1			


;////////////////////////////
;// Weathertop
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Weather_Hills_1

WOTRGatherPoint_Weather_Hills_1			

WOTRSpawnPoint_Rhudaur_1

WOTRGatherPoint_Rhudaur_1		

WOTRSpawnPoint_Trollshaws_1

WOTRGatherPoint_Trollshaws_1	

WOTRSpawnPoint_Cardolan_1

WOTRGatherPoint_Cardolan_1

WOTRSpawnPoint_Barrow_Downs_1

WOTRGatherPoint_Barrow_Downs_1	

WOTRSpawnPoint_Bree_1

WOTRGatherPoint_Bree_1			


//-----------------------------------------------------------------------------------------------------------------------------------------------------------------
// 										ENEDWAITH REGION - 8 TERRITORIES - 2 SUB-REGIONS
//-----------------------------------------------------------------------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------
// DUNLAND SUB-REGION
//-------------------------------------------------------------------------------------------------
;////////////////////////////
;// Dunfearn
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Cardolan_1

WOTRGatherPoint_Cardolan_1	

WOTRSpawnPoint_Dunland_1

WOTRGatherPoint_Dunland_1

WOTRSpawnPoint_Greyflood_1

WOTRGatherPoint_Greyflood_1

WOTRSpawnPoint_Minhiriath_1

WOTRGatherPoint_Minhiriath_1		

WOTRSpawnPoint_Ost_In_Edhil_1

WOTRGatherPoint_Ost_In_Edhil_1

WOTRSpawnPoint_Swanfleet_1

WOTRGatherPoint_Swanfleet_1	

WOTRSpawnPoint_Tharbad_1

WOTRGatherPoint_Tharbad_1		



;////////////////////////////
;// Dunland
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Dunfearn_1

WOTRGatherPoint_Dunfearn_1

WOTRSpawnPoint_Enedwaith_1

WOTRGatherPoint_Enedwaith_1			

WOTRSpawnPoint_Frecalund_1

WOTRGatherPoint_Frecalund_1			

WOTRSpawnPoint_Gap_Of_Rohan_1

WOTRGatherPoint_Gap_Of_Rohan_1	

WOTRSpawnPoint_Greyflood_1

WOTRGatherPoint_Greyflood_1

WOTRSpawnPoint_Regnfells_1

WOTRGatherPoint_Regnfells_1		



;////////////////////////////
;// Wulfborg
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Druwaith_Iaur_1

WOTRGatherPoint_Druwaith_Iaur_1

WOTRSpawnPoint_Enedwaith_1

WOTRGatherPoint_Enedwaith_1		

WOTRSpawnPoint_Frecalund_1

WOTRGatherPoint_Frecalund_1			



;////////////////////////////
;// Frecalund
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Dunland_1

WOTRGatherPoint_Dunland_1

WOTRSpawnPoint_Enedwaith_1

WOTRGatherPoint_Enedwaith_1			

WOTRSpawnPoint_Regnfells_1

WOTRGatherPoint_Regnfells_1			

WOTRSpawnPoint_Wulfborg_1

WOTRGatherPoint_Wulfborg_1


;////////////////////////////
;// Regnfells
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Frecalund_1

WOTRGatherPoint_Frecalund_1

WOTRSpawnPoint_Dunland_1

WOTRGatherPoint_Dunland_1		

WOTRSpawnPoint_Gap_Of_Rohan_1

WOTRGatherPoint_Gap_Of_Rohan_1



//-------------------------------------------------------------------------------------------------
// ENEDWAITH SUB-REGION
//-------------------------------------------------------------------------------------------------
;////////////////////////////
;// Enedwaith
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Greyflood_1

WOTRGatherPoint_Greyflood_1

WOTRSpawnPoint_Dunland_1

WOTRGatherPoint_Dunland_1		

WOTRSpawnPoint_Frecalund_1

WOTRGatherPoint_Frecalund_1

WOTRSpawnPoint_Wulfborg_1

WOTRGatherPoint_Wulfborg_1

WOTRSpawnPoint_Druwaith_Iaur_1

WOTRGatherPoint_Druwaith_Iaur_1			


;////////////////////////////
;// Greyflood
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Minhiriath_1

WOTRGatherPoint_Minhiriath_1

WOTRSpawnPoint_Dunfearn_1

WOTRGatherPoint_Dunfearn_1		

WOTRSpawnPoint_Dunland_1

WOTRGatherPoint_Dunland_1

WOTRSpawnPoint_Enedwaith_1

WOTRGatherPoint_Enedwaith_1		


;////////////////////////////
;// Druwaith Iaur
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Andrast_1

WOTRGatherPoint_Andrast_1

WOTRSpawnPoint_Enedwaith_1

WOTRGatherPoint_Enedwaith_1		

WOTRSpawnPoint_Wulfborg_1

WOTRGatherPoint_Wulfborg_1		


//-----------------------------------------------------------------------------------------------------------------------------------------------------------------
// 										EREBOR REGION - 9 TERRITORIES - 3 SUB-REGIONS
//-----------------------------------------------------------------------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------
// IRON HILLS SUB-REGION
//-------------------------------------------------------------------------------------------------
;////////////////////////////
;// Ironfoot Halls
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Iron_Hills_1

WOTRGatherPoint_Iron_Hills_1

WOTRSpawnPoint_Iron_Foothills_1

WOTRGatherPoint_Iron_Foothills_1			


;////////////////////////////
;// Iron Foothills
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Ironfoot_Halls_1

WOTRGatherPoint_Ironfoot_Halls_1	

WOTRSpawnPoint_Iron_Hills_1

WOTRGatherPoint_Iron_Hills_1

WOTRSpawnPoint_Eastern_Wastes_1

WOTRGatherPoint_Eastern_Wastes_1	

WOTRSpawnPoint_Vales_Celduin_1

WOTRGatherPoint_Vales_Celduin_1

WOTRSpawnPoint_Carnen_1

WOTRGatherPoint_Carnen_1			


;////////////////////////////
;// Iron Hills
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Eastern_Wastes_1

WOTRGatherPoint_Eastern_Wastes_1	

WOTRSpawnPoint_Targul_1

WOTRGatherPoint_Targul_1

WOTRSpawnPoint_Ironfoot_Halls_1

WOTRGatherPoint_Ironfoot_Halls_1

WOTRSpawnPoint_Iron_Foothills_1

WOTRGatherPoint_Iron_Foothills_1			



;////////////////////////////
;// Targul
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Eastern_Wastes_1

WOTRGatherPoint_Eastern_Wastes_1

WOTRSpawnPoint_Erebor_1

WOTRGatherPoint_Erebor_1

WOTRSpawnPoint_Withered_Heath_1

WOTRGatherPoint_Withered_Heath_1		

WOTRSpawnPoint_Iron_Hills_1

WOTRGatherPoint_Iron_Hills_1		

//-------------------------------------------------------------------------------------------------
// KINGDOM OF EREBOR AND DALE SUB-REGION
//-------------------------------------------------------------------------------------------------
;////////////////////////////
;// Eastern Wastes
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Esgaroth_1

WOTRGatherPoint_Esgaroth_1

WOTRSpawnPoint_Erebor_1

WOTRGatherPoint_Erebor_1		

WOTRSpawnPoint_Iron_Hills_1

WOTRGatherPoint_Iron_Hills_1

WOTRSpawnPoint_Iron_Foothills_1

WOTRGatherPoint_Iron_Foothills_1	

WOTRSpawnPoint_Vales_Celduin_1

WOTRGatherPoint_Vales_Celduin_1				

WOTRSpawnPoint_Targul_1

WOTRGatherPoint_Targul_1		



;////////////////////////////
;// Esgaroth
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Eastern_Wastes_1

WOTRGatherPoint_Eastern_Wastes_1

WOTRSpawnPoint_Vales_Celduin_1

WOTRGatherPoint_Vales_Celduin_1		

WOTRSpawnPoint_Erebor_1

WOTRGatherPoint_Erebor_1

WOTRSpawnPoint_Halls_Elvenking_1

WOTRGatherPoint_Halls_Elvenking_1

WOTRSpawnPoint_Taur_En_Morvith_1

WOTRGatherPoint_Taur_En_Morvith_1		



;////////////////////////////
;// Erebor
;////////////////////////////


WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Eastern_Wastes_1

WOTRGatherPoint_Eastern_Wastes_1

WOTRSpawnPoint_Esgaroth_1

WOTRGatherPoint_Esgaroth_1	

WOTRSpawnPoint_Targul_1

WOTRGatherPoint_Targul_1	

WOTRSpawnPoint_Taur_Na_Faroth_1

WOTRGatherPoint_Taur_Na_Faroth_1

WOTRSpawnPoint_Halls_Elvenking_1

WOTRGatherPoint_Halls_Elvenking_1

WOTRSpawnPoint_Withered_Heath_1

WOTRGatherPoint_Withered_Heath_1			


//-------------------------------------------------------------------------------------------------
// RIVERLANDS SUB-REGION
//-------------------------------------------------------------------------------------------------
;////////////////////////////
;// Carnen
;////////////////////////////


WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Rhun_1

WOTRGatherPoint_Rhun_1

WOTRSpawnPoint_Dorwinion_1

WOTRGatherPoint_Dorwinion_1		

WOTRSpawnPoint_Iron_Foothills_1

WOTRGatherPoint_Iron_Foothills_1	

WOTRSpawnPoint_Vales_Celduin_1

WOTRGatherPoint_Vales_Celduin_1				


;////////////////////////////
;// Vales of Celduin
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Eastern_Wastes_1

WOTRGatherPoint_Eastern_Wastes_1	

WOTRSpawnPoint_Iron_Foothills_1

WOTRGatherPoint_Iron_Foothills_1	

WOTRSpawnPoint_Carnen_1

WOTRGatherPoint_Carnen_1

WOTRSpawnPoint_Dorwinion_1

WOTRGatherPoint_Dorwinion_1	

WOTRSpawnPoint_East_Bight_1

WOTRGatherPoint_East_Bight_1

WOTRSpawnPoint_Mirkwood_1

WOTRGatherPoint_Mirkwood_1

WOTRSpawnPoint_Taur_En_Morvith_1

WOTRGatherPoint_Taur_En_Morvith_1

WOTRSpawnPoint_Esgaroth_1

WOTRGatherPoint_Esgaroth_1			

//-----------------------------------------------------------------------------------------------------------------------------------------------------------------
// 										ERIADOR REGION - 12 TERRITORIES - 4 SUB-REGIONS
//-----------------------------------------------------------------------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------
// CARDOLAN SUB-REGION
//-------------------------------------------------------------------------------------------------
;////////////////////////////
;// Cardolan
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Barrow_Downs_1

WOTRGatherPoint_Barrow_Downs_1	

WOTRSpawnPoint_Weathertop_1

WOTRGatherPoint_Weathertop_1

WOTRSpawnPoint_Trollshaws_1

WOTRGatherPoint_Trollshaws_1

WOTRSpawnPoint_The_Angle_1

WOTRGatherPoint_The_Angle_1

WOTRSpawnPoint_Swanfleet_1

WOTRGatherPoint_Swanfleet_1	

WOTRSpawnPoint_Tharbad_1

WOTRGatherPoint_Tharbad_1

WOTRSpawnPoint_Dunfearn_1

WOTRGatherPoint_Dunfearn_1

WOTRSpawnPoint_Minhiriath_1

WOTRGatherPoint_Minhiriath_1			


;////////////////////////////
;// Minhiriath
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Harlindon_1

WOTRGatherPoint_Harlindon_1	

WOTRSpawnPoint_Sarn_Ford_1

WOTRGatherPoint_Sarn_Ford_1

WOTRSpawnPoint_Barrow_Downs_1

WOTRGatherPoint_Barrow_Downs_1

WOTRSpawnPoint_Cardolan_1

WOTRGatherPoint_Cardolan_1

WOTRSpawnPoint_Dunfearn_1

WOTRGatherPoint_Dunfearn_1	

WOTRSpawnPoint_Greyflood_1

WOTRGatherPoint_Greyflood_1		


;////////////////////////////
;// Swanfleet
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_The_Angle_1

WOTRGatherPoint_The_Angle_1	

WOTRSpawnPoint_Eregion_1

WOTRGatherPoint_Eregion_1

WOTRSpawnPoint_Ost_In_Edhil_1

WOTRGatherPoint_Ost_In_Edhil_1

WOTRSpawnPoint_Dunfearn_1

WOTRGatherPoint_Dunfearn_1

WOTRSpawnPoint_Tharbad_1

WOTRGatherPoint_Tharbad_1	

WOTRSpawnPoint_Cardolan_1

WOTRGatherPoint_Cardolan_1		


;////////////////////////////
;// Tharbad
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Cardolan_1

WOTRGatherPoint_Cardolan_1	

WOTRSpawnPoint_Swanfleet_1

WOTRGatherPoint_Swanfleet_1

WOTRSpawnPoint_Dunfearn_1

WOTRGatherPoint_Dunfearn_1


//-------------------------------------------------------------------------------------------------
// EREGION SUB-REGION
//-------------------------------------------------------------------------------------------------
;////////////////////////////
;// Eregion
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Hollin_1

WOTRGatherPoint_Hollin_1	

WOTRSpawnPoint_Ost_In_Edhil_1

WOTRGatherPoint_Ost_In_Edhil_1

WOTRSpawnPoint_The_Angle_1

WOTRGatherPoint_The_Angle_1

WOTRSpawnPoint_Caradhras_1

WOTRGatherPoint_Caradhras_1	

WOTRSpawnPoint_Moria_1

WOTRGatherPoint_Moria_1

WOTRSpawnPoint_Swanfleet_1

WOTRGatherPoint_Swanfleet_1		




;////////////////////////////
;// Hollin
;////////////////////////////


WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Caradhras_1

WOTRGatherPoint_Caradhras_1	

WOTRSpawnPoint_Rivendell_1

WOTRGatherPoint_Rivendell_1

WOTRSpawnPoint_Fords_Bruinen_1

WOTRGatherPoint_Fords_Bruinen_1	

WOTRSpawnPoint_Trollshaws_1

WOTRGatherPoint_Trollshaws_1

WOTRSpawnPoint_The_Angle_1

WOTRGatherPoint_The_Angle_1		

WOTRSpawnPoint_Eregion_1

WOTRGatherPoint_Eregion_1		


;////////////////////////////
;// Ost-in-Edhil



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Eregion_1

WOTRGatherPoint_Eregion_1

WOTRSpawnPoint_Moria_1

WOTRGatherPoint_Moria_1

WOTRSpawnPoint_Dunfearn_1

WOTRGatherPoint_Dunfearn_1				

WOTRSpawnPoint_Swanfleet_1

WOTRGatherPoint_Swanfleet_1				


//-------------------------------------------------------------------------------------------------
// RHUDAUR SUB-REGION
//-------------------------------------------------------------------------------------------------
;////////////////////////////
;// The Angle
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Trollshaws_1

WOTRGatherPoint_Trollshaws_1

WOTRSpawnPoint_Hollin_1

WOTRGatherPoint_Hollin_1

WOTRSpawnPoint_Eregion_1

WOTRGatherPoint_Eregion_1				

WOTRSpawnPoint_Swanfleet_1

WOTRGatherPoint_Swanfleet_1

WOTRSpawnPoint_Cardolan_1

WOTRGatherPoint_Cardolan_1			

;////////////////////////////
;// Rhudaur
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Ettenmoors_1

WOTRGatherPoint_Ettenmoors_1

WOTRSpawnPoint_Coldfells_1

WOTRGatherPoint_Coldfells_1

WOTRSpawnPoint_Trollshaws_1

WOTRGatherPoint_Trollshaws_1				

WOTRSpawnPoint_Weathertop_1

WOTRGatherPoint_Weathertop_1

WOTRSpawnPoint_Weather_Hills_1

WOTRGatherPoint_Weather_Hills_1		



;////////////////////////////
;// Trollshaws
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Coldfells_1

WOTRGatherPoint_Coldfells_1

WOTRSpawnPoint_Fords_Bruinen_1

WOTRGatherPoint_Fords_Bruinen_1

WOTRSpawnPoint_Hollin_1

WOTRGatherPoint_Hollin_1				

WOTRSpawnPoint_The_Angle_1

WOTRGatherPoint_The_Angle_1

WOTRSpawnPoint_Cardolan_1

WOTRGatherPoint_Cardolan_1

WOTRSpawnPoint_Weathertop_1

WOTRGatherPoint_Weathertop_1

WOTRSpawnPoint_Rhudaur_1

WOTRGatherPoint_Rhudaur_1		




//-------------------------------------------------------------------------------------------------
// RIVENDELL SUB-REGION
//-------------------------------------------------------------------------------------------------
;////////////////////////////
;// Fords of Bruinen
;////////////////////////////

WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_High_Pass_1

WOTRGatherPoint_High_Pass_1	

WOTRSpawnPoint_Rivendell_1

WOTRGatherPoint_Rivendell_1

WOTRSpawnPoint_Hollin_1

WOTRGatherPoint_Hollin_1

WOTRSpawnPoint_Trollshaws_1

WOTRGatherPoint_Trollshaws_1

WOTRSpawnPoint_Coldfells_1

WOTRGatherPoint_Coldfells_1				



;////////////////////////////
;// Rivendell
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Fords_Bruinen_1

WOTRGatherPoint_Fords_Bruinen_1

WOTRSpawnPoint_Hollin_1

WOTRGatherPoint_Hollin_1		



//-----------------------------------------------------------------------------------------------------------------------------------------------------------------
// 										FORODWAITH REGION - 6 TERRITORIES - 2 SUB-REGIONS
//-----------------------------------------------------------------------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------
// FOROCHEL SUB-REGION
//-------------------------------------------------------------------------------------------------
;////////////////////////////
;// Ice Bay of Forochel
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Cape_Forlond_1

WOTRGatherPoint_Cape_Forlond_1

WOTRSpawnPoint_Ered_Luin_Highlands_1

WOTRGatherPoint_Ered_Luin_Highlands_1		

WOTRSpawnPoint_Hills_Evendim_1

WOTRGatherPoint_Hills_Evendim_1	

WOTRSpawnPoint_Tuli_Ma_1

WOTRGatherPoint_Tuli_Ma_1

WOTRSpawnPoint_Ettenmoors_1

WOTRGatherPoint_Ettenmoors_1

WOTRSpawnPoint_Grey_Havens_1

WOTRGatherPoint_Grey_Havens_1



;////////////////////////////
;// Itä-mâ
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Forodwaith_1

WOTRGatherPoint_Forodwaith_1

WOTRSpawnPoint_Jotunstath_1

WOTRGatherPoint_Jotunstath_1			

WOTRSpawnPoint_Tuli_Ma_1

WOTRGatherPoint_Tuli_Ma_1

WOTRSpawnPoint_Northtarn_1

WOTRGatherPoint_Northtarn_1


;////////////////////////////
;// Tuli-mâ
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Carn_Dum_1

WOTRGatherPoint_Carn_Dum_1

WOTRSpawnPoint_Ettenmoors_1

WOTRGatherPoint_Ettenmoors_1			

WOTRSpawnPoint_Hills_Evendim_1

WOTRGatherPoint_Hills_Evendim_1	

WOTRSpawnPoint_Ice_Bay_Of_Forochel_1

WOTRGatherPoint_Ice_Bay_Of_Forochel_1

WOTRSpawnPoint_Ita_Ma_1

WOTRGatherPoint_Ita_Ma_1

WOTRSpawnPoint_Northtarn_1

WOTRGatherPoint_Northtarn_1		



//-------------------------------------------------------------------------------------------------
// NORTHERN WASTES SUB-REGION
//-------------------------------------------------------------------------------------------------
;////////////////////////////
;// Forodwaith
;////////////////////////////


WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Ita_Ma_1

WOTRGatherPoint_Ita_Ma_1

WOTRSpawnPoint_Jotunstath_1

WOTRGatherPoint_Jotunstath_1

WOTRSpawnPoint_Northtarn_1

WOTRGatherPoint_Northtarn_1

WOTRSpawnPoint_Carn_Dum_1

WOTRGatherPoint_Carn_Dum_1

WOTRSpawnPoint_Gundabad_1

WOTRGatherPoint_Gundabad_1	

WOTRSpawnPoint_Grey_Mountains_1

WOTRGatherPoint_Grey_Mountains_1			




;////////////////////////////
;// Jotunstath
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Forodwaith_1

WOTRGatherPoint_Forodwaith_1

WOTRSpawnPoint_Ita_Ma_1

WOTRGatherPoint_Ita_Ma_1

WOTRSpawnPoint_Northtarn_1

WOTRGatherPoint_Northtarn_1		



;////////////////////////////
;// Northtarn
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Carn_Dum_1

WOTRGatherPoint_Carn_Dum_1	

WOTRSpawnPoint_Forodwaith_1

WOTRGatherPoint_Forodwaith_1

WOTRSpawnPoint_Ita_Ma_1

WOTRGatherPoint_Ita_Ma_1

WOTRSpawnPoint_Jotunstath_1

WOTRGatherPoint_Jotunstath_1

WOTRSpawnPoint_Tuli_Ma_1

WOTRGatherPoint_Tuli_Ma_1				

//-------------------------------------------------------------------------------------------------

//-----------------------------------------------------------------------------------------------------------------------------------------------------------------
// 										HARADWAITH REGION - 23 TERRITORIES - 7 SUB-REGIONS
//-----------------------------------------------------------------------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------
// ABRAKHAN SUB-REGION
//-------------------------------------------------------------------------------------------------
;////////////////////////////
;// Abrakhan
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Desert_Of_Azkahar_1

WOTRGatherPoint_Desert_Of_Azkahar_1

WOTRSpawnPoint_Tombs_Of_Abrakhan_1

WOTRGatherPoint_Tombs_Of_Abrakhan_1


;////////////////////////////
;// Desert of Azkâhar
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Abrakhan_1

WOTRGatherPoint_Abrakhan_1

WOTRSpawnPoint_Borders_Of_Khand_1

WOTRGatherPoint_Borders_Of_Khand_1

WOTRSpawnPoint_Near_Harad_1

WOTRGatherPoint_Near_Harad_1			

WOTRSpawnPoint_Itakh_Khand_1

WOTRGatherPoint_Itakh_Khand_1			


;////////////////////////////
;// Tombs of Abrakhân
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Abrakhan_1

WOTRGatherPoint_Abrakhan_1



//-------------------------------------------------------------------------------------------------
// FAR HARAD SUB-REGION
//-------------------------------------------------------------------------------------------------

;////////////////////////////
;// Kârna
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Far_Harad_1

WOTRGatherPoint_Far_Harad_1

WOTRSpawnPoint_Nafarat_1

WOTRGatherPoint_Nafarat_1



;////////////////////////////
;// Far Harad
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Karna_1

WOTRGatherPoint_Karna_1

WOTRSpawnPoint_Dusalan_1

WOTRGatherPoint_Dusalan_1		

WOTRSpawnPoint_Nafarat_Delta_1

WOTRGatherPoint_Nafarat_Delta_1

WOTRSpawnPoint_Hidar_1

WOTRGatherPoint_Hidar_1		

WOTRSpawnPoint_Amathuna_1

WOTRGatherPoint_Amathuna_1

WOTRSpawnPoint_Nafarat_1

WOTRGatherPoint_Nafarat_1		

WOTRSpawnPoint_Near_Harad_1

WOTRGatherPoint_Near_Harad_1



;////////////////////////////
;// Nafarat Delta
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Cape_Of_Mardruak_1

WOTRGatherPoint_Cape_Of_Mardruak_1	

WOTRSpawnPoint_Far_Harad_1

WOTRGatherPoint_Far_Harad_1

WOTRSpawnPoint_Hidar_1

WOTRGatherPoint_Hidar_1		

WOTRSpawnPoint_Nafarat_1

WOTRGatherPoint_Nafarat_1



;////////////////////////////
;// Nafarat
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Karna_1

WOTRGatherPoint_Karna_1	

WOTRSpawnPoint_Far_Harad_1

WOTRGatherPoint_Far_Harad_1

WOTRSpawnPoint_Nafarat_Delta_1

WOTRGatherPoint_Nafarat_Delta_1



//-------------------------------------------------------------------------------------------------
// HARONDOR SUB-REGION
//-------------------------------------------------------------------------------------------------
;////////////////////////////
;// Ethir Anduin
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Harondor_1

WOTRGatherPoint_Harondor_1

WOTRSpawnPoint_Southern_Ithilien_1

WOTRGatherPoint_Southern_Ithilien_1

WOTRSpawnPoint_Pelargir_1

WOTRGatherPoint_Pelargir_1



;////////////////////////////
;// Harad Road
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Desert_Of_Lostladen_1

WOTRGatherPoint_Desert_Of_Lostladen_1

WOTRSpawnPoint_Harondor_1

WOTRGatherPoint_Harondor_1

WOTRSpawnPoint_Near_Harad_1

WOTRGatherPoint_Near_Harad_1

WOTRSpawnPoint_Southern_Ithilien_1

WOTRGatherPoint_Southern_Ithilien_1			


;////////////////////////////
;// Harondor
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Ethir_Anduin_1

WOTRGatherPoint_Ethir_Anduin_1

WOTRSpawnPoint_Harad_Road_1

WOTRGatherPoint_Harad_Road_1

WOTRSpawnPoint_Near_Harad_1

WOTRGatherPoint_Near_Harad_1	

WOTRSpawnPoint_Southern_Ithilien_1

WOTRGatherPoint_Southern_Ithilien_1		

WOTRSpawnPoint_Umbar_1

WOTRGatherPoint_Umbar_1		


//-------------------------------------------------------------------------------------------------
// KHAND SUB-REGION
//-------------------------------------------------------------------------------------------------
;////////////////////////////
;// Borders of Khand
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Desert_Of_Azkahar_1

WOTRGatherPoint_Desert_Of_Azkahar_1

WOTRSpawnPoint_Desert_Of_Lostladen_1

WOTRGatherPoint_Desert_Of_Lostladen_1		

WOTRSpawnPoint_Khand_1

WOTRGatherPoint_Khand_1

WOTRSpawnPoint_Near_Harad_1

WOTRGatherPoint_Near_Harad_1		

WOTRSpawnPoint_Itakh_Khand_1

WOTRGatherPoint_Itakh_Khand_1		


;////////////////////////////
;// Khand
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Borders_Of_Khand_1

WOTRGatherPoint_Borders_Of_Khand_1

WOTRSpawnPoint_Desert_Of_Lostladen_1

WOTRGatherPoint_Desert_Of_Lostladen_1		

WOTRSpawnPoint_Itakh_Khand_1

WOTRGatherPoint_Itakh_Khand_1




;////////////////////////////
;// Itakh Khand
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Borders_Of_Khand_1

WOTRGatherPoint_Borders_Of_Khand_1			

WOTRSpawnPoint_Desert_Of_Azkahar_1

WOTRGatherPoint_Desert_Of_Azkahar_1

WOTRSpawnPoint_Khand_1

WOTRGatherPoint_Khand_1


//-------------------------------------------------------------------------------------------------
// MARDRUAK SUB-REGION
//-------------------------------------------------------------------------------------------------
;////////////////////////////
;// Cape of Mardruak
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Dusalan_1

WOTRGatherPoint_Dusalan_1

WOTRSpawnPoint_Harad_Coast_1

WOTRGatherPoint_Harad_Coast_1		

WOTRSpawnPoint_Nafarat_Delta_1

WOTRGatherPoint_Nafarat_Delta_1



;////////////////////////////
;// Dûsalan
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Cape_Of_Mardruak_1

WOTRGatherPoint_Cape_Of_Mardruak_1

WOTRSpawnPoint_Far_Harad_1

WOTRGatherPoint_Far_Harad_1		

WOTRSpawnPoint_Harad_Coast_1

WOTRGatherPoint_Harad_Coast_1		

WOTRSpawnPoint_Hidar_1

WOTRGatherPoint_Hidar_1

WOTRSpawnPoint_Amathuna_1

WOTRGatherPoint_Amathuna_1			



;////////////////////////////
;// Hidar
;////////////////////////////


WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Dusalan_1

WOTRGatherPoint_Dusalan_1

WOTRSpawnPoint_Far_Harad_1

WOTRGatherPoint_Far_Harad_1		

WOTRSpawnPoint_Nafarat_Delta_1

WOTRGatherPoint_Nafarat_Delta_1



;////////////////////////////
;// Harad Coast
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Cape_Of_Mardruak_1

WOTRGatherPoint_Cape_Of_Mardruak_1		

WOTRSpawnPoint_Dusalan_1

WOTRGatherPoint_Dusalan_1	

WOTRSpawnPoint_White_Pillar_1

WOTRGatherPoint_White_Pillar_1



//-------------------------------------------------------------------------------------------------
// NEAR HARD SUB-REGION
//-------------------------------------------------------------------------------------------------
;////////////////////////////
;// Desert of Lostladen
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Borders_Of_Khand_1

WOTRGatherPoint_Borders_Of_Khand_1

WOTRSpawnPoint_Harad_Road_1

WOTRGatherPoint_Harad_Road_1		

WOTRSpawnPoint_Khand_1

WOTRGatherPoint_Khand_1

WOTRSpawnPoint_Near_Harad_1

WOTRGatherPoint_Near_Harad_1



;////////////////////////////
;// Near Harad
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Borders_Of_Khand_1

WOTRGatherPoint_Borders_Of_Khand_1

WOTRSpawnPoint_Desert_Of_Lostladen_1

WOTRGatherPoint_Desert_Of_Lostladen_1		

WOTRSpawnPoint_Desert_Of_Azkahar_1

WOTRGatherPoint_Desert_Of_Azkahar_1

WOTRSpawnPoint_Far_Harad_1

WOTRGatherPoint_Far_Harad_1

WOTRSpawnPoint_Harad_Road_1

WOTRGatherPoint_Harad_Road_1	

WOTRSpawnPoint_Harondor_1

WOTRGatherPoint_Harondor_1		

WOTRSpawnPoint_Amathuna_1

WOTRGatherPoint_Amathuna_1

WOTRSpawnPoint_Umbar_1

WOTRGatherPoint_Umbar_1		



;////////////////////////////
;// Amathuna
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Dusalan_1

WOTRGatherPoint_Dusalan_1	

WOTRSpawnPoint_Far_Harad_1

WOTRGatherPoint_Far_Harad_1

WOTRSpawnPoint_Near_Harad_1

WOTRGatherPoint_Near_Harad_1



//-------------------------------------------------------------------------------------------------
// UMBAR SUB-REGION
//-------------------------------------------------------------------------------------------------

;////////////////////////////
;// Umbar
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Harondor_1

WOTRGatherPoint_Harondor_1	

WOTRSpawnPoint_Maros_1

WOTRGatherPoint_Maros_1

WOTRSpawnPoint_Near_Harad_1

WOTRGatherPoint_Near_Harad_1		

WOTRSpawnPoint_White_Pillar_1

WOTRGatherPoint_White_Pillar_1

WOTRSpawnPoint_Tolfalas_1

WOTRGatherPoint_Tolfalas_1

WOTRSpawnPoint_Pelargir_1

WOTRGatherPoint_Pelargir_1

WOTRSpawnPoint_Dol_Amroth_1

WOTRGatherPoint_Dol_Amroth_1	




;////////////////////////////
;// Maros
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Umbar_1

WOTRGatherPoint_Umbar_1

WOTRSpawnPoint_Tolfalas_1

WOTRGatherPoint_Tolfalas_1

WOTRSpawnPoint_Dol_Amroth_1

WOTRGatherPoint_Dol_Amroth_1




;////////////////////////////
;// White Pillar
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Harad_Coast_1

WOTRGatherPoint_Harad_Coast_1	

WOTRSpawnPoint_Umbar_1

WOTRGatherPoint_Umbar_1



//-----------------------------------------------------------------------------------------------------------------------------------------------------------------
// 										LINDON REGION - 8 TERRITORIES - 2 SUB-REGIONS
//-----------------------------------------------------------------------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------
// FORLINDON SUB-REGION
//-------------------------------------------------------------------------------------------------
;////////////////////////////
;// Cape of Forlond
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Ice_Bay_Of_Forochel_1

WOTRGatherPoint_Ice_Bay_Of_Forochel_1	

WOTRSpawnPoint_Ered_Luin_Highlands_1

WOTRGatherPoint_Ered_Luin_Highlands_1

WOTRSpawnPoint_Forlindon_1

WOTRGatherPoint_Forlindon_1		


;////////////////////////////
;// Ered Luin Highlands
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Cape_Forlond_1

WOTRGatherPoint_Cape_Forlond_1	

WOTRSpawnPoint_Ice_Bay_Of_Forochel_1

WOTRGatherPoint_Ice_Bay_Of_Forochel_1

WOTRSpawnPoint_Hills_Evendim_1

WOTRGatherPoint_Hills_Evendim_1	

WOTRSpawnPoint_Grey_Havens_1

WOTRGatherPoint_Grey_Havens_1

WOTRSpawnPoint_Ered_Luin_1

WOTRGatherPoint_Ered_Luin_1			


;////////////////////////////
;// Forlindon
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Cape_Forlond_1

WOTRGatherPoint_Cape_Forlond_1	

WOTRSpawnPoint_Ered_Luin_1

WOTRGatherPoint_Ered_Luin_1

WOTRSpawnPoint_Grey_Havens_1

WOTRGatherPoint_Grey_Havens_1		


;////////////////////////////
;// Ered Luin
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Forlindon_1

WOTRGatherPoint_Forlindon_1	

WOTRSpawnPoint_Ered_Luin_Highlands_1

WOTRGatherPoint_Ered_Luin_Highlands_1	


;////////////////////////////
;// Grey Havens
;////////////////////////////


WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Ered_Luin_Highlands_1

WOTRGatherPoint_Ered_Luin_Highlands_1	

WOTRSpawnPoint_Hills_Evendim_1

WOTRGatherPoint_Hills_Evendim_1

WOTRSpawnPoint_Annuminas_1

WOTRGatherPoint_Annuminas_1

WOTRSpawnPoint_Tower_Hills_1

WOTRGatherPoint_Tower_Hills_1	

WOTRSpawnPoint_Forlindon_1

WOTRGatherPoint_Forlindon_1

WOTRSpawnPoint_Ice_Bay_Of_Forochel_1

WOTRGatherPoint_Ice_Bay_Of_Forochel_1	

WOTRSpawnPoint_Dol_Amroth_1

WOTRGatherPoint_Dol_Amroth_1			



//-------------------------------------------------------------------------------------------------
// HARLINDON SUB-REGION
//-------------------------------------------------------------------------------------------------
;////////////////////////////
;// Thorin's Halls
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Harlindon_1

WOTRGatherPoint_Harlindon_1	

WOTRSpawnPoint_Tower_Hills_1

WOTRGatherPoint_Tower_Hills_1	



;////////////////////////////
;// Harlindon
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Tower_Hills_1

WOTRGatherPoint_Tower_Hills_1	

WOTRSpawnPoint_Thorins_Halls_1

WOTRGatherPoint_Thorins_Halls_1

WOTRSpawnPoint_Sarn_Ford_1

WOTRGatherPoint_Sarn_Ford_1

WOTRSpawnPoint_Minhiriath_1

WOTRGatherPoint_Minhiriath_1			



;////////////////////////////
;// Tower Hills
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Grey_Havens_1

WOTRGatherPoint_Grey_Havens_1	

WOTRSpawnPoint_Annuminas_1

WOTRGatherPoint_Annuminas_1

WOTRSpawnPoint_The_Shire_1

WOTRGatherPoint_The_Shire_1

WOTRSpawnPoint_Sarn_Ford_1

WOTRGatherPoint_Sarn_Ford_1

WOTRSpawnPoint_Harlindon_1

WOTRGatherPoint_Harlindon_1

WOTRSpawnPoint_Thorins_Halls_1

WOTRGatherPoint_Thorins_Halls_1		

//-----------------------------------------------------------------------------------------------------------------------------------------------------------------
// 										MISTY MOUNTAINS REGION - 13 TERRITORIES - 4 SUB-REGIONS
//-----------------------------------------------------------------------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------
// ANGMAR SUB-REGION
//-------------------------------------------------------------------------------------------------
;////////////////////////////
;// Angmar
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Gundabad_1

WOTRGatherPoint_Gundabad_1

WOTRSpawnPoint_Mount_Gram_1

WOTRGatherPoint_Mount_Gram_1

WOTRSpawnPoint_Ettenmoors_1

WOTRGatherPoint_Ettenmoors_1	

WOTRSpawnPoint_Carn_Dum_1

WOTRGatherPoint_Carn_Dum_1			


;////////////////////////////
;// Ettenmoors
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Tuli_Ma_1

WOTRGatherPoint_Tuli_Ma_1

WOTRSpawnPoint_Carn_Dum_1

WOTRGatherPoint_Carn_Dum_1

WOTRSpawnPoint_Angmar_1

WOTRGatherPoint_Angmar_1	

WOTRSpawnPoint_Mount_Gram_1

WOTRGatherPoint_Mount_Gram_1

WOTRSpawnPoint_Coldfells_1

WOTRGatherPoint_Coldfells_1

WOTRSpawnPoint_Rhudaur_1

WOTRGatherPoint_Rhudaur_1

WOTRSpawnPoint_Weather_Hills_1

WOTRGatherPoint_Weather_Hills_1

WOTRSpawnPoint_North_Downs_1

WOTRGatherPoint_North_Downs_1

WOTRSpawnPoint_Hills_Evendim_1

WOTRGatherPoint_Hills_Evendim_1			


;////////////////////////////
;// Mount Gram
;////////////////////////////


WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Angmar_1

WOTRGatherPoint_Angmar_1

WOTRSpawnPoint_Coldfells_1

WOTRGatherPoint_Coldfells_1

WOTRSpawnPoint_Ettenmoors_1

WOTRGatherPoint_Ettenmoors_1	



;////////////////////////////
;// Coldfells
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Mount_Gram_1

WOTRGatherPoint_Mount_Gram_1

WOTRSpawnPoint_Goblin_Town_1

WOTRGatherPoint_Goblin_Town_1

WOTRSpawnPoint_High_Pass_1

WOTRGatherPoint_High_Pass_1	

WOTRSpawnPoint_Fords_Bruinen_1

WOTRGatherPoint_Fords_Bruinen_1

WOTRSpawnPoint_Trollshaws_1

WOTRGatherPoint_Trollshaws_1

WOTRSpawnPoint_Rhudaur_1

WOTRGatherPoint_Rhudaur_1

WOTRSpawnPoint_Ettenmoors_1

WOTRGatherPoint_Ettenmoors_1			


;////////////////////////////
;// Carn Dum
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Northtarn_1

WOTRGatherPoint_Northtarn_1

WOTRSpawnPoint_Forodwaith_1

WOTRGatherPoint_Forodwaith_1

WOTRSpawnPoint_Gundabad_1

WOTRGatherPoint_Gundabad_1	

WOTRSpawnPoint_Angmar_1

WOTRGatherPoint_Angmar_1

WOTRSpawnPoint_Ettenmoors_1

WOTRGatherPoint_Ettenmoors_1

WOTRSpawnPoint_Tuli_Ma_1

WOTRGatherPoint_Tuli_Ma_1		



//-------------------------------------------------------------------------------------------------
// GUNDABAD SUB-REGION
//-------------------------------------------------------------------------------------------------
;////////////////////////////
;// Gundabad
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Carn_Dum_1

WOTRGatherPoint_Carn_Dum_1

WOTRSpawnPoint_Angmar_1

WOTRGatherPoint_Angmar_1

WOTRSpawnPoint_Grey_Mountains_1

WOTRGatherPoint_Grey_Mountains_1

WOTRSpawnPoint_Forodwaith_1

WOTRGatherPoint_Forodwaith_1			



;////////////////////////////
;// Grey Mountains
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Forodwaith_1

WOTRGatherPoint_Forodwaith_1

WOTRSpawnPoint_Withered_Heath_1

WOTRGatherPoint_Withered_Heath_1

WOTRSpawnPoint_Taur_Na_Faroth_1

WOTRGatherPoint_Taur_Na_Faroth_1	

WOTRSpawnPoint_Northern_Mirkwood_1

WOTRGatherPoint_Northern_Mirkwood_1

WOTRSpawnPoint_Framsburg_1

WOTRGatherPoint_Framsburg_1

WOTRSpawnPoint_Gundabad_1

WOTRGatherPoint_Gundabad_1		


;////////////////////////////
;// Withered Heath
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Grey_Mountains_1

WOTRGatherPoint_Grey_Mountains_1

WOTRSpawnPoint_Taur_Na_Faroth_1

WOTRGatherPoint_Taur_Na_Faroth_1	

WOTRSpawnPoint_Erebor_1

WOTRGatherPoint_Erebor_1

WOTRSpawnPoint_Targul_1

WOTRGatherPoint_Targul_1	


//-------------------------------------------------------------------------------------------------
// HIGH PASS SUB-REGION
//-------------------------------------------------------------------------------------------------
;////////////////////////////
;// High Pass
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Carrock_1

WOTRGatherPoint_Carrock_1

WOTRSpawnPoint_Old_Ford_Anduin_1

WOTRGatherPoint_Old_Ford_Anduin_1			

WOTRSpawnPoint_Coldfells_1

WOTRGatherPoint_Coldfells_1	

WOTRSpawnPoint_Fords_Bruinen_1

WOTRGatherPoint_Fords_Bruinen_1

WOTRSpawnPoint_Goblin_Town_1

WOTRGatherPoint_Goblin_Town_1		


;////////////////////////////
;// Goblin Town
;////////////////////////////


WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Coldfells_1

WOTRGatherPoint_Coldfells_1

WOTRSpawnPoint_High_Pass_1

WOTRGatherPoint_High_Pass_1		


//-------------------------------------------------------------------------------------------------
// MORIA SUB-REGION
//-------------------------------------------------------------------------------------------------
;////////////////////////////
;// Caradhras
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Dimrill_Dale_1

WOTRGatherPoint_Dimrill_Dale_1		

WOTRSpawnPoint_Eregion_1

WOTRGatherPoint_Eregion_1	

WOTRSpawnPoint_Hollin_1

WOTRGatherPoint_Hollin_1	

WOTRSpawnPoint_Lothlorien_1

WOTRGatherPoint_Lothlorien_1				

WOTRSpawnPoint_Moria_1

WOTRGatherPoint_Moria_1

WOTRSpawnPoint_Taur_Hith_1

WOTRGatherPoint_Taur_Hith_1				



;////////////////////////////
;// Dimrill Dale
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Caradhras_1

WOTRGatherPoint_Caradhras_1

WOTRSpawnPoint_Lothlorien_1

WOTRGatherPoint_Lothlorien_1

WOTRSpawnPoint_Moria_1

WOTRGatherPoint_Moria_1

WOTRSpawnPoint_Nan_Celebrant_1

WOTRGatherPoint_Nan_Celebrant_1				



;////////////////////////////
;// Moria
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Caradhras_1

WOTRGatherPoint_Caradhras_1

WOTRSpawnPoint_Dimrill_Dale_1

WOTRGatherPoint_Dimrill_Dale_1

WOTRSpawnPoint_Eregion_1

WOTRGatherPoint_Eregion_1

WOTRSpawnPoint_Ost_In_Edhil_1

WOTRGatherPoint_Ost_In_Edhil_1				


//-----------------------------------------------------------------------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------
// 										ROHAN REGION - 15 TERRITORIES - 4 SUB-REGIONS
//-------------------------------------------------------------------------------------------------

//-------------------------------------------------------------------------------------------------
// EAST-MARK SUB-REGION
//-------------------------------------------------------------------------------------------------
;////////////////////////////
;// East Emnet
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Amon_Hen_1

WOTRGatherPoint_Amon_Hen_1

WOTRSpawnPoint_The_Wold_1

WOTRGatherPoint_The_Wold_1		

WOTRSpawnPoint_Snowbourn_1

WOTRGatherPoint_Snowbourn_1

WOTRSpawnPoint_Eastern_Rohan_1

WOTRGatherPoint_Eastern_Rohan_1		


;////////////////////////////
;// Eastern Rohan
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Amon_Hen_1

WOTRGatherPoint_Amon_Hen_1

WOTRSpawnPoint_Eastfold_1

WOTRGatherPoint_Eastfold_1		

WOTRSpawnPoint_Mouths_Entwash_1

WOTRGatherPoint_Mouths_Entwash_1

WOTRSpawnPoint_East_Emnet_1

WOTRGatherPoint_East_Emnet_1

WOTRSpawnPoint_The_Folde_1

WOTRGatherPoint_The_Folde_1

WOTRSpawnPoint_West_Emnet_1

WOTRGatherPoint_West_Emnet_1

WOTRSpawnPoint_Snowbourn_1

WOTRGatherPoint_Snowbourn_1			


;////////////////////////////
;// Eastfold
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Halifirien_1

WOTRGatherPoint_Halifirien_1

WOTRSpawnPoint_Eastern_Rohan_1

WOTRGatherPoint_Eastern_Rohan_1		

WOTRSpawnPoint_Mouths_Entwash_1

WOTRGatherPoint_Mouths_Entwash_1

WOTRSpawnPoint_The_Folde_1

WOTRGatherPoint_The_Folde_1		


//-------------------------------------------------------------------------------------------------
// ISENGARD SUB-REGION
//-------------------------------------------------------------------------------------------------
;////////////////////////////
;// Eaves of Fangorn
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Isengard_1

WOTRGatherPoint_Isengard_1

WOTRSpawnPoint_Westfold_1

WOTRGatherPoint_Westfold_1		

WOTRSpawnPoint_Fords_Isen_1

WOTRGatherPoint_Fords_Isen_1

WOTRSpawnPoint_Snowbourn_1

WOTRGatherPoint_Snowbourn_1

WOTRSpawnPoint_Fangorn_1

WOTRGatherPoint_Fangorn_1		


;////////////////////////////
;// Fords of Isen
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Isengard_1

WOTRGatherPoint_Isengard_1

WOTRSpawnPoint_Eaves_Fangorn_1

WOTRGatherPoint_Eaves_Fangorn_1		

WOTRSpawnPoint_Westfold_1

WOTRGatherPoint_Westfold_1

WOTRSpawnPoint_Gap_Of_Rohan_1

WOTRGatherPoint_Gap_Of_Rohan_1

WOTRSpawnPoint_Helms_Deep_1

WOTRGatherPoint_Helms_Deep_1		

;////////////////////////////
;// Isengard
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Eaves_Fangorn_1

WOTRGatherPoint_Eaves_Fangorn_1		

WOTRSpawnPoint_Fords_Isen_1

WOTRGatherPoint_Fords_Isen_1		


;////////////////////////////
;// Gap of Rohan
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Fords_Isen_1

WOTRGatherPoint_Fords_Isen_1		

WOTRSpawnPoint_Dunland_1

WOTRGatherPoint_Dunland_1

WOTRSpawnPoint_Regnfells_1

WOTRGatherPoint_Regnfells_1

WOTRSpawnPoint_Helms_Deep_1

WOTRGatherPoint_Helms_Deep_1			



//-------------------------------------------------------------------------------------------------
// KING'S LANDS SUB-REGION
//-------------------------------------------------------------------------------------------------
;////////////////////////////
;// Dunharrow
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Helms_Deep_1

WOTRGatherPoint_Helms_Deep_1		

WOTRSpawnPoint_Westfold_1

WOTRGatherPoint_Westfold_1

WOTRSpawnPoint_Harrowdale_1

WOTRGatherPoint_Harrowdale_1

WOTRSpawnPoint_Erech_1

WOTRGatherPoint_Erech_1			


;////////////////////////////
;// Edoras
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_The_Folde_1

WOTRGatherPoint_The_Folde_1		

WOTRSpawnPoint_West_Emnet_1

WOTRGatherPoint_West_Emnet_1

WOTRSpawnPoint_Harrowdale_1

WOTRGatherPoint_Harrowdale_1		


;////////////////////////////
;// Harrowdale
;////////////////////////////


WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Edoras_1

WOTRGatherPoint_Edoras_1		

WOTRSpawnPoint_Dunharrow_1

WOTRGatherPoint_Dunharrow_1

WOTRSpawnPoint_Westfold_1

WOTRGatherPoint_Westfold_1

WOTRSpawnPoint_West_Emnet_1

WOTRGatherPoint_West_Emnet_1			



;////////////////////////////
;// The Folde
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Eastfold_1

WOTRGatherPoint_Eastfold_1		

WOTRSpawnPoint_Eastern_Rohan_1

WOTRGatherPoint_Eastern_Rohan_1

WOTRSpawnPoint_Edoras_1

WOTRGatherPoint_Edoras_1

WOTRSpawnPoint_West_Emnet_1

WOTRGatherPoint_West_Emnet_1			



//-------------------------------------------------------------------------------------------------
// WEST-MARK SUB-REGION
//-------------------------------------------------------------------------------------------------
;////////////////////////////
;// Helm's Deep
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Dunharrow_1

WOTRGatherPoint_Dunharrow_1		

WOTRSpawnPoint_Westfold_1

WOTRGatherPoint_Westfold_1

WOTRSpawnPoint_Fords_Isen_1

WOTRGatherPoint_Fords_Isen_1

WOTRSpawnPoint_Gap_Of_Rohan_1

WOTRGatherPoint_Gap_Of_Rohan_1


;////////////////////////////
;// Snowbourn
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Fangorn_1

WOTRGatherPoint_Fangorn_1		

WOTRSpawnPoint_The_Wold_1

WOTRGatherPoint_The_Wold_1

WOTRSpawnPoint_East_Emnet_1

WOTRGatherPoint_East_Emnet_1

WOTRSpawnPoint_Eastern_Rohan_1

WOTRGatherPoint_Eastern_Rohan_1

WOTRSpawnPoint_West_Emnet_1

WOTRGatherPoint_West_Emnet_1			

WOTRSpawnPoint_Westfold_1

WOTRGatherPoint_Westfold_1	

WOTRSpawnPoint_Eaves_Fangorn_1

WOTRGatherPoint_Eaves_Fangorn_1			


;////////////////////////////
;// West-Emnet
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Snowbourn_1

WOTRGatherPoint_Snowbourn_1		

WOTRSpawnPoint_Eastern_Rohan_1

WOTRGatherPoint_Eastern_Rohan_1

WOTRSpawnPoint_The_Folde_1

WOTRGatherPoint_The_Folde_1

WOTRSpawnPoint_Edoras_1

WOTRGatherPoint_Edoras_1

WOTRSpawnPoint_Harrowdale_1

WOTRGatherPoint_Harrowdale_1			

WOTRSpawnPoint_Westfold_1

WOTRGatherPoint_Westfold_1			


;////////////////////////////
;// Westfold
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Eaves_Fangorn_1

WOTRGatherPoint_Eaves_Fangorn_1		

WOTRSpawnPoint_Snowbourn_1

WOTRGatherPoint_Snowbourn_1

WOTRSpawnPoint_West_Emnet_1

WOTRGatherPoint_West_Emnet_1

WOTRSpawnPoint_Harrowdale_1

WOTRGatherPoint_Harrowdale_1

WOTRSpawnPoint_Dunharrow_1

WOTRGatherPoint_Dunharrow_1			

WOTRSpawnPoint_Helms_Deep_1

WOTRGatherPoint_Helms_Deep_1

WOTRSpawnPoint_Fords_Isen_1

WOTRGatherPoint_Fords_Isen_1		


//-----------------------------------------------------------------------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------
// 										GONDOR REGION - 24 TERRITORIES - 2 SUB-REGIONS
//-------------------------------------------------------------------------------------------------

//-------------------------------------------------------------------------------------------------
// NORTHERN GONDOR SUB-REGION
//-------------------------------------------------------------------------------------------------
;////////////////////////////
;// Mouths of the Entwash
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Amon_Hen_1

WOTRGatherPoint_Amon_Hen_1

WOTRSpawnPoint_Dead_Marshes_1

WOTRGatherPoint_Dead_Marshes_1		

WOTRSpawnPoint_Emyn_Muil_1

WOTRGatherPoint_Emyn_Muil_1

WOTRSpawnPoint_Anorien_1

WOTRGatherPoint_Anorien_1			

WOTRSpawnPoint_Halifirien_1

WOTRGatherPoint_Halifirien_1	

WOTRSpawnPoint_Eastern_Rohan_1

WOTRGatherPoint_Eastern_Rohan_1

WOTRSpawnPoint_Druadan_Forest_1

WOTRGatherPoint_Druadan_Forest_1	

WOTRSpawnPoint_Northern_Ithilien_1

WOTRGatherPoint_Northern_Ithilien_1

WOTRSpawnPoint_Cair_Andros_1

WOTRGatherPoint_Cair_Andros_1		


;////////////////////////////
;// Halifirien
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Mouths_Entwash_1

WOTRGatherPoint_Mouths_Entwash_1

WOTRSpawnPoint_Anorien_1

WOTRGatherPoint_Anorien_1		

WOTRSpawnPoint_Eastfold_1

WOTRGatherPoint_Eastfold_1		


;////////////////////////////
;// Anorien
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Mouths_Entwash_1

WOTRGatherPoint_Mouths_Entwash_1

WOTRSpawnPoint_Halifirien_1

WOTRGatherPoint_Halifirien_1		

WOTRSpawnPoint_Druadan_Forest_1

WOTRGatherPoint_Druadan_Forest_1		


;////////////////////////////
;// Druadan Forest
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Minas_Tirith_1

WOTRGatherPoint_Minas_Tirith_1

WOTRSpawnPoint_Mouths_Entwash_1

WOTRGatherPoint_Mouths_Entwash_1		

WOTRSpawnPoint_Anorien_1

WOTRGatherPoint_Anorien_1

WOTRSpawnPoint_Cair_Andros_1

WOTRGatherPoint_Cair_Andros_1		

_1
;////////////////////////////
;// Cair Andros
;////////////////////////////


WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Druadan_Forest_1

WOTRGatherPoint_Druadan_Forest_1

WOTRSpawnPoint_Minas_Tirith_1

WOTRGatherPoint_Minas_Tirith_1		

WOTRSpawnPoint_Mouths_Entwash_1

WOTRGatherPoint_Mouths_Entwash_1

WOTRSpawnPoint_Northern_Ithilien_1

WOTRGatherPoint_Northern_Ithilien_1

WOTRSpawnPoint_Osgiliath_1

WOTRGatherPoint_Osgiliath_1		


;////////////////////////////
;// Northern Ithilien
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Dead_Marshes_1

WOTRGatherPoint_Dead_Marshes_1

WOTRSpawnPoint_Mouths_Entwash_1

WOTRGatherPoint_Mouths_Entwash_1		

WOTRSpawnPoint_Cair_Andros_1

WOTRGatherPoint_Cair_Andros_1

WOTRSpawnPoint_Osgiliath_1

WOTRGatherPoint_Osgiliath_1

WOTRSpawnPoint_Crossroads_1

WOTRGatherPoint_Crossroads_1		


;////////////////////////////
;// Minas Tirith
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Druadan_Forest_1

WOTRGatherPoint_Druadan_Forest_1

WOTRSpawnPoint_Osgiliath_1

WOTRGatherPoint_Osgiliath_1		

WOTRSpawnPoint_Cair_Andros_1

WOTRGatherPoint_Cair_Andros_1

WOTRSpawnPoint_Harlond_1

WOTRGatherPoint_Harlond_1

WOTRSpawnPoint_Lossarnach_1

WOTRGatherPoint_Lossarnach_1			


;////////////////////////////
;// Osgiliath
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Cair_Andros_1

WOTRGatherPoint_Cair_Andros_1

WOTRSpawnPoint_Northern_Ithilien_1

WOTRGatherPoint_Northern_Ithilien_1		

WOTRSpawnPoint_Minas_Tirith_1

WOTRGatherPoint_Minas_Tirith_1

WOTRSpawnPoint_Crossroads_1

WOTRGatherPoint_Crossroads_1

WOTRSpawnPoint_Emyn_Arnen_1

WOTRGatherPoint_Emyn_Arnen_1		


;////////////////////////////
;// Crossroads
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Northern_Ithilien_1

WOTRGatherPoint_Northern_Ithilien_1

WOTRSpawnPoint_Osgiliath_1

WOTRGatherPoint_Osgiliath_1		

WOTRSpawnPoint_Emyn_Arnen_1

WOTRGatherPoint_Emyn_Arnen_1	


;////////////////////////////
;// Emyn Arnen
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Crossroads_1

WOTRGatherPoint_Crossroads_1

WOTRSpawnPoint_Osgiliath_1

WOTRGatherPoint_Osgiliath_1		

WOTRSpawnPoint_Central_Ithilien_1

WOTRGatherPoint_Central_Ithilien_1			

WOTRSpawnPoint_Minas_Morgul_1

WOTRGatherPoint_Minas_Morgul_1		


;////////////////////////////
;// Central Ithilien
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Emyn_Arnen_1

WOTRGatherPoint_Emyn_Arnen_1

WOTRSpawnPoint_Southern_Ithilien_1

WOTRGatherPoint_Southern_Ithilien_1				


;////////////////////////////
;// Southern Ithilien
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Central_Ithilien_1

WOTRGatherPoint_Central_Ithilien_1

WOTRSpawnPoint_Pelargir_1

WOTRGatherPoint_Pelargir_1		

WOTRSpawnPoint_Ethir_Anduin_1

WOTRGatherPoint_Ethir_Anduin_1	

WOTRSpawnPoint_Harondor_1

WOTRGatherPoint_Harondor_1

WOTRSpawnPoint_Harad_Road_1

WOTRGatherPoint_Harad_Road_1						


;////////////////////////////
;// Harlond
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Minas_Tirith_1

WOTRGatherPoint_Minas_Tirith_1	

WOTRSpawnPoint_Lossarnach_1

WOTRGatherPoint_Lossarnach_1		


;////////////////////////////
;// Lossarnach
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Minas_Tirith_1

WOTRGatherPoint_Minas_Tirith_1

WOTRSpawnPoint_Harlond_1

WOTRGatherPoint_Harlond_1

WOTRSpawnPoint_Pelargir_1

WOTRGatherPoint_Pelargir_1			


;////////////////////////////
;// Lebennin
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Pelargir_1

WOTRGatherPoint_Pelargir_1

WOTRSpawnPoint_Ringlo_Vale_1

WOTRGatherPoint_Ringlo_Vale_1		

WOTRSpawnPoint_Belfalas_1

WOTRGatherPoint_Belfalas_1		


;////////////////////////////
;// Pelargir
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Lossarnach_1

WOTRGatherPoint_Lossarnach_1

WOTRSpawnPoint_Southern_Ithilien_1

WOTRGatherPoint_Southern_Ithilien_1		

WOTRSpawnPoint_Ethir_Anduin_1

WOTRGatherPoint_Ethir_Anduin_1

WOTRSpawnPoint_Lebennin_1

WOTRGatherPoint_Lebennin_1

WOTRSpawnPoint_Tolfalas_1

WOTRGatherPoint_Tolfalas_1

WOTRSpawnPoint_Umbar_1

WOTRGatherPoint_Umbar_1

WOTRSpawnPoint_Dol_Amroth_1

WOTRGatherPoint_Dol_Amroth_1



;////////////////////////////
;// Ringlo Vale
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Lebennin_1

WOTRGatherPoint_Lebennin_1

WOTRSpawnPoint_Lamedon_1

WOTRGatherPoint_Lamedon_1		

WOTRSpawnPoint_Belfalas_1

WOTRGatherPoint_Belfalas_1		


;////////////////////////////
;// Belfalas
;////////////////////////////


WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Lebennin_1

WOTRGatherPoint_Lebennin_1

WOTRSpawnPoint_Ringlo_Vale_1

WOTRGatherPoint_Ringlo_Vale_1		

WOTRSpawnPoint_Lamedon_1

WOTRGatherPoint_Lamedon_1

WOTRSpawnPoint_Anfalas_1

WOTRGatherPoint_Anfalas_1

WOTRSpawnPoint_Dol_Amroth_1

WOTRGatherPoint_Dol_Amroth_1			


;////////////////////////////
;// Lamedon
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Belfalas_1

WOTRGatherPoint_Belfalas_1

WOTRSpawnPoint_Ringlo_Vale_1

WOTRGatherPoint_Ringlo_Vale_1		

WOTRSpawnPoint_Erech_1

WOTRGatherPoint_Erech_1

WOTRSpawnPoint_Anfalas_1

WOTRGatherPoint_Anfalas_1		


;////////////////////////////
;// Dol Amroth
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Belfalas_1

WOTRGatherPoint_Belfalas_1

WOTRSpawnPoint_Tolfalas_1

WOTRGatherPoint_Tolfalas_1

WOTRSpawnPoint_Grey_Havens_1

WOTRGatherPoint_Grey_Havens_1

WOTRSpawnPoint_Umbar_1

WOTRGatherPoint_Umbar_1

WOTRSpawnPoint_Pelargir_1

WOTRGatherPoint_Pelargir_1

WOTRSpawnPoint_Maros_1

WOTRGatherPoint_Maros_1	



;////////////////////////////
;// Erech
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Dunharrow_1

WOTRGatherPoint_Dunharrow_1

WOTRSpawnPoint_Lamedon_1

WOTRGatherPoint_Lamedon_1		

WOTRSpawnPoint_Anfalas_1

WOTRGatherPoint_Anfalas_1		


;////////////////////////////
;// Anfalas
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Erech_1

WOTRGatherPoint_Erech_1

WOTRSpawnPoint_Lamedon_1

WOTRGatherPoint_Lamedon_1		

WOTRSpawnPoint_Belfalas_1

WOTRGatherPoint_Belfalas_1

WOTRSpawnPoint_Andrast_1

WOTRGatherPoint_Andrast_1			


;////////////////////////////
;// Andrast
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Anfalas_1

WOTRGatherPoint_Anfalas_1

WOTRSpawnPoint_Druwaith_Iaur_1

WOTRGatherPoint_Druwaith_Iaur_1				


;////////////////////////////
;// Tolfalas
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Umbar_1

WOTRGatherPoint_Umbar_1

WOTRSpawnPoint_Pelargir_1

WOTRGatherPoint_Pelargir_1

WOTRSpawnPoint_Dol_Amroth_1

WOTRGatherPoint_Dol_Amroth_1

WOTRSpawnPoint_Maros_1

WOTRGatherPoint_Maros_1


//-----------------------------------------------------------------------------------------------------------------------------------------------------------------
// 										MORDOR REGION - 12 TERRITORIES - 4 SUB-REGIONS
//-----------------------------------------------------------------------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------
// DAGORLAD SUB-REGION
//-------------------------------------------------------------------------------------------------
;////////////////////////////
;// Black Gate
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Dagorlad_1

WOTRGatherPoint_Dagorlad_1

WOTRSpawnPoint_Dead_Marshes_1

WOTRGatherPoint_Dead_Marshes_1		

WOTRSpawnPoint_Durthang_1

WOTRGatherPoint_Durthang_1

WOTRSpawnPoint_Gorgoroth_1

WOTRGatherPoint_Gorgoroth_1			

WOTRSpawnPoint_Rhun_1

WOTRGatherPoint_Rhun_1		



;////////////////////////////
;// Dagorlad
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Black_Gate_1

WOTRGatherPoint_Black_Gate_1

WOTRSpawnPoint_Dead_Marshes_1

WOTRGatherPoint_Dead_Marshes_1		

WOTRSpawnPoint_Emyn_Muil_1

WOTRGatherPoint_Emyn_Muil_1

WOTRSpawnPoint_South_Rhun_1

WOTRGatherPoint_South_Rhun_1



;////////////////////////////
;// Dead Marshes
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Black_Gate_1

WOTRGatherPoint_Black_Gate_1

WOTRSpawnPoint_Dagorlad_1

WOTRGatherPoint_Dagorlad_1		

WOTRSpawnPoint_Emyn_Muil_1

WOTRGatherPoint_Emyn_Muil_1

WOTRSpawnPoint_Mouths_Entwash_1

WOTRGatherPoint_Mouths_Entwash_1

WOTRSpawnPoint_Northern_Ithilien_1

WOTRGatherPoint_Northern_Ithilien_1		


//-------------------------------------------------------------------------------------------------
// EPHEL DUATH SUB-REGION
//-------------------------------------------------------------------------------------------------
;////////////////////////////
;// Cirith_Ungol
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Durthang_1

WOTRGatherPoint_Durthang_1

WOTRSpawnPoint_Gorgoroth_1

WOTRGatherPoint_Gorgoroth_1

WOTRSpawnPoint_Minas_Morgul_1

WOTRGatherPoint_Minas_Morgul_1			



;////////////////////////////
;// Durthang
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Black_Gate_1

WOTRGatherPoint_Black_Gate_1	

WOTRSpawnPoint_Cirith_Ungol_1

WOTRGatherPoint_Cirith_Ungol_1

WOTRSpawnPoint_Gorgoroth_1

WOTRGatherPoint_Gorgoroth_1	



;////////////////////////////
;// Minas Morgul
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Cirith_Ungol_1

WOTRGatherPoint_Cirith_Ungol_1

WOTRSpawnPoint_Emyn_Arnen_1

WOTRGatherPoint_Emyn_Arnen_1	



//-------------------------------------------------------------------------------------------------
// GORGOROTH SUB-REGION
//-------------------------------------------------------------------------------------------------
;////////////////////////////
;// Ered Lithui
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Gorgoroth_1

WOTRGatherPoint_Gorgoroth_1

WOTRSpawnPoint_Mount_Doom_1

WOTRGatherPoint_Mount_Doom_1

WOTRSpawnPoint_Nurn_1

WOTRGatherPoint_Nurn_1

WOTRSpawnPoint_Sea_Of_Nurnen_1

WOTRGatherPoint_Sea_Of_Nurnen_1			


;////////////////////////////
;// Plains of Gorgoroth
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Black_Gate_1

WOTRGatherPoint_Black_Gate_1

WOTRSpawnPoint_Cirith_Ungol_1

WOTRGatherPoint_Cirith_Ungol_1		

WOTRSpawnPoint_Durthang_1

WOTRGatherPoint_Durthang_1

WOTRSpawnPoint_Ered_Lithui_1

WOTRGatherPoint_Ered_Lithui_1				

WOTRSpawnPoint_Mount_Doom_1

WOTRGatherPoint_Mount_Doom_1

WOTRSpawnPoint_Sea_Of_Nurnen_1

WOTRGatherPoint_Sea_Of_Nurnen_1	

WOTRSpawnPoint_Slavefields_Of_Nurn_1

WOTRGatherPoint_Slavefields_Of_Nurn_1		



;////////////////////////////
;// Mount_Doom
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Ered_Lithui_1

WOTRGatherPoint_Ered_Lithui_1				

WOTRSpawnPoint_Gorgoroth_1

WOTRGatherPoint_Gorgoroth_1


//-------------------------------------------------------------------------------------------------
// NURN SUB-REGION
//-------------------------------------------------------------------------------------------------
;////////////////////////////
;// Nurn
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Ered_Lithui_1

WOTRGatherPoint_Ered_Lithui_1				

WOTRSpawnPoint_Sea_Of_Nurnen_1

WOTRGatherPoint_Sea_Of_Nurnen_1



;////////////////////////////
;// Sea of Nurnen
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Ered_Lithui_1

WOTRGatherPoint_Ered_Lithui_1				

WOTRSpawnPoint_Gorgoroth_1

WOTRGatherPoint_Gorgoroth_1

WOTRSpawnPoint_Slavefields_Of_Nurn_1

WOTRGatherPoint_Slavefields_Of_Nurn_1

WOTRSpawnPoint_Nurn_1

WOTRGatherPoint_Nurn_1			



;////////////////////////////
;// Slavefields of Nurn
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Gorgoroth_1

WOTRGatherPoint_Gorgoroth_1

WOTRSpawnPoint_Sea_Of_Nurnen_1

WOTRGatherPoint_Sea_Of_Nurnen_1		


//-----------------------------------------------------------------------------------------------------------------------------------------------------------------
// 										RHOVANION REGION - 24 TERRITORIES - 5 SUB-REGIONS
//-----------------------------------------------------------------------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------
// ANDUIN SUB-REGION
//-------------------------------------------------------------------------------------------------
;////////////////////////////
;// Vale of Anduin
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Old_Ford_Anduin_1

WOTRGatherPoint_Old_Ford_Anduin_1

WOTRSpawnPoint_Taur_En_Ungolath_1

WOTRGatherPoint_Taur_En_Ungolath_1

WOTRSpawnPoint_Gladden_Fields_1

WOTRGatherPoint_Gladden_Fields_1

WOTRSpawnPoint_Taur_Hith_1

WOTRGatherPoint_Taur_Hith_1			


;////////////////////////////
;// Carrock
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Framsburg_1

WOTRGatherPoint_Framsburg_1

WOTRSpawnPoint_Northern_Mirkwood_1

WOTRGatherPoint_Northern_Mirkwood_1

WOTRSpawnPoint_Hall_Oak_1

WOTRGatherPoint_Hall_Oak_1

WOTRSpawnPoint_Forest_Gate_1

WOTRGatherPoint_Forest_Gate_1

WOTRSpawnPoint_Old_Ford_Anduin_1

WOTRGatherPoint_Old_Ford_Anduin_1	

WOTRSpawnPoint_High_Pass_1

WOTRGatherPoint_High_Pass_1			

;////////////////////////////
;// Framsburg
;////////////////////////////


WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Grey_Mountains_1

WOTRGatherPoint_Grey_Mountains_1

WOTRSpawnPoint_Northern_Mirkwood_1

WOTRGatherPoint_Northern_Mirkwood_1

WOTRSpawnPoint_Carrock_1		

WOTRGatherPoint_Carrock_1		


;////////////////////////////
;// Gladden Fields
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Vale_Anduin_1

WOTRGatherPoint_Vale_Anduin_1

WOTRSpawnPoint_Taur_En_Ungolath_1

WOTRGatherPoint_Taur_En_Ungolath_1

WOTRSpawnPoint_Dol_Guldur_1

WOTRGatherPoint_Dol_Guldur_1

WOTRSpawnPoint_Field_Celebrant_1

WOTRGatherPoint_Field_Celebrant_1

WOTRSpawnPoint_Taur_Hith_1

WOTRGatherPoint_Taur_Hith_1			
_1
;////////////////////////////
;// Old Fords of Anduin
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_High_Pass_1

WOTRGatherPoint_High_Pass_1

WOTRSpawnPoint_Carrock_1

WOTRGatherPoint_Carrock_1

WOTRSpawnPoint_Forest_Gate_1

WOTRGatherPoint_Forest_Gate_1

WOTRSpawnPoint_Mirkwood_1

WOTRGatherPoint_Mirkwood_1

WOTRSpawnPoint_Taur_En_Ungolath_1

WOTRGatherPoint_Taur_En_Ungolath_1

WOTRSpawnPoint_Vale_Anduin_1

WOTRGatherPoint_Vale_Anduin_1			


//-------------------------------------------------------------------------------------------------
// BROWN LANDS SUB-REGION
//-------------------------------------------------------------------------------------------------
;////////////////////////////
;// Amon Hen
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Old_Brown_Lands_1

WOTRGatherPoint_Old_Brown_Lands_1

WOTRSpawnPoint_Emyn_Muil_1

WOTRGatherPoint_Emyn_Muil_1

WOTRSpawnPoint_Mouths_Entwash_1

WOTRGatherPoint_Mouths_Entwash_1

WOTRSpawnPoint_Eastern_Rohan_1

WOTRGatherPoint_Eastern_Rohan_1

WOTRSpawnPoint_East_Emnet_1

WOTRGatherPoint_East_Emnet_1

WOTRSpawnPoint_The_Wold_1

WOTRGatherPoint_The_Wold_1			


;////////////////////////////
;// East Bight
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Vales_Celduin_1

WOTRGatherPoint_Vales_Celduin_1

WOTRSpawnPoint_Dorwinion_1

WOTRGatherPoint_Dorwinion_1

WOTRSpawnPoint_South_Rhun_1

WOTRGatherPoint_South_Rhun_1

WOTRSpawnPoint_Old_Brown_Lands_1

WOTRGatherPoint_Old_Brown_Lands_1

WOTRSpawnPoint_Mirkwood_1

WOTRGatherPoint_Mirkwood_1		


;////////////////////////////
;// Emyn Muil
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Old_Brown_Lands_1

WOTRGatherPoint_Old_Brown_Lands_1

WOTRSpawnPoint_South_Rhun_1

WOTRGatherPoint_South_Rhun_1

WOTRSpawnPoint_Dagorlad_1

WOTRGatherPoint_Dagorlad_1

WOTRSpawnPoint_Dead_Marshes_1

WOTRGatherPoint_Dead_Marshes_1

WOTRSpawnPoint_Mouths_Entwash_1

WOTRGatherPoint_Mouths_Entwash_1

WOTRSpawnPoint_Amon_Hen_1

WOTRGatherPoint_Amon_Hen_1			


;////////////////////////////
;// Fangorn
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Nan_Celebrant_1

WOTRGatherPoint_Nan_Celebrant_1

WOTRSpawnPoint_The_Wold_1

WOTRGatherPoint_The_Wold_1

WOTRSpawnPoint_Snowbourn_1

WOTRGatherPoint_Snowbourn_1

WOTRSpawnPoint_Eaves_Fangorn_1

WOTRGatherPoint_Eaves_Fangorn_1			


;////////////////////////////
;// Old Brown Lands
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Dol_Guldur_1

WOTRGatherPoint_Dol_Guldur_1

WOTRSpawnPoint_Mirkwood_1

WOTRGatherPoint_Mirkwood_1

WOTRSpawnPoint_East_Bight_1

WOTRGatherPoint_East_Bight_1

WOTRSpawnPoint_South_Rhun_1

WOTRGatherPoint_South_Rhun_1

WOTRSpawnPoint_Emyn_Muil_1

WOTRGatherPoint_Emyn_Muil_1	

WOTRSpawnPoint_Amon_Hen_1

WOTRGatherPoint_Amon_Hen_1	

WOTRSpawnPoint_The_Wold_1

WOTRGatherPoint_The_Wold_1

WOTRSpawnPoint_Field_Celebrant_1

WOTRGatherPoint_Field_Celebrant_1			


;////////////////////////////
;// The Wold
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Field_Celebrant_1

WOTRGatherPoint_Field_Celebrant_1

WOTRSpawnPoint_Old_Brown_Lands_1

WOTRGatherPoint_Old_Brown_Lands_1

WOTRSpawnPoint_Amon_Hen_1

WOTRGatherPoint_Amon_Hen_1

WOTRSpawnPoint_East_Emnet_1

WOTRGatherPoint_East_Emnet_1

WOTRSpawnPoint_Snowbourn_1

WOTRGatherPoint_Snowbourn_1	

WOTRSpawnPoint_Fangorn_1

WOTRGatherPoint_Fangorn_1	

WOTRSpawnPoint_Nan_Celebrant_1

WOTRGatherPoint_Nan_Celebrant_1		


//-------------------------------------------------------------------------------------------------
// DOL GULDUR SUB-REGION
//-------------------------------------------------------------------------------------------------
;////////////////////////////
;// Dol Guldur
;////////////////////////////

WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Taur_En_Ungolath_1

WOTRGatherPoint_Taur_En_Ungolath_1

WOTRSpawnPoint_Mirkwood_1

WOTRGatherPoint_Mirkwood_1

WOTRSpawnPoint_Old_Brown_Lands_1

WOTRGatherPoint_Old_Brown_Lands_1

WOTRSpawnPoint_Field_Celebrant_1

WOTRGatherPoint_Field_Celebrant_1	

WOTRSpawnPoint_Gladden_Fields_1

WOTRGatherPoint_Gladden_Fields_1

;////////////////////////////
;// Taur-en-Ungolath
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Mirkwood_1

WOTRGatherPoint_Mirkwood_1

WOTRSpawnPoint_Dol_Guldur_1

WOTRGatherPoint_Dol_Guldur_1

WOTRSpawnPoint_Gladden_Fields_1

WOTRGatherPoint_Gladden_Fields_1

WOTRSpawnPoint_Vale_Anduin_1

WOTRGatherPoint_Vale_Anduin_1

WOTRSpawnPoint_Old_Ford_Anduin_1

WOTRGatherPoint_Old_Ford_Anduin_1	


//-------------------------------------------------------------------------------------------------
// LOTHLORIEN SUB-REGION
//-------------------------------------------------------------------------------------------------
;////////////////////////////
;// Field of Celebrant
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Gladden_Fields_1

WOTRGatherPoint_Gladden_Fields_1

WOTRSpawnPoint_Dol_Guldur_1

WOTRGatherPoint_Dol_Guldur_1

WOTRSpawnPoint_Old_Brown_Lands_1

WOTRGatherPoint_Old_Brown_Lands_1

WOTRSpawnPoint_The_Wold_1

WOTRGatherPoint_The_Wold_1

WOTRSpawnPoint_Nan_Celebrant_1

WOTRGatherPoint_Nan_Celebrant_1

WOTRSpawnPoint_Lothlorien_1

WOTRGatherPoint_Lothlorien_1

WOTRSpawnPoint_Taur_Hith_1

WOTRGatherPoint_Taur_Hith_1		


;////////////////////////////
;// Lothlorien
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Caradhras_1

WOTRGatherPoint_Caradhras_1	

WOTRSpawnPoint_Dimrill_Dale_1

WOTRGatherPoint_Dimrill_Dale_1

WOTRSpawnPoint_Field_Celebrant_1

WOTRGatherPoint_Field_Celebrant_1

WOTRSpawnPoint_Nan_Celebrant_1

WOTRGatherPoint_Nan_Celebrant_1		

WOTRSpawnPoint_Taur_Hith_1

WOTRGatherPoint_Taur_Hith_1

;////////////////////////////
;// Nan_Celebrant
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Lothlorien_1

WOTRGatherPoint_Lothlorien_1

WOTRSpawnPoint_Field_Celebrant_1

WOTRGatherPoint_Field_Celebrant_1

WOTRSpawnPoint_The_Wold_1

WOTRGatherPoint_The_Wold_1

WOTRSpawnPoint_Fangorn_1

WOTRGatherPoint_Fangorn_1

WOTRSpawnPoint_Dimrill_Dale_1

WOTRGatherPoint_Dimrill_Dale_1		


;////////////////////////////
;// Taur Hithlin
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Vale_Anduin_1

WOTRGatherPoint_Vale_Anduin_1

WOTRSpawnPoint_Gladden_Fields_1

WOTRGatherPoint_Gladden_Fields_1

WOTRSpawnPoint_Field_Celebrant_1

WOTRGatherPoint_Field_Celebrant_1

WOTRSpawnPoint_Lothlorien_1

WOTRGatherPoint_Lothlorien_1

WOTRSpawnPoint_Caradhras_1

WOTRGatherPoint_Caradhras_1		


//-------------------------------------------------------------------------------------------------
// WOODLAND REALM SUB-REGION
//-------------------------------------------------------------------------------------------------
;////////////////////////////
;// Forest Gate
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Hall_Oak_1

WOTRGatherPoint_Hall_Oak_1

WOTRSpawnPoint_Halls_Elvenking_1

WOTRGatherPoint_Halls_Elvenking_1

WOTRSpawnPoint_Mirkwood_1

WOTRGatherPoint_Mirkwood_1

WOTRSpawnPoint_Old_Ford_Anduin_1

WOTRGatherPoint_Old_Ford_Anduin_1

WOTRSpawnPoint_Carrock_1

WOTRGatherPoint_Carrock_1

;////////////////////////////
;// Halls of the Elvenking
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Taur_Na_Faroth_1

WOTRGatherPoint_Taur_Na_Faroth_1	

WOTRSpawnPoint_Erebor_1

WOTRGatherPoint_Erebor_1

WOTRSpawnPoint_Esgaroth_1

WOTRGatherPoint_Esgaroth_1

WOTRSpawnPoint_Taur_En_Morvith_1

WOTRGatherPoint_Taur_En_Morvith_1		

WOTRSpawnPoint_Mirkwood_1

WOTRGatherPoint_Mirkwood_1

WOTRSpawnPoint_Forest_Gate_1

WOTRGatherPoint_Forest_Gate_1

WOTRSpawnPoint_Hall_Oak_1

WOTRGatherPoint_Hall_Oak_1

WOTRSpawnPoint_Northern_Mirkwood_1

WOTRGatherPoint_Northern_Mirkwood_1			



;////////////////////////////
;// Hall of Oak
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Northern_Mirkwood_1

WOTRGatherPoint_Northern_Mirkwood_1

WOTRSpawnPoint_Halls_Elvenking_1

WOTRGatherPoint_Halls_Elvenking_1

WOTRSpawnPoint_Forest_Gate_1

WOTRGatherPoint_Forest_Gate_1

WOTRSpawnPoint_Carrock_1

WOTRGatherPoint_Carrock_1


;////////////////////////////
;// Mirkwood
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Dol_Guldur_1

WOTRGatherPoint_Dol_Guldur_1

WOTRSpawnPoint_Taur_En_Ungolath_1

WOTRGatherPoint_Taur_En_Ungolath_1

WOTRSpawnPoint_East_Bight_1

WOTRGatherPoint_East_Bight_1

WOTRSpawnPoint_Halls_Elvenking_1

WOTRGatherPoint_Halls_Elvenking_1

WOTRSpawnPoint_Old_Brown_Lands_1

WOTRGatherPoint_Old_Brown_Lands_1

WOTRSpawnPoint_Old_Ford_Anduin_1

WOTRGatherPoint_Old_Ford_Anduin_1

WOTRSpawnPoint_Vales_Celduin_1

WOTRGatherPoint_Vales_Celduin_1

WOTRSpawnPoint_Forest_Gate_1

WOTRGatherPoint_Forest_Gate_1

WOTRSpawnPoint_Taur_En_Morvith_1

WOTRGatherPoint_Taur_En_Morvith_1		


;////////////////////////////
;// Northern Mirkwood
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Taur_Na_Faroth_1

WOTRGatherPoint_Taur_Na_Faroth_1

WOTRSpawnPoint_Halls_Elvenking_1

WOTRGatherPoint_Halls_Elvenking_1

WOTRSpawnPoint_Hall_Oak_1

WOTRGatherPoint_Hall_Oak_1

WOTRSpawnPoint_Carrock_1

WOTRGatherPoint_Carrock_1

WOTRSpawnPoint_Framsburg_1

WOTRGatherPoint_Framsburg_1

WOTRSpawnPoint_Grey_Mountains_1

WOTRGatherPoint_Grey_Mountains_1	

;////////////////////////////
;// Taur-en-Morvith
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Esgaroth_1

WOTRGatherPoint_Esgaroth_1

WOTRSpawnPoint_Vales_Celduin_1

WOTRGatherPoint_Vales_Celduin_1

WOTRSpawnPoint_Mirkwood_1

WOTRGatherPoint_Mirkwood_1

WOTRSpawnPoint_Halls_Elvenking_1

WOTRGatherPoint_Halls_Elvenking_1



;////////////////////////////
;// Taur-na-Faroth
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Grey_Mountains_1

WOTRGatherPoint_Grey_Mountains_1

WOTRSpawnPoint_Withered_Heath_1

WOTRGatherPoint_Withered_Heath_1

WOTRSpawnPoint_Erebor_1

WOTRGatherPoint_Erebor_1

WOTRSpawnPoint_Halls_Elvenking_1

WOTRGatherPoint_Halls_Elvenking_1

WOTRSpawnPoint_Northern_Mirkwood_1

WOTRGatherPoint_Northern_Mirkwood_1		



//-----------------------------------------------------------------------------------------------------------------------------------------------------------------
// 										RHUN REGION - 7 TERRITORIES - 3 SUB-REGIONS
//-----------------------------------------------------------------------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------
// DORWINION SUB-REGION
//-------------------------------------------------------------------------------------------------
;////////////////////////////
;// Dorwinion
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Carnen_1

WOTRGatherPoint_Carnen_1

WOTRSpawnPoint_Rhun_1

WOTRGatherPoint_Rhun_1

WOTRSpawnPoint_South_Rhun_1

WOTRGatherPoint_South_Rhun_1

WOTRSpawnPoint_Vales_Celduin_1

WOTRGatherPoint_Vales_Celduin_1	

WOTRSpawnPoint_East_Bight_1

WOTRGatherPoint_East_Bight_1		



//-------------------------------------------------------------------------------------------------
// RHÛN SUB-REGION
//-------------------------------------------------------------------------------------------------
;////////////////////////////
;// Kunin
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Steppes_Sarakhax_1

WOTRGatherPoint_Steppes_Sarakhax_1

WOTRSpawnPoint_Rhun_1

WOTRGatherPoint_Rhun_1

WOTRSpawnPoint_Ul_Tala_1

WOTRGatherPoint_Ul_Tala_1		



;////////////////////////////
;// Rhûn
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Steppes_Sarakhax_1

WOTRGatherPoint_Steppes_Sarakhax_1

WOTRSpawnPoint_Kunin_1

WOTRGatherPoint_Kunin_1

WOTRSpawnPoint_Ul_Tala_1

WOTRGatherPoint_Ul_Tala_1	

WOTRSpawnPoint_Carnen_1

WOTRGatherPoint_Carnen_1

WOTRSpawnPoint_Dorwinion_1

WOTRGatherPoint_Dorwinion_1			


;////////////////////////////
;// Steppes of Sarâkhax
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Kunin_1

WOTRGatherPoint_Kunin_1

WOTRSpawnPoint_Rhun_1

WOTRGatherPoint_Rhun_1	

WOTRSpawnPoint_Surubeki_1

WOTRGatherPoint_Surubeki_1		



;////////////////////////////
;// Ul-tala
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Kunin_1

WOTRGatherPoint_Kunin_1

WOTRSpawnPoint_Rhun_1

WOTRGatherPoint_Rhun_1	


//-------------------------------------------------------------------------------------------------
// SOUTH RHÛN SUB-REGION
//-------------------------------------------------------------------------------------------------
;////////////////////////////
;// Surubeki
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Steppes_Sarakhax_1

WOTRGatherPoint_Steppes_Sarakhax_1

WOTRSpawnPoint_South_Rhun_1

WOTRGatherPoint_South_Rhun_1		


;////////////////////////////
;// South Rhûn
;////////////////////////////



WOTRSpawnPoint_DefenderReinforcements_1

WOTRGatherPoint_DefenderReinforcements_1

WOTRSpawnPoint_Dorwinion_1

WOTRGatherPoint_Dorwinion_1		

WOTRSpawnPoint_Surubeki_1

WOTRGatherPoint_Surubeki_1

WOTRSpawnPoint_East_Bight_1

WOTRGatherPoint_East_Bight_1

WOTRSpawnPoint_Old_Brown_Lands_1

WOTRGatherPoint_Old_Brown_Lands_1

WOTRSpawnPoint_Emyn_Muil_1

WOTRGatherPoint_Emyn_Muil_1

WOTRSpawnPoint_Dagorlad_1

WOTRGatherPoint_Dagorlad_1				
