;/////////////////////////////////////////////////////////////////////////////
;///							Map Evil Lorien                            ///
;///////////////////////////////////////////////////////////////////////////// 


MissionObjectiveList

;    MissionObjectiveTag         = SCRIPT:OBJECTIVE_SPELorien_01		; Build a Goblin Cave
;    MissionObjectiveTag         = SCRIPT:OBJECTIVE_SPELorien_02		; Build Goblin Hordes
;	MissionObjectiveTag         = SCRIPT:OBJECTIVE_SPELorien_03		; Build a Tunnel.
;	MissionObjectiveTag         = SCRIPT:OBJECTIVE_SPELorien_04		; Build a Fissure.
;	MissionObjectiveTag         = SCRIPT:OBJECTIVE_SPELorien_05		; Upgrade Fissure
;	MissionObjectiveTag         = SCRIPT:OBJECTIVE_SPELorien_06		; Build Cave Trolls.
	MissionObjectiveTag         = SCRIPT:OBJECTIVE_SPELorien_08		; Cross the River & destroy Treehouses
    MissionObjectiveTag         = SCRIPT:OBJECTIVE_SPELorien_09		; Destroy Lorien Stronghold
;    BonusMissionObjectiveTag    = SCRIPT:OBJECTIVE_SPELorien_07		; Build Fortress Upgrades.
    BonusMissionObjectiveTag    = SCRIPT:BONUS_SPELorien_01         ; Free all 3 Giants.
;   BonusMissionObjectiveTag    = SCRIPT:BONUS_SPELorien_02         ; Build a tunnel across the river
;   BonusMissionObjectiveTag    = SCRIPT:BONUS_SPELorien_03         ; Revive a hero (if dead)

End

;-----------------------------------------------------------------

; WaterTransparency can be overridden per each map to change these values.
WaterTransparency
  ReflectionPlaneZ = 80.0;
  ReflectionOn = Yes
End


Weather

  HardwareFogColor = R:220 G:226 B:235

  HardwareFogEnable = Yes

  HardwareFogStart = 450

  HardwareFogEnd = 2000

End

AIData

  LowLodTreeName = TreeLowLODGreyHavens

END

;///////////////////////////////////////////////////////////////////////////// 
;
;Object ElvenHaldir
;
;	LocomotorSet
;		Locomotor = HumanLocomotor
;		Condition = SET_NORMAL 
;		Speed     = 75	
;	End
;End
;
;///////////////////////////////////////////////////////////////////////////// 
;
;Object ElvenGaladrielLorien
;	LocomotorSet
;		Locomotor = HeroHumanLocomotor
;		Condition = SET_NORMAL 
;		Speed     = 75
;	End
;End
;
;///////////////////////////////////////////////////////////////////////////// 

CommandSet GuldurPorterCommandSetX
	1  = Command_EvilStop
	2  = Command_SpecialAbilityGuldurShade
	3  = Command_PorterConstructGuldurSlaveMill
	4  = Command_PorterConstructGuldurFountOfCorruption
	5  = Command_PorterConstructGuldurGaol
	6  = Command_PorterConstructGuldurSpiderLair
	7  = Command_PorterConstructGuldurRuinousTower
	8 = Command_PorterConstructGuldurFortress
End

Object GuldurPorter
CommandSet = GuldurPorterCommandSetX
End

Object GuldurSpiderLair
CommandSet = GuldurSpiderLairCommandSetX
ReplaceModule ModueTag_SpiderPitLevel2CommandSet
Behavior = CommandSetUpgrade ModueTag_SpiderPitLevel2CommandSetX
		TriggeredBy			= Upgrade_StructureLevel2
		ConflictsWith		= Upgrade_StructureLevel3
		CommandSet			= GuldurSpiderLairCommandSetLevel2X
	End   
End
ReplaceModule ModueTag_SpiderPitLevel3CommandSet
	Behavior = CommandSetUpgrade ModueTag_SpiderPitLevel3CommandSetX
		TriggeredBy			= Upgrade_StructureLevel3		
		CommandSet			= GuldurSpiderLairCommandSetLevel3X
	End  
End
End

CommandSet GuldurSpiderLairCommandSetX
	1 = Command_SpecialAbilityDarkPresence
	2 = Command_SpecialAbilitySpiderLairInfestation
	3 = Command_ConstructGuldurFellBroodHorde
	4 = Command_ConstructGuldurSpiderRiderHorde
      5 = Command_ConstructGuldurGreatSpider
	6 = Command_PurchaseUpgradeGuldurSpiderLairLevel2
	7 = Command_Sell
End
CommandSet GuldurSpiderLairCommandSetLevel2X
	1 = Command_SpecialAbilityDarkPresence
	2 = Command_SpecialAbilitySpiderLairInfestation
	3 = Command_ConstructGuldurFellBroodHorde
	4 = Command_ConstructGuldurSpiderRiderHorde
      5 = Command_ConstructGuldurGreatSpider
      6 = Command_PurchaseUpgradeGuldurSpiderLairLevel3
	7 = Command_Sell
End
CommandSet GuldurSpiderLairCommandSetLevel3X
	1 = Command_SpecialAbilityDarkPresence
	2 = Command_SpecialAbilitySpiderLairInfestation
	3 = Command_ConstructGuldurFellBroodHorde
	4 = Command_ConstructGuldurSpiderRiderHorde
      5 = Command_ConstructGuldurGreatSpider
	6 = Command_Sell
End

CommandSet GuldurFortressCommandSetX
	InitialVisible = 5
	//Main Menu
	1   = Command_SpecialAbilityDarkPresence
	2   = Command_ConstructGuldurPorter
	3   = Command_SelectUpgradesGuldurFortress
	5   = Command_SpecialAbilityGuldurEnsnareCaster ; Command_SpecialAbilityGuldurEnsnare
	4	= Command_Sell
	//Upgrades Menu
	9  = Command_PurchaseUpgradeGuldurFortressFireArrows
	10  = Command_PurchaseUpgradeGuldurFortressBlight
	11  = Command_PurchaseUpgradeGuldurFortressSorcery
	12	= Command_RadialBack
End

Object GuldurFortress		
	CommandSet = GuldurFortressCommandSetX
End

Object GuldurFortressCitadel		
	CommandSet = GuldurFortressCommandSetX
End

;;-------------------------------------------------------------------------------------------------------
; BFME 2 SPELLBOOK
;-------------------------------------------------------------------------------------------------------


CommandSet EvilSpellBookCommandSetX
	1 = Command_SpellBookWarChantMordor
	2 = Command_SpellBookCaveBats
	3 = Command_SpellBookChillWind
	
	4 = Command_SpellBookGuldurForestOfFear
	5 = Command_SpellBookGuldurBlackWarg
	6 = Command_SpellBookAOTRScavenger
	7 = Command_SpellBookBarricade
	
	8 = Command_SpellBookWatcherAlly
	9 = Command_SpellBookGuldurDarkness
	10 = Command_SpellBookDragonStrike
	
	11 = Command_SpellBookRainOfFire
	12 = Command_SpellBookEyeofSauronNew
End

CommandSet EvilSpellStoreCommandSetX
	1 = Command_PurchaseSpellWarChantMordor
	2 = Command_PurchaseSpellCaveBats
	3 = Command_PurchaseSpellChillWind
	
	4 = Command_PurchaseSpellGuldurForestOfFear
	5 = Command_PurchaseSpellGuldurBlackWarg
	6 = Command_PurchaseSpellAOTRScavenger
	7 = Command_PurchaseSpellBarricade
	
	8 = Command_PurchaseSpellWatcherAlly
	9 = Command_PurchaseSpellGuldurDarkness
	10 = Command_PurchaseSpellDragonStrike
	
	11 = Command_PurchaseSpellRainOfFire
	12 = Command_PurchaseSpellEyeofSauronNew
End


;-------5 points
Science SCIENCE_WarChantMordor
  PrerequisiteSciences = SCIENCE_MORDOR OR SCIENCE_EVIL
  SciencePurchasePointCost = EVIL_RANK_1_COST
  SciencePurchasePointCostMP = 5
  IsGrantable = Yes
End
Science SCIENCE_CaveBats
  PrerequisiteSciences = SCIENCE_EVIL OR SCIENCE_MORDOR OR SCIENCE_ELVES OR SCIENCE_DWARVES OR SCIENCE_ARNOR
  SciencePurchasePointCost = EVIL_RANK_1_COST
  SciencePurchasePointCostMP = 5
  IsGrantable = Yes
End
Science SCIENCE_ChillWind
  PrerequisiteSciences = SCIENCE_GULDUR OR SCIENCE_EVIL ;SCIENCE_EnshroudingMistSP
  SciencePurchasePointCost = EVIL_RANK_1_COST
  SciencePurchasePointCostMP = 5
  IsGrantable = Yes
End
;-------10 points
Science SCIENCE_GuldurFearForest
  PrerequisiteSciences = SCIENCE_GULDUR OR SCIENCE_EVIL SCIENCE_WarChantMordor
  SciencePurchasePointCost = EVIL_RANK_2_COST
  SciencePurchasePointCostMP = 10
  IsGrantable = Yes
End
Science SCIENCE_GuldurBlackWarg
  PrerequisiteSciences = SCIENCE_EVIL OR SCIENCE_EVIL SCIENCE_WarChantMordor OR SCIENCE_EVIL SCIENCE_CaveBats
  SciencePurchasePointCost = EVIL_RANK_2_COST
  SciencePurchasePointCostMP = 10
  IsGrantable = Yes
End
Science SCIENCE_Scavenger
  PrerequisiteSciences = SCIENCE_GULDUR OR SCIENCE_EVIL SCIENCE_CaveBats OR SCIENCE_ChillWind
  SciencePurchasePointCost = EVIL_RANK_2_COST
  SciencePurchasePointCostMP = 10
  IsGrantable = Yes
End
Science SCIENCE_Barricade
  PrerequisiteSciences = SCIENCE_GULDUR OR SCIENCE_EVIL SCIENCE_ChillWind
  SciencePurchasePointCost = EVIL_RANK_2_COST
  SciencePurchasePointCostMP = 10
  IsGrantable = Yes
End
;-------15 points
Science SCIENCE_WatcherAlly
  PrerequisiteSciences = SCIENCE_GULDUR OR SCIENCE_EVIL SCIENCE_GuldurFearForest OR SCIENCE_GuldurBlackWarg
  SciencePurchasePointCost = EVIL_RANK_3_COST
  SciencePurchasePointCostMP = 15
  IsGrantable = Yes
End
Science SCIENCE_GuldurDarkness
  PrerequisiteSciences = SCIENCE_GULDUR OR SCIENCE_EVIL SCIENCE_GuldurBlackWarg OR SCIENCE_Scavenger
  SciencePurchasePointCost = EVIL_RANK_3_COST
  SciencePurchasePointCostMP = 15
  IsGrantable = Yes
End
Science SCIENCE_DragonStrike
  PrerequisiteSciences = SCIENCE_GULDUR OR SCIENCE_EVIL SCIENCE_Scavenger OR SCIENCE_Barricade
  SciencePurchasePointCost = EVIL_RANK_3_COST
  SciencePurchasePointCostMP = 15
  IsGrantable = Yes
End
;-------25 points
Science SCIENCE_RainOfFire
  PrerequisiteSciences = SCIENCE_GULDUR OR SCIENCE_EVIL SCIENCE_WatcherAlly OR SCIENCE_GuldurDarkness
  SciencePurchasePointCost = EVIL_RANK_4_COST
  SciencePurchasePointCostMP = 25
  IsGrantable = Yes
End
Science SCIENCE_EyeofSauronNew
  PrerequisiteSciences = SCIENCE_GULDUR OR SCIENCE_EVIL SCIENCE_DragonStrike OR SCIENCE_GuldurDarkness
  SciencePurchasePointCost = EVIL_RANK_4_COST
  SciencePurchasePointCostMP = 25
  IsGrantable = Yes
End

Object EvilSpellBook
CommandSet = EvilSpellBookCommandSetX
End

;-------------------------------------------------------------------------------------------------
;BFME 2 PLAYER PORTERS AND SPELLBOOK
;-------------------------------------------------------------------------------------------------

PlayerTemplate FactionCivilian
StartingBuilding = NONE
StartingUnit0 = NONE
StartingUnit1 = NONE
StartingUnit2 =  NONE
StartingUnitOffset2 = X:300 Y:0 Z:0
StartingUnit3 = NONE
StartingUnitOffset3 = X:0 Y:300 Z:0
StartingUnit4 = NONE
StartingUnitOffset4 = X:-300 Y:0 Z:0
StartingUnit7 = NONE
StartingUnitOffset7 = X:0 Y:-300 Z:0
StartMoney = 0
DefaultPlayerAIType		= NONE
	IntrinsicSciences		= SCIENCE_GOOD
	IntrinsicSciencesMP 		= SCIENCE_GOOD
	SpellBook			= GoodSpellBook
	SpellBookMp			= GoodSpellBook
	PurchaseScienceCommandSet	= GoodSpellStoreCommandSetX
	PurchaseScienceCommandSetMP	= GoodSpellStoreCommandSetX
End

PlayerTemplate FactionMen
Side = Fellowship
StartingBuilding = NONE
StartingUnit0 = NONE
StartingUnit1 = NONE
StartingUnit2 =  NONE
StartingUnitOffset2 = X:300 Y:0 Z:0
StartingUnit3 = NONE
StartingUnitOffset3 = X:0 Y:300 Z:0
StartingUnit4 = NONE
StartingUnitOffset4 = X:-300 Y:0 Z:0
StartingUnit7 = NONE
StartingUnitOffset7 = X:0 Y:-300 Z:0
StartMoney = 0
BuildableHeroesMP		= NONE
DefaultPlayerAIType		= NONE
	IntrinsicSciences		= SCIENCE_EVIL
	IntrinsicSciencesMP 		= SCIENCE_EVIL
	SpellBook			= EvilSpellBook
	SpellBookMp			= EvilSpellBook
	PurchaseScienceCommandSet	= EvilSpellStoreCommandSetX
	PurchaseScienceCommandSetMP	= EvilSpellStoreCommandSetX
End

PlayerTemplate FactionDwarves
StartingBuilding = NONE
StartingUnit0 = NONE
StartingUnit1 = NONE
StartingUnit2 =  NONE
StartingUnitOffset2 = X:300 Y:0 Z:0
StartingUnit3 = NONE
StartingUnitOffset3 = X:0 Y:300 Z:0
StartingUnit4 = NONE
StartingUnitOffset4 = X:-300 Y:0 Z:0
StartingUnit7 = NONE
StartingUnitOffset7 = X:0 Y:-300 Z:0
StartMoney = 0
BuildableHeroesMP		= NONE
DefaultPlayerAIType		= NONE
	IntrinsicSciences		= SCIENCE_EVIL
	IntrinsicSciencesMP 		= SCIENCE_EVIL
	SpellBook			= EvilSpellBook
	SpellBookMp			= EvilSpellBook
	PurchaseScienceCommandSet	= EvilSpellStoreCommandSetX
	PurchaseScienceCommandSetMP	= EvilSpellStoreCommandSetX
End

PlayerTemplate FactionElves
StartingBuilding = NONE
StartingUnit0 = NONE
StartingUnit1 = NONE
StartingUnit2 =  NONE
StartingUnitOffset2 = X:300 Y:0 Z:0
StartingUnit3 = NONE
StartingUnitOffset3 = X:0 Y:300 Z:0
StartingUnit4 = NONE
StartingUnitOffset4 = X:-300 Y:0 Z:0
StartingUnit7 = NONE
StartingUnitOffset7 = X:0 Y:-300 Z:0
StartMoney = 0
BuildableHeroesMP		= NONE
DefaultPlayerAIType		= NONE
	IntrinsicSciences		= SCIENCE_EVIL
	IntrinsicSciencesMP 		= SCIENCE_EVIL
	SpellBook			= EvilSpellBook
	SpellBookMp			= EvilSpellBook
	PurchaseScienceCommandSet	= EvilSpellStoreCommandSetX
	PurchaseScienceCommandSetMP	= EvilSpellStoreCommandSetX
End

PlayerTemplate FactionRohan
Side = Fellowship
StartingBuilding = NONE
StartingUnit0 = NONE
StartingUnit1 = NONE
StartingUnit2 =  NONE
StartingUnitOffset2 = X:300 Y:0 Z:0
StartingUnit3 = NONE
StartingUnitOffset3 = X:0 Y:300 Z:0
StartingUnit4 = NONE
StartingUnitOffset4 = X:-300 Y:0 Z:0
StartingUnit7 = NONE
StartingUnitOffset7 = X:0 Y:-300 Z:0
StartMoney = 0
BuildableHeroesMP		= NONE
DefaultPlayerAIType		= NONE
	IntrinsicSciences		= SCIENCE_EVIL
	IntrinsicSciencesMP 		= SCIENCE_EVIL
	SpellBook			= EvilSpellBook
	SpellBookMp			= EvilSpellBook
	PurchaseScienceCommandSet	= EvilSpellStoreCommandSetX
	PurchaseScienceCommandSetMP	= EvilSpellStoreCommandSetX
End

PlayerTemplate FactionGuldur
StartingBuilding = NONE
StartingUnit0 = NONE
StartingUnit1 = NONE
StartingUnit2 =  NONE
StartingUnitOffset2 = X:300 Y:0 Z:0
StartingUnit3 = NONE
StartingUnitOffset3 = X:0 Y:300 Z:0
StartingUnit4 = NONE
StartingUnitOffset4 = X:-300 Y:0 Z:0
StartingUnit7 = NONE
StartingUnitOffset7 = X:0 Y:-300 Z:0
StartMoney = 0
BuildableHeroesMP		= NONE
DefaultPlayerAIType		= NONE
	IntrinsicSciences		= SCIENCE_EVIL
	IntrinsicSciencesMP 		= SCIENCE_EVIL
	SpellBook			= EvilSpellBook
	SpellBookMp			= EvilSpellBook
	PurchaseScienceCommandSet	= EvilSpellStoreCommandSetX
	PurchaseScienceCommandSetMP	= EvilSpellStoreCommandSetX
End

PlayerTemplate FactionWild
StartingBuilding = NONE
StartingUnit0 = NONE
StartingUnit1 = NONE
StartingUnit2 =  NONE
StartingUnitOffset2 = X:300 Y:0 Z:0
StartingUnit3 = NONE
StartingUnitOffset3 = X:0 Y:300 Z:0
StartingUnit4 = NONE
StartingUnitOffset4 = X:-300 Y:0 Z:0
StartingUnit7 = NONE
StartingUnitOffset7 = X:0 Y:-300 Z:0
StartMoney = 0
BuildableHeroesMP		= NONE
DefaultPlayerAIType		= NONE
	IntrinsicSciences		= SCIENCE_EVIL
	IntrinsicSciencesMP 		= SCIENCE_EVIL
	SpellBook			= EvilSpellBook
	SpellBookMp			= EvilSpellBook
	PurchaseScienceCommandSet	= EvilSpellStoreCommandSetX
	PurchaseScienceCommandSetMP	= EvilSpellStoreCommandSetX
End


PlayerTemplate FactionMordor
StartingBuilding = NONE
StartingUnit0 = NONE
StartingUnit1 = NONE
StartingUnit2 =  NONE
StartingUnitOffset2 = X:300 Y:0 Z:0
StartingUnit3 = NONE
StartingUnitOffset3 = X:0 Y:300 Z:0
StartingUnit4 = NONE
StartingUnitOffset4 = X:-300 Y:0 Z:0
StartingUnit7 = NONE
StartingUnitOffset7 = X:0 Y:-300 Z:0
StartMoney = 0
BuildableHeroesMP		= NONE
DefaultPlayerAIType		= NONE
	IntrinsicSciences		= SCIENCE_EVIL
	IntrinsicSciencesMP 		= SCIENCE_EVIL
	SpellBook			= EvilSpellBook
	SpellBookMp			= EvilSpellBook
	PurchaseScienceCommandSet	= EvilSpellStoreCommandSetX
	PurchaseScienceCommandSetMP	= EvilSpellStoreCommandSetX
End


PlayerTemplate FactionIsengard
StartingBuilding = NONE
StartingUnit0 = NONE
StartingUnit1 = NONE
StartingUnit2 =  NONE
StartingUnitOffset2 = X:300 Y:0 Z:0
StartingUnit3 = NONE
StartingUnitOffset3 = X:0 Y:300 Z:0
StartingUnit4 = NONE
StartingUnitOffset4 = X:-300 Y:0 Z:0
StartingUnit7 = NONE
StartingUnitOffset7 = X:0 Y:-300 Z:0
StartMoney = 0
BuildableHeroesMP		= NONE
DefaultPlayerAIType		= NONE
	IntrinsicSciences		= SCIENCE_EVIL
	IntrinsicSciencesMP 		= SCIENCE_EVIL
	SpellBook			= EvilSpellBook
	SpellBookMp			= EvilSpellBook
	PurchaseScienceCommandSet	= EvilSpellStoreCommandSetX
	PurchaseScienceCommandSetMP	= EvilSpellStoreCommandSetX
End


PlayerTemplate FactionArnor
StartingBuilding = NONE
StartingUnit0 = NONE
StartingUnit1 = NONE
StartingUnit2 =  NONE
StartingUnitOffset2 = X:300 Y:0 Z:0
StartingUnit3 = NONE
StartingUnitOffset3 = X:0 Y:300 Z:0
StartingUnit4 = NONE
StartingUnitOffset4 = X:-300 Y:0 Z:0
StartingUnit7 = NONE
StartingUnitOffset7 = X:0 Y:-300 Z:0
StartMoney = 0
BuildableHeroesMP		= NONE
DefaultPlayerAIType		= NONE
	IntrinsicSciences		= SCIENCE_EVIL
	IntrinsicSciencesMP 		= SCIENCE_EVIL
	SpellBook			= EvilSpellBook
	SpellBookMp			= EvilSpellBook
	PurchaseScienceCommandSet	= EvilSpellStoreCommandSetX
	PurchaseScienceCommandSetMP	= EvilSpellStoreCommandSetX
End

CommandSet MordorMouthOfSauronCommandSetX
	1 	= Command_ToggleStance
	2 	= Command_MountHorseMouthOfSauron
	3 	= Command_MouthOfSauronDoubtCampaign
	4 	= Command_MOSAmbassador ;Command_MouthOfSauronEvilEye
	5 	= Command_SpecialAbilityMOSLieutenant ;Command_MouthOfSauronDissent
	6 	= Command_MouthOfSauronDissent
	12 	= Command_CaptureBuilding
	13 	= Command_AttackMove
	14 	= Command_Stop
	16  	= Command_SetStanceBattle
	17  	= Command_SetStanceAggressive
	18 	= Command_SetStanceHoldGround
	19	= Command_SpecialAbilityHeroAutoRetreat
End

Object MordorMouthOfSauron
CommandSet = MordorMouthOfSauronCommandSetX
ReplaceModule ModuleTag_MouthOfSauronDoubtEnabler
	Behavior = UnpauseSpecialPowerUpgrade ModuleTag_MouthOfSauronDoubtEnablerX
		SpecialPowerTemplate = SpecialAbilityMouthOfSauronDoubtButReal
		TriggeredBy = Upgrade_ObjectLevel3 ;Upgrade_MouthOfSauronDoubt
	End
End
ENd