Object AIBaseMarkerBase // THIS IS SPAWNED TO MAKE A TEAM EXIST, ALLOWING UNITS TO BE RECRUITED ONTO IT
RemoveModule ModuleTag_01
AddModule
	Body = ActiveBody ModuleTag_02
		MaxHealth         = 1
	End
End
End

ChildObject PrimaryAIBaseMarker AIBaseMarkerBase // DARK PRESENCE CASTER
	KindOf          = PRELOAD STRUCTURE IMMOBILE AUTO_RALLYPOINT FS_FACTORY IGNORE_FOR_VICTORY IGNORE_FOR_EVA_SPEECH_POSITION NO_COLLIDE UNATTACKABLE NOT_AUTOACQUIRABLE
AddModule
	Behavior = GrantUpgradeCreate ModuleTag_GrantUpgrade
		UpgradeToGrant	= Upgrade_GondorStableLevel2
	End
End
AddModule
	Behavior = AttributeModifierAuraUpdate ModuleTag_DarkPresence
		StartsActive	= Yes
		TriggeredBy		= Upgrade_GondorStableLevel2
		BonusName		= GuldurDarkPresence
		RefreshDelay	= 2000
		Range			= 20000
		ObjectFilter	= ANY +GuldurBrokenRabble +GuldurBrokenRabbleA +GuldurBrokenRabbleB +GuldurBrokenRabbleC +GuldurBrokenRabbleHorde +GuldurOrcArcher +GuldurOrcArcherHorde +GuldurOrcPikeman +GuldurOrcPikemanForBrokenRabble +GuldurOrcPikemanHorde +GuldurOrcArcherHorde_Summoned +GuldurOrcPikemanHorde_Summoned +GuldurBannerOrc +GuldurPikemenArcherComboHorde
	End
End
End

;///////////////////////////////////////////////////////////////////////////// 

; WaterTransparency can be overridden per each map to change these values.
WaterTransparency
  ReflectionPlaneZ = 5.0;
  ReflectionOn = Yes
End

Weather
	CloudTextureSize = X:3850 Y:3850
	CloudOffsetPerSecond = X:-0 Y:-0
	
	
HardwareFogColor = R:185 G:205 B:210
HardwareFogEnable = Yes
HardwareFogStart = 500
HardwareFogEnd = 8500
End

ShadowMap
    MapSize = 2048
    MaxViewDistance = 2200.0
    MinShadowedTerrainHeight = 0.0
End


;-------------------------------------------------------------------------------------------------


Object TDHEreborSecretGate
 ReplaceModule 	Draw_Gate
  Draw = W3DScriptedModelDraw Draw_Gate_Override
	DefaultModelConditionState
	  Model = dbMerebsec_skn
  End
 End
End
End


Object Daleprops2
KindOf          = STRUCTURE IMMOBILE NOT_AUTOACQUIRABLE UNATTACKABLE; CLEARED_BY_BUILD 
END

Object Celduin_FishNet01
KindOf          = STRUCTURE IMMOBILE NOT_AUTOACQUIRABLE UNATTACKABLE; CLEARED_BY_BUILD 
END

Object Celduin_FishNet02
KindOf          = STRUCTURE IMMOBILE NOT_AUTOACQUIRABLE UNATTACKABLE; CLEARED_BY_BUILD 
END

Object Celduin_FishNet03
KindOf          = STRUCTURE IMMOBILE NOT_AUTOACQUIRABLE UNATTACKABLE; CLEARED_BY_BUILD 
END

Object Celduin_LobTrap01
KindOf          = STRUCTURE IMMOBILE NOT_AUTOACQUIRABLE UNATTACKABLE; CLEARED_BY_BUILD 
END

Object Celduin_LobTrap02
KindOf          = STRUCTURE IMMOBILE NOT_AUTOACQUIRABLE UNATTACKABLE; CLEARED_BY_BUILD 
END

Object Celduin_LobTrap03
KindOf          = STRUCTURE IMMOBILE NOT_AUTOACQUIRABLE UNATTACKABLE; CLEARED_BY_BUILD 
END


;-------------------------------------------------------------------------------------------------
;REMOVE BUILDER FROM KEEP
;-------------------------------------------------------------------------------------------------

Object IronHillsRockyOutcropping01
  KindOf = ROCK_VENDOR IMMOBILE IGNORED_IN_GUI INERT INERT_SHROUD_REVEALER CAN_CAST_REFLECTIONS CLEARED_BY_BUILD
End

Object IronHillsRockyOutcropping02
  KindOf = ROCK_VENDOR IMMOBILE IGNORED_IN_GUI INERT INERT_SHROUD_REVEALER CAN_CAST_REFLECTIONS CLEARED_BY_BUILD
End

Object IronHillsRockyOutcropping03
  KindOf = ROCK_VENDOR IMMOBILE IGNORED_IN_GUI INERT INERT_SHROUD_REVEALER CAN_CAST_REFLECTIONS CLEARED_BY_BUILD
End

Object IronHillsRockyOutcropping04
  KindOf = ROCK_VENDOR IMMOBILE IGNORED_IN_GUI INERT INERT_SHROUD_REVEALER CAN_CAST_REFLECTIONS CLEARED_BY_BUILD
End

Object IronHillsRockyOutcropping05
  KindOf = ROCK_VENDOR IMMOBILE IGNORED_IN_GUI INERT INERT_SHROUD_REVEALER CAN_CAST_REFLECTIONS CLEARED_BY_BUILD
End

Object IronHillsRockyOutcropping06
  KindOf = ROCK_VENDOR IMMOBILE IGNORED_IN_GUI INERT INERT_SHROUD_REVEALER CAN_CAST_REFLECTIONS CLEARED_BY_BUILD
End

Object AotRIronHillsBridge01
  KindOf = IMMOBILE WALK_ON_TOP_OF_WALL STRUCTURE IGNORED_IN_GUI CAN_CAST_REFLECTIONS NOT_AUTOACQUIRABLE INERT INERT_SHROUD_REVEALER DONT_HIDE_IF_FOGGED
End

Object AotRIronHillsBridge02
  KindOf = IMMOBILE WALK_ON_TOP_OF_WALL STRUCTURE IGNORED_IN_GUI CAN_CAST_REFLECTIONS NOT_AUTOACQUIRABLE INERT INERT_SHROUD_REVEALER DONT_HIDE_IF_FOGGED
End

Object AotRIronHillsBridge03
  KindOf = IMMOBILE WALK_ON_TOP_OF_WALL STRUCTURE IGNORED_IN_GUI CAN_CAST_REFLECTIONS NOT_AUTOACQUIRABLE INERT INERT_SHROUD_REVEALER DONT_HIDE_IF_FOGGED
End

Object AOTRIronHillsGate
	KindOf = IMMOBILE STRUCTURE IGNORED_IN_GUI CAN_CAST_REFLECTIONS NOT_AUTOACQUIRABLE INERT INERT_SHROUD_REVEALER DONT_HIDE_IF_FOGGED
End

;startOfAuto-Generation
;------------------------------------------------------------------------;
;	  EREBOR REGION 														 ;
;------------------------------------------------------------------------;
Object Inn
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Erebor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Erebor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Erebor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Erebor
		End
	End
End
Object InnDesert
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Erebor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Erebor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Erebor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Erebor
		End
	End
End
Object InnSnow
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Erebor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Erebor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Erebor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Erebor
		End
	End
End
Object Inn_old
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Erebor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Erebor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Erebor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Erebor
		End
	End
End
;endOfAuto-Generation


;==== Auto Generated AI Fix =====;
SkirmishAIData TheSkirmishAIData
    DisableBaseBuilding        = No
    DisableEconomyBuilding     = No
    DisableUnitBuilding        = No
    DisableScienceUpgrading    = No
    DisableUnitUpgrading       = No
    DisableTacticalAI          = No
    DisableTeamBuilding        = No
    DisableWallBuilding        = Yes ;,; No
End
