Weather

	HardwareFogColor = R:165 G:180 B:180
	HardwareFogEnable = Yes
	HardwareFogStart = 450
	HardwareFogEnd = 10000


	
	CloudTextureSize		= X:6000 Y:6000
	CloudOffsetPerSecond	= X:-0 Y:-0
End

WaterTransparency
  ReflectionPlaneZ = 150.0;
  ReflectionOn = Yes
End

AIData
  LowLodTreeName = TreeLowLODTowerHills
End

ShadowMap
	MapSize = 2048
	MaxViewDistance = 6000.0
	MinShadowedTerrainHeight = 0.0
End

PlayerTemplate FactionCivilian
	Side              = Civilian
	PlayableSide      = No
	StartMoney        = 0
	PreferredColor    = R:64 G:64 B:64
	IntrinsicSciences = None
	DisplayName       = INI:FactionCivilian
	ScoreScreenImage  = MutiPlayer_ScoreScreen
	LoadScreenMusic   = Shell2MusicForLoadScreen
	IntrinsicSciences		= SCIENCE_GOOD
	IntrinsicSciencesMP 		= SCIENCE_DWARVES
	SpellBook			= GoodSpellBook
	SpellBookMp			= DwarvesSpellBook
	PurchaseScienceCommandSet	= GoodSpellStoreCommandSet
	PurchaseScienceCommandSetMP	= DwarvesSpellStoreCommandSet
End

CommandButton Command_ConstructDwarvenEreborTowerTowerExpansion
  Command                 = DOZER_CONSTRUCT 
	Object           = DwarvenEreborTowerTowerExpansion
	TextLabel        = CONTROLBAR:ConstructDwarvenEreborTowerTowerExpansion
	ButtonImage      = BIEreborWallTower
	ButtonBorderType = BUILD 
	DescriptLabel    = CONTROLBAR:ToolTipConstructDwarvenEreborTowerTowerExpansion
	Radial           = Yes  
End 

; -----------------------------------------------------------------------------------------------------------------------------
; MORDOR INFANTRY SETUP
; -----------------------------------------------------------------------------------------------------------------------------

Object MordorSiegeWorks

	CommandSet = MordorSiegeWorksCommandSetLevel1_ForMP

	ReplaceModule ModuleTag_MordorSiegeWorksLevel2
		Behavior = CommandSetUpgrade ModuleTag_MordorSiegeWorksLevel2_ForMP
			TriggeredBy		= Upgrade_MordorSiegeWorksLevel2
			ConflictsWith	= Upgrade_MordorSiegeWorksLevel3
			CommandSet		= MordorSiegeWorksCommandSetLevel2_ForMP
		End
	End
	
	ReplaceModule ModuleTag_MordorSiegeWorksLevel3
		Behavior = CommandSetUpgrade ModuleTag_MordorSiegeWorksLevel3_ForMP
			TriggeredBy		= Upgrade_MordorSiegeWorksLevel3
			CommandSet		= MordorSiegeWorksCommandSetLevel3_ForMP
		End
	End
End
	
;///////////////////////////////////////////////////////////////////////////	

Object IsengardSiegeWorks
	
	CommandSet = IsengardSiegeWorksCommandSetLevel1_ForMP
	
	ReplaceModule ModuleTag_IsengardSiegeWorksLevel2CommandSet
		Behavior = CommandSetUpgrade ModuleTag_IsengardSiegeWorksLevel2CommandSet_ForMP
			TriggeredBy		= Upgrade_StructureLevel2
			ConflictsWith	= Upgrade_StructureLevel3
			CommandSet		= IsengardSiegeWorksCommandSetLevel2_ForMP
		End
	End
	
	ReplaceModule ModuleTag_IsengardSiegeWorksLevel3CommandSet
		Behavior = CommandSetUpgrade ModuleTag_IsengardSiegeWorksLevel3CommandSet_ForMP
			TriggeredBy		= Upgrade_StructureLevel3
			CommandSet		= IsengardSiegeWorksCommandSetLevel3_ForMP
		End
	End
End

Object MordorSiegeTower
	ReplaceModule ModuleTag_07
		Behavior = SiegeDeploySpecialPower ModuleTag_WallSearchDistanceLocal
	    	SpecialPowerTemplate = SpecialAbilitySiegeDeploy
            LowerDelay = 1200
            RaiseDelay = 2000
            EvacuatePassengersOnDeploy = Yes
            SkipAdjustPosition = Yes ; have to skip the path find adjust or it this will not go to the right docking position
            WallSearchDistance = 99999.0
 		End
	End
End

Armor SiegeTowerArmor
  Armor = DEFAULT          10%     ;this sets the level for all nonspecified damage types
  Armor = CRUSH           15% ;25%     ;horseman damage
  Armor = SLASH           25% ;1%     ;soldier damage
  Armor = SIEGE		  30%     ;war machine attack
  Armor = STRUCTURAL	  30%	   ;Structural damage (Ent rocks)
  Armor = FLAME            20% ;10%     ;fire attack
  Armor = PIERCE            1%     ;archer damage 
  Armor = HERO		   10%     ;hero damage
  Armor = MAGIC		  50%     ;hero damage
  Armor = HERO_RANGED       1%     ;Hero bow damage     
End


;--------------------------------------------------------------------------
; Dwarves Castle Setup
;--------------------------------------------------------------------------

ChildObject DwarfBarracksFoundation DwarfBarracks
RemoveModule MakeTheFreeGuard
RemoveModule ModuleTag_SpawnPatrols
RemoveModule ModuleTag_SpawnPatrols2
RemoveModule ModuleTag_SpawnPatrols3
ReplaceModule ModuleTag_04
 	Behavior = GettingBuiltBehavior GetBuiltBehaviorTagX
		SpawnTimer	= DEFAULT_STRUCTURE_HEALDELAY
		RebuildWhenDead = Yes
        SelfBuildingLoop = BuildingConstructionLoop ; Only played if we DON'T spawn a worker
		SelfRepairFromDamageLoop  = NoSound         ; This doesn't cause an animation, so don't bother playing a sound
		SelfRepairFromRubbleLoop  = BuildingConstructionLoop
	End
End
End

ChildObject DwarvenSentryTowerFoundation DwarvenSentryTower
ReplaceModule GetBuiltBehaviorTag
 	Behavior = GettingBuiltBehavior GetBuiltBehaviorTagX
		SpawnTimer	= DEFAULT_STRUCTURE_HEALDELAY
		RebuildWhenDead = Yes
        SelfBuildingLoop = BuildingConstructionLoop ; Only played if we DON'T spawn a worker
		SelfRepairFromDamageLoop  = NoSound         ; This doesn't cause an animation, so don't bother playing a sound
		SelfRepairFromRubbleLoop  = BuildingConstructionLoop
	End
End
End

Object DwarvenStatue
ReplaceModule GetBuiltBehaviorTag
 	Behavior = GettingBuiltBehavior GetBuiltBehaviorTagX
		SpawnTimer	= DEFAULT_STRUCTURE_HEALDELAY
		RebuildWhenDead = Yes
        SelfBuildingLoop = BuildingConstructionLoop ; Only played if we DON'T spawn a worker
		SelfRepairFromDamageLoop  = NoSound         ; This doesn't cause an animation, so don't bother playing a sound
		SelfRepairFromRubbleLoop  = BuildingConstructionLoop
	End
End
End

ChildObject DwarvenArcheryRangeFoundation DwarvenArcheryRange
RemoveModule ModuleTag_SpawnPatrols
RemoveModule ModuleTag_SpawnPatrols2
RemoveModule ModuleTag_SpawnPatrols3
ReplaceModule ModuleTag_04
 	Behavior = GettingBuiltBehavior GetBuiltBehaviorTagX
		SpawnTimer	= DEFAULT_STRUCTURE_HEALDELAY
		RebuildWhenDead = Yes
        SelfBuildingLoop = BuildingConstructionLoop ; Only played if we DON'T spawn a worker
		SelfRepairFromDamageLoop  = NoSound         ; This doesn't cause an animation, so don't bother playing a sound
		SelfRepairFromRubbleLoop  = BuildingConstructionLoop
	End
End
End

ChildObject DwarvenMineShaftFoundation MineShaft_Interface
ReplaceModule GetBuiltBehaviorTag
 	Behavior = GettingBuiltBehavior GetBuiltBehaviorTagX
		SpawnTimer	= DEFAULT_STRUCTURE_HEALDELAY
		RebuildWhenDead = Yes
        SelfBuildingLoop = BuildingConstructionLoop ; Only played if we DON'T spawn a worker
		SelfRepairFromDamageLoop  = NoSound         ; This doesn't cause an animation, so don't bother playing a sound
		SelfRepairFromRubbleLoop  = BuildingConstructionLoop
	End
End
End

ChildObject DwarvenSiegeWorksFoundation DwarvenSiegeWorks
RemoveModule ModuleTag_SpawnPatrols
ReplaceModule GetBuiltBehaviorTag
 	Behavior = GettingBuiltBehavior GetBuiltBehaviorTagX
		SpawnTimer	= DEFAULT_STRUCTURE_HEALDELAY
		RebuildWhenDead = Yes
        SelfBuildingLoop = BuildingConstructionLoop ; Only played if we DON'T spawn a worker
		SelfRepairFromDamageLoop  = NoSound         ; This doesn't cause an animation, so don't bother playing a sound
		SelfRepairFromRubbleLoop  = BuildingConstructionLoop
	End
End
End

Object EreborForgeFoundation
ReplaceModule GetBuiltBehaviorTag
 	Behavior = GettingBuiltBehavior GetBuiltBehaviorTagX
		SpawnTimer	= DEFAULT_STRUCTURE_HEALDELAY
		RebuildWhenDead = Yes
        SelfBuildingLoop = BuildingConstructionLoop ; Only played if we DON'T spawn a worker
		SelfRepairFromDamageLoop  = NoSound         ; This doesn't cause an animation, so don't bother playing a sound
		SelfRepairFromRubbleLoop  = BuildingConstructionLoop
	End
End
End

ChildObject DwarvenWorkshopFoundation DwarvenWorkshop
RemoveModule ModuleTag_SpawnPatrols
RemoveModule ModuleTag_SpawnPatrols2
RemoveModule ModuleTag_SpawnPatrols3
ReplaceModule GetBuiltBehaviorTag
 	Behavior = GettingBuiltBehavior GetBuiltBehaviorTagX
		SpawnTimer	= DEFAULT_STRUCTURE_HEALDELAY
		RebuildWhenDead = Yes
        SelfBuildingLoop = BuildingConstructionLoop ; Only played if we DON'T spawn a worker
		SelfRepairFromDamageLoop  = NoSound         ; This doesn't cause an animation, so don't bother playing a sound
		SelfRepairFromRubbleLoop  = BuildingConstructionLoop
	End
End
End
;startOfAuto-Generation
;------------------------------------------------------------------------;
;	  EREBOR REGION 														 ;
;------------------------------------------------------------------------;
Object Inn
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Erebor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Erebor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Erebor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Erebor
		End
	End
End
Object InnDesert
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Erebor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Erebor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Erebor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Erebor
		End
	End
End
Object InnSnow
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Erebor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Erebor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Erebor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Erebor
		End
	End
End
Object Inn_old
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Erebor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Erebor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Erebor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Erebor
		End
	End
End
;endOfAuto-Generation


;==== Auto Generated AI Fix =====;
SkirmishAIData TheSkirmishAIData
    DisableBaseBuilding        = No
    DisableEconomyBuilding     = No
    DisableUnitBuilding        = No
    DisableScienceUpgrading    = No
    DisableUnitUpgrading       = No
    DisableTacticalAI          = No
    DisableTeamBuilding        = No
    DisableWallBuilding        = Yes ;,; No
End
