AIData
    AltCameraZoomOverride = 1.1 ; 1.0 = no change, 0.5 = half height, 2.0 = twice height.
    AltCameraPitchOverride = 1 ; 1.0 = no change, 0.0 = looking straight down. 2.0 = looking more towards the horizon
End

;; --------------------------------- 
;;               FALLING SNOW 
;; --------------------------------- 
;; This code will automatically put in falling snow.  The denser the snow, the more laggy the map. 
 
Weather 
        SnowEnabled = Yes                         ; enable/disable snow on the map. 
        IsSnowing = Yes                         ; is it snowing today? 
        SnowTexture = exraindrop.tga    ; which .tga texture is falling from the sky? 
        SnowBoxHeight = 800                     ; height from which snow falls 
        SnowSpacing = 10                          ; snow spacing -- less means more; 
        NumberTiles = 4 
 
        SnowAmplitude = 3                     ; amount of side-to-side movement.  
        SnowFrequencyScaleX = 0.01       ; speed of side-to-side wave movement. 
        SnowFrequencyScaleY = 0.005     ; speed of side-to-side wave movement.  
 
        SnowPointSize = 22                        ; scale the size of snow particles. 
        SnowMinPointSize =  12              ; min point size 
        SnowMaxPointSize = 19               ; max point size 
 
        SnowPointSprites = No             ; set to "no" for point-sprite emulation. 
        SnowQuadSize = 3                           ; scale the size of snow particles when using point-sprite emulation. 
 
        SnowSpeed = 100                           ; speed at which snow falls 
   ;;;SnowXYSpeed = X:40 Y:25 
 
 
 

	HardwareFogColor = R:175 G:180 B:180
	HardwareFogEnable = Yes
	HardwareFogStart = 350
	HardwareFogEnd = 8500




End

WaterTransparency
  ReflectionPlaneZ = 9.0;
  ReflectionOn = Yes
End


Object RivendellWaterfall01
 ReplaceModule 	ModuleTag_01
    Draw = W3DScriptedModelDraw ModuleTag_01_Override
    DefaultModelConditionState
      Model = PMRivFalls01
  End
 End
End
End


Object CINE_ParticleSysProxy

  ; *** ART Parameters ***
 ReplaceModule ModuleTag_01
  Draw = W3DScriptedModelDraw ModuleTag_01_Override
    DefaultModelConditionState
      Model = NONE
      ParticleSysBone = None AtmosphericHaze
    End
  
    ModelConditionState = WORLD_BUILDER
	  Model = locator
	End
  End
 End
End

Object IronHillsRockyOutcropping01
  KindOf = ROCK_VENDOR IMMOBILE IGNORED_IN_GUI INERT INERT_SHROUD_REVEALER CAN_CAST_REFLECTIONS CLEARED_BY_BUILD
End

Object IronHillsRockyOutcropping02
  KindOf = ROCK_VENDOR IMMOBILE IGNORED_IN_GUI INERT INERT_SHROUD_REVEALER CAN_CAST_REFLECTIONS CLEARED_BY_BUILD
End

Object IronHillsRockyOutcropping03
  KindOf = ROCK_VENDOR IMMOBILE IGNORED_IN_GUI INERT INERT_SHROUD_REVEALER CAN_CAST_REFLECTIONS CLEARED_BY_BUILD
End

Object IronHillsRockyOutcropping04
  KindOf = ROCK_VENDOR IMMOBILE IGNORED_IN_GUI INERT INERT_SHROUD_REVEALER CAN_CAST_REFLECTIONS CLEARED_BY_BUILD
End

Object IronHillsRockyOutcropping05
  KindOf = ROCK_VENDOR IMMOBILE IGNORED_IN_GUI INERT INERT_SHROUD_REVEALER CAN_CAST_REFLECTIONS CLEARED_BY_BUILD
End

Object IronHillsRockyOutcropping06
  KindOf = ROCK_VENDOR IMMOBILE IGNORED_IN_GUI INERT INERT_SHROUD_REVEALER CAN_CAST_REFLECTIONS CLEARED_BY_BUILD
End

;Object AotRIronHillsBridge01
;  KindOf = IMMOBILE WALK_ON_TOP_OF_WALL STRUCTURE IGNORED_IN_GUI CAN_CAST_REFLECTIONS NOT_AUTOACQUIRABLE DONT_HIDE_IF_FOGGED
;End

;Object AotRIronHillsBridge02
;  KindOf = IMMOBILE WALK_ON_TOP_OF_WALL STRUCTURE IGNORED_IN_GUI CAN_CAST_REFLECTIONS NOT_AUTOACQUIRABLE DONT_HIDE_IF_FOGGED
;End

;Object AotRIronHillsBridge03
;  KindOf = IMMOBILE WALK_ON_TOP_OF_WALL STRUCTURE IGNORED_IN_GUI CAN_CAST_REFLECTIONS NOT_AUTOACQUIRABLE DONT_HIDE_IF_FOGGED
;End


;startOfAuto-Generation
;------------------------------------------------------------------------;
;	  EREBOR REGION 														 ;
;------------------------------------------------------------------------;
Object Inn
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Erebor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Erebor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Erebor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Erebor
		End
	End
End
Object InnDesert
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Erebor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Erebor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Erebor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Erebor
		End
	End
End
Object InnSnow
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Erebor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Erebor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Erebor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Erebor
		End
	End
End
Object Inn_old
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Erebor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Erebor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Erebor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Erebor
		End
	End
End
;endOfAuto-Generation


;==== Auto Generated AI Fix =====;
SkirmishAIData TheSkirmishAIData
    DisableBaseBuilding        = No
    DisableEconomyBuilding     = No
    DisableUnitBuilding        = No
    DisableScienceUpgrading    = No
    DisableUnitUpgrading       = No
    DisableTacticalAI          = No
    DisableTeamBuilding        = No
    DisableWallBuilding        = Yes ;,; No
End
