FXParticleSystem FogMist;FXParticleSystem CINECampfireEmbers;ground fog

  System
    Priority = VERY_LOW_OR_ABOVE
	Shader = ALPHA
    ParticleName = EXCloud02.tga; EXCineSparks.tga
    Lifetime = 150 150
    SortLevel = 1
    Size = .8 1
    BurstDelay = 10 20; 1 10
    BurstCount = 8 15; 3 5
  End
 
  Color = DefaultColor
    Color1 = R:185 G:185 B:185 0; R:205 G:192 B:168 0; R:255 G:185 B:79 0
    ;Color2 = R:105 G:92 B:68 50; R:0 G:0 B:0 200
    ;ColorScale = 2 -2
  End
    Alpha = DefaultAlpha
    ;Alpha1 = 0 0 50
	Alpha2 = 0.05 0.05 50; 0.1 0.1 50
    Alpha3 = 0 0 120; 150
  End
  Update = DefaultUpdate
    SizeRate = 1 3; 1 3
    SizeRateDamping = 0.9 0.99
    ;AngularRateZ = -0.02 0.02
    ;AngularDamping = 1 1
    ;AngularDampingXY = 1 1
  End
  Physics = DefaultPhysics
    ;Gravity = -0.008
    VelocityDamping = 0.95 0.99
    DriftVelocity = X:0.2 Y:0.-2 Z:0.08; X:0 Y:0 Z:0.64
  End
  EmissionVelocity = OrthoEmissionVelocity
  X = .5 1
  Y = -1 1
  Z = 0 0.1
	End
  EmissionVolume = CylinderEmissionVolume
    Radius = 120
	Length = 2
	Offset = X:0 Y:0 Z:20
  End
  Draw = DefaultDraw
  End
  Wind = DefaultWind
    WindMotion = PingPong

    WindStrength = 0.25; 0.25
    WindFullStrengthDist = 5
    WindZeroStrengthDist = 100
    WindAngleChangeMin = 0.034907
    WindAngleChangeMax = 0.034907
    WindPingPongStartAngleMin = 1.22173
    WindPingPongStartAngleMax = 1.22173
    WindPingPongEndAngleMin = 1.91986
    WindPingPongEndAngleMax = 1.91986
    TurbulenceAmplitude = 0.2
    TurbulenceFrequency = 50
  End
End

WaterTransparency
 ReflectionPlaneZ = 59.0;
 ReflectionOn = Yes
End

Object CINE_ParticleSysProxy2

  ; *** ART Parameters ***
 ReplaceModule ModuleTag_01
  Draw = W3DScriptedModelDraw ModuleTag_01_Override
    DefaultModelConditionState
      Model = NONE
      ParticleSysBone = emberBone LightSunRays
      ParticleSysBone = None None;FireSmokeBig
    End
  
    ModelConditionState = WORLD_BUILDER
	  Model = locator
	End
  End
 End
End

; FXParticleSystem CloudBreakRays
  ; System
    ; Priority = ALWAYS_RENDER
    ; Shader = W3D_EMISSIVE
    ; Type = DRAWABLE
    ; ParticleName = EXCldBrkRays.W3D
    ; Lifetime = 300 300
 ; ;   SystemLifetime = 200
    ; Size = 1.2 1.2;0.1 0.1
    ; BurstDelay = 180 180;20 90
    ; BurstCount = 1 1; 0 2
  ; End
  ; Color = DefaultColor
    ; Color1 = R:164 G:140 B:104 0
    ; Color2 = R:0 G:0 B:0 400
  ; End
  ; Alpha = DefaultAlpha
    ; Alpha2 = 0.05 0.05 120
    ; Alpha3 = 0.0 0.0 220
	; ;Alpha4 = 0 0 400
	; ;Alpha5 = 0 0 400
  ; End
    ; Update = DefaultUpdate
    ; ;SizeRate = 0.04 0.04
    ; ;SizeRateDamping = 0.95 0.97
    ; AngleZ = -5.9 -5.9
    ; ;AngularDamping = 1 1
    ; Rotation = ROTATE_Y
    ; ;AngularDampingXY = 1 1
  ; End
  ; ; Update = RenderObjectUpdate
    ; ; StartSizeX = 0.3 0.3
    ; ; StartSizeY = 0.3 0.3
    ; ; StartSizeZ = 1 1
    ; ; SizeRateX = 0.01 0.01
    ; ; SizeRateY = 0.01 0.01
    ; ; SizeDampingX = 0.99 0.99
    ; ; SizeDampingY = 0.99 0.99
    ; ; SizeDampingZ = 0.98 0.98
    ; ; AngleZ = 1.6 1.6; -5 5
    ; ; AngularRateZ = -0.01 0.01
    ; ; AngularDamping = 0.99 0.99
    ; ; Rotation = ROTATE_Z
  ; ; End
  ; Physics = DefaultPhysics
    ; VelocityDamping = 1 1
	; DriftVelocity = X:0.02 Y:0 Z:0.05;
  ; End
  ; EmissionVelocity = OrthoEmissionVelocity
    ; ; X = 0.5 0.5
    ; ; Y = 0 0
    ; ; Z = -0.2 -0.2
  ; End
   ; EmissionVolume = PointEmissionVolume;
    ; ; Radius = 50
    ; ; Length = 5
   ; End
  ; Draw = RenderObjectDraw
  ; End
; End

Object CINE_ParticleSysProxy3

  ; *** ART Parameters ***
 ReplaceModule ModuleTag_01
  Draw = W3DScriptedModelDraw ModuleTag_01_Override
    DefaultModelConditionState
      Model = NONE
      ParticleSysBone = emberBone FloatingDust
      ParticleSysBone = None None;FireSmokeBig
    End
  
    ModelConditionState = WORLD_BUILDER
	  Model = locator
	End
  End
 End
End


; FXParticleSystem FloatingDust;falling dust
  ; System
    ; Priority = ALWAYS_RENDER
	; Shader = ALPHA
    ; ParticleName = EXCloud02.tga; EXCineSparks.tga
    ; Lifetime = 150 300; 100 200
    ; SortLevel = 1
    ; Size = 0.5 0.8; 0.1 0.2
    ; BurstDelay = 1 10
    ; BurstCount = 12 20; 3 5
  ; End
 
  ; Color = DefaultColor
    ; Color1 = R:205 G:192 B:168 0; R:255 G:185 B:79 0
    ; Color2 = R:105 G:92 B:68 100; R:0 G:0 B:0 200
    ; ColorScale = 2 -2
  ; End
  
    ; Alpha = DefaultAlpha
    ; Alpha1 = 1 1 30; 0.1 0.3 50
    ; Alpha2 = .7 .7 150; 0 0 350
	; Alpha3 = 0 0 200; 0 0 350
  ; End
  ; Update = DefaultUpdate
    ; SizeRate = 0.01 0.07
    ; SizeRateDamping = 0.65 0.8
    ; AngleZ = -3 3
    ; AngularRateZ = -0.3 0.3
    ; AngularDamping = 0.9 0.99
    ; AngularDampingXY = 1 1
  ; End
  ; Physics = DefaultPhysics
    ; Gravity = 0.008
    ; VelocityDamping = 0.95 0.99
    ; DriftVelocity = X:0.2 Y:0.15 Z:-0.3; X:0 Y:0 Z:0.64
  ; End
  ; EmissionVelocity = OrthoEmissionVelocity
  ; End
  ; EmissionVolume = CylinderEmissionVolume
    ; Radius = 100; 7
    ; Length = 5; 1
  ; End
  ; Draw = DefaultDraw
  ; End
  ; Wind = DefaultWind
    ; WindMotion = PingPong

    ; WindStrength = 0.25; 0.25
    ; WindFullStrengthDist = 5
    ; WindZeroStrengthDist = 100
    ; WindAngleChangeMin = 0.034907
    ; WindAngleChangeMax = 0.034907
    ; WindPingPongStartAngleMin = 1.22173
    ; WindPingPongStartAngleMax = 1.22173
    ; WindPingPongEndAngleMin = 1.91986
    ; WindPingPongEndAngleMax = 1.91986
    ; TurbulenceAmplitude = 0.2
    ; TurbulenceFrequency = 50
  ; End
; End


Object CINE_ParticleSysProxy4

  ; *** ART Parameters ***
 ReplaceModule ModuleTag_01
  Draw = W3DScriptedModelDraw ModuleTag_01_Override
    DefaultModelConditionState
      Model = NONE
      ParticleSysBone = emberBone FlowerPollen; campfireEmbers
      ParticleSysBone = None None;FireSmokeBig
    End
  
    ModelConditionState = WORLD_BUILDER
	  Model = locator
	End
  End
 End
End


; FXParticleSystem campfireEmbers;leaves blowing
  ; System
    ; Priority = ALWAYS_RENDER
	; Shader = ALPHA
    ; ParticleName = EXLeaf01.tga; EXCloud02.tga; EXCineSparks.tga
    ; Lifetime = 150 300; 100 200
    ; SortLevel = 1
    ; Size = 2 3; 0.1 0.2
    ; BurstDelay = 10 20
    ; BurstCount = 20 25; 3 5
  ; End
 
  ; Color = DefaultColor
    ; Color1 = R:225 G:80 B:55 0; R:255 G:185 B:79 0
    ; ;Color2 = R:105 G:92 B:68 100; R:0 G:0 B:0 200
    ; ColorScale = 2 -2
  ; End
  
    ; Alpha = DefaultAlpha
    ; Alpha1 = 1 1 0; 0.1 0.3 50
    ; Alpha2 = 1 1 80; 0 0 350
	; Alpha3 = 0 0 180; 0 0 350
  ; End
  ; Update = DefaultUpdate
    ; SizeRate = 0.01 0.07
    ; SizeRateDamping = 0.65 0.8
    ; AngleZ = -10 10
    ; AngularRateZ = -1 1
    ; AngularDamping = 0.9 0.99
    ; AngularDampingXY = 1 1
  ; End
  ; Physics = DefaultPhysics
    ; Gravity = -0.01
    ; VelocityDamping = 0.95 0.99
    ; DriftVelocity = X:0.1 Y:0.08 Z:0.1; X:0 Y:0 Z:0.64
  ; End
  ; EmissionVelocity = OrthoEmissionVelocity
    ; X = .6 1.8
    ; Y = -0.4 0.4
    ; Z = 0.1 .8
  ; End
  ; EmissionVolume = CylinderEmissionVolume
    ; Radius = 10; 7
    ; Length = 5; 1
  ; End
  ; Draw = DefaultDraw
  ; End
  ; Wind = DefaultWind
    ; WindMotion = PingPong

    ; WindStrength = 0.25; 0.25
    ; WindFullStrengthDist = 5
    ; WindZeroStrengthDist = 100
    ; WindAngleChangeMin = 0.034907
    ; WindAngleChangeMax = 0.034907
    ; WindPingPongStartAngleMin = 1.22173
    ; WindPingPongStartAngleMax = 1.22173
    ; WindPingPongEndAngleMin = 1.91986
    ; WindPingPongEndAngleMax = 1.91986
    ; TurbulenceAmplitude = 0.2
    ; TurbulenceFrequency = 50
  ; End
; End

; FXParticleSystem campfireEmbers;FlowerPollen
  ; System
    ; Priority = ALWAYS_RENDER
	; Shader = ALPHA
    ; ParticleName = EXCloud02.tga; EXCineSparks.tga
    ; Lifetime = 150 300; 100 200
    ; SortLevel = 1
    ; Size = 0.3 0.6; 0.1 0.2
    ; BurstDelay = 1 10
    ; BurstCount = 15 20; 3 5
  ; End
 
  ; Color = DefaultColor
    ; Color1 = R:175 G:195 B:220 0; R:255 G:185 B:79 0
    ; ;Color2 = R:105 G:92 B:68 100; R:0 G:0 B:0 200
    ; ColorScale = 2 -2
  ; End
  
    ; Alpha = DefaultAlpha
    ; Alpha1 = 1 1 10; 0.1 0.3 50
    ; Alpha2 = .5 .5 100; 0 0 350
	; Alpha3 = 0 0 180; 0 0 350
  ; End
  ; Update = DefaultUpdate
    ; SizeRate = 0.01 0.07
    ; SizeRateDamping = 0.65 0.8
    ; AngleZ = -3 3
    ; AngularRateZ = -0.3 0.3
    ; AngularDamping = 0.9 0.99
    ; AngularDampingXY = 1 1
  ; End
  ; Physics = DefaultPhysics
    ; ;Gravity = 0.008
    ; VelocityDamping = 0.95 0.99
    ; DriftVelocity = X:0.3 Y:0.08 Z:0.08; X:0 Y:0 Z:0.64
  ; End
  ; EmissionVelocity = OrthoEmissionVelocity
    ; X = .9 .9
    ; Y = -0.4 0.4
    ; Z = -0.3 .8
  ; End
  ; EmissionVolume = CylinderEmissionVolume
    ; Radius = 60; 7
    ; Length = 5; 1
  ; End
  ; Draw = DefaultDraw
  ; End
  ; Wind = DefaultWind
    ; WindMotion = PingPong

    ; WindStrength = 0.25; 0.25
    ; WindFullStrengthDist = 5
    ; WindZeroStrengthDist = 100
    ; WindAngleChangeMin = 0.034907
    ; WindAngleChangeMax = 0.034907
    ; WindPingPongStartAngleMin = 1.22173
    ; WindPingPongStartAngleMax = 1.22173
    ; WindPingPongEndAngleMin = 1.91986
    ; WindPingPongEndAngleMax = 1.91986
    ; TurbulenceAmplitude = 0.2
    ; TurbulenceFrequency = 50
  ; End
; End

Weather

	HardwareFogColor = R:145 G:160 B:165
	HardwareFogEnable = Yes
	HardwareFogStart = 400
	HardwareFogEnd = 8000

End







;startOfAuto-Generation
;------------------------------------------------------------------------;
;	#################### WAR OF THE RING SETTINGS ####################   ;
;   - Upgrade_WOTRMode is now used to deal with WOTR commandsets         ;
;------------------------------------------------------------------------;
;-------------------
;	GONDOR
;-------------------
PlayerTemplate FactionMen
	StartMoney        				= 0
	SpellBookMp						= MenSpellBook_WOTR
	PurchaseScienceCommandSetMP		= MenSpellStoreCommandSet_WOTR
	InitialUpgrades					= Upgrade_MenFaction Upgrade_WOTRMode
	BuildableHeroesMP				= CreateAHero GondorPippin_WOTR GondorForlong_WOTR GondorBeregond_WOTR GondorImrahil_WOTR GondorDenethor_WOTR GondorFaramir GondorBoromir GondorGandalf_WOTR
End

;-------------------
;	ROHAN
;-------------------
PlayerTemplate FactionRohan
	StartMoney        				= 0
	SpellBookMp						= RohanSpellBook_WOTR
	PurchaseScienceCommandSetMP		= RohanSpellStoreCommandSet_WOTR
	InitialUpgrades					= Upgrade_RohanFaction Upgrade_WOTRMode
	BuildableHeroesMP				= CreateAHero RohanMerry_WOTR RohanEowyn_WOTR RohanElfhelm_WOTR RohanErkenbrand RohanTheodred RohanEomer RohanTheoden
End

;-------------------
;	LOTHLORIEN
;-------------------
PlayerTemplate FactionElves
	StartMoney        				= 0
	SpellBookMp						= ElvesSpellBook_WOTR
	PurchaseScienceCommandSetMP		= ElvesSpellStoreCommandSet_WOTR
	InitialUpgrades					= Upgrade_ElfFaction Upgrade_WOTRMode
	BuildableHeroesMP				= CreateAHero ElvenOrophin_WOTR ElvenRumil ElvenIdrial_WOTR ElvenHaldir ElvenCeleborn ElvenGaladrielLorien_WOTR MirkwoodThranduil_NCS
End

;-------------------
;	RIVENDELL
;-------------------
PlayerTemplate FactionArnor
	StartMoney        				= 0
	SpellBookMp						= ArnorSpellBook_WOTR
	PurchaseScienceCommandSetMP		= ArnorSpellStoreCommandSet_WOTR
	InitialUpgrades					= Upgrade_ArnorFaction Upgrade_WOTRMode	
	BuildableHeroesMP				= CreateAHero ArnorFattyBolger_WOTR ArnorFarmerMaggot_WOTR ElvenArwen_WOTR ElvenGildor ElvenElladan_WOTR ElvenElrohir_WOTR ArnorHalbarad_WOTR ElvenAragorn ElvenGlorfindel_WOTR ElvenElrond_WOTR
End

;-------------------
;	MIRKWOOD
;-------------------
PlayerTemplate FactionMirkwood
	StartMoney        				= 0
	SpellBookMp						= MirkwoodSpellBook_WOTR
	PurchaseScienceCommandSetMP		= MirkwoodSpellStoreCommandSet_WOTR
	InitialUpgrades					= Upgrade_MirkwoodFaction Upgrade_WOTRMode	
	BuildableHeroesMP				= CreateAHero MirkwoodTauriel MirkwoodGalion_WOTR MirkwoodFeren DorwinionFrumgar_WOTR MirkwoodRadagast_WOTR MirkwoodGrimbeorn_WOTR MirkwoodLegolas MirkwoodThranduil
End

;-------------------
;	EREBOR
;-------------------
PlayerTemplate FactionDwarves
	StartMoney        				= 0
	SpellBookMp						= DwarvesSpellBook_WOTR
	PurchaseScienceCommandSetMP		= DwarvesSpellStoreCommandSet_WOTR
	InitialUpgrades					= Upgrade_DwarfFaction Upgrade_WOTRMode	
	BuildableHeroesMP				= CreateAHero DwarvenArcah_WOTR DwarvenGloin_WOTR DwarvenHadhod_WOTR DwarvenBrand_WOTR DwarvenGimli_WOTR DwarvenThorinStonehelm_WOTR DwarvenKingDain_WOTR YoungThorin_WOTR DwarvenThrain_WOTR YoungDain_WOTR YoungDwalin_WOTR YoungBalin_WOTR
End

;-------------------
;	MORDOR
;-------------------
PlayerTemplate FactionMordor
	StartMoney        				= 0
	SpellBookMp						= MordorSpellBook_WOTR
	PurchaseScienceCommandSetMP		= MordorSpellStoreCommandSet_WOTR
	InitialUpgrades					= Upgrade_MordorDualEconomyChoice Upgrade_MordorFaction Upgrade_EvilDualEconomyChoice Upgrade_WOTRMode
	BuildableHeroesMP				= CreateAHero MordorGorbag_WOTR MordorShagrat_WOTR MordorAkhorahil_WOTR MordorUvatha_WOTR  MordorGothmog MordorMouthOfSauron MordorMollok_WOTR MordorWitchKing_WOTR RhunBelokhZa_WOTR RhunKhrenTak_WOTR RhunVahRus_WOTR
End

;-------------------
;	ISENGARD
;-------------------
PlayerTemplate FactionIsengard
	StartMoney        				= 0
	SpellBookMp						= IsengardSpellBook_WOTR
	PurchaseScienceCommandSetMP		= IsengardSpellStoreCommandSet_WOTR
	InitialUpgrades					= Upgrade_IsengardDualEconomyChoice Upgrade_IsengardFaction Upgrade_EvilDualEconomyChoice Upgrade_WOTRMode
	BuildableHeroesMP				= CreateAHero IsengardGrishnakh_WOTR IsengardWormTongue_WOTR IsengardSharku_WOTR IsengardUgluk IsengardLurtz IsengardWulfgar_WOTR IsengardSaruman_WOTR
End

;-------------------
;	MISTY MOUNTAINS
;-------------------
PlayerTemplate FactionWild
	StartMoney        				= 0
	SpellBookMp						= WildSpellBook_WOTR
	PurchaseScienceCommandSetMP		= WildSpellStoreCommandSet_WOTR
	InitialUpgrades					= Upgrade_WildFaction Upgrade_GoblinDualEconomyChoice Upgrade_EvilDualEconomyChoice Upgrade_WOTRMode	
	BuildableHeroesMP				= CreateAHero WildMuzgash WildGolfimbul_WOTR WildUrshak WildLugtheMauled_WOTR WildGreatGoblin WildBolgNew_WOTR WildTrueAzog_WOTR
End

;-------------------
;	DOL GULDUR
;-------------------
PlayerTemplate FactionGuldur
	StartMoney        				= 0
	SpellBookMp						= GuldurSpellBook_WOTR
	PurchaseScienceCommandSetMP		= GuldurSpellStoreCommandSet_WOTR
	InitialUpgrades					= Upgrade_GuldurFaction Upgrade_MordorDualEconomyChoice Upgrade_EvilDualEconomyChoice Upgrade_WOTRMode
	BuildableHeroesMP				= CreateAHero GuldurThrain_WOTR GuldurKrimpul_WOTR GuldurCargast_WOTR GuldurSaenathra_WOTR GuldurKhamul_WOTR GuldurNecromancer_WOTR
End

;-------------------
;	HARADWAITH
;-------------------
PlayerTemplate FactionAngmar
	StartMoney        				= 0
	SpellBookMp						= AngmarSpellBook_WOTR
	PurchaseScienceCommandSetMP		= AngmarSpellStoreCommandSet_WOTR
	InitialUpgrades					= Upgrade_AngmarFaction Upgrade_WOTRMode
	BuildableHeroesMP				= CreateAHero HaradBeruthiel_WOTR HaradSyarRhul_WOTR HaradSuladan HaradBurodapan HaradCassimir HaradCaranLambar_WOTR HaradGoldenKing
End

SkirmishAIData TheSkirmishAIData
    DisableBaseBuilding        = No
    DisableEconomyBuilding    = Yes
    DisableUnitBuilding        = No
    DisableScienceUpgrading = No
    DisableUnitUpgrading    = No
    DisableTacticalAI        = No
    DisableTeamBuilding        = No
    DisableWallBuilding        = Yes ;,; No

    AnyTypeTemplateDisabledSlots = 1
    AnyTypeTemplateDisabledSlots = 2
    AnyTypeTemplateDisabledSlots = 3
    AnyTypeTemplateDisabledSlots = 4
    AnyTypeTemplateDisabledSlots = 5
    AnyTypeTemplateDisabledSlots = 6
End
;------------------------------------------------------------------------;
;	  RHOVANION REGION 														 ;
;------------------------------------------------------------------------;
Object Inn
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Rhovanion
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Rhovanion
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Rhovanion
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Rhovanion
		End
	End
End
Object InnDesert
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Rhovanion
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Rhovanion
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Rhovanion
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Rhovanion
		End
	End
End
Object InnSnow
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Rhovanion
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Rhovanion
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Rhovanion
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Rhovanion
		End
	End
End
Object Inn_old
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Rhovanion
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Rhovanion
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Rhovanion
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Rhovanion
		End
	End
End
;endOfAuto-Generation
