ShadowMap
    MapSize = 2048
    MaxViewDistance = 2200.0
    MinShadowedTerrainHeight = 0.0
End

Weather

	HardwareFogColor = R:120 G:130 B:115
	HardwareFogEnable = Yes
	HardwareFogStart = 350
	HardwareFogEnd = 7000
	
End


Object UniversalBuildingFoundation
	ReplaceModule ModuleTag_DrawGuldurFloor
	Draw = W3DFloorDraw ModuleTag_DrawGuldurFloor_New
		ModelName		= UBFoundatiotX
		HideIfModelConditions	= USER_1	; Gondor
		HideIfModelConditions	= USER_2	; Rohan
		HideIfModelConditions	= USER_3	; Lothlorien
		HideIfModelConditions	= USER_4	; Dwarves
		HideIfModelConditions	= USER_5	; Mordor
		HideIfModelConditions	= USER_6	; Isengard
		HideIfModelConditions	= USER_7	; Goblins
		HideIfModelConditions	= USER_8	; Rivendell	
		HideIfModelConditions	= USER_10	; Mirkwood		
	End
	End
	ReplaceModule ModuleTag_DrawMirkwoodFloor
	Draw = W3DFloorDraw ModuleTag_DrawMirkwoodFloor_New
		ModelName		= TBFoundatiotX
		HideIfModelConditions	= USER_1	; Gondor
		HideIfModelConditions	= USER_2	; Rohan
		HideIfModelConditions	= USER_3	; Lothlorien
		HideIfModelConditions	= USER_4	; Dwarves
		HideIfModelConditions	= USER_5	; Mordor
		HideIfModelConditions	= USER_6	; Isengard
		HideIfModelConditions	= USER_7	; Goblins
		HideIfModelConditions	= USER_8	; Rivendell	
		HideIfModelConditions	= USER_9	; Dol Guldur	
	End
	End	
End	
;startOfAuto-Generation
;------------------------------------------------------------------------;
;	  RHOVANION REGION 														 ;
;------------------------------------------------------------------------;
Object Inn
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Rhovanion
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Rhovanion
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Rhovanion
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Rhovanion
		End
	End
End
Object InnDesert
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Rhovanion
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Rhovanion
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Rhovanion
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Rhovanion
		End
	End
End
Object InnSnow
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Rhovanion
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Rhovanion
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Rhovanion
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Rhovanion
		End
	End
End
Object Inn_old
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Rhovanion
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Rhovanion
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Rhovanion
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Rhovanion
		End
	End
End
;endOfAuto-Generation


;==== Auto Generated AI Fix =====;
SkirmishAIData TheSkirmishAIData
    DisableBaseBuilding        = No
    DisableEconomyBuilding     = No
    DisableUnitBuilding        = No
    DisableScienceUpgrading    = No
    DisableUnitUpgrading       = No
    DisableTacticalAI          = No
    DisableTeamBuilding        = No
    DisableWallBuilding        = Yes ;,; No
End
