Weather

HardwareFogColor = R:185 G:205 B:210
HardwareFogEnable = Yes
HardwareFogStart = 500
HardwareFogEnd = 9500
End

WaterTransparency
  ReflectionPlaneZ = 180.0;
  ReflectionOn = Yes
End


Object AIBaseMarkerBase // THIS IS SPAWNED TO MAKE A TEAM EXIST, ALLOWING UNITS TO BE RECRUITED ONTO IT
RemoveModule ModuleTag_01
AddModule
	Body = ActiveBody ModuleTag_02
		MaxHealth         = 1
	End
End
End

ChildObject PrimaryAIBaseMarker AIBaseMarkerBase // DARK PRESENCE CASTER
	KindOf          = PRELOAD STRUCTURE IMMOBILE AUTO_RALLYPOINT FS_FACTORY IGNORE_FOR_VICTORY IGNORE_FOR_EVA_SPEECH_POSITION NO_COLLIDE UNATTACKABLE NOT_AUTOACQUIRABLE
AddModule
	Behavior = GrantUpgradeCreate ModuleTag_GrantUpgrade
		UpgradeToGrant	= Upgrade_GondorStableLevel2
	End
End
AddModule
	Behavior = AttributeModifierAuraUpdate ModuleTag_DarkPresence
		StartsActive	= Yes
		TriggeredBy		= Upgrade_GondorStableLevel2
		BonusName		= GuldurDarkPresence
		RefreshDelay	= 2000
		Range			= 20000
		ObjectFilter	= ANY +GuldurBrokenRabble +GuldurBrokenRabbleA +GuldurBrokenRabbleB +GuldurBrokenRabbleC +GuldurBrokenRabbleHorde +GuldurOrcArcher +GuldurOrcArcherHorde +GuldurOrcPikeman +GuldurOrcPikemanForBrokenRabble +GuldurOrcPikemanHorde +GuldurOrcArcherHorde_Summoned +GuldurOrcPikemanHorde_Summoned +GuldurBannerOrc +GuldurPikemenArcherComboHorde
	End
End
End

Object MinisGateDoor
RemoveModule ModuleTag_AI
RemoveModule ModuleTage_AIGateUpdate
ReplaceModule ModuleTag_GATE
	Behavior = GateOpenAndCloseBehavior ModuleTag_GATEX
		ResetTimeInMilliseconds = 10500;must be longer than animation to avoid ->pop<-
		OpenByDefault = Yes
		PercentOpenForPathing = 50
		SoundOpeningGateLoop = GateOpenStart
		SoundClosingGateLoop = GateCloseStart
		SoundFinishedOpeningGate = GateOpenEnd
		SoundFinishedClosingGate = GateCloseEnd
		TimeBeforePlayingOpenSound = 9500
		TimeBeforePlayingClosedSound = 9500
	End
End
ArmorSet
        Conditions        = None
        Armor             = CastleGateArmorAttackable ; DefaultWallArmor
        DamageFX          = GateDamageFX
    End

End

Object AmonSulGate
RemoveModule ModuleTage_AIGateUpdate
ReplaceModule ModuleTag_GATE
	Behavior = GateOpenAndCloseBehavior ModuleTag_GATEX
		ResetTimeInMilliseconds			= 4000				;important! this must be longer than the gates animation, ir it will twitch
		OpenByDefault					= Yes
		PercentOpenForPathing			= 50
		SoundOpeningGateLoop			= GateOpenStart
		SoundClosingGateLoop			= GateCloseStart
		SoundFinishedOpeningGate		= GateOpenEnd
		SoundFinishedClosingGate		= GateCloseEnd
		TimeBeforePlayingOpenSound		= 3000
		TimeBeforePlayingClosedSound	= 3000
	End
End
ArmorSet
        Conditions        = None
        Armor             = CastleGateArmorAttackable ; DefaultWallArmor
        DamageFX          = GateDamageFX
    End

End

; -----------------------------------------------------------------------------------------------------------------------------
; MORDOR INFANTRY SETUP
; -----------------------------------------------------------------------------------------------------------------------------

Object MordorSiegeWorks

	CommandSet = MordorSiegeWorksCommandSetLevel1_ForMP

	ReplaceModule ModuleTag_MordorSiegeWorksLevel2
		Behavior = CommandSetUpgrade ModuleTag_MordorSiegeWorksLevel2_ForMP
			TriggeredBy		= Upgrade_MordorSiegeWorksLevel2
			ConflictsWith	= Upgrade_MordorSiegeWorksLevel3
			CommandSet		= MordorSiegeWorksCommandSetLevel2_ForMP
		End
	End
	
	ReplaceModule ModuleTag_MordorSiegeWorksLevel3
		Behavior = CommandSetUpgrade ModuleTag_MordorSiegeWorksLevel3_ForMP
			TriggeredBy		= Upgrade_MordorSiegeWorksLevel3
			CommandSet		= MordorSiegeWorksCommandSetLevel3_ForMP
		End
	End
End
	
;///////////////////////////////////////////////////////////////////////////	

Object IsengardSiegeWorks
	
	CommandSet = IsengardSiegeWorksCommandSetLevel1_ForMP
	
	ReplaceModule ModuleTag_IsengardSiegeWorksLevel2CommandSet
		Behavior = CommandSetUpgrade ModuleTag_IsengardSiegeWorksLevel2CommandSet_ForMP
			TriggeredBy		= Upgrade_StructureLevel2
			ConflictsWith	= Upgrade_StructureLevel3
			CommandSet		= IsengardSiegeWorksCommandSetLevel2_ForMP
		End
	End
	
	ReplaceModule ModuleTag_IsengardSiegeWorksLevel3CommandSet
		Behavior = CommandSetUpgrade ModuleTag_IsengardSiegeWorksLevel3CommandSet_ForMP
			TriggeredBy		= Upgrade_StructureLevel3
			CommandSet		= IsengardSiegeWorksCommandSetLevel3_ForMP
		End
	End
End

Object MordorSiegeTower
	ReplaceModule ModuleTag_07
		Behavior = SiegeDeploySpecialPower ModuleTag_WallSearchDistanceLocal
	    	SpecialPowerTemplate = SpecialAbilitySiegeDeploy
            LowerDelay = 1200
            RaiseDelay = 2000
            EvacuatePassengersOnDeploy = Yes
            SkipAdjustPosition = Yes ; have to skip the path find adjust or it this will not go to the right docking position
            WallSearchDistance = 99999.0
 		End
	End
End

Armor SiegeTowerArmor
  Armor = DEFAULT          10%     ;this sets the level for all nonspecified damage types
  Armor = CRUSH           15% ;25%     ;horseman damage
  Armor = SLASH           25% ;1%     ;soldier damage
  Armor = SIEGE		  30%     ;war machine attack
  Armor = STRUCTURAL	  30%	   ;Structural damage (Ent rocks)
  Armor = FLAME            20% ;10%     ;fire attack
  Armor = PIERCE            1%     ;archer damage 
  Armor = HERO		   10%     ;hero damage
  Armor = MAGIC		  50%     ;hero damage
  Armor = HERO_RANGED       1%     ;Hero bow damage     
End









;startOfAuto-Generation
;------------------------------------------------------------------------;
;	#################### WAR OF THE RING SETTINGS ####################   ;
;   - Upgrade_WOTRMode is now used to deal with WOTR commandsets         ;
;------------------------------------------------------------------------;
;-------------------
;	GONDOR
;-------------------
PlayerTemplate FactionMen
	StartMoney        				= 0
	SpellBookMp						= MenSpellBook_WOTR
	PurchaseScienceCommandSetMP		= MenSpellStoreCommandSet_WOTR
	InitialUpgrades					= Upgrade_MenFaction Upgrade_WOTRMode
	BuildableHeroesMP				= CreateAHero GondorPippin_WOTR GondorForlong_WOTR GondorBeregond_WOTR GondorImrahil_WOTR GondorDenethor_WOTR GondorFaramir GondorBoromir GondorGandalf_WOTR
End

;-------------------
;	ROHAN
;-------------------
PlayerTemplate FactionRohan
	StartMoney        				= 0
	SpellBookMp						= RohanSpellBook_WOTR
	PurchaseScienceCommandSetMP		= RohanSpellStoreCommandSet_WOTR
	InitialUpgrades					= Upgrade_RohanFaction Upgrade_WOTRMode
	BuildableHeroesMP				= CreateAHero RohanMerry_WOTR RohanEowyn_WOTR RohanElfhelm_WOTR RohanErkenbrand RohanTheodred RohanEomer RohanTheoden
End

;-------------------
;	LOTHLORIEN
;-------------------
PlayerTemplate FactionElves
	StartMoney        				= 0
	SpellBookMp						= ElvesSpellBook_WOTR
	PurchaseScienceCommandSetMP		= ElvesSpellStoreCommandSet_WOTR
	InitialUpgrades					= Upgrade_ElfFaction Upgrade_WOTRMode
	BuildableHeroesMP				= CreateAHero ElvenOrophin_WOTR ElvenRumil ElvenIdrial_WOTR ElvenHaldir ElvenCeleborn ElvenGaladrielLorien_WOTR MirkwoodThranduil_NCS
End

;-------------------
;	RIVENDELL
;-------------------
PlayerTemplate FactionArnor
	StartMoney        				= 0
	SpellBookMp						= ArnorSpellBook_WOTR
	PurchaseScienceCommandSetMP		= ArnorSpellStoreCommandSet_WOTR
	InitialUpgrades					= Upgrade_ArnorFaction Upgrade_WOTRMode	
	BuildableHeroesMP				= CreateAHero ArnorFattyBolger_WOTR ArnorFarmerMaggot_WOTR ElvenArwen_WOTR ElvenGildor ElvenElladan_WOTR ElvenElrohir_WOTR ArnorHalbarad_WOTR ElvenAragorn ElvenGlorfindel_WOTR ElvenElrond_WOTR
End

;-------------------
;	MIRKWOOD
;-------------------
PlayerTemplate FactionMirkwood
	StartMoney        				= 0
	SpellBookMp						= MirkwoodSpellBook_WOTR
	PurchaseScienceCommandSetMP		= MirkwoodSpellStoreCommandSet_WOTR
	InitialUpgrades					= Upgrade_MirkwoodFaction Upgrade_WOTRMode	
	BuildableHeroesMP				= CreateAHero MirkwoodTauriel MirkwoodGalion_WOTR MirkwoodFeren DorwinionFrumgar_WOTR MirkwoodRadagast_WOTR MirkwoodGrimbeorn_WOTR MirkwoodLegolas MirkwoodThranduil
End

;-------------------
;	EREBOR
;-------------------
PlayerTemplate FactionDwarves
	StartMoney        				= 0
	SpellBookMp						= DwarvesSpellBook_WOTR
	PurchaseScienceCommandSetMP		= DwarvesSpellStoreCommandSet_WOTR
	InitialUpgrades					= Upgrade_DwarfFaction Upgrade_WOTRMode	
	BuildableHeroesMP				= CreateAHero DwarvenArcah_WOTR DwarvenGloin_WOTR DwarvenHadhod_WOTR DwarvenBrand_WOTR DwarvenGimli_WOTR DwarvenThorinStonehelm_WOTR DwarvenKingDain_WOTR YoungThorin_WOTR DwarvenThrain_WOTR YoungDain_WOTR YoungDwalin_WOTR YoungBalin_WOTR
End

;-------------------
;	MORDOR
;-------------------
PlayerTemplate FactionMordor
	StartMoney        				= 0
	SpellBookMp						= MordorSpellBook_WOTR
	PurchaseScienceCommandSetMP		= MordorSpellStoreCommandSet_WOTR
	InitialUpgrades					= Upgrade_MordorDualEconomyChoice Upgrade_MordorFaction Upgrade_EvilDualEconomyChoice Upgrade_WOTRMode
	BuildableHeroesMP				= CreateAHero MordorGorbag_WOTR MordorShagrat_WOTR MordorAkhorahil_WOTR MordorUvatha_WOTR  MordorGothmog MordorMouthOfSauron MordorMollok_WOTR MordorWitchKing_WOTR RhunBelokhZa_WOTR RhunKhrenTak_WOTR RhunVahRus_WOTR
End

;-------------------
;	ISENGARD
;-------------------
PlayerTemplate FactionIsengard
	StartMoney        				= 0
	SpellBookMp						= IsengardSpellBook_WOTR
	PurchaseScienceCommandSetMP		= IsengardSpellStoreCommandSet_WOTR
	InitialUpgrades					= Upgrade_IsengardDualEconomyChoice Upgrade_IsengardFaction Upgrade_EvilDualEconomyChoice Upgrade_WOTRMode
	BuildableHeroesMP				= CreateAHero IsengardGrishnakh_WOTR IsengardWormTongue_WOTR IsengardSharku_WOTR IsengardUgluk IsengardLurtz IsengardWulfgar_WOTR IsengardSaruman_WOTR
End

;-------------------
;	MISTY MOUNTAINS
;-------------------
PlayerTemplate FactionWild
	StartMoney        				= 0
	SpellBookMp						= WildSpellBook_WOTR
	PurchaseScienceCommandSetMP		= WildSpellStoreCommandSet_WOTR
	InitialUpgrades					= Upgrade_WildFaction Upgrade_GoblinDualEconomyChoice Upgrade_EvilDualEconomyChoice Upgrade_WOTRMode	
	BuildableHeroesMP				= CreateAHero WildMuzgash WildGolfimbul_WOTR WildUrshak WildLugtheMauled_WOTR WildGreatGoblin WildBolgNew_WOTR WildTrueAzog_WOTR
End

;-------------------
;	DOL GULDUR
;-------------------
PlayerTemplate FactionGuldur
	StartMoney        				= 0
	SpellBookMp						= GuldurSpellBook_WOTR
	PurchaseScienceCommandSetMP		= GuldurSpellStoreCommandSet_WOTR
	InitialUpgrades					= Upgrade_GuldurFaction Upgrade_MordorDualEconomyChoice Upgrade_EvilDualEconomyChoice Upgrade_WOTRMode
	BuildableHeroesMP				= CreateAHero GuldurThrain_WOTR GuldurKrimpul_WOTR GuldurCargast_WOTR GuldurSaenathra_WOTR GuldurKhamul_WOTR GuldurNecromancer_WOTR
End

;-------------------
;	HARADWAITH
;-------------------
PlayerTemplate FactionAngmar
	StartMoney        				= 0
	SpellBookMp						= AngmarSpellBook_WOTR
	PurchaseScienceCommandSetMP		= AngmarSpellStoreCommandSet_WOTR
	InitialUpgrades					= Upgrade_AngmarFaction Upgrade_WOTRMode
	BuildableHeroesMP				= CreateAHero HaradBeruthiel_WOTR HaradSyarRhul_WOTR HaradSuladan HaradBurodapan HaradCassimir HaradCaranLambar_WOTR HaradGoldenKing
End

SkirmishAIData TheSkirmishAIData
    DisableBaseBuilding        = No
    DisableEconomyBuilding    = Yes
    DisableUnitBuilding        = No
    DisableScienceUpgrading = No
    DisableUnitUpgrading    = No
    DisableTacticalAI        = No
    DisableTeamBuilding        = No
    DisableWallBuilding        = Yes ;,; No

    AnyTypeTemplateDisabledSlots = 1
    AnyTypeTemplateDisabledSlots = 2
    AnyTypeTemplateDisabledSlots = 3
    AnyTypeTemplateDisabledSlots = 4
    AnyTypeTemplateDisabledSlots = 5
    AnyTypeTemplateDisabledSlots = 6
    AnyTypeTemplateDisabledSlots = 7
    AnyTypeTemplateDisabledSlots = 8
End
;------------------------------------------------------------------------;
;	  GONDOR REGION 														 ;
;------------------------------------------------------------------------;
Object Inn
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Gondor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Gondor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Gondor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Gondor
		End
	End
End
Object InnDesert
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Gondor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Gondor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Gondor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Gondor
		End
	End
End
Object InnSnow
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Gondor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Gondor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Gondor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Gondor
		End
	End
End
Object Inn_old
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Gondor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Gondor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Gondor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Gondor
		End
	End
End
;endOfAuto-Generation
