Weather
	
;; ---------------------------------
;;              SNOW, ACTUALLY ASH
;; ---------------------------------
    SnowEnabled = Yes               ; enable/disable snow on the map.
    IsSnowing = Yes               ; is it snowing today?
    SnowTexture = exash01.tga
    SnowBoxHeight = 1100             ; height from which snow falls
    SnowSpacing = 60             ; snow spacing -- less means more
    NumberTiles = 4

    SnowAmplitude = 40              ; amount of side-to-side movement. 
    SnowFrequencyScaleX = 0.02        ; speed of side-to-side wave movement.
    SnowFrequencyScaleY = 0.005         ; speed of side-to-side wave movement. 

    SnowPointSize = 1               ; scale the size of snow particles.
    SnowMinPointSize = 1           ; min point size
    SnowMaxPointSize = 3           ; max point size

    SnowPointSprites = No           ; set to "no" for point-sprite emulation.
    SnowQuadSize = 3               ; scale the size of snow particles when using point-sprite emulation.

    SnowSpeed = 30               ; speed at which snow falls
    SnowXYSpeed = X:50 Y:30



  HardwareFogColor = R:135 G:115 B:90
  HardwareFogEnable = Yes
  HardwareFogStart = 450
  HardwareFogEnd = 8000


End

WaterTransparency
  ReflectionPlaneZ = 62.0;
  ReflectionOn = Yes
End


FXParticleSystem FogMist;FXParticleSystem CINECampfireEmbers;ground fog

  System
    Priority = VERY_LOW_OR_ABOVE
    Shader = ALPHA
    ParticleName = EXCloud02.tga
    Lifetime = 350 350; 350 350
    Size = 0.1 0.1; 1 1
    BurstDelay = .2 .5; 2 5
    BurstCount = 1 2; 1 1
    IsEmitAboveGroundOnly = No
  End
  Color = DefaultColor
    Color1 = R:200 G:95 B:50 50; R:255 G:255 B:255 75
  End
  Alpha = DefaultAlpha
    Alpha1 = 0.1 0.3 50; 0.1 0.3 50
    Alpha2 = 0 0 120; 0 0 350
  End
  Update = DefaultUpdate
    SizeRate = 1 3; 1 3
    SizeRateDamping = 0.9 0.99
    AngularRateZ = -0.02 0.02
    AngularDamping = 1 1
    AngularDampingXY = 1 1
  End
  Physics = DefaultPhysics
    VelocityDamping = 0.7 0.8
    DriftVelocity = X:1 Y:.3 Z:0.7; X:0.2 Y:0.2 Z:0.08
  End
  EmissionVelocity = OrthoEmissionVelocity
    X = -0.8 -0.8; -0.4 -0.4
  End
  EmissionVolume = LineEmissionVolume
    IsHollow = Yes
    StartPoint = X:0 Y:-80 Z:0
    EndPoint = X:0 Y:100 Z:0
  End
  Draw = DefaultDraw
  End
End

;startOfAuto-Generation
;------------------------------------------------------------------------;
;	  MORDOR REGION 														 ;
;------------------------------------------------------------------------;
Object Inn
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Mordor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Mordor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Mordor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Mordor
		End
	End
End
Object InnDesert
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Mordor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Mordor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Mordor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Mordor
		End
	End
End
Object InnSnow
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Mordor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Mordor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Mordor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Mordor
		End
	End
End
Object Inn_old
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Mordor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Mordor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Mordor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Mordor
		End
	End
End
;endOfAuto-Generation


;==== Auto Generated AI Fix =====;
SkirmishAIData TheSkirmishAIData
    DisableBaseBuilding        = No
    DisableEconomyBuilding     = No
    DisableUnitBuilding        = No
    DisableScienceUpgrading    = No
    DisableUnitUpgrading       = No
    DisableTacticalAI          = No
    DisableTeamBuilding        = No
    DisableWallBuilding        = Yes ;,; No
End
