Weather

HardwareFogColor = R:185 G:205 B:210
HardwareFogEnable = Yes
HardwareFogStart = 500
HardwareFogEnd = 8500
End


Object AIBaseMarkerBase // THIS IS SPAWNED TO MAKE A TEAM EXIST, ALLOWING UNITS TO BE RECRUITED ONTO IT
RemoveModule ModuleTag_01
AddModule
	Body = ActiveBody ModuleTag_02
		MaxHealth         = 1
	End
End
End

ChildObject PrimaryAIBaseMarker AIBaseMarkerBase // DARK PRESENCE CASTER
	KindOf          = PRELOAD STRUCTURE IMMOBILE AUTO_RALLYPOINT FS_FACTORY IGNORE_FOR_VICTORY IGNORE_FOR_EVA_SPEECH_POSITION NO_COLLIDE UNATTACKABLE NOT_AUTOACQUIRABLE
AddModule
	Behavior = GrantUpgradeCreate ModuleTag_GrantUpgrade
		UpgradeToGrant	= Upgrade_GondorStableLevel2
	End
End
AddModule
	Behavior = AttributeModifierAuraUpdate ModuleTag_DarkPresence
		StartsActive	= Yes
		TriggeredBy		= Upgrade_GondorStableLevel2
		BonusName		= GuldurDarkPresence
		RefreshDelay	= 2000
		Range			= 20000
		ObjectFilter	= ANY +GuldurBrokenRabble +GuldurBrokenRabbleA +GuldurBrokenRabbleB +GuldurBrokenRabbleC +GuldurBrokenRabbleHorde +GuldurOrcArcher +GuldurOrcArcherHorde +GuldurOrcPikeman +GuldurOrcPikemanForBrokenRabble +GuldurOrcPikemanHorde +GuldurOrcArcherHorde_Summoned +GuldurOrcPikemanHorde_Summoned +GuldurBannerOrc +GuldurPikemenArcherComboHorde
	End
End
End

;-------------------------------------------------------------------------------------------------
Object RohanCastleBaseKeep
        DisplayName     =  OBJECT:Rohan Golden Hall

ReplaceModule ModuleTag_Draw
  ; *** ART Parameters ***
  Draw = W3DScriptedModelDraw ModuleTag_Draw_Override
     DefaultModelConditionState
      Model = RBGoldHall
    End

	IdleAnimationState
		StateName = STATE_None
		;BeginScript
		;	Prev = CurDrawablePrevAnimationState()
		;	if Prev == "BeingConstructed" then 
			    ; Don't play completed sound when canceling build-in-progress or when
			    ; destroyed halfway
		;	    if not CurDrawableModelcondition( "DYING" ) then 
		;			CurDrawablePlaySound("CampSoldierCompleteGeneric")
		;		end
		;	end
		;EndScript
	End

;------------Build Up States
    ModelConditionState   = ACTIVELY_BEING_CONSTRUCTED
      Model               = RBCastKeep_A
;      ParticleSysBone	  = NONE BuildingDoughnutCloud
      ParticleSysBone     = NONE BuildingContructDust
    End  

	AnimationState          = ACTIVELY_BEING_CONSTRUCTED
		StateName = STATE_Constructing
		Animation
			AnimationName	= RBCastKeep_A.RBCastKeep_A
			AnimationMode   = MANUAL
		End
		BeginScript
			CurDrawablePlaySound("GondorBarracksBeginConstruction")
			CurDrawablePlaySound("BuildingTopple")
		EndScript
	End

    ModelConditionState   = DESTROYED_WHILST_BEING_CONSTRUCTED
		Model = RBCastKeep_A
		ParticleSysBone NONE Explosion3
		ParticleSysBone NONE ExplosiveMineSmoke02
    End  
	AnimationState	= DESTROYED_WHILST_BEING_CONSTRUCTED
		StateName = STATE_DetroyedConstructing
		Animation
			AnimationName		= RBCastKeep_A.RBCastKeep_A
			AnimationMode		= ONCE_BACKWARDS
			AnimationBlendTime	= 90	; 3 seconds * 30 frames
		End
		; Specifically no start last frame flag here.
		Flags = START_FRAME_FIRST
	End
	
;------------Build Up States
    ModelConditionState   = BASE_BUILD
      Model               = RBCastKeep_A
;      ParticleSysBone	  = NONE BuildingDoughnutCloud
      ParticleSysBone     = NONE BuildingContructDust
    End  

	AnimationState		  = BASE_BUILD
		StateName = STATE_None
		Animation
			AnimationName = RBCastKeep_A.RBCastKeep_A
			AnimationMode = ONCE
			AnimationBlendTime = 0			
			AnimationSpeedFactorRange = 2.0 2.0 ; 300 frame anim, but need to shrink down to 5 seconds
		End
		BeginScript
			CurDrawablePlaySound("GondorBarracksBeginConstruction")
			CurDrawablePlaySound("BuildingTopple")
		EndScript
	End

    ModelConditionState   = JUST_BUILT
      Model               = RBCastKeep_A
;      ParticleSysBone	  = NONE BuildingDoughnutCloud
      ParticleSysBone     = NONE BuildingContructDust
    End  
	AnimationState		  = JUST_BUILT
		StateName = STATE_None
		Animation
			AnimationName = RBCastKeep_A.RBCastKeep_A
			AnimationMode = MANUAL			
			AnimationBlendTime = 0
		End
        Flags = START_FRAME_FIRST
	End
	
    ModelConditionState  = DAMAGED
      Model         = RBCastKeep_D1  
	
    End
    
    AnimationState = DAMAGED
		StateName = STATE_None
		EnteringStateFX	= FX_BuildingDamaged
    End

    ModelConditionState  = REALLYDAMAGED
      Model         = RBCastKeep_D2
;      ParticleSysBone NONE furnaceSmoke
	
    End
	AnimationState = REALLYDAMAGED
		StateName = STATE_None
       	Animation				=	ReallyDamagedanimation
			AnimationName		=	 RBCastKeep_D2.RBCastKeep_D2
			AnimationMode		=	ONCE
		End
		EnteringStateFX	= FX_BuildingReallyDamaged
    End


	;-------RUBBLE--------------------------------------------------------------------------------
	TransitionState = TRANS_U_IntoRubble
		Animation = D3
			AnimationName		= RBCastKeep_D3.RBCastKeep_D3
			AnimationMode		= ONCE
			AnimationBlendTime = 0
		End
		ParticleSysBone NONE Explosion3
		ParticleSysBone NONE ExplosiveMineSmoke02
	End
    ModelConditionState  = RUBBLE
		Model         = RBCastKeep_D3
    End
    AnimationState = RUBBLE
		Flags = START_FRAME_LAST
		StateName = STATE_Rubble
		Animation				=	Death
			AnimationName		=	RBCastKeep_D3.RBCastKeep_D3
			AnimationMode		=	ONCE
		End
		BeginScript
			Prev = CurDrawablePrevAnimationState()
			if Prev == "STATE_None"
			then
				; Only play the rubble anim if we havn't come from another rubble.
				CurDrawableSetTransitionAnimState("TRANS_U_IntoRubble")
			end
		EndScript
    End      

  End
End
End
;startOfAuto-Generation
;------------------------------------------------------------------------;
;	  ROHAN REGION 														 ;
;------------------------------------------------------------------------;
Object Inn
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Rohan
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Rohan
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Rohan
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Rohan
		End
	End
End
Object InnDesert
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Rohan
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Rohan
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Rohan
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Rohan
		End
	End
End
Object InnSnow
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Rohan
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Rohan
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Rohan
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Rohan
		End
	End
End
Object Inn_old
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Rohan
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Rohan
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Rohan
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Rohan
		End
	End
End
;endOfAuto-Generation


PlayerTemplate FactionCivilian
	Side              = Civilian
	PlayableSide      = No
	StartMoney        = 0
	PreferredColor    = R:64 G:64 B:64
	IntrinsicSciences = None
	DisplayName       = INI:FactionCivilian
	ScoreScreenImage  = MutiPlayer_ScoreScreen
	LoadScreenMusic   = Shell2MusicForLoadScreen
	IntrinsicSciences		= SCIENCE_GOOD
	IntrinsicSciencesMP 		= SCIENCE_ROHAN
	SpellBook			= GoodSpellBook
	SpellBookMp			= RohanSpellBook
	PurchaseScienceCommandSet	= GoodSpellStoreCommandSet
	PurchaseScienceCommandSetMP	= RohanSpellStoreCommandSet
End

; -----------------------------------------------------------------------------------------------------------------------------
; MORDOR INFANTRY SETUP
; -----------------------------------------------------------------------------------------------------------------------------

Object MordorSiegeWorks

	CommandSet = MordorSiegeWorksCommandSetLevel1_ForMP

	ReplaceModule ModuleTag_MordorSiegeWorksLevel2
		Behavior = CommandSetUpgrade ModuleTag_MordorSiegeWorksLevel2_ForMP
			TriggeredBy		= Upgrade_MordorSiegeWorksLevel2
			ConflictsWith	= Upgrade_MordorSiegeWorksLevel3
			CommandSet		= MordorSiegeWorksCommandSetLevel2_ForMP
		End
	End
	
	ReplaceModule ModuleTag_MordorSiegeWorksLevel3
		Behavior = CommandSetUpgrade ModuleTag_MordorSiegeWorksLevel3_ForMP
			TriggeredBy		= Upgrade_MordorSiegeWorksLevel3
			CommandSet		= MordorSiegeWorksCommandSetLevel3_ForMP
		End
	End
End
	
;///////////////////////////////////////////////////////////////////////////	

Object IsengardSiegeWorks
	
	CommandSet = IsengardSiegeWorksCommandSetLevel1_ForMP
	
	ReplaceModule ModuleTag_IsengardSiegeWorksLevel2CommandSet
		Behavior = CommandSetUpgrade ModuleTag_IsengardSiegeWorksLevel2CommandSet_ForMP
			TriggeredBy		= Upgrade_StructureLevel2
			ConflictsWith	= Upgrade_StructureLevel3
			CommandSet		= IsengardSiegeWorksCommandSetLevel2_ForMP
		End
	End
	
	ReplaceModule ModuleTag_IsengardSiegeWorksLevel3CommandSet
		Behavior = CommandSetUpgrade ModuleTag_IsengardSiegeWorksLevel3CommandSet_ForMP
			TriggeredBy		= Upgrade_StructureLevel3
			CommandSet		= IsengardSiegeWorksCommandSetLevel3_ForMP
		End
	End
End

Object MordorSiegeTower
	ReplaceModule ModuleTag_07
		Behavior = SiegeDeploySpecialPower ModuleTag_WallSearchDistanceLocal
	    	SpecialPowerTemplate = SpecialAbilitySiegeDeploy
            LowerDelay = 1200
            RaiseDelay = 2000
            EvacuatePassengersOnDeploy = Yes
            SkipAdjustPosition = Yes ; have to skip the path find adjust or it this will not go to the right docking position
            WallSearchDistance = 99999.0
 		End
	End
End

Armor SiegeTowerArmor
  Armor = DEFAULT          10%     ;this sets the level for all nonspecified damage types
  Armor = CRUSH           15% ;25%     ;horseman damage
  Armor = SLASH           25% ;1%     ;soldier damage
  Armor = SIEGE		  30%     ;war machine attack
  Armor = STRUCTURAL	  30%	   ;Structural damage (Ent rocks)
  Armor = FLAME            20% ;10%     ;fire attack
  Armor = PIERCE            1%     ;archer damage 
  Armor = HERO		   10%     ;hero damage
  Armor = MAGIC		  50%     ;hero damage
  Armor = HERO_RANGED       1%     ;Hero bow damage     
End

;--------------------------------------------------------------------------
; Rohan Castle Setup
;--------------------------------------------------------------------------

Object RohanCastleDoor
ReplaceModule ModuleTag_02
 Body                  = ActiveBody ModuleTag_52X
   MaxHealth			= 10000.0
   MaxHealthDamaged		= 4000.0
   MaxHealthReallyDamaged	= 100.0
   
  End
End
End

ChildObject RohanArcherRangeFoundation RohanArcherRange
RemoveModule ModuleTag_SpawnPatrols
RemoveModule ModuleTag_SpawnPatrolsWestolders
RemoveModule ModuleTag_SpawnPatrols2
RemoveModule ModuleTag_SpawnPatrols3
ReplaceModule ModuleTag_04
 	Behavior = GettingBuiltBehavior ModuleTag_04X
		SpawnTimer	= DEFAULT_STRUCTURE_HEALDELAY
		RebuildWhenDead = Yes
        SelfBuildingLoop = BuildingConstructionLoop ; Only played if we DON'T spawn a worker
		SelfRepairFromDamageLoop  = NoSound         ; This doesn't cause an animation, so don't bother playing a sound
		SelfRepairFromRubbleLoop  = BuildingConstructionLoop
	End
End
End

ChildObject RohanBarracksFoundation RohanBarracks
RemoveModule ModuleTag_SpawnPatrols
RemoveModule ModuleTag_SpawnPatrolsWestolders
RemoveModule ModuleTag_SpawnPatrols2
RemoveModule ModuleTag_SpawnPatrols3
ReplaceModule ModuleTag_04
 	Behavior = GettingBuiltBehavior ModuleTag_04X
		SpawnTimer	= DEFAULT_STRUCTURE_HEALDELAY
		RebuildWhenDead = Yes
        SelfBuildingLoop = BuildingConstructionLoop ; Only played if we DON'T spawn a worker
		SelfRepairFromDamageLoop  = NoSound         ; This doesn't cause an animation, so don't bother playing a sound
		SelfRepairFromRubbleLoop  = BuildingConstructionLoop
	End
End
End

ChildObject RohanFarmFoundation RohanFarm
ReplaceModule GetBuiltBehaviorTag
 	Behavior = GettingBuiltBehavior GetBuiltBehaviorTagx
		SpawnTimer	= DEFAULT_STRUCTURE_HEALDELAY
		RebuildWhenDead = Yes
        SelfBuildingLoop = BuildingConstructionLoop ; Only played if we DON'T spawn a worker
		SelfRepairFromDamageLoop  = NoSound         ; This doesn't cause an animation, so don't bother playing a sound
		SelfRepairFromRubbleLoop  = BuildingConstructionLoop
	End
End
End


ChildObject RohanStableFoundation RohanStable
RemoveModule ModuleTag_SpawnPatrols
RemoveModule ModuleTag_SpawnPatrolsWestolders
RemoveModule ModuleTag_SpawnPatrols2
RemoveModule ModuleTag_SpawnPatrols3
ReplaceModule GetBuiltBehaviorTag
 	Behavior = GettingBuiltBehavior ModuleTag_GetBuilt2
		SpawnTimer	= DEFAULT_STRUCTURE_HEALDELAY
		RebuildWhenDead = Yes
        SelfBuildingLoop = BuildingConstructionLoop ; Only played if we DON'T spawn a worker
		SelfRepairFromDamageLoop  = NoSound         ; This doesn't cause an animation, so don't bother playing a sound
		SelfRepairFromRubbleLoop  = BuildingConstructionLoop
	End
End
End

ChildObject RohanWindmillFoundation RohanWindmill
ReplaceModule GetBuiltBehaviorTag
 	Behavior = GettingBuiltBehavior ModuleTag_GetBuilt2
		SpawnTimer	= DEFAULT_STRUCTURE_HEALDELAY
		RebuildWhenDead = Yes
        SelfBuildingLoop = BuildingConstructionLoop ; Only played if we DON'T spawn a worker
		SelfRepairFromDamageLoop  = NoSound         ; This doesn't cause an animation, so don't bother playing a sound
		SelfRepairFromRubbleLoop  = BuildingConstructionLoop
	End
End
End

ChildObject RohanWorkshopFoundation RohanWorkshop
RemoveModule ModuleTag_SpawnPatrols
RemoveModule ModuleTag_SpawnPatrolsWestolders
RemoveModule ModuleTag_SpawnPatrols2
RemoveModule ModuleTag_SpawnPatrols3
ReplaceModule GetBuiltBehaviorTag
 	Behavior = GettingBuiltBehavior ModuleTag_GetBuilt2
		SpawnTimer	= DEFAULT_STRUCTURE_HEALDELAY
		RebuildWhenDead = Yes
        SelfBuildingLoop = BuildingConstructionLoop ; Only played if we DON'T spawn a worker
		SelfRepairFromDamageLoop  = NoSound         ; This doesn't cause an animation, so don't bother playing a sound
		SelfRepairFromRubbleLoop  = BuildingConstructionLoop
	End
End
End

Object RohanHeroStatueFoundation
ReplaceModule ModuleTag_04
 	Behavior = GettingBuiltBehavior ModuleTag_04x
		SpawnTimer	= DEFAULT_STRUCTURE_HEALDELAY
		RebuildWhenDead = Yes
        SelfBuildingLoop = BuildingConstructionLoop ; Only played if we DON'T spawn a worker
		SelfRepairFromDamageLoop  = NoSound         ; This doesn't cause an animation, so don't bother playing a sound
		SelfRepairFromRubbleLoop  = BuildingConstructionLoop
	End
End
End

ChildObject RohanWellFoundation RohanWell
ReplaceModule GetBuiltBehaviorTag
 	Behavior = GettingBuiltBehavior GetBuiltBehaviorTagx
		SpawnTimer	= DEFAULT_STRUCTURE_HEALDELAY
		RebuildWhenDead = Yes
        SelfBuildingLoop = BuildingConstructionLoop ; Only played if we DON'T spawn a worker
		SelfRepairFromDamageLoop  = NoSound         ; This doesn't cause an animation, so don't bother playing a sound
		SelfRepairFromRubbleLoop  = BuildingConstructionLoop
	End
End
End

;==== Auto Generated AI Fix =====;
SkirmishAIData TheSkirmishAIData
    DisableBaseBuilding        = No
    DisableEconomyBuilding     = No
    DisableUnitBuilding        = No
    DisableScienceUpgrading    = No
    DisableUnitUpgrading       = No
    DisableTacticalAI          = No
    DisableTeamBuilding        = No
    DisableWallBuilding        = Yes ;,; No
End
