Object AIBaseMarkerBase // THIS IS SPAWNED TO MAKE A TEAM EXIST, ALLOWING UNITS TO BE RECRUITED ONTO IT
RemoveModule ModuleTag_01
AddModule
	Body = ActiveBody ModuleTag_02
		MaxHealth         = 1
	End
End
End

ChildObject PrimaryAIBaseMarker AIBaseMarkerBase // DARK PRESENCE CASTER
	KindOf          = PRELOAD STRUCTURE IMMOBILE AUTO_RALLYPOINT FS_FACTORY IGNORE_FOR_VICTORY IGNORE_FOR_EVA_SPEECH_POSITION NO_COLLIDE UNATTACKABLE NOT_AUTOACQUIRABLE
AddModule
	Behavior = GrantUpgradeCreate ModuleTag_GrantUpgrade
		UpgradeToGrant	= Upgrade_GondorStableLevel2
	End
End
AddModule
	Behavior = AttributeModifierAuraUpdate ModuleTag_DarkPresence
		StartsActive	= Yes
		TriggeredBy		= Upgrade_GondorStableLevel2
		BonusName		= GuldurDarkPresence
		RefreshDelay	= 2000
		Range			= 20000
		ObjectFilter	= ANY +GuldurBrokenRabble +GuldurBrokenRabbleA +GuldurBrokenRabbleB +GuldurBrokenRabbleC +GuldurBrokenRabbleHorde +GuldurOrcArcher +GuldurOrcArcherHorde +GuldurOrcPikeman +GuldurOrcPikemanForBrokenRabble +GuldurOrcPikemanHorde +GuldurOrcArcherHorde_Summoned +GuldurOrcPikemanHorde_Summoned +GuldurBannerOrc +GuldurPikemenArcherComboHorde
	End
End
End

Object TDHEreborMainGateDoor 
ArmorSet
        Conditions        = None
        Armor             = CastleGateArmorAttackable ; DefaultWallArmor
        DamageFX          = GateDamageFX
    End

End

WaterTransparency
  ReflectionPlaneZ = 35.0;
  ReflectionOn = Yes
End

Weather
	CloudTextureSize = X:4250 Y:4000
	CloudOffsetPerSecond = X:-0 Y:-0


	HardwareFogColor = R:155 G:182 B:190
	HardwareFogEnable = Yes
	HardwareFogStart = 600
	HardwareFogEnd = 6000 ;2200
	
End

;-----------------------------------------------------------------

AIData
  LowLodTreeName = TreeLowLODGreyHavens
END
;startOfAuto-Generation
;------------------------------------------------------------------------;
;	  EREBOR REGION 														 ;
;------------------------------------------------------------------------;
Object Inn
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Erebor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Erebor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Erebor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Erebor
		End
	End
End
Object InnDesert
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Erebor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Erebor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Erebor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Erebor
		End
	End
End
Object InnSnow
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Erebor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Erebor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Erebor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Erebor
		End
	End
End
Object Inn_old
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Erebor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Erebor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Erebor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Erebor
		End
	End
End
;endOfAuto-Generation


;==== Auto Generated AI Fix =====;
SkirmishAIData TheSkirmishAIData
    DisableBaseBuilding        = No
    DisableEconomyBuilding     = No
    DisableUnitBuilding        = No
    DisableScienceUpgrading    = No
    DisableUnitUpgrading       = No
    DisableTacticalAI          = No
    DisableTeamBuilding        = No
    DisableWallBuilding        = Yes ;,; No
End
