Weather
    SnowEnabled = Yes               ; enable/disable snow on the map.
    IsSnowing = Yes               ; is it snowing today?
    SnowTexture = EXSnowFlake2.tga
    SnowBoxHeight = 2000             ; height from which snow falls
    SnowSpacing = 30             ; snow spacing -- less means more
    NumberTiles = 4

    SnowAmplitude = 30              ; 20 amount of side-to-side movement. 
    SnowFrequencyScaleX = 0.01        ; 0.01 speed of side-to-side wave movement.
    SnowFrequencyScaleY = 0.005         ; 0.005 speed of side-to-side wave movement. 

    SnowPointSize = 2               ; scale the size of snow particles.
    SnowMinPointSize = 3           ; min point size
    SnowMaxPointSize = 7           ; max point size

    SnowPointSprites = No           ; set to "no" for point-sprite emulation.
    SnowQuadSize = 3               ; scale the size of snow particles when using point-sprite emulation.

    SnowSpeed = 60              ; speed at which snow falls
    SnowXYSpeed = X:40 Y:25
	
	
	HardwareFogColor = R:105 G:115 B:130; R:46 G:55 B:70
	HardwareFogEnable = Yes
	HardwareFogStart = 300
	HardwareFogEnd = 6000

End

Object AotRAmonHenN08
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End


Object ForBWall5
 
  Geometry              = BOX
  GeometryMajorRadius   = 0.1
  GeometryMinorRadius   = 0.1
  GeometryHeight        = 0.1
  GeometryIsSmall       = No
End
;startOfAuto-Generation
;------------------------------------------------------------------------;
;	  GONDOR REGION 														 ;
;------------------------------------------------------------------------;
Object Inn
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Gondor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Gondor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Gondor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Gondor
		End
	End
End
Object InnDesert
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Gondor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Gondor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Gondor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Gondor
		End
	End
End
Object InnSnow
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Gondor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Gondor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Gondor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Gondor
		End
	End
End
Object Inn_old
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Gondor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Gondor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Gondor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Gondor
		End
	End
End
;endOfAuto-Generation


;==== Auto Generated AI Fix =====;
SkirmishAIData TheSkirmishAIData
    DisableBaseBuilding        = No
    DisableEconomyBuilding     = No
    DisableUnitBuilding        = No
    DisableScienceUpgrading    = No
    DisableUnitUpgrading       = No
    DisableTacticalAI          = No
    DisableTeamBuilding        = No
    DisableWallBuilding        = Yes ;,; No
End
