//-------------------------------
// Create a Hero Appearance Bling.
//-------------------------------
//-------------------------------
// Head	Gear
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHH01
	DescriptionTag	 = CreateAHero:BlingName_CHH01
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_CHH01
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHH02
	DescriptionTag	 = CreateAHero:BlingName_CHH02
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_CHH02
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHH03
	DescriptionTag	 = CreateAHero:BlingName_CHH03
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_CHH03
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHH04
	DescriptionTag	 = CreateAHero:BlingName_CHH04
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_CHH04
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHH05
	DescriptionTag	 = CreateAHero:BlingName_CHH05
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_CHH05
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHH06
	DescriptionTag	 = CreateAHero:BlingName_CHH06
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_CHH06
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHH07
	DescriptionTag	 = CreateAHero:BlingName_CHH07
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_CHH07
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHH08
	DescriptionTag	 = CreateAHero:BlingName_CHH08
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_CHH08
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHH09
	DescriptionTag	 = CreateAHero:BlingName_CHH09
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_CHH09
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHH10
	DescriptionTag	 = CreateAHero:BlingName_CHH10
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_CHH10
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHH11
	DescriptionTag	 = CreateAHero:BlingName_CHH11
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_CHH11
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHH12
	DescriptionTag	 = CreateAHero:BlingName_CHH12
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_CHH12
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHH13
	DescriptionTag	 = CreateAHero:BlingName_CHH13
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_CHH13
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHH14
	DescriptionTag	 = CreateAHero:BlingName_CHH14
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_CHH14
End


CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHSP01
	DescriptionTag	 = CreateAHero:BlingName_CHSP01
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_CHSP01
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHSP02
	DescriptionTag	 = CreateAHero:BlingName_CHSP02
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_CHSP02
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHSP03
	DescriptionTag	 = CreateAHero:BlingName_CHSP03
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_CHSP03
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHSP04
	DescriptionTag	 = CreateAHero:BlingName_CHSP04
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_CHSP04
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHSP05
	DescriptionTag	 = CreateAHero:BlingName_CHSP05
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_CHSP05
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHSP06
	DescriptionTag	 = CreateAHero:BlingName_CHSP06
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_CHSP06
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHSP07
	DescriptionTag	 = CreateAHero:BlingName_CHSP07
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_CHSP07
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHSP08
	DescriptionTag	 = CreateAHero:BlingName_CHSP08
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_CHSP08
End


CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHG01
	DescriptionTag	 = CreateAHero:BlingName_CHG01
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_CHG01
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHG02
	DescriptionTag	 = CreateAHero:BlingName_CHG02
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_CHG02
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHG03
	DescriptionTag	 = CreateAHero:BlingName_CHG03
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_CHG03
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHG04
	DescriptionTag	 = CreateAHero:BlingName_CHG04
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_CHG04
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHG05
	DescriptionTag	 = CreateAHero:BlingName_CHG05
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_CHG05
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHG06
	DescriptionTag	 = CreateAHero:BlingName_CHG06
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_CHG06
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHG07
	DescriptionTag	 = CreateAHero:BlingName_CHG07
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_CHG07
End


CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHS01
	DescriptionTag	 = CreateAHero:BlingName_CHS01
	GroupName		 = CreateAHero_Shield
	BlingUpgradeName = Upgrade_CHS01
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHS02
	DescriptionTag	 = CreateAHero:BlingName_CHS02
	GroupName		 = CreateAHero_Shield
	BlingUpgradeName = Upgrade_CHS02
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHS03
	DescriptionTag	 = CreateAHero:BlingName_CHS03
	GroupName		 = CreateAHero_Shield
	BlingUpgradeName = Upgrade_CHS03
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHS04
	DescriptionTag	 = CreateAHero:BlingName_CHS04
	GroupName		 = CreateAHero_Shield
	BlingUpgradeName = Upgrade_CHS04
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHS05
	DescriptionTag	 = CreateAHero:BlingName_CHS05
	GroupName		 = CreateAHero_Shield
	BlingUpgradeName = Upgrade_CHS05
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHS06
	DescriptionTag	 = CreateAHero:BlingName_CHS06
	GroupName		 = CreateAHero_Shield
	BlingUpgradeName = Upgrade_CHS06
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHS07
	DescriptionTag	 = CreateAHero:BlingName_CHS07
	GroupName		 = CreateAHero_Shield
	BlingUpgradeName = Upgrade_CHS07
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHS08
	DescriptionTag	 = CreateAHero:BlingName_CHS08
	GroupName		 = CreateAHero_Shield
	BlingUpgradeName = Upgrade_CHS08
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHS09
	DescriptionTag	 = CreateAHero:BlingName_CHS09
	GroupName		 = CreateAHero_Shield
	BlingUpgradeName = Upgrade_CHS09
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHS10
	DescriptionTag	 = CreateAHero:BlingName_CHS10
	GroupName		 = CreateAHero_Shield
	BlingUpgradeName = Upgrade_CHS10
End


CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHB01
	DescriptionTag	 = CreateAHero:BlingName_CHB01
	GroupName		 = CreateAHero_Boots
	BlingUpgradeName = Upgrade_CHB01
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHB02
	DescriptionTag	 = CreateAHero:BlingName_CHB02
	GroupName		 = CreateAHero_Boots
	BlingUpgradeName = Upgrade_CHB02
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHB03
	DescriptionTag	 = CreateAHero:BlingName_CHB03
	GroupName		 = CreateAHero_Boots
	BlingUpgradeName = Upgrade_CHB03
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHB04
	DescriptionTag	 = CreateAHero:BlingName_CHB04
	GroupName		 = CreateAHero_Boots
	BlingUpgradeName = Upgrade_CHB04
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHB05
	DescriptionTag	 = CreateAHero:BlingName_CHB05
	GroupName		 = CreateAHero_Boots
	BlingUpgradeName = Upgrade_CHB05
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHB06
	DescriptionTag	 = CreateAHero:BlingName_CHB06
	GroupName		 = CreateAHero_Boots
	BlingUpgradeName = Upgrade_CHB06
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHB07
	DescriptionTag	 = CreateAHero:BlingName_CHB07
	GroupName		 = CreateAHero_Boots
	BlingUpgradeName = Upgrade_CHB07
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHB08
	DescriptionTag	 = CreateAHero:BlingName_CHB08
	GroupName		 = CreateAHero_Boots
	BlingUpgradeName = Upgrade_CHB08
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHB09
	DescriptionTag	 = CreateAHero:BlingName_CHB09
	GroupName		 = CreateAHero_Boots
	BlingUpgradeName = Upgrade_CHB09
End


CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHBOD01
	DescriptionTag	 = CreateAHero:BlingName_CHBOD01
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_CHBOD01
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHBOD02
	DescriptionTag	 = CreateAHero:BlingName_CHBOD02
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_CHBOD02
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHBOD03
	DescriptionTag	 = CreateAHero:BlingName_CHBOD03
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_CHBOD03
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHBOD04
	DescriptionTag	 = CreateAHero:BlingName_CHBOD04
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_CHBOD04
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHBOD05
	DescriptionTag	 = CreateAHero:BlingName_CHBOD05
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_CHBOD05
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHBOD06
	DescriptionTag	 = CreateAHero:BlingName_CHBOD06
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_CHBOD06
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHBOD07
	DescriptionTag	 = CreateAHero:BlingName_CHBOD07
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_CHBOD07
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHBOD08
	DescriptionTag	 = CreateAHero:BlingName_CHBOD08
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_CHBOD08
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHBOD09
	DescriptionTag	 = CreateAHero:BlingName_CHBOD09
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_CHBOD09
End
CreateAHeroBling // DWARF
	NameTag			 = CreateAHero:BlingName_CHBOD10
	DescriptionTag	 = CreateAHero:BlingName_CHBOD10
	GroupName		 = CreateAHero_Body
	BlingUpgradeName = Upgrade_CHBOD10
End




//-------------------------------
// Generic No Upgrades
CreateAHeroBling // No Head Gear
	NameTag			 = CreateAHero:BlingName_NoHelmet
	DescriptionTag	 = CreateAHero:BlingDesc_NoHelmet
	GroupName		 = CreateAHero_Helmet
	BlingUpgradeName = Upgrade_NoHelmet
End
CreateAHeroBling // No Gauntlets
	NameTag			 = CreateAHero:BlingName_NoGauntlets
	DescriptionTag	 = CreateAHero:BlingDesc_NoGauntlets
	GroupName		 = CreateAHero_Gauntlets
	BlingUpgradeName = Upgrade_NoGauntlets
End
CreateAHeroBling // No Shoulder Plates
	NameTag			 = CreateAHero:BlingName_NoShoulderPlates
	DescriptionTag	 = CreateAHero:BlingDesc_NoShoulderPlates
	GroupName		 = CreateAHero_ShoulderPlates
	BlingUpgradeName = Upgrade_NoShoulderPlates
End
CreateAHeroBling // No Shield
	NameTag			 = CreateAHero:BlingName_NoShield
	DescriptionTag	 = CreateAHero:BlingDesc_NoShield
	GroupName		 = CreateAHero_Shield
	BlingUpgradeName = Upgrade_NoShield
End
CreateAHeroBling // No Boots
	NameTag			 = CreateAHero:BlingName_NoBoots
	DescriptionTag	 = CreateAHero:BlingDesc_NoBoots
	GroupName		 = CreateAHero_Boots
	BlingUpgradeName = Upgrade_NoBoots
End
