;////////////
;////////////
;/// This Includes file contains long voice.ini AudioEvents
;/// to bypass them getting loaded into WB and causing crashes
;////////////
AudioEvent mgfotr_aragorn001
  Sounds = mgfotr_aragorn001
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn002
  Sounds = mgfotr_aragorn002
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn003
  Sounds = mgfotr_aragorn003
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn004
  Sounds = mgfotr_aragorn004
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn005
  Sounds = mgfotr_aragorn005
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn006
  Sounds = mgfotr_aragorn006
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn007
  Sounds = mgfotr_aragorn007
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn008
  Sounds = mgfotr_aragorn008
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn009
  Sounds = mgfotr_aragorn009
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn010
  Sounds = mgfotr_aragorn010
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn011
  Sounds = mgfotr_aragorn011
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn012
  Sounds = mgfotr_aragorn012
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn013
  Sounds = mgfotr_aragorn013
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn014
  Sounds = mgfotr_aragorn014
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn015
  Sounds = mgfotr_aragorn015
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn016
  Sounds = mgfotr_aragorn016
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn017
  Sounds = mgfotr_aragorn017
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn018
  Sounds = mgfotr_aragorn018
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn019
  Sounds = mgfotr_aragorn019
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn020
  Sounds = mgfotr_aragorn020
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn021
  Sounds = mgfotr_aragorn021
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn022
  Sounds = mgfotr_aragorn022
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn023
  Sounds = mgfotr_aragorn023
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn024
  Sounds = mgfotr_aragorn024
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn025
  Sounds = mgfotr_aragorn025
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn026
  Sounds = mgfotr_aragorn026
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn027
  Sounds = mgfotr_aragorn027
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn028
  Sounds = mgfotr_aragorn028
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn029
  Sounds = mgfotr_aragorn029
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn030
  Sounds = mgfotr_aragorn030
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn031
  Sounds = mgfotr_aragorn031
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn032
  Sounds = mgfotr_aragorn032
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn033
  Sounds = mgfotr_aragorn033
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn034
  Sounds = mgfotr_aragorn034
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn035
  Sounds = mgfotr_aragorn035
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn036
  Sounds = mgfotr_aragorn036
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn037
  Sounds = mgfotr_aragorn037
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn038
  Sounds = mgfotr_aragorn038
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn039
  Sounds = mgfotr_aragorn039
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn040
  Sounds = mgfotr_aragorn040
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn041
  Sounds = mgfotr_aragorn041
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn042
  Sounds = mgfotr_aragorn042
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn043
  Sounds = mgfotr_aragorn043
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn044
  Sounds = mgfotr_aragorn044
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn045
  Sounds = mgfotr_aragorn045
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn046
  Sounds = mgfotr_aragorn046
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn047
  Sounds = mgfotr_aragorn047
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn048
  Sounds = mgfotr_aragorn048
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn049
  Sounds = mgfotr_aragorn049
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn050
  Sounds = mgfotr_aragorn050
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn051
  Sounds = mgfotr_aragorn051
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn052
  Sounds = mgfotr_aragorn052
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn053
  Sounds = mgfotr_aragorn053
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn054
  Sounds = mgfotr_aragorn054
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn055
  Sounds = mgfotr_aragorn055
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn056
  Sounds = mgfotr_aragorn056
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn057
  Sounds = mgfotr_aragorn057
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn058
  Sounds = mgfotr_aragorn058
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn059
  Sounds = mgfotr_aragorn059
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn060
  Sounds = mgfotr_aragorn060
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn061
  Sounds = mgfotr_aragorn061
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn062
  Sounds = mgfotr_aragorn062
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn063
  Sounds = mgfotr_aragorn063
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn064
  Sounds = mgfotr_aragorn064
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn065
  Sounds = mgfotr_aragorn065
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn066
  Sounds = mgfotr_aragorn066
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn067
  Sounds = mgfotr_aragorn067
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn068
  Sounds = mgfotr_aragorn068
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn069
  Sounds = mgfotr_aragorn069
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn070
  Sounds = mgfotr_aragorn070
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn071
  Sounds = mgfotr_aragorn071
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn072
  Sounds = mgfotr_aragorn072
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn073
  Sounds = mgfotr_aragorn073
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn074
  Sounds = mgfotr_aragorn074
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn075
  Sounds = mgfotr_aragorn075
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn076
  Sounds = mgfotr_aragorn076
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn077
  Sounds = mgfotr_aragorn077
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End


AudioEvent mgfotr_aragorn078
  Sounds = mgfotr_aragorn078
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End


AudioEvent mgfotr_aragorn079
  Sounds = mgfotr_aragorn079
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn080
  Sounds = mgfotr_aragorn080
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn081
  Sounds = mgfotr_aragorn081
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn082
  Sounds = mgfotr_aragorn082
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn083
  Sounds = mgfotr_aragorn083
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn084
  Sounds = mgfotr_aragorn084
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn085
  Sounds = mgfotr_aragorn085
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn086
  Sounds = mgfotr_aragorn086
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn087
  Sounds = mgfotr_aragorn087
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End


AudioEvent mgfotr_aragorn088
  Sounds = mgfotr_aragorn088
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn089
  Sounds = mgfotr_aragorn089
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn090
  Sounds = mgfotr_aragorn090
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn091
  Sounds = mgfotr_aragorn091
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn092
  Sounds = mgfotr_aragorn092
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn093
  Sounds = mgfotr_aragorn093
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn094
  Sounds = mgfotr_aragorn094
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn095
  Sounds = mgfotr_aragorn095
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn096
  Sounds = mgfotr_aragorn096
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn097
  Sounds = mgfotr_aragorn097
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn098
  Sounds = mgfotr_aragorn098
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn099
  Sounds = mgfotr_aragorn099
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn100
  Sounds = mgfotr_aragorn100
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn101
  Sounds = mgfotr_aragorn101
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn102
  Sounds = mgfotr_aragorn102
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End


AudioEvent mgfotr_aragorn103
  Sounds = mgfotr_aragorn103
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn104
  Sounds = mgfotr_aragorn104
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn105
  Sounds = mgfotr_aragorn105
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn106
  Sounds = mgfotr_aragorn106
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn107
  Sounds = mgfotr_aragorn107
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn108
  Sounds = mgfotr_aragorn108
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn109
  Sounds = mgfotr_aragorn109
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn110
  Sounds = mgfotr_aragorn110
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn111
  Sounds = mgfotr_aragorn111
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn112
  Sounds = mgfotr_aragorn112
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn113
  Sounds = mgfotr_aragorn113
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn114
  Sounds = mgfotr_aragorn114
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn115
  Sounds = mgfotr_aragorn115
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn116
  Sounds = mgfotr_aragorn116
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn117
  Sounds = mgfotr_aragorn117
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn118
  Sounds = mgfotr_aragorn118
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn119
  Sounds = mgfotr_aragorn119
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn120
  Sounds = mgfotr_aragorn120
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn121
  Sounds = mgfotr_aragorn121
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn122
  Sounds = mgfotr_aragorn122
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn123
  Sounds = mgfotr_aragorn123
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn124
  Sounds = mgfotr_aragorn124
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn125
  Sounds = mgfotr_aragorn125
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn126
  Sounds = mgfotr_aragorn126
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn127
  Sounds = mgfotr_aragorn127
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn128
  Sounds = mgfotr_aragorn128
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn129
  Sounds = mgfotr_aragorn129
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn130
  Sounds = mgfotr_aragorn130
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn131
  Sounds = mgfotr_aragorn131
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn132
  Sounds = mgfotr_aragorn132
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn133
  Sounds = mgfotr_aragorn133
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn134
  Sounds = mgfotr_aragorn134
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn135
  Sounds = mgfotr_aragorn135
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn136
  Sounds = mgfotr_aragorn136
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn137
  Sounds = mgfotr_aragorn137
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn138
  Sounds = mgfotr_aragorn138
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn139
  Sounds = mgfotr_aragorn139
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn140
  Sounds = mgfotr_aragorn140
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn141
  Sounds = mgfotr_aragorn141
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn142
  Sounds = mgfotr_aragorn142
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn143
  Sounds = mgfotr_aragorn143
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn144
  Sounds = mgfotr_aragorn144
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn145
  Sounds = mgfotr_aragorn145
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn146
  Sounds = mgfotr_aragorn146
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn147
  Sounds = mgfotr_aragorn147
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn148
  Sounds = mgfotr_aragorn148
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn149
  Sounds = mgfotr_aragorn149
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn150
  Sounds = mgfotr_aragorn150
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn151
  Sounds = mgfotr_aragorn151
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn152
  Sounds = mgfotr_aragorn152
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn153
  Sounds = mgfotr_aragorn153
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn154
  Sounds = mgfotr_aragorn154
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn155
  Sounds = mgfotr_aragorn155
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn156
  Sounds = mgfotr_aragorn156
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn157
  Sounds = mgfotr_aragorn157
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn158
  Sounds = mgfotr_aragorn158
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn159
  Sounds = mgfotr_aragorn159
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn160
  Sounds = mgfotr_aragorn160
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn161
  Sounds = mgfotr_aragorn161
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn162
  Sounds = mgfotr_aragorn162
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn163
  Sounds = mgfotr_aragorn163
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn164
  Sounds = mgfotr_aragorn164
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn165
  Sounds = mgfotr_aragorn165
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn166
  Sounds = mgfotr_aragorn166
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn167
  Sounds = mgfotr_aragorn167
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn168
  Sounds = mgfotr_aragorn168
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End


AudioEvent mgfotr_aragorn169
  Sounds = mgfotr_aragorn169
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn170
  Sounds = mgfotr_aragorn170
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn171
  Sounds = mgfotr_aragorn171
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn172
  Sounds = mgfotr_aragorn172
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn173
  Sounds = mgfotr_aragorn173
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn174
  Sounds = mgfotr_aragorn174
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn175
  Sounds = mgfotr_aragorn175
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn176
  Sounds = mgfotr_aragorn176
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn177
  Sounds = mgfotr_aragorn177
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn178
  Sounds = mgfotr_aragorn178
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End


AudioEvent mgfotr_aragorn179
  Sounds = mgfotr_aragorn179
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn180
  Sounds = mgfotr_aragorn180
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn181
  Sounds = mgfotr_aragorn181
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn182
  Sounds = mgfotr_aragorn182
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn183
  Sounds = mgfotr_aragorn183
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn184
  Sounds = mgfotr_aragorn184
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn185
  Sounds = mgfotr_aragorn185
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn186
  Sounds = mgfotr_aragorn186
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn187
  Sounds = mgfotr_aragorn187
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn188
  Sounds = mgfotr_aragorn188
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn189
  Sounds = mgfotr_aragorn189
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn190
  Sounds = mgfotr_aragorn190
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn191
  Sounds = mgfotr_aragorn191
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn192
  Sounds = mgfotr_aragorn192
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn193
  Sounds = mgfotr_aragorn193
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn194
  Sounds = mgfotr_aragorn194
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn195
  Sounds = mgfotr_aragorn195
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn196
  Sounds = mgfotr_aragorn196
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn197
  Sounds = mgfotr_aragorn197
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn198
  Sounds = mgfotr_aragorn198
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn199
  Sounds = mgfotr_aragorn199
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn200
  Sounds = mgfotr_aragorn200
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn201
  Sounds = mgfotr_aragorn201
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn202
  Sounds = mgfotr_aragorn202
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn203
  Sounds = mgfotr_aragorn203
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn204
  Sounds = mgfotr_aragorn204
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn205
  Sounds = mgfotr_aragorn205
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn206
  Sounds = mgfotr_aragorn206
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn207
  Sounds = mgfotr_aragorn207
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn208
  Sounds = mgfotr_aragorn208
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn209
  Sounds = mgfotr_aragorn209
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn210
  Sounds = mgfotr_aragorn210
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn211
  Sounds = mgfotr_aragorn211
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn212
  Sounds = mgfotr_aragorn212
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn213
  Sounds = mgfotr_aragorn213
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn214
  Sounds = mgfotr_aragorn214
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn215
  Sounds = mgfotr_aragorn215
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn216
  Sounds = mgfotr_aragorn216
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn217
  Sounds = mgfotr_aragorn217
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn218
  Sounds = mgfotr_aragorn218
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn219
  Sounds = mgfotr_aragorn219
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn220
  Sounds = mgfotr_aragorn220
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn221
  Sounds = mgfotr_aragorn221
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn222
  Sounds = mgfotr_aragorn222
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn223
  Sounds = mgfotr_aragorn223
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn224
  Sounds = mgfotr_aragorn224
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn225
  Sounds = mgfotr_aragorn225
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn226
  Sounds = mgfotr_aragorn226
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn227
  Sounds = mgfotr_aragorn227
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn228
  Sounds = mgfotr_aragorn228
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn229
  Sounds = mgfotr_aragorn229
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn230
  Sounds = mgfotr_aragorn230
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn231
  Sounds = mgfotr_aragorn231
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn232
  Sounds = mgfotr_aragorn232
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn233
  Sounds = mgfotr_aragorn233
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn234
  Sounds = mgfotr_aragorn234
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn235
  Sounds = mgfotr_aragorn235
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn236
  Sounds = mgfotr_aragorn236
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn237
  Sounds = mgfotr_aragorn237
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn238
  Sounds = mgfotr_aragorn238
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn239
  Sounds = mgfotr_aragorn239
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn240
  Sounds = mgfotr_aragorn240
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn241
  Sounds = mgfotr_aragorn241
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn242
  Sounds = mgfotr_aragorn242
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn243
  Sounds = mgfotr_aragorn243
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn244
  Sounds = mgfotr_aragorn244
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn245
  Sounds = mgfotr_aragorn245
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn246
  Sounds = mgfotr_aragorn246
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn247
  Sounds = mgfotr_aragorn247
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn248
  Sounds = mgfotr_aragorn248
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn249
  Sounds = mgfotr_aragorn249
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn250
  Sounds = mgfotr_aragorn250
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn251
  Sounds = mgfotr_aragorn251
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn252
  Sounds = mgfotr_aragorn252
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn253
  Sounds = mgfotr_aragorn253
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn254
  Sounds = mgfotr_aragorn254
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn255
  Sounds = mgfotr_aragorn255
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn256
  Sounds = mgfotr_aragorn256
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn257
  Sounds = mgfotr_aragorn257
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn258
  Sounds = mgfotr_aragorn258
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn259
  Sounds = mgfotr_aragorn259
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn260
  Sounds = mgfotr_aragorn260
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn261
  Sounds = mgfotr_aragorn261
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn262
  Sounds = mgfotr_aragorn262
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn263
  Sounds = mgfotr_aragorn263
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn264
  Sounds = mgfotr_aragorn264
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn265
  Sounds = mgfotr_aragorn265
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn266
  Sounds = mgfotr_aragorn266
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn267
  Sounds = mgfotr_aragorn267
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn268
  Sounds = mgfotr_aragorn268
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn269
  Sounds = mgfotr_aragorn269
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn270
  Sounds = mgfotr_aragorn270
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn271
  Sounds = mgfotr_aragorn271
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn272
  Sounds = mgfotr_aragorn272
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn273
  Sounds = mgfotr_aragorn273
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn274
  Sounds = mgfotr_aragorn274
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn275
  Sounds = mgfotr_aragorn275
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn276
  Sounds = mgfotr_aragorn276
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn277
  Sounds = mgfotr_aragorn277
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn277B
  Sounds = mgfotr_aragorn277B
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn278
  Sounds = mgfotr_aragorn278
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn279
  Sounds = mgfotr_aragorn279
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End


AudioEvent mgfotr_aragorn280
  Sounds = mgfotr_aragorn280
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn281
  Sounds = mgfotr_aragorn281
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn282
  Sounds = mgfotr_aragorn282
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn283
  Sounds = mgfotr_aragorn283
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn284
  Sounds = mgfotr_aragorn284
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn285
  Sounds = mgfotr_aragorn285
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn286
  Sounds = mgfotr_aragorn286
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn287
  Sounds = mgfotr_aragorn287
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn288
  Sounds = mgfotr_aragorn288
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn289
  Sounds = mgfotr_aragorn289
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End


AudioEvent mgfotr_aragorn290
  Sounds = mgfotr_aragorn290
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn291
  Sounds = mgfotr_aragorn291
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn292
  Sounds = mgfotr_aragorn292
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn293
  Sounds = mgfotr_aragorn293
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn294
  Sounds = mgfotr_aragorn294
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn295
  Sounds = mgfotr_aragorn295
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn296
  Sounds = mgfotr_aragorn296
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn297
  Sounds = mgfotr_aragorn297
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn298
  Sounds = mgfotr_aragorn298
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn299
  Sounds = mgfotr_aragorn299
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn300
  Sounds = mgfotr_aragorn300
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn301
  Sounds = mgfotr_aragorn301
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End


AudioEvent mgfotr_aragorn302
  Sounds = mgfotr_aragorn302
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn303
  Sounds = mgfotr_aragorn303
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn304
  Sounds = mgfotr_aragorn304
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn305
  Sounds = mgfotr_aragorn305
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn306
  Sounds = mgfotr_aragorn306
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn307
  Sounds = mgfotr_aragorn307
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn308
  Sounds = mgfotr_aragorn308
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn309
  Sounds = mgfotr_aragorn309
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn310
  Sounds = mgfotr_aragorn310
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn311
  Sounds = mgfotr_aragorn311
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn312
  Sounds = mgfotr_aragorn312
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn313
  Sounds = mgfotr_aragorn313
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn314
  Sounds = mgfotr_aragorn314
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn315
  Sounds = mgfotr_aragorn315
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn316
  Sounds = mgfotr_aragorn316
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn317
  Sounds = mgfotr_aragorn317
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn318
  Sounds = mgfotr_aragorn318
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn319
  Sounds = mgfotr_aragorn319
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn320
  Sounds = mgfotr_aragorn320
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn321
  Sounds = mgfotr_aragorn321
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn322
  Sounds = mgfotr_aragorn322
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn323
  Sounds = mgfotr_aragorn323
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn324
  Sounds = mgfotr_aragorn324
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn325
  Sounds = mgfotr_aragorn325
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn326
  Sounds = mgfotr_aragorn326
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn327
  Sounds = mgfotr_aragorn327
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn328
  Sounds = mgfotr_aragorn328
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn329
  Sounds = mgfotr_aragorn329
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn330
  Sounds = mgfotr_aragorn330
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn331
  Sounds = mgfotr_aragorn331
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn332
  Sounds = mgfotr_aragorn332
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn333
  Sounds = mgfotr_aragorn333
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn334
  Sounds = mgfotr_aragorn334
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn335
  Sounds = mgfotr_aragorn335
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn336
  Sounds = mgfotr_aragorn336
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn337
  Sounds = mgfotr_aragorn337
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn338
  Sounds = mgfotr_aragorn338
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn339
  Sounds = mgfotr_aragorn339
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn340
  Sounds = mgfotr_aragorn340
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn341
  Sounds = mgfotr_aragorn341
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn342
  Sounds = mgfotr_aragorn342
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn343
  Sounds = mgfotr_aragorn343
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn344
  Sounds = mgfotr_aragorn344
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn345
  Sounds = mgfotr_aragorn345
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn346
  Sounds = mgfotr_aragorn346
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn347
  Sounds = mgfotr_aragorn347
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn348
  Sounds = mgfotr_aragorn348
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn349
  Sounds = mgfotr_aragorn349
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn350
  Sounds = mgfotr_aragorn350
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn351
  Sounds = mgfotr_aragorn351
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn352
  Sounds = mgfotr_aragorn352
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn353
  Sounds = mgfotr_aragorn353
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn354
  Sounds = mgfotr_aragorn354
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn355
  Sounds = mgfotr_aragorn355
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn356
  Sounds = mgfotr_aragorn356
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn357
  Sounds = mgfotr_aragorn357
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn358
  Sounds = mgfotr_aragorn358
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn359
  Sounds = mgfotr_aragorn359
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn360
  Sounds = mgfotr_aragorn360
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn361
  Sounds = mgfotr_aragorn361
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn362
  Sounds = mgfotr_aragorn362
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn363
  Sounds = mgfotr_aragorn363
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn364
  Sounds = mgfotr_aragorn364
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn365
  Sounds = mgfotr_aragorn365
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn366
  Sounds = mgfotr_aragorn366
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn367
  Sounds = mgfotr_aragorn367
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn368
  Sounds = mgfotr_aragorn368
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn369
  Sounds = mgfotr_aragorn369
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn370
  Sounds = mgfotr_aragorn370
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn371
  Sounds = mgfotr_aragorn371
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn372
  Sounds = mgfotr_aragorn372
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn373
  Sounds = mgfotr_aragorn373
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn374
  Sounds = mgfotr_aragorn374
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn375
  Sounds = mgfotr_aragorn375
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn376
  Sounds = mgfotr_aragorn376
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn377
  Sounds = mgfotr_aragorn377
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn378
  Sounds = mgfotr_aragorn378
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn379
  Sounds = mgfotr_aragorn379
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn380
  Sounds = mgfotr_aragorn380
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn381
  Sounds = mgfotr_aragorn381
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn382
  Sounds = mgfotr_aragorn382
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn383
  Sounds = mgfotr_aragorn383
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn384
  Sounds = mgfotr_aragorn384
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn385
  Sounds = mgfotr_aragorn385
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn386
  Sounds = mgfotr_aragorn386
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn387
  Sounds = mgfotr_aragorn387
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn388
  Sounds = mgfotr_aragorn388
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn389
  Sounds = mgfotr_aragorn389
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn390
  Sounds = mgfotr_aragorn390
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn391
  Sounds = mgfotr_aragorn391
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn392
  Sounds = mgfotr_aragorn392
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn393
  Sounds = mgfotr_aragorn393
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn394
  Sounds = mgfotr_aragorn394
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn395
  Sounds = mgfotr_aragorn395
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn396
  Sounds = mgfotr_aragorn396
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn397
  Sounds = mgfotr_aragorn397
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn398
  Sounds = mgfotr_aragorn398
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn399
  Sounds = mgfotr_aragorn399
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn400
  Sounds = mgfotr_aragorn400
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn401
  Sounds = mgfotr_aragorn401
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn402
  Sounds = mgfotr_aragorn402
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_aragorn403
  Sounds = mgfotr_aragorn403
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf001
  Sounds = mgfotr_gandalf001
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf002
  Sounds = mgfotr_gandalf002
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf003
  Sounds = mgfotr_gandalf003
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf004
  Sounds = mgfotr_gandalf004
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf005
  Sounds = mgfotr_gandalf005
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf006
  Sounds = mgfotr_gandalf006
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf007
  Sounds = mgfotr_gandalf007
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf008
  Sounds = mgfotr_gandalf008
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf009
  Sounds = mgfotr_gandalf009
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf010
  Sounds = mgfotr_gandalf010
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf011
  Sounds = mgfotr_gandalf011
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf012
  Sounds = mgfotr_gandalf012
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf013
  Sounds = mgfotr_gandalf013
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf014
  Sounds = mgfotr_gandalf014
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf015
  Sounds = mgfotr_gandalf015
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf016
  Sounds = mgfotr_gandalf016
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf017
  Sounds = mgfotr_gandalf017
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf018
  Sounds = mgfotr_gandalf018
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf019
  Sounds = mgfotr_gandalf019
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf020
  Sounds = mgfotr_gandalf020
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf021
  Sounds = mgfotr_gandalf021
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf022
  Sounds = mgfotr_gandalf022
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf023
  Sounds = mgfotr_gandalf023
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf024
  Sounds = mgfotr_gandalf024
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf025
  Sounds = mgfotr_gandalf025
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf026
  Sounds = mgfotr_gandalf026
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf027
  Sounds = mgfotr_gandalf027
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf028
  Sounds = mgfotr_gandalf028
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf029
  Sounds = mgfotr_gandalf029
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf030
  Sounds = mgfotr_gandalf030
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf031
  Sounds = mgfotr_gandalf031
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf032
  Sounds = mgfotr_gandalf032
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf033
  Sounds = mgfotr_gandalf033
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf034
  Sounds = mgfotr_gandalf034
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf035
  Sounds = mgfotr_gandalf035
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf036
  Sounds = mgfotr_gandalf036
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf037
  Sounds = mgfotr_gandalf037
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf038
  Sounds = mgfotr_gandalf038
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf039
  Sounds = mgfotr_gandalf039
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf040
  Sounds = mgfotr_gandalf040
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf041
  Sounds = mgfotr_gandalf041
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf042
  Sounds = mgfotr_gandalf042
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf043
  Sounds = mgfotr_gandalf043
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf044
  Sounds = mgfotr_gandalf044
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf045
  Sounds = mgfotr_gandalf045
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf046
  Sounds = mgfotr_gandalf046
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf047
  Sounds = mgfotr_gandalf047
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf048
  Sounds = mgfotr_gandalf048
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf049
  Sounds = mgfotr_gandalf049
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf050
  Sounds = mgfotr_gandalf050
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf051
  Sounds = mgfotr_gandalf051
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf052
  Sounds = mgfotr_gandalf052
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf053
  Sounds = mgfotr_gandalf053
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf054
  Sounds = mgfotr_gandalf054
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf055
  Sounds = mgfotr_gandalf055
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf056
  Sounds = mgfotr_gandalf056
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf057
  Sounds = mgfotr_gandalf057
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf058
  Sounds = mgfotr_gandalf058
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf059
  Sounds = mgfotr_gandalf059
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf060
  Sounds = mgfotr_gandalf060
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf061
  Sounds = mgfotr_gandalf061
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf062
  Sounds = mgfotr_gandalf062
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf063
  Sounds = mgfotr_gandalf063
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf064
  Sounds = mgfotr_gandalf064
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf065
  Sounds = mgfotr_gandalf065
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf066
  Sounds = mgfotr_gandalf066
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf067
  Sounds = mgfotr_gandalf067
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf068
  Sounds = mgfotr_gandalf068
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf069
  Sounds = mgfotr_gandalf069
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf070
  Sounds = mgfotr_gandalf070
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf071
  Sounds = mgfotr_gandalf071
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End


AudioEvent mgfotr_gandalf072
  Sounds = mgfotr_gandalf072
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf073
  Sounds = mgfotr_gandalf073
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf074
  Sounds = mgfotr_gandalf074
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf075
  Sounds = mgfotr_gandalf075
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf076
  Sounds = mgfotr_gandalf076
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf077
  Sounds = mgfotr_gandalf077
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf078
  Sounds = mgfotr_gandalf078
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf079
  Sounds = mgfotr_gandalf079
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf080
  Sounds = mgfotr_gandalf080
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf081
  Sounds = mgfotr_gandalf081
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf082
  Sounds = mgfotr_gandalf082
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf083
  Sounds = mgfotr_gandalf083
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf084
  Sounds = mgfotr_gandalf084
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf085
  Sounds = mgfotr_gandalf085
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf086
  Sounds = mgfotr_gandalf086
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf087
  Sounds = mgfotr_gandalf087
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf088
  Sounds = mgfotr_gandalf088
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf089
  Sounds = mgfotr_gandalf089
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf090
  Sounds = mgfotr_gandalf090
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf091
  Sounds = mgfotr_gandalf091
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf092
  Sounds = mgfotr_gandalf092
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf093
  Sounds = mgfotr_gandalf093
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf094
  Sounds = mgfotr_gandalf094
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf095
  Sounds = mgfotr_gandalf095
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf096
  Sounds = mgfotr_gandalf096
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf097
  Sounds = mgfotr_gandalf097
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf098
  Sounds = mgfotr_gandalf098
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf099
  Sounds = mgfotr_gandalf099
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf100
  Sounds = mgfotr_gandalf100
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf101
  Sounds = mgfotr_gandalf101
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End


AudioEvent mgfotr_gandalf102
  Sounds = mgfotr_gandalf102
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf103
  Sounds = mgfotr_gandalf103
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf104
  Sounds = mgfotr_gandalf104
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf105
  Sounds = mgfotr_gandalf105
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf106
  Sounds = mgfotr_gandalf106
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf107
  Sounds = mgfotr_gandalf107
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf108
  Sounds = mgfotr_gandalf108
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf109
  Sounds = mgfotr_gandalf109
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf110
  Sounds = mgfotr_gandalf110
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf111
  Sounds = mgfotr_gandalf111
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf112
  Sounds = mgfotr_gandalf112
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf113
  Sounds = mgfotr_gandalf113
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf114
  Sounds = mgfotr_gandalf114
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf115
  Sounds = mgfotr_gandalf115
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf116
  Sounds = mgfotr_gandalf116
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf117
  Sounds = mgfotr_gandalf117
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf118
  Sounds = mgfotr_gandalf118
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf119
  Sounds = mgfotr_gandalf119
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf120
  Sounds = mgfotr_gandalf120
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf121
  Sounds = mgfotr_gandalf121
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf122
  Sounds = mgfotr_gandalf122
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf123
  Sounds = mgfotr_gandalf123
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf124
  Sounds = mgfotr_gandalf124
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf125
  Sounds = mgfotr_gandalf125
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf126
  Sounds = mgfotr_gandalf126
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf127
  Sounds = mgfotr_gandalf127
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf128
  Sounds = mgfotr_gandalf128
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf129
  Sounds = mgfotr_gandalf129
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf130
  Sounds = mgfotr_gandalf130
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf131
  Sounds = mgfotr_gandalf131
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf132
  Sounds = mgfotr_gandalf132
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf133
  Sounds = mgfotr_gandalf133
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf134
  Sounds = mgfotr_gandalf134
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf135
  Sounds = mgfotr_gandalf135
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf136
  Sounds = mgfotr_gandalf136
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf137
  Sounds = mgfotr_gandalf137
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf138
  Sounds = mgfotr_gandalf138
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf139
  Sounds = mgfotr_gandalf139
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End


AudioEvent mgfotr_gandalf140
  Sounds = mgfotr_gandalf140
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf141
  Sounds = mgfotr_gandalf141
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf142
  Sounds = mgfotr_gandalf142
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf143
  Sounds = mgfotr_gandalf143
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf144
  Sounds = mgfotr_gandalf144
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf145
  Sounds = mgfotr_gandalf145
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf146
  Sounds = mgfotr_gandalf146
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf147
  Sounds = mgfotr_gandalf147
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf148
  Sounds = mgfotr_gandalf148
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf149
  Sounds = mgfotr_gandalf149
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End


AudioEvent mgfotr_gandalf150
  Sounds = mgfotr_gandalf150
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf151
  Sounds = mgfotr_gandalf151
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf152
  Sounds = mgfotr_gandalf152
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf153
  Sounds = mgfotr_gandalf153
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf154
  Sounds = mgfotr_gandalf154
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf155
  Sounds = mgfotr_gandalf155
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf156
  Sounds = mgfotr_gandalf156
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf157
  Sounds = mgfotr_gandalf157
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf158
  Sounds = mgfotr_gandalf158
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf159
  Sounds = mgfotr_gandalf159
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End


AudioEvent mgfotr_gandalf160
  Sounds = mgfotr_gandalf160
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf161
  Sounds = mgfotr_gandalf161
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf162
  Sounds = mgfotr_gandalf162
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf163
  Sounds = mgfotr_gandalf163
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf164
  Sounds = mgfotr_gandalf164
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf165
  Sounds = mgfotr_gandalf165
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf166
  Sounds = mgfotr_gandalf166
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf167
  Sounds = mgfotr_gandalf167
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf168
  Sounds = mgfotr_gandalf168
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf169
  Sounds = mgfotr_gandalf169
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End


AudioEvent mgfotr_gandalf170
  Sounds = mgfotr_gandalf170
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf171
  Sounds = mgfotr_gandalf171
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf172
  Sounds = mgfotr_gandalf172
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf173
  Sounds = mgfotr_gandalf173
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf174
  Sounds = mgfotr_gandalf174
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf175
  Sounds = mgfotr_gandalf175
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf176
  Sounds = mgfotr_gandalf176
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf177
  Sounds = mgfotr_gandalf177
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf178
  Sounds = mgfotr_gandalf178
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf179
  Sounds = mgfotr_gandalf179
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End


AudioEvent mgfotr_gandalf180
  Sounds = mgfotr_gandalf180
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf181
  Sounds = mgfotr_gandalf181
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf182
  Sounds = mgfotr_gandalf182
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf183
  Sounds = mgfotr_gandalf183
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf184
  Sounds = mgfotr_gandalf184
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf185
  Sounds = mgfotr_gandalf185
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf186
  Sounds = mgfotr_gandalf186
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf187
  Sounds = mgfotr_gandalf187
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf188
  Sounds = mgfotr_gandalf188
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf189
  Sounds = mgfotr_gandalf189
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End


AudioEvent mgfotr_gandalf190
  Sounds = mgfotr_gandalf190
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf191
  Sounds = mgfotr_gandalf191
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf192
  Sounds = mgfotr_gandalf192
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf193
  Sounds = mgfotr_gandalf193
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf194
  Sounds = mgfotr_gandalf194
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf195
  Sounds = mgfotr_gandalf195
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf196
  Sounds = mgfotr_gandalf196
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf197
  Sounds = mgfotr_gandalf197
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf198
  Sounds = mgfotr_gandalf198
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf199
  Sounds = mgfotr_gandalf199
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End


AudioEvent mgfotr_gandalf200
  Sounds = mgfotr_gandalf200
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf201
  Sounds = mgfotr_gandalf201
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf202
  Sounds = mgfotr_gandalf202
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf203
  Sounds = mgfotr_gandalf203
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf204
  Sounds = mgfotr_gandalf204
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf205
  Sounds = mgfotr_gandalf205
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf206
  Sounds = mgfotr_gandalf206
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf207
  Sounds = mgfotr_gandalf207
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf208
  Sounds = mgfotr_gandalf208
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf209
  Sounds = mgfotr_gandalf209
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End


AudioEvent mgfotr_gandalf210
  Sounds = mgfotr_gandalf210
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf211
  Sounds = mgfotr_gandalf211
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf212
  Sounds = mgfotr_gandalf212
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf213
  Sounds = mgfotr_gandalf213
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf214
  Sounds = mgfotr_gandalf214
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf215
  Sounds = mgfotr_gandalf215
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf216
  Sounds = mgfotr_gandalf216
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf217
  Sounds = mgfotr_gandalf217
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf218
  Sounds = mgfotr_gandalf218
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf219
  Sounds = mgfotr_gandalf219
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf220
  Sounds = mgfotr_gandalf220
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf221
  Sounds = mgfotr_gandalf221
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf222
  Sounds = mgfotr_gandalf222
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf223
  Sounds = mgfotr_gandalf223
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf224
  Sounds = mgfotr_gandalf224
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf225
  Sounds = mgfotr_gandalf225
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf226
  Sounds = mgfotr_gandalf226
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf227
  Sounds = mgfotr_gandalf227
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf228
  Sounds = mgfotr_gandalf228
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf229
  Sounds = mgfotr_gandalf229
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf230
  Sounds = mgfotr_gandalf230
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf231
  Sounds = mgfotr_gandalf231
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf232
  Sounds = mgfotr_gandalf232
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf233
  Sounds = mgfotr_gandalf233
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf234
  Sounds = mgfotr_gandalf234
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf235
  Sounds = mgfotr_gandalf235
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf236
  Sounds = mgfotr_gandalf236
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf237
  Sounds = mgfotr_gandalf237
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf238
  Sounds = mgfotr_gandalf238
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf239
  Sounds = mgfotr_gandalf239
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf240
  Sounds = mgfotr_gandalf240
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf241
  Sounds = mgfotr_gandalf241
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf242
  Sounds = mgfotr_gandalf242
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf243
  Sounds = mgfotr_gandalf243
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf244
  Sounds = mgfotr_gandalf244
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf245
  Sounds = mgfotr_gandalf245
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf246
  Sounds = mgfotr_gandalf246
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf247
  Sounds = mgfotr_gandalf247
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf248
  Sounds = mgfotr_gandalf248
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf249
  Sounds = mgfotr_gandalf249
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf250
  Sounds = mgfotr_gandalf250
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf251
  Sounds = mgfotr_gandalf251
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf252
  Sounds = mgfotr_gandalf252
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf253
  Sounds = mgfotr_gandalf253
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf254
  Sounds = mgfotr_gandalf254
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf255
  Sounds = mgfotr_gandalf255
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf256
  Sounds = mgfotr_gandalf256
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf257
  Sounds = mgfotr_gandalf257
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf258
  Sounds = mgfotr_gandalf258
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf259
  Sounds = mgfotr_gandalf259
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf260
  Sounds = mgfotr_gandalf260
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf261
  Sounds = mgfotr_gandalf261
  Volume = 109
  MinVolume = 109
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf262
  Sounds = mgfotr_gandalf262
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End
AudioEvent mgfotr_gandalf263
  Sounds = mgfotr_gandalf263
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf264
  Sounds = mgfotr_gandalf264
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf265
  Sounds = mgfotr_gandalf265
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf266
  Sounds = mgfotr_gandalf266
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf267
  Sounds = mgfotr_gandalf267
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf268
  Sounds = mgfotr_gandalf268
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf269
  Sounds = mgfotr_gandalf269
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf270
  Sounds = mgfotr_gandalf270
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf271
  Sounds = mgfotr_gandalf271
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf272
  Sounds = mgfotr_gandalf272
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf273
  Sounds = mgfotr_gandalf273
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf274
  Sounds = mgfotr_gandalf274
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf275
  Sounds = mgfotr_gandalf275
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf276
  Sounds = mgfotr_gandalf276
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf277
  Sounds = mgfotr_gandalf277
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf278
  Sounds = mgfotr_gandalf278
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf279
  Sounds = mgfotr_gandalf279
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End


AudioEvent mgfotr_gandalf280
  Sounds = mgfotr_gandalf280
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf281
  Sounds = mgfotr_gandalf281
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf282
  Sounds = mgfotr_gandalf282
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf283
  Sounds = mgfotr_gandalf283
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf284
  Sounds = mgfotr_gandalf284
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf285
  Sounds = mgfotr_gandalf285
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf286
  Sounds = mgfotr_gandalf286
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf287
  Sounds = mgfotr_gandalf287
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf288
  Sounds = mgfotr_gandalf288
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf289
  Sounds = mgfotr_gandalf289
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End
 
AudioEvent mgfotr_gandalf290
  Sounds = mgfotr_gandalf290
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf291
  Sounds = mgfotr_gandalf291
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf292
  Sounds = mgfotr_gandalf292
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf293
  Sounds = mgfotr_gandalf293
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf294
  Sounds = mgfotr_gandalf294
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf295
  Sounds = mgfotr_gandalf295
  Volume = 100
  MinRange = 800
  MaxRange = 1500
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf296
  Sounds = mgfotr_gandalf296
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf297
  Sounds = mgfotr_gandalf297
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf298
  Sounds = mgfotr_gandalf298
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf299
  Sounds = mgfotr_gandalf299
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf300
  Sounds = mgfotr_gandalf300
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf301
  Sounds = mgfotr_gandalf301
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf302
  Sounds = mgfotr_gandalf302
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf303
  Sounds = mgfotr_gandalf303
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf304
  Sounds = mgfotr_gandalf304
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf305
  Sounds = mgfotr_gandalf305
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf306
  Sounds = mgfotr_gandalf306
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf307
  Sounds = mgfotr_gandalf307
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf308
  Sounds = mgfotr_gandalf308
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf309
  Sounds = mgfotr_gandalf309
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf310
  Sounds = mgfotr_gandalf310
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf311
  Sounds = mgfotr_gandalf311
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf312
  Sounds = mgfotr_gandalf312
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf313
  Sounds = mgfotr_gandalf313
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf314
  Sounds = mgfotr_gandalf314
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf315
  Sounds = mgfotr_gandalf315
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf316
  Sounds = mgfotr_gandalf316
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf317
  Sounds = mgfotr_gandalf317
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf318
  Sounds = mgfotr_gandalf318
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf319
  Sounds = mgfotr_gandalf319
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf320
  Sounds = mgfotr_gandalf320
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf321
  Sounds = mgfotr_gandalf321
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf322
  Sounds = mgfotr_gandalf322
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf323
  Sounds = mgfotr_gandalf323
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf324
  Sounds = mgfotr_gandalf324
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf325
  Sounds = mgfotr_gandalf325
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf326
  Sounds = mgfotr_gandalf326
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf327
  Sounds = mgfotr_gandalf327
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_gandalf328
  Sounds = mgfotr_gandalf328
  Volume = 120
  MinVolume = 120
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf329
  Sounds = mgfotr_gandalf329
  Volume = 120
  MinVolume = 120
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf330
  Sounds = mgfotr_gandalf330
  Volume = 120
  MinVolume = 120
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf331
  Sounds = mgfotr_gandalf331
  Volume = 120
  MinVolume = 120
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf332
  Sounds = mgfotr_gandalf332
  Volume = 120
  MinVolume = 120
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf333
  Sounds = mgfotr_gandalf333
  Volume = 120
  MinVolume = 120
  MinRange = 800
  MaxRange = 1500
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf334
  Sounds = mgfotr_gandalf334
  Volume = 120
  MinVolume = 120
  MinRange = 800
  MaxRange = 1500
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf335
  Sounds = mgfotr_gandalf335
  Volume = 120
  MinVolume = 120
  MinRange = 800
  MaxRange = 1500
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf336
  Sounds = mgfotr_gandalf336
  Volume = 120
  MinVolume = 120
  MinRange = 800
  MaxRange = 1500
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf337
  Sounds = mgfotr_gandalf337
  Volume = 120
  MinVolume = 120
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf338
  Sounds = mgfotr_gandalf338
  Volume = 120
  MinVolume = 120
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf339
  Sounds = mgfotr_gandalf339
  Volume = 120
  MinVolume = 120
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf340
  Sounds = mgfotr_gandalf340
  Volume = 120
  MinVolume = 120
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf341
  Sounds = mgfotr_gandalf341
  Volume = 120
  MinVolume = 120
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf342
  Sounds = mgfotr_gandalf342
  Volume = 120
  MinVolume = 120
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf343
  Sounds = mgfotr_gandalf343
  Volume = 120
  MinVolume = 120
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf344
  Sounds = mgfotr_gandalf344
  Volume = 120
  MinVolume = 120
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf345
  Sounds = mgfotr_gandalf345
  Volume = 120
  MinVolume = 120
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf346
  Sounds = mgfotr_gandalf346
  Volume = 120
  MinVolume = 120
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf347
  Sounds = mgfotr_gandalf347
  Volume = 120
  MinVolume = 120
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf348
  Sounds = mgfotr_gandalf348
  Volume = 120
  MinVolume = 120
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf349
  Sounds = mgfotr_gandalf349
  Volume = 120
  MinVolume = 120
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf350
  Sounds = mgfotr_gandalf350
  Volume = 120
  MinVolume = 120
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf351
  Sounds = mgfotr_gandalf351
  Volume = 120
  MinVolume = 120
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf352
  Sounds = mgfotr_gandalf352
  Volume = 120
  MinVolume = 120
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf353
  Sounds = mgfotr_gandalf353
  Volume = 120
  MinVolume = 120
  MinRange = 800
  MaxRange = 1500
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf354
  Sounds = mgfotr_gandalf354
  Volume = 120
  MinVolume = 120
  MinRange = 800
  MaxRange = 1500
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf355
  Sounds = mgfotr_gandalf355
  Volume = 120
  MinVolume = 120
  MinRange = 800
  MaxRange = 1500
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf356
  Sounds = mgfotr_gandalf356
  Volume = 120
  MinVolume = 120
  MinRange = 800
  MaxRange = 1500
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf357
  Sounds = mgfotr_gandalf357
  Volume = 120
  MinVolume = 120
  MinRange = 800
  MaxRange = 1500
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf358
  Sounds = mgfotr_gandalf358
  Volume = 120
  MinVolume = 120
  MinRange = 800
  MaxRange = 1500
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf359
  Sounds = mgfotr_gandalf359
  Volume = 120
  MinVolume = 120
  MinRange = 800
  MaxRange = 1500
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf360
  Sounds = mgfotr_gandalf360
  Volume = 120
  MinVolume = 120
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf361
  Sounds = mgfotr_gandalf361
  Volume = 120
  MinVolume = 120
  MinRange = 800
  MaxRange = 1500
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf362
  Sounds = mgfotr_gandalf362
  Volume = 120
  MinVolume = 120
  MinRange = 800
  MaxRange = 1500
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf363
  Sounds = mgfotr_gandalf363
  Volume = 120
  MinVolume = 120
  MinRange = 800
  MaxRange = 1500
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf364
  Sounds = mgfotr_gandalf364
  Volume = 120
  MinVolume = 120
  MinRange = 800
  MaxRange = 1500
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf365
  Sounds = mgfotr_gandalf365
  Volume = 120
  MinVolume = 120
  MinRange = 800
  MaxRange = 1500
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf366
  Sounds = mgfotr_gandalf366
  Volume = 120
  MinVolume = 120
  MinRange = 800
  MaxRange = 1500
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf367
  Sounds = mgfotr_gandalf367
  Volume = 120
  MinVolume = 120
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf368
  Sounds = mgfotr_gandalf368
  Volume = 120
  MinVolume = 120
  MinRange = 800
  MaxRange = 1500
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf369
  Sounds = mgfotr_gandalf369
  Volume = 120
  MinVolume = 120
  MinRange = 800
  MaxRange = 1500
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf370
  Sounds = mgfotr_gandalf370
  Volume = 120
  MinVolume = 120
  MinRange = 800
  MaxRange = 1500
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf371
  Sounds = mgfotr_gandalf371
  Volume = 120
  MinVolume = 120
  MinRange = 800
  MaxRange = 1500
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf372
  Sounds = mgfotr_gandalf372
  Volume = 120
  MinVolume = 120
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf373
  Sounds = mgfotr_gandalf373
  Volume = 120
  MinVolume = 120
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf374
  Sounds = mgfotr_gandalf374
  Volume = 120
  MinVolume = 120
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf375
  Sounds = mgfotr_gandalf375
  Volume = 120
  MinVolume = 120
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf376
  Sounds = mgfotr_gandalf376
  Volume = 120
  MinVolume = 120
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End


AudioEvent mgfotr_gandalf377
  Sounds = mgfotr_gandalf377
  Volume = 120
  MinVolume = 120
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf378
  Sounds = mgfotr_gandalf378
  Volume = 120
  MinVolume = 120
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf379
  Sounds = mgfotr_gandalf379
  Volume = 120
  MinVolume = 120
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf380
  Sounds = mgfotr_gandalf380
  Volume = 120
  MinVolume = 120
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf381
  Sounds = mgfotr_gandalf381
  Volume = 120
  MinVolume = 120
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf382
  Sounds = mgfotr_gandalf382
  Volume = 120
  MinVolume = 120
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf383
  Sounds = mgfotr_gandalf383
  Volume = 120
  MinVolume = 120
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf384
  Sounds = mgfotr_gandalf384
  Volume = 120
  MinVolume = 120
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf385
  Sounds = mgfotr_gandalf385
  Volume = 120
  MinVolume = 120
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf386
  Sounds = mgfotr_gandalf386
  Volume = 120
  MinVolume = 120
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf387
  Sounds = mgfotr_gandalf387
  Volume = 120
  MinVolume = 120
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf388
  Sounds = mgfotr_gandalf388
  Volume = 120
  MinVolume = 120
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_gandalf389
  Sounds = mgfotr_gandalf389
  Volume = 120
  MinVolume = 120
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent mgfotr_frodo001
  Sounds = mgfotr_frodo001
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo002
  Sounds = mgfotr_frodo002
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo003
  Sounds = mgfotr_frodo003
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo004
  Sounds = mgfotr_frodo004
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo005
  Sounds = mgfotr_frodo005
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo006
  Sounds = mgfotr_frodo006
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo007
  Sounds = mgfotr_frodo007
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo008
  Sounds = mgfotr_frodo008
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo009
  Sounds = mgfotr_frodo009
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo010
  Sounds = mgfotr_frodo010
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo011
  Sounds = mgfotr_frodo011
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo012
  Sounds = mgfotr_frodo012
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo013
  Sounds = mgfotr_frodo013
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo014
  Sounds = mgfotr_frodo014
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo015
  Sounds = mgfotr_frodo015
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo016
  Sounds = mgfotr_frodo016
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo017
  Sounds = mgfotr_frodo017
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo018
  Sounds = mgfotr_frodo018
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo019
  Sounds = mgfotr_frodo019
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo020
  Sounds = mgfotr_frodo020
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo021
  Sounds = mgfotr_frodo021
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo022
  Sounds = mgfotr_frodo022
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo023
  Sounds = mgfotr_frodo023
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo024
  Sounds = mgfotr_frodo024
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo025
  Sounds = mgfotr_frodo025
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo026
  Sounds = mgfotr_frodo026
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo027
  Sounds = mgfotr_frodo027
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo028
  Sounds = mgfotr_frodo028
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo029
  Sounds = mgfotr_frodo029
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo030
  Sounds = mgfotr_frodo030
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo031
  Sounds = mgfotr_frodo031
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo032
  Sounds = mgfotr_frodo032
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo033
  Sounds = mgfotr_frodo033
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo034
  Sounds = mgfotr_frodo034
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo035
  Sounds = mgfotr_frodo035
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo036
  Sounds = mgfotr_frodo036
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo037
  Sounds = mgfotr_frodo037
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo038
  Sounds = mgfotr_frodo038
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo039
  Sounds = mgfotr_frodo039
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo040
  Sounds = mgfotr_frodo040
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo041
  Sounds = mgfotr_frodo041
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo042
  Sounds = mgfotr_frodo042
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo043
  Sounds = mgfotr_frodo043
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo044
  Sounds = mgfotr_frodo044
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo045
  Sounds = mgfotr_frodo045
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo046
  Sounds = mgfotr_frodo046
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End


AudioEvent mgfotr_frodo047
  Sounds = mgfotr_frodo047
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End


AudioEvent mgfotr_frodo048
  Sounds = mgfotr_frodo048
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo049
  Sounds = mgfotr_frodo049
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo050
  Sounds = mgfotr_frodo050
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo051
  Sounds = mgfotr_frodo051
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo052
  Sounds = mgfotr_frodo052
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo053
  Sounds = mgfotr_frodo053
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo054
  Sounds = mgfotr_frodo054
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo055
  Sounds = mgfotr_frodo055
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo056
  Sounds = mgfotr_frodo056
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo057
  Sounds = mgfotr_frodo057
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo058
  Sounds = mgfotr_frodo058
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo059
  Sounds = mgfotr_frodo059
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo060
  Sounds = mgfotr_frodo060
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo061
  Sounds = mgfotr_frodo061
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo062
  Sounds = mgfotr_frodo062
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo063
  Sounds = mgfotr_frodo063
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo064
  Sounds = mgfotr_frodo064
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo065
  Sounds = mgfotr_frodo065
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo066
  Sounds = mgfotr_frodo066
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo067
  Sounds = mgfotr_frodo067
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo068
  Sounds = mgfotr_frodo068
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo069
  Sounds = mgfotr_frodo069
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo070
  Sounds = mgfotr_frodo070
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo071
  Sounds = mgfotr_frodo071
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo072
  Sounds = mgfotr_frodo072
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo073
  Sounds = mgfotr_frodo073
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo074
  Sounds = mgfotr_frodo074
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo075
  Sounds = mgfotr_frodo075
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo076
  Sounds = mgfotr_frodo076
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo077
  Sounds = mgfotr_frodo077
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo078
  Sounds = mgfotr_frodo078
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo079
  Sounds = mgfotr_frodo079
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo080
  Sounds = mgfotr_frodo080
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo081
  Sounds = mgfotr_frodo081
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo082
  Sounds = mgfotr_frodo082
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo083
  Sounds = mgfotr_frodo083
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo084
  Sounds = mgfotr_frodo084
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo085
  Sounds = mgfotr_frodo085
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo086
  Sounds = mgfotr_frodo086
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo087
  Sounds = mgfotr_frodo087
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo088
  Sounds = mgfotr_frodo088
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo089
  Sounds = mgfotr_frodo089
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo090
  Sounds = mgfotr_frodo090
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo091
  Sounds = mgfotr_frodo091
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo092
  Sounds = mgfotr_frodo092
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo093
  Sounds = mgfotr_frodo093
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo094
  Sounds = mgfotr_frodo094
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo095
  Sounds = mgfotr_frodo095
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo096
  Sounds = mgfotr_frodo096
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo097
  Sounds = mgfotr_frodo097
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo098
  Sounds = mgfotr_frodo098
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo099
  Sounds = mgfotr_frodo099
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo100
  Sounds = mgfotr_frodo100
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo101
  Sounds = mgfotr_frodo101
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo102
  Sounds = mgfotr_frodo102
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo103
  Sounds = mgfotr_frodo103
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo104
  Sounds = mgfotr_frodo104
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo105
  Sounds = mgfotr_frodo105
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo106
  Sounds = mgfotr_frodo106
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo107
  Sounds = mgfotr_frodo107
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo108
  Sounds = mgfotr_frodo108
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo109
  Sounds = mgfotr_frodo109
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo110
  Sounds = mgfotr_frodo110
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo111
  Sounds = mgfotr_frodo111
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo112
  Sounds = mgfotr_frodo112
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo113
  Sounds = mgfotr_frodo113
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo114
  Sounds = mgfotr_frodo114
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo115
  Sounds = mgfotr_frodo115
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo116
  Sounds = mgfotr_frodo116
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo117
  Sounds = mgfotr_frodo117
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo118
  Sounds = mgfotr_frodo118
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo119
  Sounds = mgfotr_frodo119
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo120
  Sounds = mgfotr_frodo120
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo121
  Sounds = mgfotr_frodo121
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo122
  Sounds = mgfotr_frodo122
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo123
  Sounds = mgfotr_frodo123
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo124
  Sounds = mgfotr_frodo124
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo125
  Sounds = mgfotr_frodo125
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo126
  Sounds = mgfotr_frodo126
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo127
  Sounds = mgfotr_frodo127
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo128
  Sounds = mgfotr_frodo128
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo129
  Sounds = mgfotr_frodo129
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo130
  Sounds = mgfotr_frodo130
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo131
  Sounds = mgfotr_frodo131
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo132
  Sounds = mgfotr_frodo132
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo133
  Sounds = mgfotr_frodo133
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo134
  Sounds = mgfotr_frodo134
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo135
  Sounds = mgfotr_frodo135
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo136
  Sounds = mgfotr_frodo136
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo137
  Sounds = mgfotr_frodo137
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo138
  Sounds = mgfotr_frodo138
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo139
  Sounds = mgfotr_frodo139
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent mgfotr_frodo140
  Sounds = mgfotr_frodo140
  Volume = 100
  MinVolume = 100
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End