CommandSet GondorFoundationCommandSet
   1  = Command_ConstructGondorFarm
   2 = Command_ConstructGondorBlackSmith
   3  = Command_ConstructGondorBarracks
   4  = Command_ConstructGondorArcherRange
   5  = Command_ConstructGondorStable
   6  = Command_ConstructGondorWorkshop
   7  = Command_ConstructGondorBattleTower
   8  = Command_ConstructGondorMonumenttoElendil
   9 = Command_ConstructGondorMarketPlace
   10 = Command_ConstructGondorStoneMaker
End
CommandSet GondorFoundationCommandSet_WotR
   1  = Command_ConstructGondorBarracksWotRRealTime
   2 = Command_ConstructGondorStableWotRRealTime
   3  = Command_ConstructGondorWorkshopWotRRealTime
End
CommandSet GondorFoundationCommandSet_NoMarketPlace
   1  = Command_ConstructGondorFarm
   2 = Command_ConstructGondorBlackSmith
   3  = Command_ConstructGondorBarracks
   4  = Command_ConstructGondorArcherRange
   5  = Command_ConstructGondorStable
   6  = Command_ConstructGondorWorkshop
   7  = Command_ConstructGondorBattleTower
   8  = Command_ConstructGondorMonumenttoElendil
   9 = Command_ConstructGondorMarketPlace_Disabled
   10 = Command_ConstructGondorStoneMaker
End
CommandSet GondorFoundationCommandSet_Osgiliath
   1  = Command_ConstructGondorFarm
   2  = Command_ConstructGondorBlackSmith
   3  = Command_ConstructGondorBarracks
   4  = Command_ConstructGondorArcherRange
   5  = Command_ConstructGondorWorkshop
   6  = Command_ConstructGondorMonumenttoElendil
   7  = Command_ConstructGondorMarketPlace
End
CommandSet GondorFoundationCommandSet_Minas
   1  = Command_ConstructGondorBarracks
   2  = Command_ConstructGondorArcherRange
   3  = Command_ConstructGondorMonumenttoElendil
End
CommandSet GondorFoundationExpansionCommandSet_Minas
   1  = Command_ConstructMenTrebuchetExpansion_Minas
End
CommandSet GondorFoundationCommandSet_ROTK
   1  = Command_ConstructGondorBarracks
   2  = Command_ConstructGondorArcherRange
   3  = Command_ConstructGondorMonumenttoElendil
End
CommandSet GondorFoundation_IndependantCommandSet
	1  = Command_ConstructGondorFarm
	2  = Command_ConstructGondorBlackSmith
	3  = Command_ConstructGondorBarracks
	4  = Command_ConstructGondorArcherRange
	5  = Command_ConstructGondorMonumenttoElendil
	6  = Command_ConstructGondorBattleTower
	7  = Command_ConstructGondorStable
	8  = Command_ConstructGondorWorkshop
	9 = Command_ConstructGondorMarketPlace
End
CommandSet GondorFoundationCommandSetUpgradedEntMoot
	1  = Command_ConstructGondorFarm
	2  = Command_ConstructGondorBlackSmith
	3  = Command_ConstructGondorBarracks
	4  = Command_ConstructGondorArcherRange
	5  = Command_ConstructGondorMonumenttoElendil
	6  = Command_ConstructGondorBattleTower
	7  = Command_ConstructGondorStable
	8  = Command_ConstructGondorWorkshop
	9 = Command_ConstructGondorStoneMaker
	10 = Command_ConstructGondorMarketPlace
	11 = Command_ConstructEntMoot
End
CommandSet GondorBaseDefenceFoundationCommandSet
	1 = Command_ConstructGondorSentryTower
End
CommandSet RohanBaseDefenceFoundationCommandSet
	1 = Command_ConstructRohanSentryTower
End
CommandSet MordorBaseDefenceFoundationCommandSet
	1 = Command_ConstructEvilSentryTower
End
CommandSet IsengardBaseDefenceFoundationCommandSet
	1 = Command_ConstructEvilSentryTower
End
CommandSet NeutralBattleTowerCommandSet
	1 = Command_ExitGarrison
End
CommandSet GondorWallFoundationCommandSet
  1  = Command_ConstructGondorWall
End
CommandSet RohanFoundationCommandSet
  1  = Command_ConstructRohanFarm
  2  = Command_ConstructRohanWindmill
  3  = Command_ConstructRohanBarracksFoundation
  4  = Command_ConstructRohanArcherRange
  5  = Command_ConstructRohanStable
  6  = Command_ConstructRohanWorkshop
  7  = Command_ConstructRohanBattleTower
  8  = Command_ConstructRohanDraftTower
  9  = Command_ConstructRohanStatue
  10  = Command_ConstructRohanWell
End
CommandSet RohanFoundationCommandSet_WotR
  1  = Command_ConstructRohanBarracksFoundationWotRRealTime
  2  = Command_ConstructRohanStableWotRRealTime
  3  = Command_ConstructRohanWorkshopWotRRealTime
End
CommandSet RohanFoundationCommandSet_Eaves
  1  = Command_ConstructRohanFarm
  2  = Command_ConstructRohanWindmill
  3  = Command_ConstructRohanStatue
  4  = Command_ConstructRohanWell
End
CommandSet RohanFoundationCommandSet_Westfold
  1  = Command_ConstructRohanFarm
  2  = Command_ConstructRohanWindmill
  3  = Command_ConstructRohanBarracksFoundation
  4  = Command_ConstructRohanArcherRange
  5  = Command_ConstructRohanStable
  6  = Command_ConstructRohanBattleTower
  7  = Command_ConstructRohanDraftTower
  8  = Command_ConstructRohanStatue
  9  = Command_ConstructRohanWell
End
CommandSet RohanFoundationCommandSetUpgradedEntMoot
  1  = Command_ConstructRohanFarm
  2  = Command_ConstructRohanArcherRange
  3  = Command_ConstructRohanStable
  4  = Command_ConstructRohanArmory
  5  = Command_ConstructEntMoot
End
CommandSet RohanWallFoundationCommandSet
  1  = Command_ConstructRohanWall
End
CommandSet MordorFoundationCommandSet
    1  = Command_ConstructMordorSlaughterHouse
	2  = Command_ConstructMordorArmory
	3  = Command_ConstructMordorLumberMill
	4  = Command_ConstructMordorOrcPit
	5  = Command_ConstructMordorHaradrimPalace
	6  = Command_ConstructMordorTrollCage
	7  = Command_ConstructMordorSiegeWorks
;	8  = Command_ConstructMumakilPen
	8  = Command_constructMordorBattleTower
End
CommandSet MordorFoundationCommandSet_WotR
    1  = Command_ConstructMordorOrcPitWotRRealTime
	2  = Command_ConstructMordorTrollCageWotRRealTime
	3  = Command_ConstructMordorSiegeWorksWotRRealTime
End
CommandSet IsengardFoundationCommandSet
    1  = Command_ConstructIsengardFurnace
	2  = Command_ConstructIsengardLumberMill
	3  = Command_ConstructIsengardUrukPit
	4  = Command_ConstructIsengardTavern
	5  = Command_ConstructIsengardWargPit
	6  = Command_ConstructIsengardLonghouse
	7  = Command_ConstructIsengardSiegeWorks
	8  = Command_ConstructIsengardBattleTower
	9  = Command_ConstructIsengardWargSentry
	10  = Command_ConstructIsengardArmory
End
CommandSet IsengardFoundationCommandSet_WotR
    1  = Command_ConstructIsengardTavernWotRRealTime
	2  = Command_ConstructIsengardWargPitWotRRealTime
	3  = Command_ConstructIsengardSiegeWorksWotRRealTime
End
CommandSet WildFoundationCommandSet
   	1  = Command_ConstructWildMineShaft
	2  = Command_ConstructWildLumberMill
	3  = Command_ConstructWildTreasureTrove
	4  = Command_ConstructWildLodge
	5  = Command_ConstructWildCave
	6  = Command_ConstructWildSpiderPit
	7  = Command_ConstructWildFissure	
	8  = Command_ConstructWyrmLair
	9  = Command_ConstructWildSentryTower
End
CommandSet WildFoundationCommandSet_WotR
   	1  = Command_ConstructWildCaveWotRRealTime
	2  = Command_ConstructWildSpiderPitWotRRealTime
	3  = Command_ConstructWildFissureWotRRealTime
End
CommandSet ElvenFoundationCommandSet  
   1  = Command_FoundationConstructElvenMallornTree
   2  = Command_FoundationConstructEregionForge 
   3  =	Command_FoundationConstructElvenBarracks
   4  = Command_FoundationConstructElvenGreenPasture
   5  =	Command_FoundationConstructHiddenSanctum
   6  = Command_FoundationConstructElvenEntMoot
   7  =	Command_FoundationConstructElvenWatchTower
   8  = Command_FoundationConstructElvenMirrorOfGaladriel
End
CommandSet ElvenFoundationCommandSet_WotR
   1  = Command_FoundationConstructElvenBarracksWotRRealTime
   2  = Command_FoundationConstructElvenGreenPastureWotRRealTime
   3  =	Command_FoundationConstructElvenEntMootWotRRealTime
End
CommandSet ElvenFoundationCommandSet_NoMirror
   1  = Command_FoundationConstructElvenMallornTree
   2  = Command_FoundationConstructEregionForge 
   3  =	Command_FoundationConstructElvenBarracks
   4  = Command_FoundationConstructElvenGreenPasture
   5  =	Command_FoundationConstructHiddenSanctum
   6  = Command_FoundationConstructElvenEntMoot
   7  =	Command_FoundationConstructElvenWatchTower
   8  = Command_FoundationConstructElvenMirrorOfGaladriel_Disabled
End
CommandSet ElvenFoundationCommandSet_Lothlorien
   1  = Command_FoundationConstructElvenMallornTree
   2  = Command_FoundationConstructEregionForge 
   3  =	Command_FoundationConstructElvenBarracks
   4  = Command_FoundationConstructElvenStatue
End
CommandSet DwarvenFoundationCommandSet
End
CommandSet DwarvenFoundationUpgradedCommandSet  
   1  = Command_FoundationConstructDwarvenMineShaft
   2  = Command_FoundationDwarvenEreborForge
   3  =	Command_FoundationConstructDwarvenBarracks
   4  = Command_FoundationConstructDwarvenAssembly
   5  = Command_FoundationConstructDwarvenForgeWorks
   6  = Command_FoundationConstructDwarvenWorkshop
   7  = Command_FoundationConstructDwarvenSentryTower
   8  = Command_FoundationConstructDwarvenWell
   9  = Command_FoundationConstructDwarvenStatue
End
CommandSet DwarvenFoundationCommandSet_WotR
   1  = Command_FoundationConstructDwarvenBarracksWotRRealTime
   2  = Command_FoundationConstructDwarvenForgeWorksWotRRealTime
   3  =	Command_FoundationConstructDwarvenWorkshopWotRRealTime
End
CommandSet DwarvenFoundationUpgradedCommandSet_Balins  
   1  = Command_FoundationConstructDwarvenMineShaft
   2  = Command_FoundationDwarvenEreborForge
   3  =	Command_FoundationConstructDwarvenBarracks
   4  = Command_FoundationConstructDwarvenForgeWorks
   5  = Command_FoundationConstructDwarvenWorkshop
   6  = Command_FoundationConstructDwarvenSentryTower
   7  = Command_FoundationConstructDwarvenWell
   8  = Command_FoundationConstructDwarvenStatue
End
CommandSet EntFoundationCommandSet
  1  = Command_ConstructEntMoot
End
CommandSet RivendellFoundationCommandSet
	1  = Command_ConstructRivendellOrchard
	2  = Command_ConstructRivendellForge
	3  = Command_ConstructRivendellBreelandCamp
	4  = Command_ConstructRivendellDunedainGathering
	5  = Command_ConstructRivendellDormitory
	6  = Command_ConstructRivendellLibrary
	7  = Command_ConstructRivendellSentryTower
	8  = Command_ConstructRivendellWell
	9  = Command_ConstructRivendellStatue
End
CommandSet RivendellFoundationCommandSet_WotR
	1  = Command_ConstructRivendellBreelandCampWotRRealTime
	2  = Command_ConstructRivendellDunedainGatheringWotRRealTime
	3  = Command_ConstructRivendellHallOfFireWotRRealTime
End
CommandSet RivendellFoundationCommandSet_Ettenmoors
	1  = Command_ConstructRivendellWell
End
CommandSet RivendellFoundationCommandSet_NoLibrary
	1  = Command_ConstructRivendellOrchard
	2  = Command_ConstructRivendellForge
	3  = Command_ConstructRivendellBreelandCamp
	4  = Command_ConstructRivendellDunedainGathering
	5  = Command_ConstructRivendellDormitory
	6  = Command_ConstructRivendellLibrary_Disabled
	7  = Command_ConstructRivendellSentryTower
	8  = Command_ConstructRivendellWell
	9  = Command_ConstructRivendellStatue
End
CommandSet AotRRushFoundationCommandSet
   1  = Command_FoundationConstructLorienFletTD
   2  = Command_FoundationConstructGondorBarracksTD
   3  = Command_FoundationConstructEreborSiegeTD
End
CommandSet GuldurFoundationCommandSet
   	1  = Command_ConstructGuldurSlaveMill
	2  = Command_ConstructGuldurFountOfCorruption
	3  = Command_ConstructGuldurGuldurGaol
	4  = Command_ConstructGuldurSpiderLair
	5  = Command_ConstructGuldurSorceryTower
	6  = Command_ConstructGuldurRuinousTower
	7  = Command_ConstructGuldurRestlessBarrow
End
CommandSet GuldurFoundationCommandSet_WotR
   	1  = Command_ConstructGuldurGuldurGaolWotRRealTime
	2  = Command_ConstructGuldurSpiderLairWotRRealTime
	3  = Command_ConstructGuldurFountOfCorruptionWotRRealTime
End
CommandSet GuldurFoundationCommandSet_DE
   	1  = Command_ConstructGuldurSlaveMill_DE
	2  = Command_ConstructGuldurFountOfCorruption_DE
	3  = Command_ConstructGuldurGuldurGaol_DE
	4  = Command_ConstructGuldurSpiderLair_DE
	5  = Command_ConstructGuldurSorceryTower_DE
	6  = Command_ConstructGuldurRuinousTower_DE
	7  = Command_ConstructGuldurRestlessBarrow_DE
End
CommandSet MirkwoodFoundationCommandSet
	1  = Command_ConstructMirkwoodHuntingLodgeFoundation
	2  = Command_ConstructMirkwoodVineyardFoundation
	3  = Command_ConstructMirkwoodTrainingGroundsFoundation
	4  = Command_ConstructMirkwoodBeorningCabinFoundation
	5  = Command_ConstructMirkwoodRoyalBarracksFoundation
	6  = Command_ConstructMirkwoodTreasuryFoundation
	7  = Command_ConstructMirkwoodSiegeGroundsFoundation
	8  = Command_ConstructMirkwoodCellarDoorFoundation
	9  = Command_ConstructMirkwoodBattleTowerFoundation
	10 = Command_ConstructMirkwoodWellFoundation
	11 = Command_ConstructMirkwoodStatueFoundation
End
CommandSet MirkwoodFoundationCommandSet_WotR
	1  = Command_ConstructMirkwoodTrainingGroundsFoundationWotRRealTime
	2  = Command_ConstructMirkwoodRoyalBarracksFoundationWotRRealTime
	3  = Command_ConstructMirkwoodSiegeGroundsFoundationWotRRealTime
End
CommandSet HaradFoundationCommandSet
   	1  	= Command_ConstructAngmarMillFoundation
   	2 	= Command_ConstructAngmarBarracksFoundation
   	3  	= Command_ConstructAngmarDenFoundation
   	4  	= Command_ConstructSanctumofZigurFoundation
   	5  	= Command_ConstructAngmarHallofTwilightFoundation
	6   = Command_ConstructAngmarForgeWorksFoundation
   	7 	= Command_PorterConstructHaradDesertLookoutFoundation
End
CommandSet HaradFoundationCommandSet_WotR
   	1  	= Command_ConstructHaradTribalCampWotRRealTime
   	2 	= Command_ConstructAngmarBarracksFoundationWotRRealTime
   	3  	= Command_ConstructAngmarForgeWorksFoundationWotRRealTime
End
CommandSet HaradFoundationCommandSet_NoSanctum
   	1  	= Command_ConstructAngmarMillFoundation
   	2 	= Command_ConstructAngmarBarracksFoundation
   	3  	= Command_ConstructAngmarDenFoundation
   	4  	= Command_ConstructSanctumofZigurFoundation_Disabled
   	5  	= Command_ConstructAngmarHallofTwilightFoundation
	6   = Command_ConstructAngmarForgeWorksFoundation
   	7 	= Command_PorterConstructHaradDesertLookoutFoundation
End

CommandSet IthilienFoundationCommandSet
   1  = Command_ConstructIthilienGatheringFoundation
   2 = Command_ConstructIthilienStorehouseFoundation
   3  = Command_ConstructIthilienBeaconFoundation
   4  = Command_ConstructIthilienWatchtowerFoundation
End	

CommandSet LastAllianceFoundationCommandSet
  1 = Command_ConstructLAAdventureNumenorTent
  2 = Command_ConstructLAAdventureNoldorTent
  3 = Command_ConstructLastAllianceSmithingTentFoundation
  4	= Command_ConstructLastAllianceSiegeTentFoundation
  5  = Command_ConstructLastAllianceWatchtowerFoundation
End 

CommandSet LastAllianceBannerFoundationCommandSet
	1 = Command_ConstructLANoldorBanner
	2 = Command_ConstructLAElendilBanner
	3 = Command_ConstructLAKhazadBanner
	4 = Command_ConstructLAErynGalenBanner
	5 = Command_ConstructLALorinandBanner
End 

CommandSet ArthedainFoundationCommandSet
   1  = Command_ConstructArnorFarmFoundation
   2  = Command_PorterConstructArnorBlacksmithFoundation
   3  = Command_PorterConstructFornostGarrisonFoundation
   4  = Command_PorterConstructArthedainWatchtowerFoundation
   5 = Command_ConstructStatueOfElendilFoundation
   6 = Command_PorterConstructMalbethStudyFoundation
   7 = Command_PorterConstructArnorEmbassyFoundation
End
CommandSet ArthedainFoundationCommandSet_StudyDisabled
   1  = Command_ConstructArnorFarmFoundation
   2  = Command_PorterConstructArnorBlacksmithFoundation
   3  = Command_PorterConstructFornostGarrisonFoundation
   4  = Command_PorterConstructArthedainWatchtowerFoundation
   5 = Command_ConstructStatueOfElendilFoundation
   6 = Command_PorterConstructMalbethStudyFoundation_Disabled
   7 = Command_PorterConstructArnorEmbassyFoundation
End		

CommandSet RhunFoundationCommandSet
    1  = Command_ConstructRhunSlaughterHouse
	2  = Command_ConstructMordorArmory
	3  = Command_ConstructRhunAuxiliaryBarracks
	4  = Command_ConstructRhunArcheryRange
	5  = Command_ConstructRhunStable
	6  = Command_ConstructRhunSiegeWorks
	7  = Command_ConstructRhunGuardTower
End

CommandSet MoriaFoundationCommandSet
   	1  = Command_ConstructWildMineShaft
	2  = Command_ConstructWildTreasureTrove
	3  = Command_ConstructWildCave
	4  = Command_ConstructWildFissure_Moria
	5  = Command_ConstructAltarofFireFoundation
	6  = Command_ConstructWildSentryTower
End

CommandSet AngmarFoundationCommandSet
   	1  = Command_ConstructAngmarSlaveMill
	2  = Command_ConstructAngmarLumberMill
	3  = Command_ConstructAngmarBastion
	4  = Command_ConstructAngmarCairn
	5  = Command_ConstructAncestralHall
	6  = Command_ConstructAngmarRuinousTower
	7  = Command_ConstructArnorianBarrow
End

CommandSet AngmarFoundationCommandSet_DE
   	1  = Command_ConstructAngmarSlaveMill_DE
	2  = Command_ConstructAngmarLumberMill_DE
	3  = Command_ConstructAngmarBastion_DE
	4  = Command_ConstructAngmarCairn_DE
	5  = Command_ConstructAncestralHall_DE
	6  = Command_ConstructAngmarRuinousTower_DE
	7  = Command_ConstructArnorianBarrow_DE
End

CommandSet MorgulFoundationCommandSet
    1  = Command_ConstructMorgulSlaveMill
	2  = Command_ConstructMorgulFoundry
	3 = Command_ConstructMorgulGarrison
	5  = Command_ConstructMorgulDungeon
	6  = Command_ConstructMorgulSiegeWorks
	7  = Command_ConstructMorgulBattleTower
End

CommandSet DorwinionFoundationCommandSet
	1  = Command_ConstructDorwinionVineyardFoundation
	2  = Command_ConstructDorwinionMarketFoundation
	3  = Command_ConstructDorwinionBarracksFoundation
	4  = Command_ConstructMirkwoodBeorningCabinFoundation
	5  = Command_ConstructAvariBarracksFoundation
	6  = Command_ConstructMirkwoodCellarDoorFoundation
	7  = Command_ConstructStatueOfGirionFoundation
	8  = Command_ConstructDorwinionSentryTowerFoundation
End

CommandSet GreyCompanyFoundationCommandSet
   1  = Command_ConstructGondorFarm
   2 = Command_ConstructGondorBlackSmith
   3  = Command_ConstructGondorBarracks
   4  = Command_ConstructDolAmrothBarracks
   5  = Command_ConstructRivendellDunedainGathering
   6  = Command_ConstructGondorWorkshop
   7  = Command_ConstructGondorBattleTower
   8  = Command_ConstructGondorMonumenttoElendil
   9 = Command_ConstructGondorMarketPlace
   10 = Command_ConstructGondorStoneMaker
End

CommandSet GreyCompanyFoundationCommandSet_NoMarketPlace
   1  = Command_ConstructGondorFarm
   2 = Command_ConstructGondorBlackSmith
   3  = Command_ConstructGondorBarracks
   4  = Command_ConstructDolAmrothBarracks
   5  = Command_ConstructRivendellDunedainGathering
   6  = Command_ConstructGondorWorkshop
   7  = Command_ConstructGondorBattleTower
   8  = Command_ConstructGondorMonumenttoElendil
   9 = Command_ConstructGondorMarketPlace_Disabled
   10 = Command_ConstructGondorStoneMaker
End

CommandSet BotFAFoundationCommandSet  
   1  = Command_FoundationConstructDwarvenMineShaft
   2  = Command_FoundationDwarvenEreborForge
   3  =	Command_ConstructDaleAuxillaryCampFoundation
   4  = Command_FoundationConstructDwarvenForgeWorks
   5  = Command_ConstructMirkwoodRoyalBarracksFoundation
   6  = Command_FoundationConstructDwarvenWorkshop
   7  = Command_FoundationConstructDwarvenSentryTower
   8  = Command_ConstructStatueOfGirionFoundation
End

CommandSet WhiteHandFoundationCommandSet
    1  = Command_ConstructIsengardFurnace
	2  = Command_ConstructIsengardLumberMill
	3  = Command_ConstructIsengardOrcPit
	4  = Command_ConstructIsengardUrukPit
	5  = Command_ConstructIsengardWargPitWhiteHand
	6  = Command_ConstructIsengardSiegeWorksWhiteHand
	7  = Command_ConstructIsengardBattleTower
	8  = Command_ConstructIsengardArmory
End

CommandSet ShireFoundationCommandSet
   1  = Command_ConstructShireHobbitHoleFoundation
   2 = Command_ConstructShireHobbitFarmFoundation
   3  = Command_ConstructShireShirriffsQuartersFoundation
   4  = Command_ConstructShireHalflingInnFoundation
   5  = Command_ConstructShireSupplyCartFoundation
End

CommandSet DolAmrothFoundationCommandSet  
   1  = Command_ConstructDolAmrothFarm
   2  = Command_ConstructDolAmrothForge
   3  =	Command_ConstructAmrothianGuardhouseFoundation
   4  = Command_ConstructDolAmrothRoyalBarracksFoundation
   5  = Command_ConstructDolAmrothRoyalStablesFoundation
   6  = Command_ConstructAmrothianGuestHouseFoundation
   7  = Command_ConstructDolAmrothStatueFoundation
   8  = Command_ConstructDolAmrothSentryTowerFoundation
End

CommandSet DolAmrothFoundationCommandSet_GuesthouseDisabled  
   1  = Command_ConstructDolAmrothFarm
   2  = Command_ConstructDolAmrothForge
   3  =	Command_ConstructAmrothianGuardhouseFoundation
   4  = Command_ConstructDolAmrothRoyalBarracksFoundation
   5  = Command_ConstructDolAmrothRoyalStablesFoundation
   6  = Command_ConstructAmrothianGuestHouseFoundation_Disabled
   7  = Command_ConstructDolAmrothStatueFoundation
   8  = Command_ConstructDolAmrothSentryTowerFoundation
End