CommandButton Command_ConstructGondorSentryTower
  Command          = FOUNDATION_CONSTRUCT
  Object           = GondorSentryTower
  TextLabel        = CONTROLBAR:ConstructGondorSentryTower
  ButtonImage      = BGSentryTwr
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipGondorBuildSentryTower
  Radial           = Yes  
End
CommandButton Command_ConstructRohanSentryTower
  Command          = FOUNDATION_CONSTRUCT
  Object           = RohanSentryTower
  TextLabel        = CONTROLBAR:ConstructRohanSentryTower
  ButtonImage      = BRSentryTwr
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipRohanBuildSentryTower
  Radial           = Yes  
End
CommandButton Command_ConstructEvilSentryTower
  Command          = FOUNDATION_CONSTRUCT
  Object           = EvilSentryTower
  TextLabel        = CONTROLBAR:ConstructEvilSentryTower
  ButtonImage      = BISentryTwr
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipEvilBuildSentryTower
  Radial           = Yes  
End
; --------------- Sentry Tower End

;---------------- Lothlorien Foundation Constructs

CommandButton Command_FoundationConstructElvenBarracks
  Command          	= FOUNDATION_CONSTRUCT
  Object           	= ElvenBarracksFoundation
  TextLabel        	= CONTROLBAR:ConstructElvenBarracks
  ButtonImage      	= BILorienBarracks
  ButtonBorderType 	= BUILD 
  DescriptLabel    	= CONTROLBAR:ToolTipElvenBarracks
  Radial           	= Yes  
End
CommandButton Command_FoundationConstructElvenBarracksWotRRealTime
  Command          	= FOUNDATION_CONSTRUCT
	Object           = ElvenBarracksFoundation_WotR
	TextLabel        = CONTROLBAR:ConstructElvenBarracksWotRRealTime
	ButtonImage      = BILorienBarracks
	ButtonBorderType = BUILD
	DescriptLabel    = CONTROLBAR:ToolTipElvenBarracksWotRRealTime
	Radial           = Yes
End
CommandButton Command_FoundationConstructHiddenSanctum
  Command          	= FOUNDATION_CONSTRUCT
  Object           	= ElvenHiddenSanctumFoundation
  TextLabel        	= CONTROLBAR:ConstructElvenHiddenSanctum
  ButtonImage      	= UIHiddenSanctum
  ButtonBorderType 	= BUILD 
  DescriptLabel    	= CONTROLBAR:ToolTipElvenHiddenSanctumFoundation
  Radial           	= Yes  
End
CommandButton Command_FoundationConstructElvenEntMoot
  Command          = FOUNDATION_CONSTRUCT
  Object           = ElvenEntMootFoundation
  TextLabel        = CONTROLBAR:ConstructEntMoot
  ButtonImage      = BILorienEntmoot
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipElvenEntMoot
  Radial           = Yes  
End
CommandButton Command_FoundationConstructElvenEntMootWotRRealTime
  Command          = FOUNDATION_CONSTRUCT
  Object           = ElvenEntMootFoundation_WotR
  TextLabel        = CONTROLBAR:ConstructEntMootWotRRealTime
  ButtonImage      = BILorienEntmoot
  ButtonBorderType = BUILD
  DescriptLabel    = CONTROLBAR:ToolTipEntMootWotRRealTime
  Radial           = Yes
End
CommandButton Command_FoundationConstructEregionForge
	Command          = FOUNDATION_CONSTRUCT
	Object           = EregionForgeFoundation
	TextLabel        = CONTROLBAR:ConstructEregionForge
	ButtonImage      = BILorienStoreHouse ;BEGreenPasture
	ButtonBorderType = BUILD 
	DescriptLabel    = CONTROLBAR:ToolTipEregionForge
	Radial           = Yes  
End
CommandButton Command_FoundationConstructElvenGreenPasture
  Command          	= FOUNDATION_CONSTRUCT
  Object           	= ElvenGreenPastureFoundation
  TextLabel        	= CONTROLBAR:ConstructElvenStable
  ButtonImage      	= BILorienPasture
  ButtonBorderType 	= BUILD 
  DescriptLabel    	= CONTROLBAR:ToolTipGreenPasture
  Radial           	= Yes  
End
CommandButton Command_FoundationConstructElvenGreenPastureWotRRealTime
  Command          	= FOUNDATION_CONSTRUCT
  Object           	= ElvenGreenPastureFoundation_WotR
  TextLabel        	= CONTROLBAR:ConstructElvenStableWotRRealTime
  ButtonImage      	= BILorienPasture
  ButtonBorderType 	= BUILD
  DescriptLabel    	= CONTROLBAR:ToolTipGreenPastureWotRRealTime
  Radial           	= Yes  
End
CommandButton Command_FoundationConstructElvenStatue
  Command          = FOUNDATION_CONSTRUCT
  Object           = ElvenStatueFoundation
  TextLabel        = CONTROLBAR:ConstructElvenStatue
  ButtonImage      = BILorienStatue
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ElvenHeroicStatueBuild
  Radial           = Yes  
End
CommandButton Command_FoundationConstructElvenWatchTower
  Command          = FOUNDATION_CONSTRUCT
  Object           = ElvenBattleTowerFoundation
  TextLabel        = CONTROLBAR:ConstructElvenBattleTower
  ButtonImage      = BILorienFlet
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipBattleTower
  Radial           = Yes  
End
CommandButton Command_FoundationConstructLorienFletTD
  Command          = FOUNDATION_CONSTRUCT
  Object           = TDLorienFlet
  TextLabel        = CONTROLBAR:ConstructElvenBattleTower
  ButtonImage      = BILorienFlet
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipConstructLothlorienFletTD
  Radial           = Yes  
End
CommandButton Command_FoundationConstructGondorBarracksTD
  Command          = FOUNDATION_CONSTRUCT
  Object           = TDGondorBarracks
  TextLabel        = CONTROLBAR:ConstructMenBarracks
  ButtonImage      = UIGondorBarracks
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipConstructMenBarracks
  Radial           = Yes  
End
CommandButton Command_FoundationConstructEreborSiegeTD
  Command          = FOUNDATION_CONSTRUCT
  Object           = TDSiegeTower
  TextLabel        = CONTROLBAR:Command_DwarvenWallUpgradeToCatapult
  ButtonImage      = BIEreborWindlance
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:TooltipCommand_DwarvenWallUpgradeToCatapult
  Radial           = Yes  
End
CommandButton Command_FoundationConstructElvenMallornTree
  Command          = FOUNDATION_CONSTRUCT
  Object           = ElvenNiphredilMallornTreeFoundation
  TextLabel        = CONTROLBAR:ConstructElvenMallornTree
  ButtonImage      = uiniphredilbloom
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipMallornTree
  Radial           = Yes  
End
CommandButton Command_FoundationConstructElvenMirrorOfGaladriel
  Command          = FOUNDATION_CONSTRUCT
  Object           = ElvenMirrorOfGaladrielFoundation
  TextLabel        = CONTROLBAR:ConstructGaladrielsWell
  ButtonImage      = BILorienWell
  ButtonBorderType = BUILD 
  DescriptLabel    = OBJECT:GMirrorDescription
  Radial           = Yes  
End
CommandButton Command_FoundationConstructElvenMirrorOfGaladriel_Disabled
  Command          = FOUNDATION_CONSTRUCT
  Object           = ElvenMirrorOfGaladrielFoundation
  Options		   = NEED_UPGRADE
  NeededUpgrade	   = Upgrade_MiniHordeLvl10  
  TextLabel        = CONTROLBAR:ConstructGaladrielsWell
  ButtonImage      = BILorienWell
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipConstructGaladrielMirror_Disabled
  Radial           = Yes  
End


;--------------- Lothlorien End

;--------------- Erebor Foundation Constructs

   CommandButton Command_FoundationConstructDwarvenWorkshop
 	Command          = FOUNDATION_CONSTRUCT
 	Object           = DwarvenWorkshopFoundation
 	TextLabel        = CONTROLBAR:ConstructDwarvenWorkshop
 	ButtonImage      = BIEreborWorkshop
 	ButtonBorderType = BUILD 
 	DescriptLabel    = CONTROLBAR:ToolTipConstructDwarvenWorkshop
 	Radial           = Yes  
 End

 CommandButton Command_FoundationConstructDwarvenWorkshopWotRRealTime
 	Command          = FOUNDATION_CONSTRUCT
 	Object           = DwarvenWorkshopFoundation_WotR
 	TextLabel        = CONTROLBAR:ConstructDwarvenWorkshopWotRRealTime
 	ButtonImage      = BIEreborWorkshop
 	ButtonBorderType = BUILD
 	DescriptLabel    = CONTROLBAR:ToolTipConstructDwarvenWorkshopWotRRealTime
 	Radial           = Yes
 End

CommandButton Command_FoundationConstructDwarvenSentryTower
	Command				= FOUNDATION_CONSTRUCT
	Object				= DwarvenSentryTowerFoundation
	TextLabel			= CONTROLBAR:ConstructDwarvenSentryTower
	ButtonImage			= BIEreborWallTower
	ButtonBorderType		= BUILD
	DescriptLabel			= CONTROLBAR:ToolTipConstructDwarvenSentryTower
	Radial				= Yes
End
CommandButton Command_FoundationConstructDwarvenBarracks
	Command          	= FOUNDATION_CONSTRUCT
	Object           	= DwarfBarracksFoundation
	TextLabel        	= CONTROLBAR:ConstructDwarvenBarracks
	ButtonImage      	= BIEreborBarracks
	ButtonBorderType 	= BUILD 
	DescriptLabel    	= CONTROLBAR:ToolTipConstructDwarvenBarracks
	Radial           	= Yes  
End
CommandButton Command_FoundationConstructDwarvenBarracksWotRRealTime
	Command          	= FOUNDATION_CONSTRUCT
	Object           	= DwarfBarracksFoundation_WotR
	TextLabel        	= CONTROLBAR:ConstructDwarvenBarracksWotRRealTime
	ButtonImage      	= BIEreborBarracks
	ButtonBorderType 	= BUILD
	DescriptLabel    	= CONTROLBAR:ToolTipConstructDwarvenBarracksWotR
	Radial           	= Yes
End
CommandButton Command_FoundationConstructDwarvenAssembly
	Command          	= FOUNDATION_CONSTRUCT
	Object           	= DwarvenAssemblyFoundation
	TextLabel        	= CONTROLBAR:ConstructDwarvenAssembly
	ButtonImage      	= BIEreborAssembly
	ButtonBorderType 	= BUILD 
	DescriptLabel    	= CONTROLBAR:TooltipConstructDwarvenAssembly
	Radial           	= Yes  
End
  CommandButton Command_FoundationDwarvenEreborForge
 	Command          = FOUNDATION_CONSTRUCT
 	Object           = EreborForgeFoundation
 	TextLabel        = CONTROLBAR:ConstructDwarvenForgeWorks
 	ButtonImage      = BIEreborForge
 	ButtonBorderType = BUILD 
 	DescriptLabel    = CONTROLBAR:ToolTipConstructDwarvenForgeWorks
 	Radial           = Yes  
 End
 CommandButton Command_FoundationConstructDwarvenForgeWorks
 	Command          = FOUNDATION_CONSTRUCT
 	Object           = DwarvenSiegeWorksFoundation ;EreborForge
 	TextLabel        = CONTROLBAR:ConstructDwarvenHusbandry
 	ButtonImage      = BIEreborRedoubt
 	ButtonBorderType = BUILD 
 	DescriptLabel    = CONTROLBAR:ToolTipConstructDwarvenHusbandry
 	Radial           = Yes
 End
 CommandButton Command_FoundationConstructDwarvenForgeWorksWotRRealTime
 	Command          = FOUNDATION_CONSTRUCT
 	Object           = DwarvenSiegeWorksFoundation_WotR
 	TextLabel        = CONTROLBAR:ConstructDwarvenHusbandryWotRRealTime
 	ButtonImage      = BIEreborRedoubt ;UIEreborHusbandryUnused
 	ButtonBorderType = BUILD
 	DescriptLabel    = CONTROLBAR:ToolTipConstructDwarvenHusbandryWotRRealTime
 	Radial           = Yes
 End
 CommandButton Command_FoundationConstructDwarvenWell
	Command         	= FOUNDATION_CONSTRUCT
	Object           	= DwarvenWell
	TextLabel        	= CONTROLBAR:ConstructDwarvenWell
	ButtonImage	 	= BIEreborWell
	ButtonBorderType 	= BUILD 
	DescriptLabel    	= OBJECT:DwarvenWellDescription
	Radial           	= Yes  
End
 CommandButton Command_FoundationConstructDwarvenMineShaft
	Command          = FOUNDATION_CONSTRUCT
	Object           = DwarvenMineShaftFoundation
	TextLabel        = CONTROLBAR:ConstructDwarvenMineShaft
	ButtonImage      = BIEreborMineshaft
	ButtonBorderType = BUILD 
	DescriptLabel    = CONTROLBAR:TooltipConstructDwarvenMineShaft
	Radial           = Yes  
End
CommandButton Command_FoundationConstructDwarvenStatue
	Command          = FOUNDATION_CONSTRUCT
	Object           = DwarvenStatue
	TextLabel        = CONTROLBAR:ConstructDwarvenStatue
	ButtonImage      = BIEreborStatue
	ButtonBorderType = BUILD 
	DescriptLabel    = CONTROLBAR:HeroicStatueBuild
	Radial           = Yes  
End
CommandButton Command_FoundationConstructDwarvenArcheryRange
	Command          	= FOUNDATION_CONSTRUCT
	Object           	= DwarvenArcheryRangeFoundation
	TextLabel        	= CONTROLBAR:ConstructDwarvenArcheryRange
	ButtonImage      	= BIEreborDaleBarracks
	ButtonBorderType 	= BUILD 
	DescriptLabel    	= CONTROLBAR:TooltipConstructDwarvenArcheryRange
	Radial           	= Yes  
End
CommandButton Command_FoundationConstructDwarvenAssembly
	Command          	= FOUNDATION_CONSTRUCT
	Object           	= DwarvenAssemblyFoundation
	TextLabel        	= CONTROLBAR:ConstructDwarvenAssembly
	ButtonImage      	= BIEreborAssembly
	ButtonBorderType 	= BUILD 
	DescriptLabel    	= CONTROLBAR:TooltipConstructDwarvenAssembly
	Radial           	= Yes  
End
CommandButton Command_ConstructDaleAuxillaryCampFoundation
	Command          	= FOUNDATION_CONSTRUCT
	Object           	= BotFADalishRuin
	TextLabel        	= CONTROLBAR:ConstructDaleAuxillaryCamp
	ButtonImage      	= UIDalishRuin
	ButtonBorderType 	= BUILD
	DescriptLabel    	= CONTROLBAR:TooltipConstructDaleAuxillaryCamp
	Radial           	= Yes
End
; --------------- Erebor End

;--------------- Gondor Foundation Constructs

CommandButton Command_ConstructGondorFarm
  Command          = FOUNDATION_CONSTRUCT
  Object        		= GondorFarmFoundation 
	TextLabel     		= CONTROLBAR:ConstructMenFarm
	ButtonImage   		= UIGondorFarm
	ButtonBorderType    = BUILD 
	DescriptLabel       = CONTROLBAR:ToolTipConstructMenFarm
	Radial				= Yes  
End
CommandButton Command_ConstructGondorWell
  Command          = FOUNDATION_CONSTRUCT
  Object				= GondorWell
	TextLabel			= CONTROLBAR:ConstructMenWell
	ButtonImage			= UIGondorWell
	ButtonBorderType	= BUILD 
	DescriptLabel		= OBJECT:HearthWellDescription
	Radial				= Yes  
End
CommandButton Command_ConstructGondorMonumenttoElendil
  Command          = FOUNDATION_CONSTRUCT
  Object				= MonumentToElendilFoundation
	TextLabel			= CONTROLBAR:ConstructMonumenttoElendil
	ButtonImage			= UIGondorStatue
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:MonumenttoElendilBuildTooltip
	Radial				= Yes  
End
CommandButton Command_ConstructGondorBarracks
  Command          = FOUNDATION_CONSTRUCT
  Object        		= GondorBarracksFoundation
	TextLabel     		= CONTROLBAR:ConstructMenBarracks
	ButtonImage   		= UIGondorBarracks
	ButtonBorderType    = BUILD 
	DescriptLabel       = CONTROLBAR:ToolTipConstructMenBarracks
	Radial				= Yes
End
CommandButton Command_ConstructGondorBarracksWotRRealTime
  Command          = FOUNDATION_CONSTRUCT
	Object        		= GondorBarracksFoundation_WotR
	TextLabel     		= CONTROLBAR:ConstructMenBarracksWotRRealTime
	ButtonImage   		= UIGondorBarracks
	ButtonBorderType    = BUILD
	DescriptLabel       = CONTROLBAR:ToolTipConstructMenBarracksWotRRealTime
	Radial				= Yes
End
CommandButton Command_ConstructGondorStable
  Command          = FOUNDATION_CONSTRUCT
  Object				= GondorStableFoundation
	TextLabel			= CONTROLBAR:ConstructMenStable
	ButtonImage			= UIGondorStables
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:ToolTipConstructMenStable
	Radial				= Yes
End
CommandButton Command_ConstructGondorStableWotRRealTime
  Command          = FOUNDATION_CONSTRUCT
	Object				= GondorStableFoundation_WotR
	TextLabel			= CONTROLBAR:ConstructMenStableWotRRealTime
	ButtonImage			= UIGondorStables
	ButtonBorderType	= BUILD
	DescriptLabel		= CONTROLBAR:ToolTipConstructMenStableWotRRealTime
	Radial				= Yes
End
CommandButton Command_ConstructGondorMarketPlace
  Command          = FOUNDATION_CONSTRUCT
  Object				= GondorMarketPlaceFoundation
	TextLabel			= CONTROLBAR:ConstructMenMarketPlace
	ButtonImage			= UIGondorMarketplace ;BUStoneWorker
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:ToolTipConstructMenMarketPlace
	Radial				= Yes  
End
CommandButton Command_ConstructGondorMarketPlace_Disabled
	Command				= FOUNDATION_CONSTRUCT
	Options				= NEED_UPGRADE
	NeededUpgrade		= Upgrade_MiniHordeLvl10
	Object				= GondorMarketPlaceFoundation
	TextLabel			= CONTROLBAR:ConstructMenMarketPlace
	ButtonImage			= UIGondorMarketplace
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:ToolTipConstructMenMarketPlace_Disabled
	Radial				= Yes  
End
CommandButton Command_ConstructGondorStatue
  Command          = FOUNDATION_CONSTRUCT
  Object				= GondorStatue
	TextLabel			= CONTROLBAR:ConstructMenStatue
	ButtonImage			= UIGondorStatue
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:HeroicStatueBuild
	Radial				= Yes  
End
CommandButton Command_ConstructGondorStoneMaker
  Command          = FOUNDATION_CONSTRUCT
  Object				= GondorStoneMakerFoundation
;	AffectsKindOf		= WALK_ON_TOP_OF_WALL DEFENSIVE_WALL
	TextLabel			= CONTROLBAR:ConstructMenStoneMaker
	ButtonImage			= UIGondorStoneworker
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:ToolTipConstructMenStoneMaker
	Radial				= Yes  
End
CommandButton Command_ConstructGondorArcherRange
  Command          = FOUNDATION_CONSTRUCT
  Object				= GondorArcherRangeFoundation
	TextLabel			= CONTROLBAR:ConstructMenArcheryRange
	ButtonImage			= UIGondorArcheryRange
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:ToolTipMenArcheryRange
	Radial				= Yes 
End
CommandButton Command_ConstructGondorWorkshop
  Command          = FOUNDATION_CONSTRUCT
  Object				= GondorWorkshopFoundation
	TextLabel			= CONTROLBAR:ConstructMenWorkshop
	ButtonImage			= UIGondorWorkshop
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:ToolTipConstructMenWorkshop
	Radial				= Yes   
End
CommandButton  Command_ConstructGondorWorkshopCampaign
  Command          = FOUNDATION_CONSTRUCT
  Object				= GondorWorkshopFoundation
    Options	   = NEED_UPGRADE
  NeededUpgrade	   = Upgrade_Evilboyos
	TextLabel			= CONTROLBAR:ConstructMenWorkshop
	ButtonImage			= UIGondorWorkshop
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:ToolTipConstructMenWorkshop
	Radial				= Yes   
End
CommandButton Command_ConstructGondorWorkshopWotRRealTime
  Command          = FOUNDATION_CONSTRUCT
	Object				= GondorWorkshopFoundation_WotR
	TextLabel			= CONTROLBAR:ConstructMenWorkshopWotRRealTime
	ButtonImage			= UIGondorWorkshop
	ButtonBorderType	= BUILD
	DescriptLabel		= CONTROLBAR:ToolTipConstructMenWorkshopWotRRealTime
	Radial				= Yes
End
CommandButton Command_ConstructGondorBattleTower
  Command          = FOUNDATION_CONSTRUCT
  Object				= GondorBattleTower
	TextLabel			= CONTROLBAR:ConstructMenSentryTower
	ButtonImage			= UIGondorBattleTowernew
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:ToolTipConstructMenSentryTower
	Radial				= Yes    
End
CommandButton Command_ConstructGondorHseHeal
  Command          = FOUNDATION_CONSTRUCT
  Object           = GondorHseHeal
  TextLabel        = CONTROLBAR:ConstructGondorHseHeal
  ButtonImage      = BGFortress_HouseofHealing
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipGondorBuildHseHeal
  Radial           = Yes  
End
CommandButton Command_ConstructGondorBlackSmith
  Command          = FOUNDATION_CONSTRUCT
  Object				= GondorForgeFoundation
	TextLabel			= CONTROLBAR:ConstructMenBlacksmith
	ButtonImage			= UIGondorBlacksmith
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:ToolTipConstructMenBlacksmith
	Radial				= Yes
End
CommandButton Command_ConstructGondorWall
  Command          = FOUNDATION_CONSTRUCT
  Object           = GondorInnerWall
  TextLabel        = CONTROLBAR:ConstructGondorWall
  ButtonImage      = BRWall
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipGondorWall
  Radial           = Yes  
End

CommandButton Command_ConstructDolAmrothBarracks
  Command          = FOUNDATION_CONSTRUCT
	Object        		= DolAmrothBarracksFoundation
	TextLabel     		= CONTROLBAR:ConstructDolAmrothBarracks
	ButtonImage   		= SBGondorsummonDolAmrothCNew
	ButtonBorderType    = BUILD
	DescriptLabel       = CONTROLBAR:ToolTipConstructDolAmrothBarracks
	Radial				= Yes
End

; --------------- Gondor End

;--------------- Mordor Foundation Constructs

CommandButton Command_ConstructMordorArmory
  Command          = FOUNDATION_CONSTRUCT
  Object           = MordorArmoryFoundation
  TextLabel        = CONTROLBAR:ConstructMordorArmory
  ButtonImage      = BIMordorArmoury
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipConstructMordorArmory
  Radial           = Yes
End
CommandButton Command_ConstructMordorOrcPit
  Command          = FOUNDATION_CONSTRUCT
  Object           = MordorOrcPitFoundation
  TextLabel        = CONTROLBAR:ConstructMordorOrcPit
  ButtonImage      = BIMordorBarracks
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipMordorOrcPit
  Radial           = Yes  
End
CommandButton Command_ConstructMordorOrcPitWotRRealTime
  Command          = FOUNDATION_CONSTRUCT
	Object        		= MordorOrcPitFoundation_WotR
	TextLabel     		= CONTROLBAR:ConstructMordorOrcPitWotR
	ButtonImage   		= BIMordorBarracks
	ButtonBorderType    = BUILD
	DescriptLabel       = CONTROLBAR:ToolTipMordorOrcPitWotR
	Radial				= Yes
End
CommandButton Command_ConstructMordorTrollCage
  Command          = FOUNDATION_CONSTRUCT
  Object           = MordorTrollCageFoundation
  TextLabel        = CONTROLBAR:ConstructMordorTrollCage
  ButtonImage      = BIMordorTrollCage
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipMordorTrollCage
  Radial           = Yes  
End
CommandButton Command_ConstructMordorTrollCageWotRRealTime
  Command          = FOUNDATION_CONSTRUCT
  Object           = MordorTrollCageFoundation_WotR
  TextLabel        = CONTROLBAR:ConstructMordorTrollCageWotR
  ButtonImage      = BIMordorTrollCage
  ButtonBorderType = BUILD
  DescriptLabel    = CONTROLBAR:ToolTipMordorTrollCageWotR
  Radial           = Yes 
End
CommandButton Command_ConstructMordorSiegeWorks
  Command          = FOUNDATION_CONSTRUCT
  Object           = MordorSiegeWorksFoundation
  TextLabel        = CONTROLBAR:ConstructMordorSiegeWorks
  ButtonImage      = BIMordorSiegeWorks
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipordorSiegeWorks
  Radial           = Yes  
End
CommandButton Command_ConstructMordorSiegeWorksWotRRealTime
  Command          = FOUNDATION_CONSTRUCT
  Object           = MordorSiegeWorksFoundation_WotR
  TextLabel        = CONTROLBAR:ConstructMordorSiegeWorksWotR
  ButtonImage      = BIMordorSiegeWorks
  ButtonBorderType = BUILD
  DescriptLabel    = CONTROLBAR:ToolTipordorSiegeWorksWotR
  Radial           = Yes
End
CommandButton Command_ConstructMordorHaradrimPalace
  Command          = FOUNDATION_CONSTRUCT
  Object           = MordorHaradrimPalaceFoundation
  TextLabel        = CONTROLBAR:ConstructMordorHaradrimPalace
  ButtonImage      = BIMordorEasterlingEncampment
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipMordorHaradrimPalace
  Radial           = Yes  
End
CommandButton Command_ConstructMumakilPen
  Command          = FOUNDATION_CONSTRUCT
  Object           = MordorMumakilPenFoundation
  TextLabel        = CONTROLBAR:ConstructMordorMumakilPen
  ButtonImage      = uiharadrimpalacebuttonnew
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipMordorMumakilPenPlot
  Radial           = Yes  
End
CommandButton Command_ConstructMordorSlaughterHouse
  Command          = FOUNDATION_CONSTRUCT
  Object           = MordorSlaughterHouseFoundation
  TextLabel        = CONTROLBAR:ConstructSlaughterHouse
  ButtonImage      = BIMordorSlaughterHouse
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipSlaughterHouse
  Radial           = Yes  
End
CommandButton Command_ConstructMordorLumberMill
  Command          = FOUNDATION_CONSTRUCT
  Object           = MordorLumberMillFoundation
  TextLabel        = CONTROLBAR:ConstructMordorLumberMill
  ButtonImage      = uilumbermillnewbutton
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipConstructLumberMill
  Radial           = Yes  
End
CommandButton Command_constructMordorBattleTower
	Command				= FOUNDATION_CONSTRUCT
	Object				= MordorBattleTowerFoundation
	TextLabel			= CONTROLBAR:ConstructMordorBattleTower
	ButtonImage			= BIMordorBattleTower
	ButtonBorderType		= BUILD 
	DescriptLabel			= CONTROLBAR:ToolTipConstructMordorBattleTower
	Radial				= Yes
End

; --------------- Mordor End

;--------------- Isengard Foundation Constructs

CommandButton Command_ConstructIsengardFurnace
  	Command          		= FOUNDATION_CONSTRUCT
  	Object           		= IsengardFurnaceFoundation
  	TextLabel        		= CONTROLBAR:ConstructFurnace
  	ButtonImage      		= BIIsenFurnace
  	ButtonBorderType 		= BUILD 
  	DescriptLabel    		= CONTROLBAR:ToolTipFurnace
  	Radial           		= Yes  
End
CommandButton Command_ConstructIsengardTavern
  	Command          		= FOUNDATION_CONSTRUCT
  	Object           		= IsengardTavernFoundation
  	TextLabel        		= CONTROLBAR:ConstructIsengardTavern
  	ButtonImage      		= BIIsenDunlandGarr
  	ButtonBorderType 		= BUILD 
  	DescriptLabel    		= CONTROLBAR:ToolTipIsengardTavern
  	Radial           		= Yes  
End
CommandButton Command_ConstructIsengardTavernWotRRealTime
  	Command          		= FOUNDATION_CONSTRUCT
  	Object           		= IsengardTavernFoundation_WotR
  	TextLabel        		= CONTROLBAR:ConstructIsengardTavernWotRRealTime
  	ButtonImage      		= BIIsenDunlandGarr
  	ButtonBorderType 		= BUILD
  	DescriptLabel    		= CONTROLBAR:TooltipIsengardTavernWotR
  	Radial           		= Yes
End
CommandButton Command_ConstructIsengardBattleTower
  Command          = FOUNDATION_CONSTRUCT
  Object           = IsengardBattleTowerFoundation
  TextLabel        = CONTROLBAR:ConstructIsengardBattleTower
  ButtonImage      = BIIsenBattleTower
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipBuildIsengardBattleTower
  Radial           = Yes  
End
CommandButton Command_ConstructIsengardUrukPit
  Command          = FOUNDATION_CONSTRUCT
  Object           = IsengardUrukPitFoundation
  TextLabel        = CONTROLBAR:ConstructIsengardUrukPit
  ButtonImage      = BIIsenUrukPit
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipIsengardUrukPit
  Radial           = Yes  
End
CommandButton Command_ConstructIsengardOrcPit
  Command          = FOUNDATION_CONSTRUCT
  Object           = IsengardOrcPitFoundation
  TextLabel        = CONTROLBAR:IsengardOrcPit
  ButtonImage      = BMOrcPit
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipIsengardOrcPit
  Radial           = Yes  
End
CommandButton Command_ConstructIsengardWargPit
  Command          = FOUNDATION_CONSTRUCT
  Object           = IsengardWargPitFoundation
  TextLabel        = CONTROLBAR:ConstructIsengardWargPit
  ButtonImage      = BIIsenWargPit
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipIsengardWargPit
  Radial           = Yes
End
CommandButton Command_ConstructIsengardWargPitWhiteHand
  Command          = FOUNDATION_CONSTRUCT
  Object           = IsengardWargPitFoundation
  TextLabel        = CONTROLBAR:ConstructIsengardWargPit
  ButtonImage      = BIIsenWargPit
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipIsengardWargPitWhiteHand
  Radial           = Yes
End
CommandButton Command_ConstructIsengardWargPitWotRRealTime
  Command          = FOUNDATION_CONSTRUCT
  Object           = IsengardWargPitFoundation_WotR
  TextLabel        = CONTROLBAR:ConstructIsengardWargPitWotRRealTime
  ButtonImage      = BIIsenWargPit
  ButtonBorderType = BUILD
  DescriptLabel    = CONTROLBAR:ToolTipIsengardWargPitWotR
  Radial           = Yes
End
CommandButton Command_ConstructIsengardSiegeWorks
  Command          = FOUNDATION_CONSTRUCT
  Object           = IsengardSiegeWorksFoundation
  TextLabel        = CONTROLBAR:ConstructIsengardSiegeWorks
  ButtonImage      = BIIsenSiegeWorks
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipIsengardSiegeWorks
  Radial           = Yes  
End
CommandButton Command_ConstructIsengardSiegeWorksWhiteHand
  Command          = FOUNDATION_CONSTRUCT
  Object           = IsengardSiegeWorksFoundation_WhiteHand
  TextLabel        = CONTROLBAR:ConstructIsengardSiegeWorks
  ButtonImage      = BIIsenSiegeWorks
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipIsengardSiegeWorksWhiteHand
  Radial           = Yes  
End
CommandButton Command_ConstructIsengardSiegeWorksWotRRealTime
  Command          = FOUNDATION_CONSTRUCT
  Object           = IsengardSiegeWorksFoundation_WotR
  TextLabel        = CONTROLBAR:ConstructIsengardSiegeWorksWotRRealTime
  ButtonImage      = BIIsenSiegeWorks
  ButtonBorderType = BUILD
  DescriptLabel    = CONTROLBAR:ToolTipIsengardSiegeWorksWotR
  Radial           = Yes
End
CommandButton Command_ConstructIsengardLonghouse
  Command          = FOUNDATION_CONSTRUCT
  Object           = DunlendingLonghouseFoundation
  Options	   = NEED_UPGRADE
  NeededUpgrade	   = Upgrade_Evilboyos
  TextLabel        = CONTROLBAR:ConstructIsengardLonghouse
  ButtonImage      = uilonghousenew
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipIsengardLonghouse
  Radial           = Yes  
End
CommandButton Command_ConstructIsengardLumberMill
	Command				= FOUNDATION_CONSTRUCT
	Object				= IsengardLumberMillFoundation
	TextLabel			= CONTROLBAR:ConstructIsengardLumberMill
	ButtonImage			= uilumbermillnewbutton
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:ToolTipConstructLumberMill
	Radial				= Yes  
End
CommandButton Command_ConstructIsengardWargSentry
	Command				= FOUNDATION_CONSTRUCT
	Object				= IsengardWargSentryFoundation
	TextLabel			= CONTROLBAR:ConstructIsengardWargSentry
	ButtonImage			= BIIsenWargCage
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:ToolTipConstructIsengardWargSentry
	Radial				= Yes
End
CommandButton Command_ConstructIsengardArmory
  Command          = FOUNDATION_CONSTRUCT
  Object           = IsengardArmoryFoundation
  TextLabel        = CONTROLBAR:ConstructIsengardArmory
  ButtonImage      = BIIsenArmoury
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipIsengardArmory
  Radial           = Yes
End

; --------------- Isengard End

;---------------- Rohan Foundation Constructs

CommandButton Command_ConstructRohanArmory
  Command          = FOUNDATION_CONSTRUCT
  Object           = RohanArmory
  TextLabel        = CONTROLBAR:ConstructRohanArmory
  ButtonImage      = BRArmory
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipRohanArmory
  Radial           = Yes  
End
CommandButton Command_ConstructRohanArcherRange
  Command          = FOUNDATION_CONSTRUCT
  Object           = RohanArcherRangeFoundation
  TextLabel        = CONTROLBAR:ConstructMenArcheryRange
  ButtonImage      = BIRohanArcherRange
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipRohanArcheryRange
  Radial           = Yes  
End
CommandButton Command_ConstructRohanStable
  Command          = FOUNDATION_CONSTRUCT
  Object           = RohanStableFoundation
  TextLabel        = CONTROLBAR:ConstructRohanStable
  ButtonImage      = BIRohanStables
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipRohanStable
  Radial           = Yes  
End
CommandButton Command_ConstructRohanStableWotRRealTime
  Command          = FOUNDATION_CONSTRUCT
	Object				= RohanStableFoundation_WotR
	TextLabel			= CONTROLBAR:ConstructMenStableWotR
	ButtonImage			= BIRohanStables
	ButtonBorderType	= BUILD
	DescriptLabel		= CONTROLBAR:ToolTipConstructRohanStableWotR
	Radial				= Yes 
End
CommandButton Command_ConstructRohanBarracksFoundation
  Command          = FOUNDATION_CONSTRUCT
  Object           = RohanBarracksFoundation
  TextLabel        = CONTROLBAR:ConstructMenBarracks
  ButtonImage      = BIRohanBarracks
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipConstructRohanBarracks
  Radial           = Yes  
End
CommandButton Command_ConstructRohanBarracksFoundationWotRRealTime
  Command          = FOUNDATION_CONSTRUCT
	Object        		= RohanBarracksFoundation_WotR
	TextLabel     		= CONTROLBAR:ConstructMenBarracksWotR
	ButtonImage   		= BIRohanBarracks
	ButtonBorderType    = BUILD
	DescriptLabel       = CONTROLBAR:ToolTipConstructRohanBarracksWotR
	Radial				= Yes
End
CommandButton Command_ConstructRohanStatue
  Command          = FOUNDATION_CONSTRUCT
  Object           = RohanHeroStatueFoundation
  TextLabel			= CONTROLBAR:ConstructRohanStatue
  ButtonImage			= BIRohanStatue
  ButtonBorderType	= BUILD  
  DescriptLabel		= CONTROLBAR:HeroicStatueBuildRohan
  Radial           = Yes  
End
CommandButton Command_ConstructRohanFarm
  Command          = FOUNDATION_CONSTRUCT
  Object           = RohanFarmFoundation
	TextLabel     		= CONTROLBAR:ConstructMenFarm
	ButtonImage   		= BIRohanFarm
	ButtonBorderType    = BUILD 
	DescriptLabel       = CONTROLBAR:ToolTipConstructRohanFarm
  Radial           = Yes  
End
CommandButton Command_ConstructRohanWindmill
  Command          = FOUNDATION_CONSTRUCT
  Object           = RohanWindmillFoundation
	TextLabel     		= CONTROLBAR:ConstructRohanWindmill
	ButtonImage   		= BIRohanWindmill
	ButtonBorderType    = BUILD 
	DescriptLabel       = CONTROLBAR:ToolTipConstructRohanWindmill
  Radial           = Yes  
End
CommandButton Command_ConstructRohanWell
  Command          = FOUNDATION_CONSTRUCT
  Object           = RohanWellFoundation
	TextLabel			= CONTROLBAR:ConstructRohanWell
	ButtonImage			= BIRohanWell
	ButtonBorderType	= BUILD 
	DescriptLabel		= OBJECT:RohanWellDescription
  Radial           = Yes  
End
CommandButton Command_ConstructRohanBattleTower
  Command          = FOUNDATION_CONSTRUCT
  Object           = RohanBattleTowerNewFoundation
	TextLabel			= CONTROLBAR:ConstructMenSentryTower
	ButtonImage			= BIRohanBattleTower
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:ToolTipConstructMenSentryTower
  Radial           = Yes  
End
CommandButton Command_ConstructRohanDraftTower
  Command          = FOUNDATION_CONSTRUCT
  Object           = RohanDraftTowerFoundation
	TextLabel			= CONTROLBAR:ConstructRohanDraftTower
	ButtonImage			= BIRohanDraftTower
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:ToolTipConstructRohanDraftTower
  Radial           = Yes  
End
CommandButton Command_ConstructRohanWorkshop
  Command          = FOUNDATION_CONSTRUCT
  Object           = RohanWorkshopFoundation
	TextLabel			= CONTROLBAR:ConstructRohanWorkshop
	ButtonImage			= BIRohanWorkshop
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:ToolTipConstructRohanWorkshop
  Radial           = Yes  
End
CommandButton Command_ConstructRohanWorkshopWotRRealTime
  Command          = FOUNDATION_CONSTRUCT
	Object				= RohanWorkshopFoundation_WotR
	TextLabel			= CONTROLBAR:ConstructRohanWorkshopWotR
	ButtonImage			= BIRohanWorkshop
	ButtonBorderType	= BUILD
	DescriptLabel		= CONTROLBAR:ToolTipConstructRohanWorkshopWotR
	Radial				= Yes  
End
CommandButton Command_ConstructRohanWall
  Command          = FOUNDATION_CONSTRUCT
  Object           = RohanInnerWall
  TextLabel        = CONTROLBAR:ConstructRohanWall
  ButtonImage      = BRWall
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipRohanWall
  Radial           = Yes  
End

; --------------- Rohan End

;--------------- Wild Foundation Constructs

CommandButton Command_ConstructWildMineShaft
	Command				= FOUNDATION_CONSTRUCT
	Object				= WildMineShaftFoundation
	TextLabel			= CONTROLBAR:ConstructWildMineShaft
	ButtonImage			= UIMMTunnel ;BWAbandonedMineShaft
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:ToolTipConstructWildMineShaft
	Radial				= Yes  
End
CommandButton Command_ConstructWildLumberMill
	Command				= FOUNDATION_CONSTRUCT
	Object				= WildLumberMillFoundation
	TextLabel			= CONTROLBAR:ConstructWildLumberMill
	ButtonImage			= uilumbermillnewbutton
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:ToolTipConstructLumberMill
	Radial				= Yes  
END
CommandButton Command_ConstructWildCave
	Command				= FOUNDATION_CONSTRUCT
	Object				= GoblinCaveFoundation
	TextLabel			= CONTROLBAR:ConstructWildGoblinCave
	ButtonImage			= UIMMGoblinCave ;BWCave
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:ToolTipConstructWildGoblinCave
	Radial				= Yes  
END
CommandButton Command_ConstructWildCaveWotRRealTime
	Command				= FOUNDATION_CONSTRUCT
	Object				= GoblinCaveFoundation_WotR
	TextLabel			= CONTROLBAR:ConstructWildGoblinCaveWotRRealTime
	ButtonImage			= UIMMGoblinCave ;BWCave
	ButtonBorderType	= BUILD
	DescriptLabel		= CONTROLBAR:ToolTipConstructWildGoblinCaveWotR
	Radial				= Yes
END
CommandButton Command_ConstructWildLodge
	Command				= FOUNDATION_CONSTRUCT
	Object				= WildLodgeFoundation
	TextLabel			= CONTROLBAR:ConstructWildMountainLodge
	ButtonImage			= UIMMGundabadPit
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:ToolTipConstructWildMountainLodge
	Radial				= Yes  
END
CommandButton Command_ConstructWildFissure
	Command				= FOUNDATION_CONSTRUCT
	Object				= GoblinFissureFoundation
	TextLabel			= CONTROLBAR:ConstructWildGoblinFissure
	ButtonImage			= BIMMTrollLair
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:ToolTipConstructWildGoblinFissure
	Radial				= Yes  
END
CommandButton Command_ConstructWildFissureWotRRealTime
	Command				= FOUNDATION_CONSTRUCT
	Object				= GoblinFissureFoundation_WotR
	TextLabel			= CONTROLBAR:ConstructWildGoblinFissureWotRRealTime
	ButtonImage			= BIMMTrollLair
	ButtonBorderType	= BUILD
	DescriptLabel		= CONTROLBAR:ToolTipConstructWildGoblinFissureWotR
	Radial				= Yes
END
CommandButton Command_ConstructWyrmLair
	Command				= FOUNDATION_CONSTRUCT
	Options				= NEED_UPGRADE
	NeededUpgrade		= Upgrade_WildFortressNorthernWastesTrigger
	Object				= FireWyrmLairFoundation
	TextLabel			= CONTROLBAR:ConstructFireWyrmLair
	ButtonImage			= UIMMWyrmLair ;BIWyrmLair
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:ToolTipConstructFireWyrmLair
	Radial				= Yes  
END
CommandButton Command_ConstructWildSpiderPit
	Command				= FOUNDATION_CONSTRUCT
	Object				= WildSpiderPitFoundation
	TextLabel			= CONTROLBAR:ConstructWildWildSpiderPit
	ButtonImage			= UIMMWargCage ;BWSpiderPit
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:ToolTipConstructWildWildSpiderPit
	Radial				= Yes  
END
CommandButton Command_ConstructWildSpiderPitWotRRealTime
	Command				= FOUNDATION_CONSTRUCT
	Object				= WildSpiderPitFoundation_WotR
	TextLabel			= CONTROLBAR:ConstructWildWildSpiderPitWotRRealTime
	ButtonImage			= UIMMWargCage ;BWSpiderPit
	ButtonBorderType	= BUILD
	DescriptLabel		= CONTROLBAR:ToolTipConstructWildWildSpiderPitWotR
	Radial				= Yes 
END
CommandButton Command_ConstructWildTreasureTrove
	Command				= FOUNDATION_CONSTRUCT
	Object				= WildTreasureTroveFoundation
	TextLabel			= CONTROLBAR:ConstructWildTreasureTrove
	ButtonImage			= UIMMTreasureTrove ;BWTreasureTrove
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:ToolTipConstructWildTreasureTrove
	Radial				= Yes
END
CommandButton Command_ConstructWildSentryTower
	Command				= FOUNDATION_CONSTRUCT
	Object				= WildSentryTowerFoundation
	TextLabel			= CONTROLBAR:ConstructWildSentryTower
	ButtonImage			= BIMMSentryTower
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:ToolTipConstructWildSentryTower
	Radial				= Yes
End

;--------------- Arnor Foundation Constructs

CommandButton Command_ConstructArnorFarm
  Command          = FOUNDATION_CONSTRUCT
  Object           = ArnorFarm
  TextLabel        = CONTROLBAR:ConstructArnorFarm
  ButtonImage     = BCFarm
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipArnorBuildFarm
  Radial           = Yes  
End
CommandButton Command_ConstructArnorWell
  Command          = FOUNDATION_CONSTRUCT
  Object           = ArnorWell
  TextLabel        = CONTROLBAR:ConstructArnorWell
  ButtonImage      = BGWell
  ButtonBorderType = BUILD 
  DescriptLabel    = OBJECT:HearthWellDescription
  Radial           = Yes  
End
CommandButton Command_ConstructArnorBarracks
  Command          = FOUNDATION_CONSTRUCT
  Object           = ArnorBarracks
  TextLabel        = CONTROLBAR:ConstructArnorBarracks
  ButtonImage      = BGBarracks
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipArnorBuildBarracks
  Radial           = Yes
End
CommandButton Command_ConstructArnorStable
  Command          = FOUNDATION_CONSTRUCT
  Object           = ArnorStable
  TextLabel        = CONTROLBAR:ConstructElvenStable
  ButtonImage      = BEGreenPasture
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipGreenPasture
  Radial           = Yes
End
CommandButton Command_ConstructArnorMarketPlace
  Command          = FOUNDATION_CONSTRUCT
  Object           = ArnorMarketPlace
  TextLabel        = CONTROLBAR:ConstructArnorMarketPlace
  ButtonImage      = BGMarketplace
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipArnorBuildMarketPlace
  Radial           = Yes  
End
CommandButton Command_ConstructArnorStatue
  Command          = FOUNDATION_CONSTRUCT
  Object           = ArnorHeroStatue
  TextLabel        = CONTROLBAR:ConstructArnorStatue
  ButtonImage      = BGHeroicStatue
  ButtonBorderType = BUILD 
  DescriptLabel    = OBJECT:HeroicStatueDescription
  Radial           = Yes  
End
CommandButton Command_ConstructArnorStoneMaker
  Command          = FOUNDATION_CONSTRUCT
  Object           = ArnorStoneMaker
  Options		   = NEEDS_CASTLE_KINDOF
  AffectsKindOf	   = WALK_ON_TOP_OF_WALL DEFENSIVE_WALL
  TextLabel        = CONTROLBAR:ConstructArnorStoneMaker
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipArnorBuildStoneMaker
  Radial           = Yes  
End
CommandButton Command_ConstructArnorArcherRange
  Command          = FOUNDATION_CONSTRUCT
  Object           = ArnorArcherRange
  TextLabel        = CONTROLBAR:ConstructArnorArcherRange
  ButtonImage      = BGArcheryRange
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipArnorBuildArcherRange
  Radial           = Yes  
End
CommandButton Command_ConstructArnorWorkshop
  Command          = FOUNDATION_CONSTRUCT
  Object           = ArnorWorkshop
  TextLabel        = CONTROLBAR:ConstructArnorWorkshop
  ButtonImage      = BGWorkshop
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipArnorBuildWorkshop
  Radial           = Yes  
End
CommandButton Command_ConstructArnorKeep
  Command          = FOUNDATION_CONSTRUCT
  Object           = ArnorKeep
  TextLabel        = CONTROLBAR:ConstructArnorKeep
  ButtonImage      = BGBattleTower
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipBuildArnorKeep
  Radial           = Yes  
End
CommandButton Command_ConstructArnorHseHeal
  Command          = FOUNDATION_CONSTRUCT
  Object           = ArnorHseHeal
  TextLabel        = CONTROLBAR:ConstructArnorHseHeal
  ButtonImage      = BGFortress_HouseofHealing
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipArnorBuildHseHeal
  Radial           = Yes  
End
CommandButton Command_ConstructArnorBlackSmith
  Command          = FOUNDATION_CONSTRUCT
  Object           = ArnorForge
  TextLabel        = CONTROLBAR:ConstructEregionForge
  ButtonImage      = BEEregionForge ;BEGreenPasture
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipEregionForge
  Radial           = Yes
End
CommandButton Command_ConstructArnorWall
  Command          = FOUNDATION_CONSTRUCT
  Object           = ArnorInnerWall
  TextLabel        = CONTROLBAR:ConstructArnorWall
  ButtonImage      = BRWall
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipArnorWall
  Radial           = Yes  
End

; --------------- Arnor End
;--------------- Rivendell Foundation Constructs
CommandButton Command_ConstructRivendellOrchard
	Command       		= FOUNDATION_CONSTRUCT
	Object        		= RivendellOrchardFoundation
	TextLabel     		= CONTROLBAR:ConstructArnorFarm
	ButtonImage   		= BIRivendellOrchard
	ButtonBorderType    = BUILD 
	DescriptLabel       = CONTROLBAR:ToolTipConstructArnorFarm
	Radial				= Yes
End
CommandButton Command_ConstructRivendellForge
	Command				= FOUNDATION_CONSTRUCT
	Object				= RivendellForgeFoundation
	TextLabel			= CONTROLBAR:ConstructRivendellBlacksmith
	ButtonImage			= BIRivendellForge
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:ToolTipConstructRivendellBlacksmith
	Radial				= Yes
End
CommandButton Command_ConstructRivendellBreelandCamp
	Command				= FOUNDATION_CONSTRUCT
	Object				= RivendellBreeLandEncampmentFoundation
	TextLabel			= CONTROLBAR:ConstructArnorArcheryRange
	ButtonImage			= BIRivendellEncampment
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:ToolTipArnorArcheryRange
	Radial				= Yes
End
CommandButton Command_ConstructRivendellBreelandCampWotRRealTime
	Command				= FOUNDATION_CONSTRUCT
	Object				= RivendellBreeLandEncampmentFoundation_WotR
	TextLabel			= CONTROLBAR:ConstructArnorArcheryRangeWotR
	ButtonImage			= BIRivendellEncampment
	ButtonBorderType	= BUILD
	DescriptLabel		= CONTROLBAR:ToolTipArnorArcheryRangeWotR
	Radial				= Yes
End
CommandButton Command_ConstructRivendellDunedainGathering
	Command				= FOUNDATION_CONSTRUCT
	Object				= RivendellDunedainGatheringFoundation
	TextLabel			= CONTROLBAR:ConstructArnorStable
	ButtonImage			= BIRivendellGathering
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:ToolTipConstructArnorStable
	Radial				= Yes
End
CommandButton Command_ConstructRivendellDunedainGatheringWotRRealTime
	Command				= FOUNDATION_CONSTRUCT
	Object				= RivendellDunedainGatheringFoundation_WotR
	TextLabel			= CONTROLBAR:ConstructArnorStableWotR
	ButtonImage			= BIRivendellGathering
	ButtonBorderType	= BUILD
	DescriptLabel		= CONTROLBAR:ToolTipConstructArnorStableWotR
	Radial				= Yes
End
CommandButton Command_ConstructRivendellHallOfFireWotRRealTime
	Command       		= FOUNDATION_CONSTRUCT
	Object				= RivendellHallOfFireFoundation_WotR
	TextLabel			= CONTROLBAR:ConstructHallOfFire
	ButtonImage			= SBRivendellHallOfFire
	ButtonBorderType	= BUILD
	DescriptLabel		= CONTROLBAR:ToolTipConstructHallOfFire
	Radial				= Yes
End
CommandButton Command_ConstructRivendellDormitory
	Command       		= FOUNDATION_CONSTRUCT
	Object        		= RivendellDormitoryFoundation
	TextLabel     		= CONTROLBAR:ConstructArnorBarracks
	ButtonImage   		= BIRivendellDormitory
	ButtonBorderType    = BUILD 
	DescriptLabel       = CONTROLBAR:ToolTipConstructArnorBarracks
	Radial				= Yes
End
CommandButton Command_ConstructRivendellLibrary
	Command				= FOUNDATION_CONSTRUCT
	Object				= RivendellLibraryFoundation
	TextLabel			= CONTROLBAR:ConstructArnorMarketPlace
	ButtonImage			= BIRivendellLibrary
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:ToolTipConstructArnorMarketPlace
	Radial				= Yes  
End
CommandButton Command_ConstructRivendellLibrary_Disabled
	Command				= FOUNDATION_CONSTRUCT
	Options				= NEED_UPGRADE
	NeededUpgrade		= Upgrade_MiniHordeLvl10
	Object				= RivendellLibraryFoundation
	TextLabel			= CONTROLBAR:ConstructArnorMarketPlace
	ButtonImage			= BIRivendellLibrary
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:ToolTipConstructArnorMarketPlace_Disabled
	Radial				= Yes  
End
CommandButton Command_ConstructRivendellSentryTower
	Command				= FOUNDATION_CONSTRUCT
	Object				= RivendellKeepFoundation
	TextLabel			= CONTROLBAR:ConstructArnorSentryTower
	ButtonImage			= BIRivendellTower
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:ToolTipConstructArnorSentryTower
	Radial				= Yes  
End
CommandButton Command_ConstructRivendellWell
	Command				= FOUNDATION_CONSTRUCT
	Object				= RivendellWellFoundation
	TextLabel			= CONTROLBAR:ConstructArnorWell
	ButtonImage			= BIRivendellWell
	ButtonBorderType	= BUILD 
	DescriptLabel		= OBJECT:HearthWellDescription
	Radial				= Yes
End
CommandButton Command_ConstructRivendellStatue
	Command				= FOUNDATION_CONSTRUCT
	Object				= RivendellStatueFoundation
	TextLabel			= CONTROLBAR:ConstructArnorStatue
	ButtonImage			= BIRivendellStatue
	ButtonBorderType	= BUILD 
	DescriptLabel		= OBJECT:HeroicStatueDescription
	Radial				= Yes  
End

; --------------- Rivendell End

;--------------- Guldur Foundation Constructs
CommandButton Command_ConstructGuldurSlaveMill
	Command				= FOUNDATION_CONSTRUCT
	Object				= GuldurSlaveMillFoundation
	TextLabel			= CONTROLBAR:ConstructGuldurSlaveMill
	ButtonImage			= BIGuldurMill
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:TooltipConstructGuldurSlaveMill
	Radial				= Yes  
End
CommandButton Command_ConstructGuldurSlaveMill_DE
	Command				= FOUNDATION_CONSTRUCT
	Object				= GuldurSlaveMillFoundation_DE
	TextLabel			= CONTROLBAR:ConstructGuldurSlaveMill
	ButtonImage			= BIGuldurMill
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:TooltipConstructGuldurSlaveMill
	Radial				= Yes  
End
CommandButton Command_ConstructGuldurFountOfCorruption
	Command				= FOUNDATION_CONSTRUCT
	Object				= GuldurFountOfCorruptionFoundation
	TextLabel			= CONTROLBAR:ConstructGuldurFountOfCorruption
	ButtonImage			= BIGuldurFount
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:ToolTipConstructGuldurFountOfCorruption
	Radial				= Yes  
End
CommandButton Command_ConstructGuldurFountOfCorruptionWotRRealTime
	Command				= FOUNDATION_CONSTRUCT
 	Object           		= GuldurFountOfCorruptionFoundation_WotR
 	TextLabel        		= CONTROLBAR:ConstructGuldurFountOfCorruptionWotRRealTime
 	ButtonImage      		= BIGuldurFount
 	ButtonBorderType 		= BUILD
 	DescriptLabel    		= CONTROLBAR:ToolTipConstructGuldurFountOfCorruptionWotR
 	Radial           		= Yes
End
CommandButton Command_ConstructGuldurFountOfCorruption_DE
	Command				= FOUNDATION_CONSTRUCT
	Object				= GuldurFountOfCorruptionFoundation_DE
	TextLabel			= CONTROLBAR:ConstructGuldurFountOfCorruption
	ButtonImage			= BIGuldurFount
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:ToolTipConstructGuldurFountOfCorruption
	Radial				= Yes  
End
CommandButton Command_ConstructGuldurGuldurGaol
	Command				= FOUNDATION_CONSTRUCT
	Object				= GuldurGaolFoundation
	TextLabel			= CONTROLBAR:ConstructGuldurGaol
	ButtonImage			= BIGuldurGaol
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:ToolTipConstructGuldurGaol
	Radial				= Yes  
End
CommandButton Command_ConstructGuldurGuldurGaolWotRRealTime
	Command				= FOUNDATION_CONSTRUCT
	Object           = GuldurGaolFoundation_WotR
	TextLabel        = CONTROLBAR:ConstructGuldurGaolWotRRealTime
	ButtonImage      = BIGuldurGaol
	ButtonBorderType = BUILD
	DescriptLabel    = CONTROLBAR:ToolTipConstructGuldurGaolWotR
	Radial           = Yes
End
CommandButton Command_ConstructGuldurGuldurGaol_DE
	Command				= FOUNDATION_CONSTRUCT
	Object				= GuldurGaolFoundation_DE
	TextLabel			= CONTROLBAR:ConstructGuldurGaol
	ButtonImage			= BIGuldurGaol
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:ToolTipConstructGuldurGaol
	Radial				= Yes  
End
CommandButton Command_ConstructGuldurSpiderLair
	Command				= FOUNDATION_CONSTRUCT
	Object				= GuldurSpiderLairFoundation
	TextLabel			= CONTROLBAR:ConstructGuldurSpiderLair
	ButtonImage			= BIGuldurSpiderLair
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:ToolTipConstructGuldurSpiderLair
	Radial				= Yes  
End
CommandButton Command_ConstructGuldurSpiderLairWotRRealTime
	Command				= FOUNDATION_CONSTRUCT
	Object				= GuldurSpiderLairFoundation_WotR
	TextLabel			= CONTROLBAR:ConstructGuldurSpiderLairWotRRealTime
	ButtonImage			= BIGuldurSpiderLair
	ButtonBorderType	= BUILD
	DescriptLabel		= CONTROLBAR:ToolTipConstructGuldurSpiderLairWotR
	Radial				= Yes 
End
CommandButton Command_ConstructGuldurSpiderLair_DE
	Command				= FOUNDATION_CONSTRUCT
	Object				= GuldurSpiderLairFoundation_DE
	TextLabel			= CONTROLBAR:ConstructGuldurSpiderLair
	ButtonImage			= BIGuldurSpiderLair
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:ToolTipConstructGuldurSpiderLair
	Radial				= Yes  
End
CommandButton Command_ConstructGuldurSorceryTower
	Command				= FOUNDATION_CONSTRUCT
	Object				= GuldurSorceryTowerFoundation
	TextLabel			= CONTROLBAR:ConstructGuldurSorceryTower
	ButtonImage			= BIGuldurSpire
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:ToolTipConstructGuldurSorceryTower
	Radial				= Yes  
End
CommandButton Command_ConstructGuldurSorceryTower_DE
	Command				= FOUNDATION_CONSTRUCT
	Object				= GuldurSorceryTowerFoundation_DE
	TextLabel			= CONTROLBAR:ConstructGuldurSorceryTower
	ButtonImage			= BIGuldurSpire
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:ToolTipConstructGuldurSorceryTower
	Radial				= Yes  
End
CommandButton Command_ConstructGuldurRuinousTower
	Command				= FOUNDATION_CONSTRUCT
	Object				= GuldurRuinousTowerFoundation
	TextLabel			= CONTROLBAR:ConstructGuldurRuinousTower
	ButtonImage			= BIGuldurRuinousTower
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:ToolTipConstructGuldurRuinousTower
	Radial				= Yes  
End
CommandButton Command_ConstructGuldurRuinousTower_DE
	Command				= FOUNDATION_CONSTRUCT
	Object				= GuldurRuinousTowerFoundation_DE
	TextLabel			= CONTROLBAR:ConstructGuldurRuinousTower
	ButtonImage			= BIGuldurRuinousTower
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:ToolTipConstructGuldurRuinousTower
	Radial				= Yes  
End
CommandButton Command_ConstructGuldurRestlessBarrow
	Command				= FOUNDATION_CONSTRUCT
	Object				= GuldurRestlessBarrowFoundation
	TextLabel			= CONTROLBAR:ConstructGuldurRestlessBarrow
	ButtonImage			= BIGuldurBarrow
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:ToolTipConstructGuldurRestlessBarrow
	Radial				= Yes  
End
CommandButton Command_ConstructGuldurRestlessBarrow_DE
	Command				= FOUNDATION_CONSTRUCT
	Object				= GuldurRestlessBarrowFoundation_DE
	TextLabel			= CONTROLBAR:ConstructGuldurRestlessBarrow
	ButtonImage			= BIGuldurBarrow
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:ToolTipConstructGuldurRestlessBarrow
	Radial				= Yes  
End
; --------------- Guldur End

;--------------- Mirkwood Foundation Constructs
CommandButton Command_ConstructMirkwoodHuntingLodgeFoundation
	Command       		= FOUNDATION_CONSTRUCT
	Object        		= MirkwoodHuntingLodgeFoundation
	TextLabel     		= CONTROLBAR:ConstructMirkwoodHuntingLodge
	ButtonImage   		= UIHuntingShrine
	ButtonBorderType    = BUILD 
	DescriptLabel       = CONTROLBAR:ToolTipMirkwoodHuntingLodge
	Radial				= Yes
End
CommandButton Command_ConstructMirkwoodVineyardFoundation
	Command       		= FOUNDATION_CONSTRUCT
	Object        		= MirkwoodVineyardFoundation
	TextLabel     		= CONTROLBAR:ConstructMirkwoodVineyard
	ButtonImage   		= UIGreenwoodVineyard
	ButtonBorderType    = BUILD 
	DescriptLabel       = CONTROLBAR:ToolTipMirkwoodVineyard
	Radial				= Yes
End
CommandButton Command_ConstructMirkwoodTrainingGroundsFoundation
	Command       		= FOUNDATION_CONSTRUCT
	Object        		= MirkwoodTrainingGroundsFoundation
	TextLabel     		= CONTROLBAR:ConstructMirkwoodTrainingGrounds
	ButtonImage   		= UISilvanClearing
	ButtonBorderType    = BUILD 
	DescriptLabel       = CONTROLBAR:ToolTipConstructMirkwoodTrainingGrounds
	Radial				= Yes
End
CommandButton Command_ConstructMirkwoodTrainingGroundsFoundationWotRRealTime
	Command       		= FOUNDATION_CONSTRUCT
	Object        		= MirkwoodTrainingGroundsFoundation_WotR
	TextLabel     		= CONTROLBAR:ConstructMirkwoodTrainingGroundsWotRRealTime
	ButtonImage   		= UISilvanClearing
	ButtonBorderType    = BUILD
	DescriptLabel       = CONTROLBAR:ToolTipConstructMirkwoodTrainingGroundsWotRRealTime
	Radial				= Yes
End
CommandButton Command_ConstructMirkwoodBeorningCabinFoundation
	Command       		= FOUNDATION_CONSTRUCT
	Object        		= MirkwoodBeorningCabinFoundation
	TextLabel     		= CONTROLBAR:ConstructMirkwoodBeorningCabin
	ButtonImage   		= UIBeorningLodge
	ButtonBorderType    = BUILD 
	DescriptLabel       = CONTROLBAR:ToolTipMirkwoodBeorningCabin
	Radial				= Yes
End
CommandButton Command_ConstructMirkwoodRoyalBarracksFoundation
	Command       		= FOUNDATION_CONSTRUCT
	Object        		= MirkwoodRoyalBarracksFoundation
	TextLabel     		= CONTROLBAR:ConstructMirkwoodRoyalBarracks
	ButtonImage   		= UIGreenwoodRoyalBarracks
	ButtonBorderType    = BUILD 
	DescriptLabel       = CONTROLBAR:ToolTipConstructMirkwoodRoyalBarracks
	Radial				= Yes
End
CommandButton Command_ConstructMirkwoodRoyalBarracksFoundation_BotFA
	Command       		= FOUNDATION_CONSTRUCT
	Object        		= MirkwoodRoyalBarracksFoundation_BotFA
	TextLabel     		= CONTROLBAR:ConstructMirkwoodRoyalBarracksBotFA
	ButtonImage   		= UIGreenwoodRoyalBarracks
	ButtonBorderType    = BUILD 
	DescriptLabel       = CONTROLBAR:ToolTipConstructMirkwoodRoyalBarracksBotFA
	Radial				= Yes
End
CommandButton Command_ConstructMirkwoodRoyalBarracksFoundationWotRRealTime
	Command       		= FOUNDATION_CONSTRUCT
	Object        		= MirkwoodRoyalBarracksFoundation_WotR
	TextLabel     		= CONTROLBAR:ConstructMirkwoodRoyalBarracksWotRRealTime
	ButtonImage   		= UIGreenwoodRoyalBarracks
	ButtonBorderType    = BUILD
	DescriptLabel       = CONTROLBAR:ToolTipConstructMirkwoodRoyalBarracksWotRRealTime
	Radial				= Yes
End
CommandButton Command_ConstructMirkwoodTreasuryFoundation
	Command       		= FOUNDATION_CONSTRUCT
	Object        		= MirkwoodTreasuryFoundation
	TextLabel     		= CONTROLBAR:ConstructMirkwoodTreasury
	ButtonImage   		= UIThranduilTreasury
	ButtonBorderType    = BUILD 
	DescriptLabel       = CONTROLBAR:ToolTipMirkwoodTreasury
	Radial				= Yes
End
CommandButton Command_ConstructMirkwoodSiegeGroundsFoundation
	Command       		= FOUNDATION_CONSTRUCT
	Object        		= MirkwoodSiegeGroundsFoundation
	TextLabel     		= CONTROLBAR:ConstructMirkwoodSiegeGrounds
	ButtonImage   		= UIGreenwoodSiegeGrounds
	ButtonBorderType    = BUILD 
	DescriptLabel       = CONTROLBAR:ToolTipConstructMirkwoodSiegeGrounds
	Radial				= Yes
End
CommandButton Command_ConstructMirkwoodSiegeGroundsFoundationWotRRealTime
	Command       		= FOUNDATION_CONSTRUCT
	Object				= MirkwoodSiegeGroundsFoundation_WotR
	TextLabel			= CONTROLBAR:ConstructMirkwoodSiegeGroundsWotRRealTime
	ButtonImage			= UIGreenwoodSiegeGrounds
	ButtonBorderType	= BUILD
	DescriptLabel		= CONTROLBAR:ToolTipConstructMirkwoodSiegeGroundsWotRRealTime
	Radial				= Yes
End
CommandButton Command_ConstructMirkwoodCellarDoorFoundation
	Command       		= FOUNDATION_CONSTRUCT
	Object        		= MirkwoodCellarDoorFoundation
	TextLabel     		= CONTROLBAR:ConstructMirkwoodCellarDoor
	ButtonImage   		= uicellardoor
	ButtonBorderType    = BUILD 
	DescriptLabel       = CONTROLBAR:ToolTipMirkwoodCellarDoor
	Radial				= Yes
End
CommandButton Command_ConstructMirkwoodBattleTowerFoundation
	Command       		= FOUNDATION_CONSTRUCT
	Object        		= MirkwoodBattleTowerFoundation
	TextLabel     		= CONTROLBAR:ConstructMirkwoodBattleTower
	ButtonImage   		= UIWoodlandLookout
	ButtonBorderType    = BUILD 
	DescriptLabel       = CONTROLBAR:ToolTipConstructArnorSentryTower
	Radial				= Yes
End
CommandButton Command_ConstructMirkwoodWellFoundation
	Command       		= FOUNDATION_CONSTRUCT
	Object        		= MirkwoodWellFoundation
	TextLabel     		= CONTROLBAR:ConstructMirkwoodWell
	ButtonImage   		= UIWellofWine
	ButtonBorderType    = BUILD 
	DescriptLabel       = OBJECT:MirkwoodWellDescription
	Radial				= Yes
End
CommandButton Command_ConstructMirkwoodStatueFoundation
	Command       		= FOUNDATION_CONSTRUCT
	Object        		= MirkwoodStatueFoundation
	TextLabel     		= CONTROLBAR:ConstructMirkwoodStatue
	ButtonImage   		= UIStatueofOropher
	ButtonBorderType    = BUILD 
	DescriptLabel       = CONTROLBAR:MirkwoodHeroicStatueBuild
	Radial				= Yes
End
; --------------- Minkwood End


;--------------- Mirkwood Foundation Constructs
CommandButton Command_ConstructAngmarMillFoundation
	Command       		= FOUNDATION_CONSTRUCT
	Object        		= HaradwaithBazaarFoundation
	TextLabel     		= CONTROLBAR:ConstructAngmarMill
	ButtonImage   		= uiharadbazaar
	ButtonBorderType    = BUILD 
	DescriptLabel       = CONTROLBAR:TooltipConstructAngmarMill
	Radial				= Yes
End
CommandButton Command_ConstructAngmarBarracksFoundation
	Command       		= FOUNDATION_CONSTRUCT
	Object        		= HarondorOutpostFoundation
	TextLabel     		= CONTROLBAR:ConstructAngmarBarracks
	ButtonImage   		= uiharondoroutpost
	ButtonBorderType    = BUILD 
	DescriptLabel       = CONTROLBAR:ToolTipConstructAngmarBarracks
	Radial				= Yes
End
CommandButton Command_ConstructHaradTribalCampWotRRealTime
	Command       		= FOUNDATION_CONSTRUCT
	Object           = HaradTribalCampFoundation_WotR
	TextLabel        = CONTROLBAR:ConstructHaradTribalCampWotR
	ButtonImage      = uitribesofharad
	ButtonBorderType = BUILD
	DescriptLabel    = CONTROLBAR:ToolTipConstructHaradTribalCampWotR
	Radial           = Yes
End
CommandButton Command_ConstructAngmarBarracksFoundationWotRRealTime
	Command       		= FOUNDATION_CONSTRUCT
	Object           = HarondorOutpostFoundation_WotR
	TextLabel        = CONTROLBAR:ConstructAngmarBarracksWotRRealTime
	ButtonImage      = uiharondoroutpost
	ButtonBorderType = BUILD
	DescriptLabel    = CONTROLBAR:ToolTipConstructAngmarBarracksWotRRealTime
	Radial           = Yes
End
CommandButton Command_ConstructAngmarDenFoundation
	Command       		= FOUNDATION_CONSTRUCT
	Object        		= MahudGatheringFoundation
	TextLabel     		= CONTROLBAR:ConstructAngmarDen
	ButtonImage   		= uimahudgathering
	ButtonBorderType    = BUILD 
	DescriptLabel       = CONTROLBAR:ToolTipAngmarDen
	Radial				= Yes
End
CommandButton Command_ConstructAngmarHallofTwilightFoundation
	Command       		= FOUNDATION_CONSTRUCT
	Object        		= UmbarianCitadelFoundation
	TextLabel     		= CONTROLBAR:ConstructAngmarHallofTwilight
	ButtonImage   		= uiumbariancitadel
	ButtonBorderType    = BUILD 
	DescriptLabel       = CONTROLBAR:ToolTipConstructAngmarHallofTwilight
	Radial				= Yes
End
CommandButton Command_ConstructAngmarForgeWorksFoundation
	Command       		= FOUNDATION_CONSTRUCT
	Object        		= GoldenKingPavillionFoundation
	TextLabel     		= CONTROLBAR:ConstructAngmarForgeWorks
	ButtonImage   		= uipavilliongoldenking
	ButtonBorderType    = BUILD 
	DescriptLabel       = CONTROLBAR:ToolTipConstructAngmarForgeWorks
	Radial				= Yes
End
CommandButton Command_ConstructAngmarForgeWorksFoundationWotRRealTime
	Command       		= FOUNDATION_CONSTRUCT
 	Object           		= GoldenKingPavillionFoundation_WotR ;AngmarForgeWorks
 	TextLabel        		= CONTROLBAR:ConstructAngmarForgeWorksWotRRealTime
 	ButtonImage      		= uipavilliongoldenking
 	ButtonBorderType 		= BUILD
 	DescriptLabel    		= CONTROLBAR:ToolTipConstructAngmarForgeWorksWotRRealTime
 	Radial           		= Yes
End
CommandButton Command_ConstructSanctumofZigurFoundation
	Command       		= FOUNDATION_CONSTRUCT
	Object        		= SanctumofZigurFoundation
	TextLabel     		= CONTROLBAR:ConstructSanctumofZigur
	ButtonImage   		= uisanctumzigur
	ButtonBorderType    = BUILD 
	DescriptLabel       = CONTROLBAR:ToolTipConstructSanctumofZigur
	Radial				= Yes
End

CommandButton Command_ConstructSanctumofZigurFoundation_Disabled
  Command          = FOUNDATION_CONSTRUCT
  Object           = SanctumofZigurFoundation
  Options		   = NEED_UPGRADE
  NeededUpgrade	   = Upgrade_MiniHordeLvl10  
  TextLabel        = CONTROLBAR:ConstructSanctumofZigur
  ButtonImage      = uisanctumzigur
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipConstructSanctumofZigur
  Radial           = Yes  
End

CommandButton Command_PorterConstructHaradDesertLookoutFoundation
	Command       		= FOUNDATION_CONSTRUCT
	Object        		= HaradDesertLookoutFoundation
	TextLabel     		= CONTROLBAR:ConstructHaradwaithSentryTower
	ButtonImage   		= uiharadguardtower
	ButtonBorderType    = BUILD 
	DescriptLabel       = CONTROLBAR:ToolTipConstructGenericSentryTower
	Radial				= Yes
End
; --------------- Harad End

; --------------- Ithilien Foundation Constructs
CommandButton Command_ConstructIthilienGatheringFoundation
	Command       		= FOUNDATION_CONSTRUCT
	Object        		= IthilienGatheringFoundation
	TextLabel     		= CONTROLBAR:IthilienGathering
	ButtonImage   		= uiithiliengathering
	ButtonBorderType    = BUILD 
	DescriptLabel       = CONTROLBAR:ToolTipConstructIthilienGatheringFoundation
	Radial				= Yes
End

CommandButton Command_ConstructIthilienStorehouseFoundation
	Command       		= FOUNDATION_CONSTRUCT
	Object        		= IthilienStorehouseFoundation
	TextLabel     		= CONTROLBAR:ConstructIthilienStorehouse
	ButtonImage   		= uiithilienstorehouse
	ButtonBorderType    = BUILD 
	DescriptLabel       = CONTROLBAR:ToolTipConstructIthilienStorehouseFoundation
	Radial				= Yes
End

CommandButton Command_ConstructIthilienBeaconFoundation
	Command       		= FOUNDATION_CONSTRUCT
	Object        		= IthilienBeaconFoundation
	TextLabel     		= CONTROLBAR:ConstructIthilienBeacon
	ButtonImage   		= uiithiliensigfire
	ButtonBorderType    = BUILD 
	DescriptLabel       = CONTROLBAR:ToolTipConstructIthilienBeaconFoundation
	Radial				= Yes
End

CommandButton Command_ConstructIthilienWatchtowerFoundation
	Command       		= FOUNDATION_CONSTRUCT
	Object        		= IthilienWatchtowerFoundation
	TextLabel     		= CONTROLBAR:ConstructIthilienWatchtower
	ButtonImage   		= uiithilientower
	ButtonBorderType    = BUILD 
	DescriptLabel       = CONTROLBAR:ToolTipConstructIthilienWatchtowerFoundation
	Radial				= Yes
End
; --------------- Ithilien End

;--------------- Arthedain Foundation Constructs

CommandButton Command_ConstructArnorFarmFoundation
  Command          = FOUNDATION_CONSTRUCT
  Object        		= ArnorFarmFoundation 
	TextLabel     		= CONTROLBAR:ConstructArnorMill
	ButtonImage   		= uiarthedwindmill
	ButtonBorderType    = BUILD
	DescriptLabel       = CONTROLBAR:ToolTipConstructArnorMill
	Radial				= Yes
End
CommandButton Command_PorterConstructArnorBlacksmithFoundation
	Command				= FOUNDATION_CONSTRUCT
	Object				= ArnorForgeFoundation
	TextLabel			= CONTROLBAR:ConstructArnorBlacksmith
	ButtonImage			= uiarthedblacksmith
	ButtonBorderType	= BUILD
	DescriptLabel		= CONTROLBAR:ToolTipConstructArnorBlacksmith
	Radial				= Yes
End
CommandButton Command_PorterConstructFornostGarrisonFoundation
	Command       		= FOUNDATION_CONSTRUCT
	Object        		= FornostGarrisonFoundation
	TextLabel     		= CONTROLBAR:ConstructFornostGarrison
	ButtonImage   		= uifornostgarrison
	ButtonBorderType    = BUILD
	DescriptLabel       = CONTROLBAR:ToolTipConstructFornostGarrison
	Radial				= Yes
End
CommandButton Command_PorterConstructArthedainWatchtowerFoundation
	Command				= FOUNDATION_CONSTRUCT
	Object				= ArthedainWatchtowerFoundation
	TextLabel			= CONTROLBAR:ConstructArthedainWatchtower
	ButtonImage			= uiarthedwatchtower
	ButtonBorderType	= BUILD
	DescriptLabel		= CONTROLBAR:ToolTipConstructGenericSentryTower
	Radial				= Yes
End
CommandButton Command_ConstructStatueOfElendilFoundation
  Command          = FOUNDATION_CONSTRUCT
  Object           = StatueOfElendilFoundation
  TextLabel        = CONTROLBAR:ConstructStatueOfElendil
  ButtonImage      = uiarthedmonument
  ButtonBorderType = BUILD
  DescriptLabel    = CONTROLBAR:StatueOfElendilBuild
  Radial           = Yes
End
CommandButton Command_PorterConstructMalbethStudyFoundation
	Command				= FOUNDATION_CONSTRUCT
	Object				= MalbethStudyFoundation
	TextLabel			= CONTROLBAR:ConstructMalbethStudy
	ButtonImage			= uimalbethsstudy
	ButtonBorderType	= BUILD
	DescriptLabel		= CONTROLBAR:ToolTipConstructMalbethStudy
	Radial				= Yes
End
CommandButton Command_PorterConstructMalbethStudyFoundation_Disabled
  Command          = FOUNDATION_CONSTRUCT
  Object           = MalbethStudyFoundation
  Options		   = NEED_UPGRADE
  NeededUpgrade	   = Upgrade_MiniHordeLvl10  
  TextLabel        = CONTROLBAR:ConstructMalbethStudy
  ButtonImage      = uimalbethsstudy
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipConstructMalbethStudy
  Radial           = Yes  
End
CommandButton Command_PorterConstructArnorEmbassyFoundation
	Command				= FOUNDATION_CONSTRUCT
	Object				= ArnorEmbassyFoundation
	TextLabel			= CONTROLBAR:ConstructArnorEmbassy
	ButtonImage			= uiarthedembassy
	ButtonBorderType	= BUILD
	DescriptLabel		= CONTROLBAR:ToolTipConstructArnorEmbassy
	Radial				= Yes
End

; --------------- Arthedain End

;--------------- Rhun Foundation Constructs

CommandButton Command_ConstructRhunSlaughterHouse
  Command          = FOUNDATION_CONSTRUCT
  Object           = MordorSlaughterHouseFoundation_Rhun
  TextLabel        = CONTROLBAR:ConstructSlaughterHouse
  ButtonImage      = BIMordorSlaughterHouse
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipConstructMenFarm
  Radial           = Yes  
End
CommandButton Command_ConstructRhunAuxiliaryBarracks
  Command          = FOUNDATION_CONSTRUCT
  Object           = MordorHaradrimPalaceFoundation_Rhun
  TextLabel        = CONTROLBAR:ConstructRhunAuxiliaryBarracks
  ButtonImage      = BIMordorEasterlingEncampment
  ButtonBorderType = BUILD
  DescriptLabel    = CONTROLBAR:ToolTipMordorHaradrimPalace
  Radial           = Yes
End
CommandButton Command_ConstructRhunArcheryRange
	Command				= FOUNDATION_CONSTRUCT
	Object				= MordorRhunArcherRangeFoundation
	TextLabel			= CONTROLBAR:ConstructRhunArcheryRange
	ButtonImage			= uirhunarcheryrange
	ButtonBorderType	= BUILD
	DescriptLabel		= CONTROLBAR:ToolTipRhunArcheryRange
	Radial				= Yes
End
CommandButton Command_ConstructRhunStable
	Command				= FOUNDATION_CONSTRUCT
	Object				= RhunStableFoundation
	TextLabel			= CONTROLBAR:ConstructRhunStable
	ButtonImage			= uirhunhorsemasterscampground
	ButtonBorderType	= BUILD
	DescriptLabel		= CONTROLBAR:ToolTipConstructRhunStable
	Radial				= Yes
End
CommandButton Command_ConstructRhunSiegeWorks
  Command          = FOUNDATION_CONSTRUCT
  Object           = RhunSiegeWorksFoundation
  TextLabel        = CONTROLBAR:ConstructMordorSiegeWorks
  ButtonImage      = BIMordorSiegeWorks
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipordorSiegeWorks
  Radial           = Yes  
End
CommandButton Command_ConstructRhunGuardTower
	Command				= FOUNDATION_CONSTRUCT
	Object				= RhunGuardTowerFoundation
	TextLabel			= CONTROLBAR:ConstructRhunGuardTower
	ButtonImage			= uirhuntower
	ButtonBorderType		= BUILD
	DescriptLabel			= CONTROLBAR:ToolTipConstructMordorBattleTower
	Radial				= Yes
End

; --------------- Rhun End

;--------------- Shadow and Flame Foundation Constructs

CommandButton Command_ConstructWildFissure_Moria
	Command				= FOUNDATION_CONSTRUCT
	Object				= GoblinFissureFoundation
	TextLabel			= CONTROLBAR:ConstructWildGoblinFissure
	ButtonImage			= BIMMTrollLair
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:ToolTipConstructWildGoblinFissure_Moria
	Radial				= Yes  
END
CommandButton Command_ConstructAltarofFireFoundation
	Command          = FOUNDATION_CONSTRUCT
	Object           = MoriaAltarofFireFoundation
	TextLabel        = CONTROLBAR:ConstructAltarofFire
	ButtonImage      = UIAltarofFlame
	ButtonBorderType = BUILD
	DescriptLabel    = CONTROLBAR:ToolTipConstructAltarofFire
	Radial           = Yes
End

; --------------- Shadow and Flame End

;--------------- Angmar Foundation Constructs

CommandButton Command_ConstructAngmarSlaveMill
	Command				= FOUNDATION_CONSTRUCT
	Object				= AngmarMillFoundation
	TextLabel			= CONTROLBAR:ConstructGuldurSlaveMill
	ButtonImage			= BIAngmarMill
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:TooltipConstructAngmarSlaveMill
	Radial				= Yes  
End
CommandButton Command_ConstructAngmarSlaveMill_DE
	Command				= FOUNDATION_CONSTRUCT
	Object				= AngmarMillFoundation_DE
	TextLabel			= CONTROLBAR:ConstructGuldurSlaveMill
	ButtonImage			= BIAngmarMill
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:TooltipConstructAngmarSlaveMill
	Radial				= Yes  
End
CommandButton Command_ConstructAngmarLumberMill
  Command          = FOUNDATION_CONSTRUCT
  Object           = GuldurLumberMillFoundation
  TextLabel        = CONTROLBAR:ConstructGuldurLumberMill
  ButtonImage      = BIAngmarLumber
  ButtonBorderType = BUILD
  DescriptLabel    = CONTROLBAR:ToolTipConstructGuldurLumberMill
  Radial           = Yes
End
CommandButton Command_ConstructAngmarLumberMill_DE
  Command          = FOUNDATION_CONSTRUCT
  Object           = GuldurLumberMillFoundation_DE
  TextLabel        = CONTROLBAR:ConstructGuldurLumberMill
  ButtonImage      = BIAngmarLumber
  ButtonBorderType = BUILD
  DescriptLabel    = CONTROLBAR:ToolTipConstructGuldurLumberMill
  Radial           = Yes
End
CommandButton Command_ConstructAngmarBastion
	Command				= FOUNDATION_CONSTRUCT
	Object           = AngmarBastionFoundation
	TextLabel        = CONTROLBAR:ConstructAngmarBastion
	ButtonImage      = BIAngmarCitadel
	ButtonBorderType = BUILD
	DescriptLabel    = CONTROLBAR:ToolTipConstructAngmarBastion
	Radial           = Yes
End
CommandButton Command_ConstructAngmarBastion_DE
	Command				= FOUNDATION_CONSTRUCT
	Object           = AngmarBastionFoundation_DE
	TextLabel        = CONTROLBAR:ConstructAngmarBastion
	ButtonImage      = BIAngmarCitadel
	ButtonBorderType = BUILD
	DescriptLabel    = CONTROLBAR:ToolTipConstructAngmarBastion
	Radial           = Yes
End
CommandButton Command_ConstructAngmarCairn
	Command				= FOUNDATION_CONSTRUCT
	Object           = AngmarCairnFoundation
	TextLabel			= CONTROLBAR:ConstructAngmarCairn
	ButtonImage			= UIMMWargCage ;BWSpiderPit
	ButtonBorderType	= BUILD
	DescriptLabel		= CONTROLBAR:ToolTipConstructAngmarCairn
	Radial				= Yes
End
CommandButton Command_ConstructAngmarCairn_DE
	Command				= FOUNDATION_CONSTRUCT
	Object           = AngmarCairnFoundation_DE
	TextLabel			= CONTROLBAR:ConstructAngmarCairn
	ButtonImage			= UIMMWargCage ;BWSpiderPit
	ButtonBorderType	= BUILD
	DescriptLabel		= CONTROLBAR:ToolTipConstructAngmarCairn
	Radial				= Yes
End
CommandButton Command_ConstructAncestralHall
	Command				= FOUNDATION_CONSTRUCT
  Options	   = NEED_UPGRADE
  NeededUpgrade	   = Upgrade_Evilboyos	
  	Object           		= AncestralHallFoundation
  	TextLabel        		= CONTROLBAR:ConstructAncestralHall
  	ButtonImage      		= BIAngmarHall
  	ButtonBorderType 		= BUILD
  	DescriptLabel    		= CONTROLBAR:ToolTipAncestralHall
  	Radial           		= Yes
End
CommandButton Command_ConstructAncestralHall_DE
	Command				= FOUNDATION_CONSTRUCT
  Options	   = NEED_UPGRADE
  NeededUpgrade	   = Upgrade_Evilboyos	
  	Object           		= AncestralHallFoundation_DE
  	TextLabel        		= CONTROLBAR:ConstructAncestralHall
  	ButtonImage      		= BIAngmarHall
  	ButtonBorderType 		= BUILD
  	DescriptLabel    		= CONTROLBAR:ToolTipAncestralHall
  	Radial           		= Yes
End
CommandButton Command_ConstructAngmarRuinousTower
	Command				= FOUNDATION_CONSTRUCT
	Object				= AngmarSentryTower_IndependentFoundation
	TextLabel			= CONTROLBAR:ConstructGuldurRuinousTower
	ButtonImage			= BIAngmarRuinousTower
	ButtonBorderType	= BUILD
	DescriptLabel		= CONTROLBAR:ToolTipConstructGuldurRuinousTower
	Radial				= Yes 
End
CommandButton Command_ConstructAngmarRuinousTower_DE
	Command				= FOUNDATION_CONSTRUCT
	Object				= AngmarSentryTower_IndependentFoundation_DE
	TextLabel			= CONTROLBAR:ConstructGuldurRuinousTower
	ButtonImage			= BIAngmarRuinousTower
	ButtonBorderType	= BUILD
	DescriptLabel		= CONTROLBAR:ToolTipConstructGuldurRuinousTower
	Radial				= Yes 
End
CommandButton Command_ConstructArnorianBarrow
	Command				= FOUNDATION_CONSTRUCT
	Object				= ArnorianBarrowFoundation
	TextLabel			= CONTROLBAR:ConstructArnorianBarrow
	ButtonImage			= BIAngmarBarrow
	ButtonBorderType	= BUILD
	DescriptLabel		= CONTROLBAR:ToolTipConstructArnorianBarrow
	Radial				= Yes
End
CommandButton Command_ConstructArnorianBarrow_DE
	Command				= FOUNDATION_CONSTRUCT
	Object				= ArnorianBarrowFoundation_DE
	TextLabel			= CONTROLBAR:ConstructArnorianBarrow
	ButtonImage			= BIAngmarBarrow
	ButtonBorderType	= BUILD
	DescriptLabel		= CONTROLBAR:ToolTipConstructArnorianBarrow
	Radial				= Yes
End

; --------------- Angmar End

;--------------- Dorwinion Foundation Constructs

CommandButton Command_ConstructDorwinionVineyardFoundation
	Command       		= FOUNDATION_CONSTRUCT
	Object        		= MirkwoodVineyardFoundation
  TextLabel        = CONTROLBAR:ConstructDorwinionVineyard
  ButtonImage      = UIDorwinionVineyard
  ButtonBorderType = BUILD
  DescriptLabel    = CONTROLBAR:ToolTipDorwinionVineyard
  Radial           = Yes
End

CommandButton Command_ConstructDorwinionMarketFoundation
	Command				= FOUNDATION_CONSTRUCT
	Object				= DorwinionMarketFoundation
	TextLabel			= CONTROLBAR:ConstructDorwinionMarket
	ButtonImage			= UIDorwinionMarket
	ButtonBorderType	= BUILD
	DescriptLabel		= CONTROLBAR:ToolTipConstructDorwinionMarket
	Radial				= Yes
End

CommandButton Command_ConstructDorwinionBarracksFoundation
	Command				= FOUNDATION_CONSTRUCT
	Object           	= DorwinionBarracksFoundation
	TextLabel        	= CONTROLBAR:ConstructDorwinionAssembly
	ButtonImage      	= BIEreborDaleBarracks
	ButtonBorderType 	= BUILD
	DescriptLabel    	= CONTROLBAR:TooltipConstructDorwinionAssembly
	Radial           	= Yes
End

CommandButton Command_ConstructAvariBarracksFoundation
	Command				= FOUNDATION_CONSTRUCT
	Object        		= AvariBarracksFoundation
	TextLabel     		= CONTROLBAR:ConstructKinnLaiGarrison
	ButtonImage   		= UIAvariBarracks
	ButtonBorderType    = BUILD
	DescriptLabel       = CONTROLBAR:ToolTipConstructKinnLaiGarrison
	Radial				= Yes
End

CommandButton Command_ConstructStatueOfGirionFoundation
  Command          = FOUNDATION_CONSTRUCT
  Object           = StatueOfGirionFoundation
  TextLabel        = CONTROLBAR:ConstructStatueOfGirion
  ButtonImage      = UIStatueofGirion
  ButtonBorderType = BUILD
  DescriptLabel    = CONTROLBAR:StatueOfGirionBuild
  Radial           = Yes
End

CommandButton Command_ConstructDorwinionSentryTowerFoundation
  Command          = FOUNDATION_CONSTRUCT
	Object				= DorwinionBattleTowerFoundation
	TextLabel			= CONTROLBAR:ConstructDorwinionSentryTower
	ButtonImage			= UIBardingTower
	ButtonBorderType		= BUILD
	DescriptLabel			= CONTROLBAR:ToolTipConstructGenericSentryTower
	Radial				= Yes
End

; --------------- Dorwinion End
;--------------- Morgul Foundation Constructs

CommandButton Command_ConstructMorgulSlaveMill
	Command         	 	= FOUNDATION_CONSTRUCT
	Object           		= MorgulSlaveMillFoundation
	TextLabel        		= CONTROLBAR:ConstructMorgulSlaveMill
	ButtonImage      		= BIGuldurMill
	ButtonBorderType 		= BUILD
	DescriptLabel    		= CONTROLBAR:TooltipConstructMorgulSlaveMill
	Radial           		= Yes
End
CommandButton Command_ConstructMorgulFoundry
	Command			 = FOUNDATION_CONSTRUCT
	Object           = MorgulFoundryFoundation
	TextLabel        = CONTROLBAR:ConstructMorgulFoundry
	ButtonImage      = uimorgulfoundry
	ButtonBorderType = BUILD
	DescriptLabel    = CONTROLBAR:ToolTipConstructMordorArmory
	Radial           = Yes
End
CommandButton Command_ConstructMorgulGarrison
	Command			 = FOUNDATION_CONSTRUCT
	Object        		= MorgulGarrisonFoundation
	TextLabel     		= CONTROLBAR:ConstructMorgulGarrison
	ButtonImage   		= BIMordorBarracks
	ButtonBorderType    = BUILD
	DescriptLabel       = CONTROLBAR:ToolTipMorgulGarrison
	Radial				= Yes
End
CommandButton Command_ConstructMorgulDungeon
	Command			 = FOUNDATION_CONSTRUCT
	Object           = MorgulDungeonFoundation
	TextLabel        = CONTROLBAR:ConstructMorgulDungeon
	ButtonImage      = uimorguldungeon
	ButtonBorderType = BUILD
	DescriptLabel    = CONTROLBAR:ToolTipConstructMorgulDungeon
	Radial           = Yes
End
CommandButton Command_ConstructMorgulSiegeWorks
	Command			 = FOUNDATION_CONSTRUCT
  Object           = MorgulSiegeWorksFoundation
  TextLabel        = CONTROLBAR:ConstructMordorSiegeWorks
  ButtonImage      = BIMordorSiegeWorks
  ButtonBorderType = BUILD
  DescriptLabel    = CONTROLBAR:ToolTipordorSiegeWorks
  Radial           = Yes
End
CommandButton Command_ConstructMorgulBattleTower
	Command			 = FOUNDATION_CONSTRUCT
	Object				= MorgulBattleTowerFoundation
	TextLabel			= CONTROLBAR:ConstructMorgulBattleTower
	ButtonImage			= BIMordorBattleTower
	ButtonBorderType		= BUILD
	DescriptLabel			= CONTROLBAR:ToolTipConstructMordorBattleTower
	Radial				= Yes
End
; --------------- Morgul End

; --------------- Shire Foundation Constructs
CommandButton Command_ConstructShireHobbitHoleFoundation
	Command       		= FOUNDATION_CONSTRUCT
	Object        		= ShireHobbitHoleFoundation
	TextLabel     		= CONTROLBAR:ConstructShireHobbitHole
	ButtonImage   		= UIShireHobbitHole
	ButtonBorderType    = BUILD 
	DescriptLabel       = CONTROLBAR:ToolTipConstructShireHobbitHole
	Radial				= Yes
End

CommandButton Command_ConstructShireHobbitFarmFoundation
	Command       		= FOUNDATION_CONSTRUCT
	Object        		= ShireHobbitFarmFoundation
	TextLabel     		= CONTROLBAR:ConstructShireHobbitFarm
	ButtonImage   		= UIHobbitFarm
	ButtonBorderType    = BUILD 
	DescriptLabel       = CONTROLBAR:ToolTipConstructShireHobbitFarm
	Radial				= Yes
End

CommandButton Command_ConstructShireShirriffsQuartersFoundation
	Command				= FOUNDATION_CONSTRUCT
	Object				= ShireShirriffsQuartersFoundation
	TextLabel			= CONTROLBAR:ConstructShireShirriffsQuarters
	ButtonImage			= UIShireShirrifsQuarters
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:ToolTipShireShirriffsQuarters
	Radial				= Yes
End

CommandButton Command_ConstructShireHalflingInnFoundation
	Command       		= FOUNDATION_CONSTRUCT
	Object        		= ShireHalflingInnFoundation
	TextLabel     		= CONTROLBAR:ConstructShireHalflingInn
	ButtonImage   		= UIShireInn
	ButtonBorderType    = BUILD 
	DescriptLabel       = CONTROLBAR:ToolTipConstructShireHalflingInn
	Radial				= Yes
End

CommandButton Command_ConstructShireSupplyCartFoundation
	Command       		= FOUNDATION_CONSTRUCT
	Object        		= ShireSupplyCartFoundation
	TextLabel     		= CONTROLBAR:ConstructShireSupplyCart
	ButtonImage   		= UIShireSupplyCart
	ButtonBorderType    = BUILD 
	DescriptLabel       = CONTROLBAR:ToolTipConstructShireSupplyCart
	Radial				= Yes
End


; --------------- Shire End

;--------------- Dol Amroth Foundation Constructs

CommandButton Command_ConstructDolAmrothFarm
  Command          = FOUNDATION_CONSTRUCT
  Object        		= DolAmrothFarmFoundation 
	TextLabel     		= CONTROLBAR:ConstructDolAmrothFarm
	ButtonImage   		= UIDolAmrothFishMarket
	ButtonBorderType    = BUILD 
	DescriptLabel       = CONTROLBAR:ToolTipConstructDolAmrothFarm
	Radial				= Yes  
End

CommandButton Command_ConstructDolAmrothForge
  Command          = FOUNDATION_CONSTRUCT
  Object        		= AmrothianForgeFoundation 
	TextLabel     		= CONTROLBAR:ConstructMenBlacksmith
	ButtonImage   		= UIDolAmrothForge
	ButtonBorderType    = BUILD 
	DescriptLabel       = CONTROLBAR:ToolTipConstructMenBlacksmith
	Radial				= Yes  
End

CommandButton Command_ConstructAmrothianGuardhouseFoundation
  Command          = FOUNDATION_CONSTRUCT
  Object        		= DolAmrothGuardhouseFoundation 
	TextLabel     		= CONTROLBAR:ConstructDolAmrothGuardhouse
	ButtonImage   		= UIDolAmrothGuardhouse
	ButtonBorderType    = BUILD 
	DescriptLabel       = CONTROLBAR:ToolTipConstructDolAmrothGuardhouse
	Radial				= Yes  
End

CommandButton Command_ConstructDolAmrothRoyalBarracksFoundation
	Command          		= FOUNDATION_CONSTRUCT
	Object           		= DolAmrothRoyalBarracksFoundation
	TextLabel        		= CONTROLBAR:ConstructDolAmrothRoyalBarracks
	ButtonImage      		= UIDolAmrothRoyalBarracks
	ButtonBorderType 		= BUILD
	DescriptLabel    		= CONTROLBAR:ToolTipConstructDolAmrothRoyalBarracks
	Radial           		= Yes
End

CommandButton Command_ConstructDolAmrothRoyalStablesFoundation
  Command          = FOUNDATION_CONSTRUCT
  Object        		= DolAmrothRoyalStableFoundation 
	TextLabel     		= CONTROLBAR:ConstructDolAmrothRoyalStables
	ButtonImage   		= UIDolAmrothRoyalStables
	ButtonBorderType    = BUILD 
	DescriptLabel       = CONTROLBAR:ToolTipConstructDolAmrothRoyalStables
	Radial				= Yes  
End

CommandButton Command_ConstructAmrothianGuestHouseFoundation
	Command          		= FOUNDATION_CONSTRUCT
	Object           		= DolAmrothGuestHouseFoundation
	Options					= NEED_UPGRADE
	NeededUpgrade    		= Upgrade_WildFortressNorthernWastesTrigger
	TextLabel        		= CONTROLBAR:ConstructAmrothianGuestHouse
	ButtonImage      		= UIAmrothianGuesthouse
	ButtonBorderType 		= BUILD
	DescriptLabel    		= CONTROLBAR:ToolTipConstructAmrothianGuestHouse
	Radial           		= Yes
End

CommandButton Command_ConstructAmrothianGuestHouseFoundation_Disabled
  Command          = FOUNDATION_CONSTRUCT
  Object           = DolAmrothGuestHouseFoundation
  Options		   = NEED_UPGRADE
  NeededUpgrade	   = Upgrade_MiniHordeLvl10  
  TextLabel        = CONTROLBAR:ConstructAmrothianGuestHouse
  ButtonImage      = UIAmrothianGuesthouse
  ButtonBorderType = BUILD 
  DescriptLabel    = CONTROLBAR:ToolTipConstructAmrothianGuestHouse
  Radial           = Yes  
End

CommandButton Command_ConstructDolAmrothStatueFoundation
	Command					= FOUNDATION_CONSTRUCT
	Object					= DolAmrothStatueFoundation
	TextLabel				= CONTROLBAR:ConstructDolAmrothStatue
	ButtonImage				= UIDolAmrothMonumenttoAmroth
	ButtonBorderType		= BUILD
	DescriptLabel			= CONTROLBAR:ToolTipConstructDolAmrothStatue
	Radial					= Yes
End

CommandButton Command_ConstructDolAmrothSentryTowerFoundation
	Command					= FOUNDATION_CONSTRUCT
	Object					= DolAmrothBattleTowerFoundation
	TextLabel				= CONTROLBAR:ConstructDolAmrothSentryTower
	ButtonImage				= UIDolAmrothCoastalStronghold
	ButtonBorderType		= BUILD
	DescriptLabel			= CONTROLBAR:ToolTipConstructGenericSentryTower
	Radial					= Yes
End

CommandButton Command_ConstructLastAllianceSmithingTentFoundation
	Command       		= FOUNDATION_CONSTRUCT
	Object        		= LastAllianceSmithingTentFoundation
	TextLabel     		= CONTROLBAR:ConstructLastAllianceBlacksmith
	ButtonImage   		= UILAGatheringofArms
	ButtonBorderType    = BUILD 
	DescriptLabel       = CONTROLBAR:ToolTipConstructLastAllianceBlacksmith
	Radial				= Yes
End

CommandButton Command_ConstructLAAdventureNoldorTent
  Command          = FOUNDATION_CONSTRUCT
  Object        		= LAAdventureNoldorTentFoundation
	TextLabel     		= CONTROLBAR:ConstructNoldorTent
	ButtonImage   		= UILANoldorTent
	ButtonBorderType    = BUILD
	DescriptLabel       = CONTROLBAR:ToolTipConstructNoldorTent
	Radial				= Yes
End

CommandButton Command_ConstructLastAllianceWoodElfTent
  Command          = FOUNDATION_CONSTRUCT
  Object        		= LastAllianceWoodElfTentFoundation
	TextLabel     		= CONTROLBAR:ConstructCampaignIthilienTent
	ButtonImage   		= uiIthilienTent
	ButtonBorderType    = BUILD
	DescriptLabel       = CONTROLBAR:ConstructCampaignIthilienTentTooltip
	Radial				= Yes
End

CommandButton Command_ConstructLAAdventureNumenorTent
  Command          = FOUNDATION_CONSTRUCT
  Object        		= LAAdventureNumenorTentFoundation
	TextLabel     		= CONTROLBAR:ConstructLastAllianceNumenorTent
	ButtonImage   		= UILAGahteringoftheFaithful
	ButtonBorderType    = BUILD
	DescriptLabel       = CONTROLBAR:ToolTipConstructLastAllianceNumenorTent
	Radial				= Yes
End

CommandButton Command_ConstructLastAllianceSiegeTentFoundation
  Command          = FOUNDATION_CONSTRUCT
  Object				= LAAdventureSiegeTentFoundation
	TextLabel			= CONTROLBAR:ConstructLastAllianceSiegeTent
	ButtonImage			= UIAdvLAGatheringSiege
	ButtonBorderType	= BUILD 
	DescriptLabel		= CONTROLBAR:ToolTipConstructMenWorkshop
	Radial				= Yes   
End

CommandButton Command_ConstructLastAllianceWatchtowerFoundation
	Command       		= FOUNDATION_CONSTRUCT
	Object        		= LastAllianceTowerFoundation
	TextLabel     		= CONTROLBAR:ConstructLastAllianceTower
	ButtonImage   		= UILABattleTower
	ButtonBorderType    = BUILD 
	DescriptLabel       = CONTROLBAR:ToolTipConstructIthilienWatchtowerFoundation
	Radial				= Yes
End

CommandButton Command_ConstructLANoldorBanner
  Command          = FOUNDATION_CONSTRUCT
  Object        		= NoldorBannerFoundation
	TextLabel     		= CONTROLBAR:LANoldorBanner
	ButtonImage   		= UILABanneroftheNoldor
	ButtonBorderType    = BUILD
	DescriptLabel       = CONTROLBAR:ToolTipLANoldorBanner
	Radial				= Yes
End

CommandButton Command_ConstructLAElendilBanner
  Command          = FOUNDATION_CONSTRUCT
  Object        		= ElendiliBannerFoundation
	TextLabel     		= CONTROLBAR:LAElendilBanner
	ButtonImage   		= UILABanneroftheElendili
	ButtonBorderType    = BUILD
	DescriptLabel       = CONTROLBAR:ToolTipLAElendilBanner
	Radial				= Yes
End

CommandButton Command_ConstructLAKhazadBanner
  Command          = FOUNDATION_CONSTRUCT
  	Options				= NEED_UPGRADE
	NeededUpgrade		= Upgrade_AmrothKnights   
  Object        		= KhazadBannerFoundation
	TextLabel     		= CONTROLBAR:LAKhazadBanner
	ButtonImage   		= UILABannerofKhazadDum
	ButtonBorderType    = BUILD
	DescriptLabel       = CONTROLBAR:ToolTipLAKhazadBanner
	Radial				= Yes
End

CommandButton Command_ConstructLAErynGalenBanner
  Command          = FOUNDATION_CONSTRUCT
  	Options				= NEED_UPGRADE
	NeededUpgrade		= Upgrade_WildFortressWebCocoon  
  Object        		= ErynGalenBannerFoundation
	TextLabel     		= CONTROLBAR:LAErynGalenBanner
	ButtonImage   		= UILABannerofErynGalen
	ButtonBorderType    = BUILD
	DescriptLabel       = CONTROLBAR:ToolTipLAErynGalenBanner
	Radial				= Yes
End

CommandButton Command_ConstructLALorinandBanner
  Command          = FOUNDATION_CONSTRUCT
  	Options				= NEED_UPGRADE
	NeededUpgrade		= Upgrade_Evilboyos
  Object        		= LorinandBannerFoundation
	TextLabel     		= CONTROLBAR:LALorinandBanner
	ButtonImage   		= UILABannerofLorinand
	ButtonBorderType    = BUILD
	DescriptLabel       = CONTROLBAR:ToolTipLALorinandBanner
	Radial				= Yes
End

CommandButton Command_ConstructLastAllianceDwarvenGathering
  Command          = FOUNDATION_CONSTRUCT
  Object        		= LastAllianceDwarvenGatheringFoundation
	TextLabel     		= CONTROLBAR:ConstructRohanTent
	ButtonImage   		= uiHelmsDeepTent
	ButtonBorderType    = BUILD
	DescriptLabel       = CONTROLBAR:ToolTipConstructRohanTent
	Radial				= Yes
End

CommandButton Command_ConstructLastAllianceWarTentFoundation
	Command       		= FOUNDATION_CONSTRUCT
	Object        		= LastAllianceWarTentFoundation
	TextLabel     		= CONTROLBAR:ConstructArnorMarketPlace
	ButtonImage   		= BIRivendellLibrary
	ButtonBorderType    = BUILD 
	DescriptLabel       = CONTROLBAR:ToolTipConstructArnorMarketPlace
	Radial				= Yes
End