CommandSet MonumentWindlordCommandSet
	1	= Command_ConstructHighPassLesserEagleHorde
	2	= Command_ConstructHighPassGwaihir 
	3	= Command_ConstructHighPassLandroval 
	4	= Command_ConstructHighPassMeneldor
	5	= Command_PurchaseUpgradeHighPassEaglesBuildingLevel2
  	6	= Command_Sell
End

CommandSet MonumentWindlordCommandSetLevel2
	1	= Command_ConstructHighPassLesserEagleHorde
	2	= Command_ConstructHighPassGwaihir 
	3	= Command_ConstructHighPassLandroval 
	4	= Command_ConstructHighPassMeneldor
	5	= Command_PurchaseUpgradeHighPassEaglesBuildingLevel3
  	6	= Command_Sell
End

CommandSet MonumentWindlordCommandSetLevel3
	1	= Command_ConstructHighPassLesserEagleHorde
	2	= Command_ConstructHighPassGwaihir 
	3	= Command_ConstructHighPassLandroval 
	4	= Command_ConstructHighPassMeneldor
  	6	= Command_Sell
End

CommandSet HPGwaihirCommandSet
	1	= Command_ToggleStance
	2	= Command_GwaihirLeadership
	3   = Command_GwaihirWingBlast
	4	= Command_GwaihirDreadVisage
	13	= Command_AttackMove
	14	= Command_Stop
	16  = Command_SetStanceBattle
	17  = Command_SetStanceAggressive
	18  = Command_SetStanceHoldGround
End

CommandSet HPMeneldorCommandSet
	1	= Command_ToggleStance
	2	= Command_MeneldorFakeButton1
	3   = Command_GwaihirWingBlast
	4	= Command_MeneldorLeadership
	13	= Command_AttackMove
	14	= Command_Stop
	16  = Command_SetStanceBattle
	17  = Command_SetStanceAggressive
	18  = Command_SetStanceHoldGround
End

CommandSet HPLandrovalCommandSet
	1	= Command_ToggleStance
	2	= Command_SpecialAbilityLandrovalBladeMaster
	3   = Command_GwaihirWingBlast
	4	= Command_SpecialAbilityLandrovalScreech
	13	= Command_AttackMove
	14	= Command_Stop
	16  = Command_SetStanceBattle
	17  = Command_SetStanceAggressive
	18  = Command_SetStanceHoldGround
End

CommandSet LesserEagleCommandSet
	1	= Command_ToggleStance
	13	= Command_AttackMove
	14	= Command_Stop
	16  = Command_SetStanceBattle
	17  = Command_SetStanceAggressive
	18  = Command_SetStanceHoldGround
End
CommandSet HighPassEncampmentCommandSet
	1	= Command_ConstructHighPassAmbusherHorde
	2	= Command_ConstructHighPassGlaivemenHorde
	3	= Command_ConstructHighPassRangerHorde
  	7 	= Command_PurchaseUpgradeHighPassEncampmentLevel2
  	6	= Command_Sell
End
CommandSet HighPassEncampmentCommandSetLevel2
	1	= Command_ConstructHighPassAmbusherHorde
	2	= Command_ConstructHighPassGlaivemenHorde
	3	= Command_ConstructHighPassRangerHorde
  	7 	= Command_PurchaseUpgradeHighPassEncampmentLevel3
  	6	= Command_Sell
End
CommandSet HighPassEncampmentCommandSetLevel3
	1	= Command_ConstructHighPassAmbusherHorde
	2	= Command_ConstructHighPassGlaivemenHorde
	3	= Command_ConstructHighPassRangerHorde
  	6	= Command_Sell
End

CommandSet HighPassBeorningCabinCommandSet
	1	= Command_ConstructWoodmenMarksmen
	2	= Command_ConstructDruids
	3	= Command_ConstructBeorning
	5 	= Command_PurchaseUpgradeMirkwoodBeorningCabinLevel2
  	6	= Command_Sell
	;7 = Command_ConstructDruidOak_AI
	;8 = Command_ConstructWoodmenMarksmen_AxesForAI
End
CommandSet HighPassBeorningCabinCommandSetLevel2
	1	= Command_ConstructWoodmenMarksmen
	2	= Command_ConstructDruids
	3	= Command_ConstructBeorning
	5 	= Command_PurchaseUpgradeMirkwoodBeorningCabinLevel3
  	6	= Command_Sell
	;7 = Command_ConstructDruidOak_AI
	;8 = Command_ConstructWoodmenMarksmen_AxesForAI
End
CommandSet HighPassBeorningCabinCommandSetLevel3
	1	= Command_ConstructWoodmenMarksmen
	2	= Command_ConstructDruids
	3	= Command_ConstructBeorning
  	6	= Command_Sell
	;7 = Command_ConstructDruidOak_AI
	;8 = Command_ConstructWoodmenMarksmen_AxesForAI
End