;//==============================================================
;//==============================================================
;//=====													=====
;//=====		    #508 - FACTION DU ROYAUME DES FORÊTS	=====
;//=====													=====
;//==============================================================
;//==============================================================

;// ----- #508.3 - POUVOIRS HÉROS D'ERYN LASGALEN -----------------------------------

;////////////////////////
;// MAÎTRE DE LACVILLE //
;////////////////////////

RadiusCursorTemplate		= SCStopRightThereLaketown2
	Texture						= scstoprighttherelaketown2
	Style						= SHADOW_ALPHA_DECAL
	OpacityMin					= 20%
	OpacityMax					= 60%
	OpacityThrobTime			= 1000
	Color						= R:255 G:255 B:255 A:255
	OnlyVisibleToOwningPlayer	= Yes
End



;////////////
;// GALION //
;////////////

RadiusCursorTemplate		= SCDorwinionRed
	Texture						= scdorwinionred
	Style						= SHADOW_ALPHA_DECAL
	OpacityMin					= 20%
	OpacityMax					= 60%
	OpacityThrobTime			= 1000
	Color						= R:255 G:255 B:255 A:255
	OnlyVisibleToOwningPlayer	= Yes
End

RadiusCursorTemplate		= SCRazanPlants
	Texture						= scrazanplants
	Style						= SHADOW_ALPHA_DECAL
	OpacityMin					= 20%
	OpacityMax					= 60%
	OpacityThrobTime			= 1000
	Color						= R:255 G:255 B:255 A:255
	OnlyVisibleToOwningPlayer	= Yes
End

RadiusCursorTemplate		= SCBadBatch
	Texture						= scbadbatch
	Style						= SHADOW_ALPHA_DECAL
	OpacityMin					= 20%
	OpacityMax					= 60%
	OpacityThrobTime			= 1000
	Color						= R:255 G:255 B:255 A:255
	OnlyVisibleToOwningPlayer	= Yes
End



;// ----- #508.6 - POUVOIRS UNITÉS D'ERYN LASGALEN ----------------------------------

;/////////////////////////
;// LE GRAND CERF BLANC //
;/////////////////////////

RadiusCursorTemplate        = SCFeyWisdom
	Texture                     = scfeywisdom
	Style                       = SHADOW_ALPHA_DECAL
	OpacityMin                  = 20%
	OpacityMax                  = 60%
	OpacityThrobTime            = 1000
	Color                       = R:255 G:255 B:255 A:255
	OnlyVisibleToOwningPlayer   = Yes
End



;// ----- #508.8 - POUVOIRS D'ERYN LASGALEN -----------------------------------------	

RadiusCursorTemplate        = scwitheringwinter
	Texture                     = scwitheringwinter
	Style                       = SHADOW_ALPHA_DECAL
	OpacityMin                  = 20%
	OpacityMax                  = 60%
	OpacityThrobTime            = 1000
	Color                       = R:255 G:255 B:255 A:255
	OnlyVisibleToOwningPlayer   = Yes
End	

;/////

RadiusCursorTemplate		= SCHornGate
	Texture						= schorngate
	Style						= SHADOW_ALPHA_DECAL
	OpacityMin					= 20%
	OpacityMax					= 60%
	OpacityThrobTime			= 1000
	Color						= R:255 G:255 B:255 A:255
	OnlyVisibleToOwningPlayer	= Yes
End

;/////

RadiusCursorTemplate		= SCElvenkingFeast
	Texture						= screclamation
	Style						= SHADOW_ALPHA_DECAL
	OpacityMin					= 20%
	OpacityMax					= 60%
	OpacityThrobTime			= 1000
	Color						= R:255 G:255 B:255 A:255
	OnlyVisibleToOwningPlayer	= Yes
End

RadiusCursorTemplate		= SCFeast
	Texture						= scfeast
	Style						= SHADOW_ALPHA_DECAL
	OpacityMin					= 20%
	OpacityMax					= 60%
	OpacityThrobTime			= 1000
	Color						= R:255 G:255 B:255 A:255
	OnlyVisibleToOwningPlayer	= Yes
End

RadiusCursorTemplate		= SCWaystoneTeleport
	Texture						= scroadteleport
	Style						= SHADOW_ALPHA_DECAL
	OpacityMin					= 20%
	OpacityMax					= 60%
	OpacityThrobTime			= 1000
	Color						= R:255 G:255 B:255 A:255
	OnlyVisibleToOwningPlayer	= Yes
End

;/////

RadiusCursorTemplate		= SCElvenkingRoad
	Texture						= scelvenkingsroad
	Style						= SHADOW_ALPHA_DECAL
	OpacityMin					= 20%
	OpacityMax					= 60%
	OpacityThrobTime			= 1000
	Color						= R:255 G:255 B:255 A:255
	OnlyVisibleToOwningPlayer	= Yes
End

;/////

RadiusCursorTemplate		= SCMirkwoodGulhir
	Texture						= screvakall
	Style						= SHADOW_ALPHA_DECAL
	OpacityMin					= 20%
	OpacityMax					= 60%
	OpacityThrobTime			= 1000
	Color						= R:255 G:255 B:255 A:255
	OnlyVisibleToOwningPlayer	= Yes
End

;/////

RadiusCursorTemplate		= SCSacredOak
	Texture						= scsacredoak
	Style						= SHADOW_ALPHA_DECAL
	OpacityMin					= 20%
	OpacityMax					= 60%
	OpacityThrobTime			= 1000
	Color						= R:255 G:255 B:255 A:255
	OnlyVisibleToOwningPlayer	= Yes
End

;/////

RadiusCursorTemplate        = SCGreatHunt
	Texture                     = scgreathunt
	Style                       = SHADOW_ALPHA_DECAL
	OpacityMin                  = 20%
	OpacityMax                  = 60%
	OpacityThrobTime            = 1000
	Color                       = R:255 G:255 B:255 A:255
	OnlyVisibleToOwningPlayer   = Yes
End

;/////

RadiusCursorTemplate        = SCWhiteStag
	Texture                     = scwhitestag
	Style                       = SHADOW_ALPHA_DECAL
	OpacityMin                  = 20%
	OpacityMax                  = 60%
	OpacityThrobTime            = 1000
	Color                       = R:255 G:255 B:255 A:255
	OnlyVisibleToOwningPlayer   = Yes
End
















































;/////

RadiusCursorTemplate		= SCHiddenSentry
	Texture						= schiddensentry
	Style						= SHADOW_ALPHA_DECAL
	OpacityMin					= 20%
	OpacityMax					= 60%
	OpacityThrobTime			= 1000
	Color						= R:255 G:255 B:255 A:255
	OnlyVisibleToOwningPlayer	= Yes
End

RadiusCursorTemplate		= SCHuntingSnare
	Texture						= scsnare
	Style						= SHADOW_ALPHA_DECAL
	OpacityMin					= 20%
	OpacityMax					= 60%
	OpacityThrobTime			= 1000
	Color						= R:255 G:255 B:255 A:255
	OnlyVisibleToOwningPlayer	= Yes
End

;/////

RadiusCursorTemplate		= SCGreenwoodSindarinArmor
	Texture						= scarmorofdoriath
	Style						= SHADOW_ALPHA_DECAL
	OpacityMin					= 20%
	OpacityMax					= 60%
	OpacityThrobTime			= 1000
	Color						= R:255 G:255 B:255 A:255
	OnlyVisibleToOwningPlayer	= Yes
End




























































































RadiusCursorTemplate		= SCElvesAwokeThem
	Texture						= scelvesawokethem
	Style						= SHADOW_ALPHA_DECAL
	OpacityMin					= 20%
	OpacityMax					= 60%
	OpacityThrobTime			= 1000
	Color						= R:255 G:255 B:255 A:255
	OnlyVisibleToOwningPlayer	= Yes
End

	RadiusCursorTemplate = GandalfSummon
		Texture        = scgandalfsummon
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
  End
  RadiusCursorTemplate = OldManWillowSummon
		Texture        = scoldmanwillow
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
  End   
	RadiusCursorTemplate = ArnorRuinRadiusCursor
		Texture        = SCArnorRuin
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
  End
  RadiusCursorTemplate = BamfurlongRadiusCursor
		Texture        = SCBamfurlong
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
  End  
  RadiusCursorTemplate = HallOfFireRadiusCursor
		Texture        = SCHOFSummon
	    Style          = SHADOW_ALPHA_DECAL
	    OpacityMin     = 20%
	    OpacityMax     = 60%
	    OpacityThrobTime  = 1000
	    Color          = R:255 G:255 B:255 A:255
	    OnlyVisibleToOwningPlayer = Yes
  End
  RadiusCursorTemplate = SongOfSpringRadiusCursor
		Texture        = scspringsong
	    Style          = SHADOW_ALPHA_DECAL
	    OpacityMin     = 20%
	    OpacityMax     = 60%
	    OpacityThrobTime  = 1000
	    Color          = R:255 G:255 B:255 A:255
	    OnlyVisibleToOwningPlayer = Yes
  End
  RadiusCursorTemplate = ArwenTinuvielRadiusCursor
		Texture        = SCTinuviel
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
  End    
  RadiusCursorTemplate = ArwenEvenstarRadiusCursor
		Texture        = scevenstar
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
  End   
  RadiusCursorTemplate = GlorfindelAmanRadiusCursor
		Texture        = sclightaman
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
  End  
  RadiusCursorTemplate = ElrondHomelyHouseRadiusCursor
		Texture        = schomelyhouse
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
  End
  RadiusCursorTemplate = ElrondRingOfAirRadiusCursor
		Texture        = scvilya
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
  End 
  RadiusCursorTemplate = AkallabethCursor
		Texture        = screvakall
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
  End
  RadiusCursorTemplate = TangadoHaidCursor
		Texture        = sctangadohaid
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
  End    
    RadiusCursorTemplate = SCRivendellHeal
		Texture        = scrivendellheal
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
  End    
	RadiusCursorTemplate = SCAncientCraftsman
		Texture        = scancientcraftsman
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCCallofBelegaer
		Texture        = sccallofbelegaer
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
;-----------------------------------------------------------------------------------------------
;-----------------------------Erebor----------------------------------------------
;-----------------------------------------------------------------------------------------------	
	RadiusCursorTemplate = IronHillsSummon
		Texture        = scIHsummon
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	
	RadiusCursorTemplate = KhazadDumSummon
		Texture        = scmoriasummon
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	
	RadiusCursorTemplate = ThorinProphecy
		Texture        = scprophecy
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	
	RadiusCursorTemplate = WyrmSlayersRunes
		Texture        = scrunesoffire
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = EreborHorn
		Texture        = scereborhorn
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = BardRabbleRouser
		Texture        = scrabblerouser
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = ThrorsHoard
		Texture        = scthrorshoard
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = EreborUnkindness
		Texture        = scunkindness
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = EreborFullyArmedandFilthy
		Texture        = scfilthy
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = MasterSpyCursor
		Texture        = scmasterspy
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SecretWaysGloinCursor
		Texture        = scsecretways
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCBardingSummon
		Texture        = scbardingsummon
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCRedAxe
		Texture        = scredaxe
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCVow
		Texture        = sccvow
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCStoneHewer
		Texture        = scstonehewer
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCMarkThrush
		Texture        = scmarkthrush
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCRangerCraft
		Texture        = scrangercraft
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCMightyVeteran
		Texture        = scmightyveteran
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCWisdomYore
		Texture        = scwisdomofyore
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCStopRightThereLaketown
		Texture        = scstoprighttherelaketown
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCThorinResentment
		Texture        = scthorinresentment
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCFuriousBlow
		Texture        = scfuriousblow
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCHighSpirits
		Texture        = schighspirits
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = DurinsSummonCursor
		Texture        = scdurinsummon
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End	
	RadiusCursorTemplate = DurinsCustodiansCursor
		Texture        = scdurinscustodians
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = HammerAuleCursor
		Texture        = schammeraule
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = LitanyoftheSevenCursor
		Texture        = sclitanyoftheseven
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
;-----------------------------------------------------------------------------------------------
;-----------------------------Lorien----------------------------------------------
;-----------------------------------------------------------------------------------------------	
	RadiusCursorTemplate = RingOfAdamant
		Texture        = scringofadamant
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = MirkwoodSummon
		Texture        = scmirksummon
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = GoNoFurther
		Texture        = scnofurther
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = NandorTreasure
		Texture        = scossiriand
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = MallornGrove
		Texture        = scmallorngrove
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = ElvenHorn
		Texture        = sclorienhorn
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = RadagastSummon
		Texture        = scradagastsummon
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = CelebornWisdom
		Texture        = scwisebeyond
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCForthAxeElves
		Texture        = scforthaxealves
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCBorderPatrol
		Texture        = scborderpatrol
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCBorderGuardJudgement
		Texture        = scborderguardjudgement
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCFeignedVoices
		Texture        = scfeignedvoices
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCGleamofNenya
		Texture        = scgleamofnenya
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCArmorofDoriath
		Texture        = scarmorofdoriath
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCLongMemory
		Texture        = sclongmemory
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCWatersofNimrodel   
		Texture        = scwatersofnimrodel
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCWatersofNimrodelRebuild   
		Texture        = scwatersofnimrodel
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCMallornSeeds
		Texture        = scmallornseeds
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
;-----------------------------------------------------------------------------------------------
;-----------------------------Gondor----------------------------------------------
;-----------------------------------------------------------------------------------------------
	RadiusCursorTemplate = DenethorFavor
		Texture        = scstewardfavor
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = DenethorHighAuthority
		Texture        = schighauthority
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End	
	RadiusCursorTemplate = GondorWhiteTree
		Texture        = scwhitetree
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = GondorLoneTower
		Texture        = scgondortower
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = IthilienGardenRadiusCursor
		Texture        = scithiliengarden
	    Style          = SHADOW_ALPHA_DECAL
	    OpacityMin     = 20%
	    OpacityMax     = 60%
	    OpacityThrobTime  = 1000
	    Color          = R:255 G:255 B:255 A:255
	    OnlyVisibleToOwningPlayer = Yes
	End 
	RadiusCursorTemplate = PrepareForBattleCursor
		Texture        = scprepareforbattle
	    Style          = SHADOW_ALPHA_DECAL
	    OpacityMin     = 20%
	    OpacityMax     = 60%
	    OpacityThrobTime  = 1000
	    Color          = R:255 G:255 B:255 A:255
	    OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = NumenorEngineeringCursor
		Texture        = scnumengi
	    Style          = SHADOW_ALPHA_DECAL
	    OpacityMin     = 20%
	    OpacityMax     = 60%
	    OpacityThrobTime  = 1000
	    Color          = R:255 G:255 B:255 A:255
	    OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = MordorChallengeCursor
		Texture        = scmordorchallenge
	    Style          = SHADOW_ALPHA_DECAL
	    OpacityMin     = 20%
	    OpacityMax     = 60%
	    OpacityThrobTime  = 1000
	    Color          = R:255 G:255 B:255 A:255
	    OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = CaptainHornCursor
		Texture        = sccapthorn
	    Style          = SHADOW_ALPHA_DECAL
	    OpacityMin     = 20%
	    OpacityMax     = 60%
	    OpacityThrobTime  = 1000
	    Color          = R:255 G:255 B:255 A:255
	    OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = LandsKeptSafeCursor
		Texture        = sclandskeptsafe
	    Style          = SHADOW_ALPHA_DECAL
	    OpacityMin     = 20%
	    OpacityMax     = 60%
	    OpacityThrobTime  = 1000
	    Color          = R:255 G:255 B:255 A:255
	    OnlyVisibleToOwningPlayer = Yes
	End	
	RadiusCursorTemplate = SCBoromirWarcry
		Texture        = scBoromir_WarCry
	    Style          = SHADOW_ALPHA_DECAL
	    OpacityMin     = 20%
	    OpacityMax     = 60%
	    OpacityThrobTime  = 1000
	    Color          = R:255 G:255 B:255 A:255
	    OnlyVisibleToOwningPlayer = Yes
	End	
	RadiusCursorTemplate = SCFaramirQuality
		Texture        = scFaramir_Quality
	    Style          = SHADOW_ALPHA_DECAL
	    OpacityMin     = 20%
	    OpacityMax     = 60%
	    OpacityThrobTime  = 1000
	    Color          = R:255 G:255 B:255 A:255
	    OnlyVisibleToOwningPlayer = Yes
	End	
	RadiusCursorTemplate = SCElessarSummon
		Texture        = scelessarsummon
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End	
;-----------------------------------------------------------------------------------------------
;-----------------------------Rohan----------------------------------------------
;-----------------------------------------------------------------------------------------------	
	RadiusCursorTemplate = OathOfCirionRadiusCursor
		Texture        = SCOathOfCirion
	    Style          = SHADOW_ALPHA_DECAL
	    OpacityMin     = 20%
	    OpacityMax     = 60%
	    OpacityThrobTime  = 1000
	    Color          = R:255 G:255 B:255 A:255
	    OnlyVisibleToOwningPlayer = Yes
  End
  RadiusCursorTemplate = EverholtBoarRadiusCursor
		Texture        = SCBoarSummon
	    Style          = SHADOW_ALPHA_DECAL
	    OpacityMin     = 20%
	    OpacityMax     = 60%
	    OpacityThrobTime  = 1000
	   Color          = R:255 G:255 B:255 A:255
	    OnlyVisibleToOwningPlayer = Yes
  End  
  RadiusCursorTemplate = StormcrowRadiusCursor
		Texture        = SCStormcrow
	    Style          = SHADOW_ALPHA_DECAL
	    OpacityMin     = 20%
	    OpacityMax     = 60%
	    OpacityThrobTime  = 1000
	    Color          = R:255 G:255 B:255 A:255
	    OnlyVisibleToOwningPlayer = Yes
  End
  RadiusCursorTemplate = WestfoldHornRadiusCursor
		Texture        = scwestfoldhorn
	    Style          = SHADOW_ALPHA_DECAL
	    OpacityMin     = 20%
	    OpacityMax     = 60%
	    OpacityThrobTime  = 1000
	    Color          = R:255 G:255 B:255 A:255
	    OnlyVisibleToOwningPlayer = Yes
  End
  RadiusCursorTemplate = MarkHelmRadiusCursor
		Texture        = scmarkhelm
	    Style          = SHADOW_ALPHA_DECAL
	    OpacityMin     = 20%
	    OpacityMax     = 60%
	    OpacityThrobTime  = 1000
	    Color          = R:255 G:255 B:255 A:255
	    OnlyVisibleToOwningPlayer = Yes
  End
  RadiusCursorTemplate = MarkFrecaRadiusCursor
		Texture        = scmarkfreca
	    Style          = SHADOW_ALPHA_DECAL
	    OpacityMin     = 20%
	    OpacityMax     = 60%
	    OpacityThrobTime  = 1000
	    Color          = R:255 G:255 B:255 A:255
	    OnlyVisibleToOwningPlayer = Yes
  End
  RadiusCursorTemplate = PukelSummonRadiusCursor
		Texture        = scpukelsummon
	    Style          = SHADOW_ALPHA_DECAL
	    OpacityMin     = 20%
	    OpacityMax     = 60%
	    OpacityThrobTime  = 1000
	    Color          = R:255 G:255 B:255 A:255
	    OnlyVisibleToOwningPlayer = Yes
  End   
  RadiusCursorTemplate = PukelFaithfulRadiusCursor
		Texture        = scpukelfaithful
	    Style          = SHADOW_ALPHA_DECAL
	    OpacityMin     = 20%
	    OpacityMax     = 60%
	    OpacityThrobTime  = 1000
	    Color          = R:255 G:255 B:255 A:255
	    OnlyVisibleToOwningPlayer = Yes
  End 
  RadiusCursorTemplate = PukelPathsRadiusCursor
		Texture        = scpukelpaths
	    Style          = SHADOW_ALPHA_DECAL
	    OpacityMin     = 20%
	    OpacityMax     = 60%
	    OpacityThrobTime  = 1000
	    Color          = R:255 G:255 B:255 A:255
	    OnlyVisibleToOwningPlayer = Yes
  End 
  RadiusCursorTemplate = PukelStoneSkinRadiusCursor
		Texture        = scpukelskin
	    Style          = SHADOW_ALPHA_DECAL
	    OpacityMin     = 20%
	    OpacityMax     = 60%
	    OpacityThrobTime  = 1000
	    Color          = R:255 G:255 B:255 A:255
	    OnlyVisibleToOwningPlayer = Yes
  End   
   RadiusCursorTemplate = SurrenderArmsRadiusCursor
 	Texture        = scsurrenderarms
    	Style          = SHADOW_ALPHA_DECAL
	OpacityMin     = 20%
    	OpacityMax     = 60%
    	OpacityThrobTime  = 1000
    	Color          = R:255 G:255 B:255 A:255
    	OnlyVisibleToOwningPlayer = Yes
  End  
 	RadiusCursorTemplate = SCMusterRohirrim
		Texture        = scmusterrohirrim
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
;-----------------------------------------------------------------------------------------------
;-----------------------------Misty Mountains----------------------------------------------
;-----------------------------------------------------------------------------------------------
	RadiusCursorTemplate = DrumsInTheDeep
		Texture        = scdrumsdeep
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = UrshakIntimidation
		Texture        = scintimidation
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = FireDrakeStrikeRadiusCursor
		Texture        = SCCDragonStrike
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1500
		Color          = R:255 G:255 B:255 A:128
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = AngmarCitadelRadiusCursor
		Texture        = scangmarruin
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1500
		Color          = R:255 G:255 B:255 A:128
		OnlyVisibleToOwningPlayer = Yes
	End	
   RadiusCursorTemplate = BlackPitRadiusCursor
 	Texture        = scblackpit
    	Style          = SHADOW_ALPHA_DECAL
	OpacityMin     = 20%
    	OpacityMax     = 60%
    	OpacityThrobTime  = 1000
    	Color          = R:255 G:255 B:255 A:255
    	OnlyVisibleToOwningPlayer = Yes
  End
  RadiusCursorTemplate = WyrmSummonRadiusCursor
	Texture        = SCCCallOfTheDeep
    Style          = SHADOW_ALPHA_DECAL
    OpacityMin     = 20%
    OpacityMax     = 60%
    OpacityThrobTime  = 1000
    Color          = R:255 G:255 B:255 A:255
    OnlyVisibleToOwningPlayer = Yes
  End  
  RadiusCursorTemplate = SCBolgSummon
		Texture        = scbolgsummon
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
End
RadiusCursorTemplate = SCFrozenWasteNew
		Texture        = scfrozenwastenew
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
End
RadiusCursorTemplate = SCTrollishStew
		Texture        = sctrollishstew
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
End
RadiusCursorTemplate = SCTheyAreComing
		Texture        = sctheyarecoming
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
End
RadiusCursorTemplate = SCScorchedEarth
		Texture        = scscorchedearth
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
End
	RadiusCursorTemplate = SCGreatGoblinFavor
		Texture        = scgreatgoblinfavor
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
;-----------------------------------------------------------------------------------------------
;-----------------------------Mordor----------------------------------------------
;-----------------------------------------------------------------------------------------------
	RadiusCursorTemplate = WitchKingsHour
		Texture        = scmyhour
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = MoSBaradDur
		Texture        = scmouthbarad
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = MoSSorcery
		Texture        = scmouthsorcery
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = MoSCursed
		Texture        = scmouthcursed
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = MordorEyeSymbol
		Texture        = scmordoreye
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End	
	RadiusCursorTemplate = scmordortrackers
		Texture        = scmordortrackers
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End		
	RadiusCursorTemplate = SCFellWard
		Texture        = scfellward
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End		
;-----------------------------------------------------------------------------------------------
;-----------------------------Isengard----------------------------------------------
;-----------------------------------------------------------------------------------------------
	RadiusCursorTemplate = IsenWhiteHand
		Texture        = scwhitehand
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
		RadiusCursorTemplate = SCRuinousWrath
		Texture        = scruinouswrath
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCSendintheWargs
		Texture        = scsendinthewargs
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCBuildMeAnArmy
		Texture        = scbuildmeanarmy
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
		RadiusCursorTemplate = SCSarumanFlood
		Texture        = scsarumanflood
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
;-----------------------------------------------------------------------------------------------
;-----------------------------Guldur----------------------------------------------
;-----------------------------------------------------------------------------------------------
	RadiusCursorTemplate = SCGuldurEnsnare
		Texture        = scensnare
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCGuldurCarnage
		Texture        = sccarnage
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCGuldurFollowLights
		Texture        = scfollowlights
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End	
	RadiusCursorTemplate = SCGuldurChill
		Texture        = scgravechill
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCGuldurWither
		Texture        = scwither
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCGuldurGift
		Texture        = scnecrogift
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCGuldurForestFear
		Texture        = scforestfear
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End	
	RadiusCursorTemplate = SCGuldurBlackWarg
		Texture        = scblackwargs
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCGuldurHysteria
		Texture        = schysteria
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End		
	RadiusCursorTemplate = SCGuldurConcealment
		Texture        = scconcealment
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End	
	RadiusCursorTemplate = SCGuldurGwanthaur
		Texture        = scgwanthaur
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End		
	RadiusCursorTemplate = SCGuldurDeadTroll
		Texture        = scdeadtroll
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End			
	RadiusCursorTemplate = GuldurEncasingWebs
		Texture        = scencasingwebs
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = GuldurWebOfLies
		Texture        = scweboflies
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = GuldurDeepRot
		Texture        = scdeeprot
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End	
	RadiusCursorTemplate = GuldurWitheringTouch
		Texture        = scwitheringtouch
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = GuldurToxicBile
		Texture        = scbile
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
;		Color          = R:47 G:144 B:111 A:255
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = GuldurRestlessBones
		Texture        = sccrestlessbones
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = GuldurGwanthaurReclamation
		Texture        = screclamation
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = GuldurGwanthaurExpulsion
		Texture        = scexpulsion
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = GuldurGwanthaurSoulTrap
		Texture        = scsoultrap
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = CargastSpellsBarrowCursor
		Texture        = scspellbarrows
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End	
	RadiusCursorTemplate = KrimpulDungeonMasterCursor
		Texture        = scdungeonmaster
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = GuldurParasiticEmbraceCursor
		Texture        = scpembrace
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End		
	RadiusCursorTemplate = GuldurDarkMemoriesCursor
		Texture        = scdarkmemories
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End	
	RadiusCursorTemplate = SCElvenkingPatience
		Texture        = scelvenkingspatience
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCSpearsofFramsburg
		Texture        = scspearsframsburg
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCNoneMayEnter
		Texture        = scelvenkingsdecree
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCLoveSilverJewels
		Texture        = scsilverjewels
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End	
	RadiusCursorTemplate = SCSoundtheAlarm
		Texture        = scsoundalarm
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCOrcWarVeteran
		Texture        = scorcwarveteran
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCEyesAndEars
		Texture        = sceyesandears
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCPrinceWoodland
		Texture        = scprinceofwoodlandrealm
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	 RadiusCursorTemplate = StopRightThereCursor
 	Texture        = scstoprightthere
    	Style          = SHADOW_ALPHA_DECAL
	OpacityMin     = 20%
    	OpacityMax     = 60%
    	OpacityThrobTime  = 1000
    	Color          = R:255 G:255 B:255 A:255
    	OnlyVisibleToOwningPlayer = Yes
  End  
	RadiusCursorTemplate = SCWardingStones
		Texture        = scstone1
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCBlessingAldaron
		Texture        = scblessingaldaron
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
    RadiusCursorTemplate = SCPrisonGuardStop
		Texture        = scprisonguardstop
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
 ;-----------------------------------------------------------------------------------------------
;-----------------------------Haradwaith----------------------------------------------
;-----------------------------------------------------------------------------------------------
	RadiusCursorTemplate = SCForthMenofDarkness
		Texture        = scforthmenofdarkness
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCKhandishCharioteers
		Texture        = sckhandishcharioteers
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCDrySpell
		Texture        = scdryspell
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCCurseWindDemon
		Texture        = scwinddemon
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCCleansingWaters ;SCOasis
		Texture        = scoasis
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCPillarFlame
		Texture        = scpillarflame
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCTakeAllYouCan
		Texture        = sctakeallyoucan
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCGiveNothingBack
		Texture        = scgivenothingback
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCAicanaroc
		Texture        = scaicanaroc
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCBurningSands
		Texture        = scburningsands
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCColdJudgement
		Texture        = sccoldjudgement
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCBreakerofStones
		Texture        = scbreakerofstones
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCCultistDesolation
		Texture        = sccultistdesolation
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCCultistMorgothPillar
		Texture        = sccultistfist
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCCulsitsHeartsofFire
		Texture        = sccultistheartsoffire
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCCultistZealotry
		Texture        = sccultistzealotry
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCDarkSacrifice
		Texture        = scdarksacrifice
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCFellWhispers
		Texture        = scfellwhispers
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCHornofKarna
		Texture        = schornofkarna
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCHornofKarnaSound
		Texture        = schornofkarnasound
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCHornoftheSerpentLord
		Texture        = schornoftheserpentlord
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCSacrificialRites
		Texture        = scsacrificialrites
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCSouthronConquest
		Texture        = scsouthronconquest
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCTribesofHarad
		Texture        = sctribesofharad
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCTametheBeast
		Texture        = sctamethebeast
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCOasis ;SCCleansingWaters
		Texture        = sccleansingwaters
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCSummonOliphaunt
		Texture        = scsummonoliphaunt
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCDarkSubjugation
		Texture        = scdarksubjugation
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCIntimidationGoldenKing
		Texture        = scintimidationgoldenking
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCSyarRhulKingsFavor
		Texture        = scsyarrhulkingsfavor
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCBeastMasterWargSummon
		Texture        = scbeastmasterwargsummon
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCKaraddLeap
		Texture        = sckaraddleap
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCHaradSumTower
		Texture        = scharadsumtower
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCBlessingBelegur
		Texture        = scblessingbelegur
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCSmokeBomb
		Texture        = scsmokebomb
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End	
  ;-----------------------------------------------------------------------------------------------
  ;-----------------------------Arthedain----------------------------------------------
  ;-----------------------------------------------------------------------------------------------
	RadiusCursorTemplate = SCLachoCalad
		Texture        = sclachocalad
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End	
	RadiusCursorTemplate = SCRoyalGarden
		Texture        = scroyalgarden
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End			
	RadiusCursorTemplate = scarnortower
		Texture        = scarnortower
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End	
	RadiusCursorTemplate = scarnorhobbits
		Texture        = scarnorhobbits
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End		
	RadiusCursorTemplate = scarnorarmaments
		Texture        = scarnorarmaments
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End		
	RadiusCursorTemplate = scarnorstarearendil
		Texture        = scarnorstarearendil
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End		
	RadiusCursorTemplate = scarnordesperateassault
		Texture        = scarnordesperateassault
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End		
	RadiusCursorTemplate = scarnorforesight
		Texture        = scarnorforesight
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End			
	RadiusCursorTemplate = scarnorpreparations
		Texture        = scarnorpreparations
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End			
	RadiusCursorTemplate = scarnorwisecounsel
		Texture        = scarnorwisecounsel
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End		
	RadiusCursorTemplate = scarnorcpttactical
		Texture        = scarnorcpttactical
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End			
	RadiusCursorTemplate = scarnorcptcallarms
		Texture        = scarnorcptcallarms
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End	
	RadiusCursorTemplate = scarnorkingsguardvigilant
		Texture        = scarnorkingsguardvigilant
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End		
;============ END OF ADVENTURE ARTHEDAIN DECALS ===================
;============ HARADWAITH DECALS ===================
	RadiusCursorTemplate = scdisdain
		Texture        = scdisdain
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End	
	RadiusCursorTemplate = scqueensescort
		Texture        = scqueensescort
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
;============ END OF HARADWAITH DECALS ===================
;============ ADVENTURE BATTLE OF THE FIVE ARMIES DECALS ===================
	RadiusCursorTemplate = scbeornsummon
		Texture        = scbeornsummon
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End			
;============ RHÛN DECALS ===================
	RadiusCursorTemplate = scrhunwarlordsdemans
		Texture        = scrhunwarlordsdemans
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End		
	RadiusCursorTemplate = scrhuncurseblackdragon
		Texture        = scrhuncurseblackdragon
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End		
	RadiusCursorTemplate = scrhunmanifestedterror
		Texture        = scrhunmanifestedterror
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End		
	RadiusCursorTemplate = scrhunfeastofsouls
		Texture        = scrhunfeastofsouls
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End		
	RadiusCursorTemplate = scrhunwhispersvoid
		Texture        = scrhunwhispersvoid
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End		
	RadiusCursorTemplate = scrhunspbannerofthekhan
		Texture        = scrhunspbannerofthekhan
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End		
	RadiusCursorTemplate = scrhunspreversaloffortune
		Texture        = scrhunspreversaloffortune
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End		
	RadiusCursorTemplate = scrhunsprecklessfervour
		Texture        = scrhunsprecklessfervour
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End		
	RadiusCursorTemplate = scrhunsphorn
		Texture        = scrhunsphorn
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End		
	RadiusCursorTemplate = scrhunspdarkdivination
		Texture        = scrhunspdarkdivination
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End		
	RadiusCursorTemplate = scrhunspgoldendrakesfavour
		Texture        = scrhunspgoldendrakesfavour
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End		
	RadiusCursorTemplate = scrhundkwyrmswisdom
		Texture        = scrhundkwyrmswisdom
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End	
;============ END OF RHÛN DECALS ===================
;============ ADVENTURE ITHILIEN DECALS ===================
	RadiusCursorTemplate = scithilienwatchfuleyes
		Texture        = scithilienwatchfuleyes
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End		
;============ END OF ADVENTURE ITHILIEN DECALS ===================
;============ ADVENTURE ANGMAR DECALS ===================
	RadiusCursorTemplate = scangmarmammoth
		Texture        = scangmarmammoth
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End		
	RadiusCursorTemplate = scdeepfrost
		Texture        = scdeepfrost
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End		
	RadiusCursorTemplate = sclunge
		Texture        = sclunge
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End		
	RadiusCursorTemplate = scthreateninggaze
		Texture        = scthreateninggaze
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End	
;============ END OF ADVENTURE ANGMAR DECALS ===================
;============ ADVENTURE DORWINION DECALS ===================
	RadiusCursorTemplate = scdorwinionherohorn
		Texture        = scdorwinionherohorn
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End	
	RadiusCursorTemplate = scspearoforome
		Texture        = scspearoforome
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End		
	RadiusCursorTemplate = schindrancetoevil
		Texture        = schindrancetoevil
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End		
;============ END OF ADVENTURE DORWINION DECALS ===================
;============ ADVENTURE SHIRE DECALS ===================
	RadiusCursorTemplate = scgreatsmial
		Texture        = scgreatsmial
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = scfearfirefoes
		Texture        = scfearfirefoes
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = schorncall
		Texture        = schorncall
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = scoldtoby
		Texture        = scoldtoby
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = scstouthearted
		Texture        = scstouthearted
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End		
;============ END OF ADVENTURE SHIRE DECALS ===================
;============ ADVENTURE DOL AMROTH DECALS ===================	
	RadiusCursorTemplate = scsummonfishingboat
		Texture        = scsummonfishingboat
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End		
;============ END OF ADVENTURE DOL AMROTH DECALS ===================
;============ ADVENTURE DUNLAND DECALS ===================		
	RadiusCursorTemplate = SCHrafvit
		Texture        = schrafvit
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End	
;============ END OF ADVENTURE DUNLAND DECALS ===================
;============ CAMPAIGN DECALS ===================	
	RadiusCursorTemplate = SCKingsfoil
		Texture        = sckingsfoil
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCHiddenCache
		Texture        = schiddencache
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCTHisDayWeFight
		Texture        = scthisdaywefight
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCMadrilTrap
		Texture        = scmadriltrap
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCLembas
		Texture        = sclembas
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCWisdomoftheEldar
		Texture        = scwisdomeldar
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = SCLothrandirSubtleWays
		Texture        = scsubtleways
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = scsaurondominion
		Texture        = scsaurondominion
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = scsauronfavour
		Texture        = scsauronfavour
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = scgildorsummon
		Texture        = scgildorsummon
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = scferensummon
		Texture        = scferensummon
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End
	RadiusCursorTemplate = sckrimpulsummon
		Texture        = sckrimpulsummon
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End	
	RadiusCursorTemplate = sceomerrestoration
		Texture        = sceomerrestoration
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End		
	RadiusCursorTemplate = scrumourmonger
		Texture        = scrumourmonger
		Style          = SHADOW_ALPHA_DECAL
		OpacityMin     = 20%
		OpacityMax     = 60%
		OpacityThrobTime  = 1000
		Color          = R:255 G:255 B:255 A:255
		OnlyVisibleToOwningPlayer = Yes
	End			