ArmyMemberDefinition WightLord_Member
  Unit			= WightLord ;big evil single unit
  ;PercentageOfArmyPhase1	= 35.0 ;;,;; 15.0
  PercentageOfArmyPhase1	= 10.0 ;;,;; 15.0
  ;PercentageOfArmyPhase2	= 20.0 ;;,;; 20.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 20.0
  ;PercentageOfArmyPhase3	= 0.0 ;;,;; 10.0 ;;,;; 15.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 10.0 ;;,;; 15.0
End

ArmyMemberDefinition EasterlingSwordsmenHorde_Member
  Unit			= MordorEasterlingSwordsmanHorde ;elite swordsmen
  ;PercentageOfArmyPhase1	= 35.0 ;;,;; 15.0
  PercentageOfArmyPhase1	= 10.0 ;;,;; 15.0
  ;PercentageOfArmyPhase2	= 20.0 ;;,;; 20.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 20.0
  ;PercentageOfArmyPhase3	= 0.0 ;;,;; 10.0 ;;,;; 15.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 10.0 ;;,;; 15.0
End

ArmyMemberDefinition RuffianBows_Member
  Unit			= RuffianBowsHorde ;basic bowmen
  ;PercentageOfArmyPhase1	= 35.0 ;;,;; 15.0
  PercentageOfArmyPhase1	= 10.0 ;;,;; 15.0
  ;PercentageOfArmyPhase2	= 20.0 ;;,;; 20.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 20.0
  ;PercentageOfArmyPhase3	= 0.0 ;;,;; 10.0 ;;,;; 15.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 10.0 ;;,;; 15.0
End

ArmyMemberDefinition HarondorSwordsmen_Member
  Unit			= HarondorSwordsHorde ;Elite swordsmen
  ;PercentageOfArmyPhase1	= 35.0 ;;,;; 15.0
  PercentageOfArmyPhase1	= 10.0 ;;,;; 15.0
  ;PercentageOfArmyPhase2	= 20.0 ;;,;; 20.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 20.0
  ;PercentageOfArmyPhase3	= 0.0 ;;,;; 10.0 ;;,;; 15.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 10.0 ;;,;; 15.0
End

ArmyMemberDefinition MahudSpearmen_Member
  Unit			= MahudSpearsHorde ;Strong basic Spearmen
  ;PercentageOfArmyPhase1	= 35.0 ;;,;; 15.0
  PercentageOfArmyPhase1	= 10.0 ;;,;; 15.0
  ;PercentageOfArmyPhase2	= 20.0 ;;,;; 20.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 20.0
  ;PercentageOfArmyPhase3	= 0.0 ;;,;; 10.0 ;;,;; 15.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 10.0 ;;,;; 15.0
End

ArmyMemberDefinition RuffianHorde_Member
  Unit			= RuffianHorde ;Basic Swordsmen
  ;PercentageOfArmyPhase1	= 35.0 ;;,;; 15.0
  PercentageOfArmyPhase1	= 10.0 ;;,;; 15.0
  ;PercentageOfArmyPhase2	= 20.0 ;;,;; 20.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 20.0
  ;PercentageOfArmyPhase3	= 0.0 ;;,;; 10.0 ;;,;; 15.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 10.0 ;;,;; 15.0
End

ArmyMemberDefinition MoriaOrcSpearmen_Member
  Unit			= MoriaSpearmanHorde ;spam spearmen
  ;PercentageOfArmyPhase1	= 35.0 ;;,;; 15.0
  PercentageOfArmyPhase1	= 10.0 ;;,;; 15.0
  ;PercentageOfArmyPhase2	= 20.0 ;;,;; 20.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 20.0
  ;PercentageOfArmyPhase3	= 0.0 ;;,;; 10.0 ;;,;; 15.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 10.0 ;;,;; 15.0
End

ArmyMemberDefinition MorgulSpearmen_Member
  Unit			= MordorMorgulOrcPikeHorde ;elite spearmen
  ;PercentageOfArmyPhase1	= 35.0 ;;,;; 15.0
  PercentageOfArmyPhase1	= 10.0 ;;,;; 15.0
  ;PercentageOfArmyPhase2	= 20.0 ;;,;; 20.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 20.0
  ;PercentageOfArmyPhase3	= 0.0 ;;,;; 10.0 ;;,;; 15.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 10.0 ;;,;; 15.0
End

ArmyMemberDefinition RavagerShieldbearers_Member
  Unit			= RavagerShieldHorde ;tanky elite swordsmen
  ;PercentageOfArmyPhase1	= 35.0 ;;,;; 15.0
  PercentageOfArmyPhase1	= 10.0 ;;,;; 15.0
  ;PercentageOfArmyPhase2	= 20.0 ;;,;; 20.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 20.0
  ;PercentageOfArmyPhase3	= 0.0 ;;,;; 10.0 ;;,;; 15.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 10.0 ;;,;; 15.0
End

ArmyMemberDefinition RhunSerfSpearmen_Member
  Unit			= TribalAuxillaryHorde ;spam spearmen
  ;PercentageOfArmyPhase1	= 35.0 ;;,;; 15.0
  PercentageOfArmyPhase1	= 10.0 ;;,;; 15.0
  ;PercentageOfArmyPhase2	= 20.0 ;;,;; 20.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 20.0
  ;PercentageOfArmyPhase3	= 0.0 ;;,;; 10.0 ;;,;; 15.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 10.0 ;;,;; 15.0
End

ArmyMemberDefinition UrukAxes_Member
  Unit			= IsengardUrukAxesHorde ;anti-spam infantry
  ;PercentageOfArmyPhase1	= 35.0 ;;,;; 15.0
  PercentageOfArmyPhase1	= 10.0 ;;,;; 15.0
  ;PercentageOfArmyPhase2	= 20.0 ;;,;; 20.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 20.0
  ;PercentageOfArmyPhase3	= 0.0 ;;,;; 10.0 ;;,;; 15.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 10.0 ;;,;; 15.0
End

ArmyMemberDefinition DunlendingSpears_Member
  Unit			= DunlandSpearmanHorde ;elite spearmen
  ;PercentageOfArmyPhase1	= 35.0 ;;,;; 15.0
  PercentageOfArmyPhase1	= 10.0 ;;,;; 15.0
  ;PercentageOfArmyPhase2	= 20.0 ;;,;; 20.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 20.0
  ;PercentageOfArmyPhase3	= 0.0 ;;,;; 10.0 ;;,;; 15.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 10.0 ;;,;; 15.0
End

ArmyMemberDefinition LossothArchers_Member
  Unit			= LossothArchersHorde ;specialist archers
  ;PercentageOfArmyPhase1	= 35.0 ;;,;; 15.0
  PercentageOfArmyPhase1	= 10.0 ;;,;; 15.0
  ;PercentageOfArmyPhase2	= 20.0 ;;,;; 20.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 20.0
  ;PercentageOfArmyPhase3	= 0.0 ;;,;; 10.0 ;;,;; 15.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 10.0 ;;,;; 15.0
End
