ArmyMemberDefinition ArthedainSentinel_Member
  Unit			= ArthedainSentinelsHorde ;elite infantry
  ;PercentageOfArmyPhase1	= 35.0 ;;,;; 15.0
  PercentageOfArmyPhase1	= 10.0 ;;,;; 15.0
  ;PercentageOfArmyPhase2	= 20.0 ;;,;; 20.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 20.0
  ;PercentageOfArmyPhase3	= 0.0 ;;,;; 10.0 ;;,;; 15.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 10.0 ;;,;; 15.0
End

ArmyMemberDefinition EreborMiners_Member
  Unit			= ArmedMinerHorde ;basic specialist infantry
  ;PercentageOfArmyPhase1	= 35.0 ;;,;; 15.0
  PercentageOfArmyPhase1	= 10.0 ;;,;; 15.0
  ;PercentageOfArmyPhase2	= 20.0 ;;,;; 20.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 20.0
  ;PercentageOfArmyPhase3	= 0.0 ;;,;; 10.0 ;;,;; 15.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 10.0 ;;,;; 15.0
End

ArmyMemberDefinition HuntersOfCombe_Member
  Unit			= HuntersofCombeHorde ;archers
  ;PercentageOfArmyPhase1	= 35.0 ;;,;; 15.0
  PercentageOfArmyPhase1	= 10.0 ;;,;; 15.0
  ;PercentageOfArmyPhase2	= 20.0 ;;,;; 20.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 20.0
  ;PercentageOfArmyPhase3	= 0.0 ;;,;; 10.0 ;;,;; 15.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 10.0 ;;,;; 15.0
End

ArmyMemberDefinition OsgiliathVets_Member
  Unit			= VeteransofOsgiliathHorde ;elite swordsmen
  ;PercentageOfArmyPhase1	= 35.0 ;;,;; 15.0
  PercentageOfArmyPhase1	= 10.0 ;;,;; 15.0
  ;PercentageOfArmyPhase2	= 20.0 ;;,;; 20.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 20.0
  ;PercentageOfArmyPhase3	= 0.0 ;;,;; 10.0 ;;,;; 15.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 10.0 ;;,;; 15.0
End

ArmyMemberDefinition PelargirExpeditionaryHorde_Member
  Unit			= PelargirExpeditionaryHorde ;Elite swordsmen
  ;PercentageOfArmyPhase1	= 35.0 ;;,;; 15.0
  PercentageOfArmyPhase1	= 10.0 ;;,;; 15.0
  ;PercentageOfArmyPhase2	= 20.0 ;;,;; 20.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 20.0
  ;PercentageOfArmyPhase3	= 0.0 ;;,;; 10.0 ;;,;; 15.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 10.0 ;;,;; 15.0
End

ArmyMemberDefinition WoodySentinels_Member
  Unit			= SentinelofWoodyEndHorde ;archers
  ;PercentageOfArmyPhase1	= 35.0 ;;,;; 15.0
  PercentageOfArmyPhase1	= 10.0 ;;,;; 15.0
  ;PercentageOfArmyPhase2	= 20.0 ;;,;; 20.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 20.0
  ;PercentageOfArmyPhase3	= 0.0 ;;,;; 10.0 ;;,;; 15.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 10.0 ;;,;; 15.0
End

ArmyMemberDefinition DismountedRivendellKnights_Member
  Unit			= NoldorKnightHorde ;elite infantry
  ;PercentageOfArmyPhase1	= 35.0 ;;,;; 15.0
  PercentageOfArmyPhase1	= 10.0 ;;,;; 15.0
  ;PercentageOfArmyPhase2	= 20.0 ;;,;; 20.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 20.0
  ;PercentageOfArmyPhase3	= 0.0 ;;,;; 10.0 ;;,;; 15.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 10.0 ;;,;; 15.0
End

ArmyMemberDefinition IthilienSpearmen_Member
  Unit			= GondorRangerSpearHorde ;elite spearmen
  ;PercentageOfArmyPhase1	= 35.0 ;;,;; 15.0
  PercentageOfArmyPhase1	= 10.0 ;;,;; 15.0
  ;PercentageOfArmyPhase2	= 20.0 ;;,;; 20.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 20.0
  ;PercentageOfArmyPhase3	= 0.0 ;;,;; 10.0 ;;,;; 15.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 10.0 ;;,;; 15.0
End

ArmyMemberDefinition DorwinionLegionaire_Member
  Unit			= DorwinionFighterHorde ;tanky elite spearmen
  ;PercentageOfArmyPhase1	= 35.0 ;;,;; 15.0
  PercentageOfArmyPhase1	= 10.0 ;;,;; 15.0
  ;PercentageOfArmyPhase2	= 20.0 ;;,;; 20.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 20.0
  ;PercentageOfArmyPhase3	= 0.0 ;;,;; 10.0 ;;,;; 15.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 10.0 ;;,;; 15.0
End

ArmyMemberDefinition KinnLaiWarriorHorde_Member
  Unit			= KinnlaiWarriorHorde ;basic spearmen
  ;PercentageOfArmyPhase1	= 35.0 ;;,;; 15.0
  PercentageOfArmyPhase1	= 10.0 ;;,;; 15.0
  ;PercentageOfArmyPhase2	= 20.0 ;;,;; 20.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 20.0
  ;PercentageOfArmyPhase3	= 0.0 ;;,;; 10.0 ;;,;; 15.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 10.0 ;;,;; 15.0
End

ArmyMemberDefinition BeaconGuards_Member
  Unit			= BeaconGuardsHorde ;elite archers
  ;PercentageOfArmyPhase1	= 35.0 ;;,;; 15.0
  PercentageOfArmyPhase1	= 10.0 ;;,;; 15.0
  ;PercentageOfArmyPhase2	= 20.0 ;;,;; 20.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 20.0
  ;PercentageOfArmyPhase3	= 0.0 ;;,;; 10.0 ;;,;; 15.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 10.0 ;;,;; 15.0
End

ArmyMemberDefinition EredLuinGuard_Member
  Unit			= EredLuinGuardHorde ;specialist archers
  ;PercentageOfArmyPhase1	= 35.0 ;;,;; 15.0
  PercentageOfArmyPhase1	= 10.0 ;;,;; 15.0
  ;PercentageOfArmyPhase2	= 20.0 ;;,;; 20.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 20.0
  ;PercentageOfArmyPhase3	= 0.0 ;;,;; 10.0 ;;,;; 15.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 10.0 ;;,;; 15.0
End

ArmyMemberDefinition LossothArchers_Member
  Unit			= LossothArchersHorde ;specialist archers
  ;PercentageOfArmyPhase1	= 35.0 ;;,;; 15.0
  PercentageOfArmyPhase1	= 10.0 ;;,;; 15.0
  ;PercentageOfArmyPhase2	= 20.0 ;;,;; 20.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 20.0
  ;PercentageOfArmyPhase3	= 0.0 ;;,;; 10.0 ;;,;; 15.0
  PercentageOfArmyPhase2 = 10.0 ;;,;; 10.0 ;;,;; 15.0
End
