;------------------------------------------------------------------------;
;	  ARNOR REGION 														 ;
;------------------------------------------------------------------------;
CommandSet CommandSetInnGoodFaction_Arnor
	1	= Command_ConstructArthedainSentinelsHorde
	2	= Command_StartSelfRepair
End
CommandSet CommandSetInnEvilFaction_Arnor
	1	= Command_ConstructWightLordsHorde
	2	= Command_StartSelfRepair
End
;------------------------------------------------------------------------;
;	  ENEDWAITH REGION 														 ;
;------------------------------------------------------------------------;
CommandSet CommandSetInnGoodFaction_Enedwaith
	1	= Command_ConstructEredLuinGuardHorde
	2	= Command_ConstructEredLuinRangerHordeWotrInn
	3	= Command_StartSelfRepair
End
CommandSet CommandSetInnEvilFaction_Enedwaith
	1	= Command_ConstructDunlendingSpearmenHorde
	2	= Command_ConstructIsengardDunlandAxemenHordeWotrInn
	3	= Command_StartSelfRepair
End
;------------------------------------------------------------------------;
;	  EREBOR REGION 														 ;
;------------------------------------------------------------------------;
CommandSet CommandSetInnGoodFaction_Erebor
	1	= Command_ConstructDwarvenMinerHorde
	2	= Command_StartSelfRepair
End
CommandSet CommandSetInnEvilFaction_Erebor
	1	= Command_ConstructMordorEasterlingSwordsmanHorde
	2	= Command_StartSelfRepair
End
;------------------------------------------------------------------------;
;	  ERIADOR REGION 														 ;
;------------------------------------------------------------------------;
CommandSet CommandSetInnGoodFaction_Eriador
	1	= Command_ConstructHuntersofCombeHorde
	2	= Command_StartSelfRepair
End
CommandSet CommandSetInnEvilFaction_Eriador
	1	= Command_ConstructRuffianBows
	2	= Command_StartSelfRepair
End
;------------------------------------------------------------------------;
;	  FORODWAITH REGION 														 ;
;------------------------------------------------------------------------;
CommandSet CommandSetInnGoodFaction_Forodwaith
	1	= Command_ConstructLossothArcherHordeForInn
	2	= Command_StartSelfRepair
End
CommandSet CommandSetInnEvilFaction_Forodwaith
	1	= Command_ConstructLossothArcherHordeForInn
	2	= Command_StartSelfRepair
End
;------------------------------------------------------------------------;
;	  GONDOR REGION 														 ;
;------------------------------------------------------------------------;
CommandSet CommandSetInnGoodFaction_Gondor
	1	= Command_ConstructVeteransofOsgiliathHorde
	2	= Command_StartSelfRepair
End
CommandSet CommandSetInnEvilFaction_Gondor
	1	= Command_ConstructHarondorSwordsHorde
	2	= Command_StartSelfRepair
End
;------------------------------------------------------------------------;
;	  HARAD REGION 														 ;
;------------------------------------------------------------------------;
CommandSet CommandSetInnGoodFaction_Harad
	1	= Command_ConstructPelargirExpeditionaryHorde
	2	= Command_StartSelfRepair
End
CommandSet CommandSetInnEvilFaction_Harad
	1	= Command_ConstructMahudSpearsHorde
	2	= Command_StartSelfRepair
End
;------------------------------------------------------------------------;
;	  LINDON REGION 														 ;
;------------------------------------------------------------------------;
CommandSet CommandSetInnGoodFaction_Lindon
	1	= Command_ConstructSentinelsofWoodyEndHorde
	2	= Command_StartSelfRepair
End
CommandSet CommandSetInnEvilFaction_Lindon
	1	= Command_ConstructRuffians
	2	= Command_StartSelfRepair
End
;------------------------------------------------------------------------;
;	  MISTY MOUNTAINS REGION 														 ;
;------------------------------------------------------------------------;
CommandSet CommandSetInnGoodFaction_MM
	1	= Command_ConstructNoldorKnightHorde
	2	= Command_StartSelfRepair
End
CommandSet CommandSetInnEvilFaction_MM
	1	= Command_ConstructMoriaSpearmanHorde
	2	= Command_StartSelfRepair
End
;------------------------------------------------------------------------;
;	  MORDOR REGION 														 ;
;------------------------------------------------------------------------;
CommandSet CommandSetInnGoodFaction_Mordor
	1	= Command_ConstructGondorRangerSpearHorde
	2	= Command_StartSelfRepair
End
CommandSet CommandSetInnEvilFaction_Mordor
	1	= Command_ConstructMordorMorgulOrcPikemenHorde_RoR
	2	= Command_StartSelfRepair
End
;------------------------------------------------------------------------;
;	  RHOVANION REGION 														 ;
;------------------------------------------------------------------------;
CommandSet CommandSetInnGoodFaction_Rhovanion
	1	= Command_ConstructInnDorwinionFighterHorde
	2	= Command_ConstructMirkwoodEotheodHordeWotrInn
	3	= Command_ConstructDismountedAmrothHordeWotrInn
	4	= Command_StartSelfRepair
End
CommandSet CommandSetInnEvilFaction_Rhovanion
	1	= Command_ConstructRavagerShieldHorde
	2	= Command_ConstructGuldurSpiderRiderHordeWotrInn
	3	= Command_ConstructGuldurRestlessArcherHordeWotrInn
	4	= Command_StartSelfRepair
End
;------------------------------------------------------------------------;
;	  RHUN REGION 														 ;
;------------------------------------------------------------------------;
CommandSet CommandSetInnGoodFaction_Rhun
	1	= Command_ConstructKinnLaiHordeForInn
	2	= Command_ConstructDorwinionCaptainWotrInn
	3   = Command_ConstructInnDorwinionFighterHordeWotrInn
	4	= Command_StartSelfRepair
End
CommandSet CommandSetInnEvilFaction_Rhun
	1	= Command_ConstructTribalAuxillaryHordeForInn
	2	= Command_ConstructMordorEasterlingSwordsmanHordeWotrInn
	3	= Command_ConstructMordorEasterlingKataphractHordeWotrInn
	4	= Command_StartSelfRepair
End
;------------------------------------------------------------------------;
;	  ROHAN REGION 														 ;
;------------------------------------------------------------------------;
CommandSet CommandSetInnGoodFaction_Rohan
	1	= Command_ConstructBeaconGuardsHorde
	2	= Command_StartSelfRepair
End
CommandSet CommandSetInnEvilFaction_Rohan
	1	= Command_ConstructIsengardUrukAxes
	2	= Command_StartSelfRepair
End