;----------------------
;----------------------
;---- AOTR Specific stuff ; Fuck me dude this gonna be hell - ROR, Oct 31st 2018
;----------------------
;----------------------

AutoResolveWeapon AutoResolve_NormalHobbitWeakWeapon
	DamagePerRound = Damage:HERO_NORMAL_HOBBIT_DEFAULT_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:HERO_NORMAL_HOBBIT_DEFAULT_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:HERO_NORMAL_HOBBIT_DEFAULT_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:HERO_NORMAL_HOBBIT_DEFAULT_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:HERO_NORMAL_HOBBIT_DEFAULT_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:HERO_NORMAL_HOBBIT_DEFAULT_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:HERO_NORMAL_HOBBIT_DEFAULT_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:HERO_NORMAL_HOBBIT_DEFAULT_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:HERO_NORMAL_HOBBIT_DEFAULT_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:HERO_NORMAL_HOBBIT_DEFAULT_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	LevelBonus = Level:6 Bonus:30%
	LevelBonus = Level:7 Bonus:35%
	LevelBonus = Level:8 Bonus:40%
	LevelBonus = Level:9 Bonus:45%
	LevelBonus = Level:10 Bonus:50%	
	ReduceAttackWhenHurt = No
End

AutoResolveWeapon AutoResolve_NormalHeroWeakWeapon
	DamagePerRound = Damage:HERO_NORMAL_WEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:HERO_NORMAL_WEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:HERO_NORMAL_WEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:HERO_NORMAL_WEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:HERO_NORMAL_WEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:HERO_NORMAL_WEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:HERO_NORMAL_WEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:HERO_NORMAL_WEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:HERO_NORMAL_WEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:HERO_NORMAL_WEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	LevelBonus = Level:6 Bonus:30%
	LevelBonus = Level:7 Bonus:35%
	LevelBonus = Level:8 Bonus:40%
	LevelBonus = Level:9 Bonus:45%
	LevelBonus = Level:10 Bonus:50%	
	ReduceAttackWhenHurt = No
End

AutoResolveWeapon AutoResolve_NormalHeroModerateWeapon
	DamagePerRound = Damage:HERO_NORMAL_MODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:HERO_NORMAL_MODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:HERO_NORMAL_MODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:HERO_NORMAL_MODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:HERO_NORMAL_MODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:HERO_NORMAL_MODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:HERO_NORMAL_MODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:HERO_NORMAL_MODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:HERO_NORMAL_MODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:HERO_NORMAL_MODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	LevelBonus = Level:6 Bonus:30%
	LevelBonus = Level:7 Bonus:35%
	LevelBonus = Level:8 Bonus:40%
	LevelBonus = Level:9 Bonus:45%
	LevelBonus = Level:10 Bonus:50%	
	ReduceAttackWhenHurt = No
End

AutoResolveWeapon AutoResolve_NormalHeroStrongWeapon
	DamagePerRound = Damage:HERO_NORMAL_STRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:HERO_NORMAL_STRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:HERO_NORMAL_STRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:HERO_NORMAL_STRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:HERO_NORMAL_STRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:HERO_NORMAL_STRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:HERO_NORMAL_STRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:HERO_NORMAL_STRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:HERO_NORMAL_STRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:HERO_NORMAL_STRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	LevelBonus = Level:6 Bonus:30%
	LevelBonus = Level:7 Bonus:35%
	LevelBonus = Level:8 Bonus:40%
	LevelBonus = Level:9 Bonus:45%
	LevelBonus = Level:10 Bonus:50%	
	ReduceAttackWhenHurt = No
End

AutoResolveWeapon AutoResolve_LeaderHeroWeakWeapon
	DamagePerRound = Damage:HERO_LEADER_WEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:HERO_LEADER_WEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:HERO_LEADER_WEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:HERO_LEADER_WEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:HERO_LEADER_WEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:HERO_LEADER_WEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:HERO_LEADER_WEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:HERO_LEADER_WEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:HERO_LEADER_WEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:HERO_LEADER_WEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	LevelBonus = Level:6 Bonus:30%
	LevelBonus = Level:7 Bonus:35%
	LevelBonus = Level:8 Bonus:40%
	LevelBonus = Level:9 Bonus:45%
	LevelBonus = Level:10 Bonus:50%	
	ReduceAttackWhenHurt = No
End

AutoResolveWeapon AutoResolve_LeaderHeroModerateWeapon
	DamagePerRound = Damage:HERO_LEADER_MODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:HERO_LEADER_MODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:HERO_LEADER_MODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:HERO_LEADER_MODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:HERO_LEADER_MODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:HERO_LEADER_MODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:HERO_LEADER_MODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:HERO_LEADER_MODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:HERO_LEADER_MODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:HERO_LEADER_MODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	LevelBonus = Level:6 Bonus:30%
	LevelBonus = Level:7 Bonus:35%
	LevelBonus = Level:8 Bonus:40%
	LevelBonus = Level:9 Bonus:45%
	LevelBonus = Level:10 Bonus:50%	
	ReduceAttackWhenHurt = No
End

AutoResolveWeapon AutoResolve_LeaderHeroStrongWeapon
	DamagePerRound = Damage:HERO_LEADER_STRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:HERO_LEADER_STRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:HERO_LEADER_STRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:HERO_LEADER_STRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:HERO_LEADER_STRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:HERO_LEADER_STRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:HERO_LEADER_STRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:HERO_LEADER_STRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:HERO_LEADER_STRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:HERO_LEADER_STRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	LevelBonus = Level:6 Bonus:30%
	LevelBonus = Level:7 Bonus:35%
	LevelBonus = Level:8 Bonus:40%
	LevelBonus = Level:9 Bonus:45%
	LevelBonus = Level:10 Bonus:50%	
	ReduceAttackWhenHurt = No
End

;----------------------
;----- Basic Archers
;----------------------

AutoResolveWeapon AutoResolve_BasicArcherWeakWeapon
	DamagePerRound = Damage:ARCHERBASICWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:ARCHERBASICWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:ARCHERBASICWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:ARCHERBASICWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:ARCHERBASICWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:ARCHERBASICWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:ARCHERBASICWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:ARCHERBASICWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:ARCHERBASICWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:ARCHERBASICWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_BasicArcherWeakUpgradedWeapon
	DamagePerRound = Damage:ARCHERBASICWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:ARCHERBASICWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:ARCHERBASICWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:ARCHERBASICWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:ARCHERBASICWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:ARCHERBASICWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:ARCHERBASICWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:ARCHERBASICWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:ARCHERBASICWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:ARCHERBASICWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_BasicArcherModerateWeapon
	DamagePerRound = Damage:ARCHERBASICMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:ARCHERBASICMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:ARCHERBASICMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:ARCHERBASICMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:ARCHERBASICMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:ARCHERBASICMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:ARCHERBASICMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:ARCHERBASICMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:ARCHERBASICMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:ARCHERBASICMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_BasicArcherModerateUpgradedWeapon
	DamagePerRound = Damage:ARCHERBASICMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:ARCHERBASICMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:ARCHERBASICMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:ARCHERBASICMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:ARCHERBASICMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:ARCHERBASICMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:ARCHERBASICMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:ARCHERBASICMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:ARCHERBASICMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:ARCHERBASICMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_BasicArcherStrongWeapon
	DamagePerRound = Damage:ARCHERBASICSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:ARCHERBASICSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:ARCHERBASICSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:ARCHERBASICSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:ARCHERBASICSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:ARCHERBASICSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:ARCHERBASICSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:ARCHERBASICSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:ARCHERBASICSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:ARCHERBASICSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_BasicArcherStrongUpgradedWeapon
	DamagePerRound = Damage:ARCHERBASICSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:ARCHERBASICSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:ARCHERBASICSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:ARCHERBASICSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:ARCHERBASICSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:ARCHERBASICSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:ARCHERBASICSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:ARCHERBASICSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:ARCHERBASICSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:ARCHERBASICSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

;----------------------
;----- Elite Archers
;----------------------

AutoResolveWeapon AutoResolve_EliteArcherWeakWeapon
	DamagePerRound = Damage:ARCHERELITEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:ARCHERELITEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:ARCHERELITEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:ARCHERELITEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:ARCHERELITEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:ARCHERELITEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:ARCHERELITEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:ARCHERELITEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:ARCHERELITEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:ARCHERELITEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_EliteArcherWeakUpgradedWeapon
	DamagePerRound = Damage:ARCHERELITEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:ARCHERELITEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:ARCHERELITEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:ARCHERELITEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:ARCHERELITEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:ARCHERELITEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:ARCHERELITEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:ARCHERELITEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:ARCHERELITEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:ARCHERELITEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_EliteArcherModerateWeapon
	DamagePerRound = Damage:ARCHERELITEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:ARCHERELITEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:ARCHERELITEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:ARCHERELITEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:ARCHERELITEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:ARCHERELITEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:ARCHERELITEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:ARCHERELITEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:ARCHERELITEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:ARCHERELITEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_EliteArcherModerateUpgradedWeapon
	DamagePerRound = Damage:ARCHERELITEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:ARCHERELITEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:ARCHERELITEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:ARCHERELITEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:ARCHERELITEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:ARCHERELITEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:ARCHERELITEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:ARCHERELITEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:ARCHERELITEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:ARCHERELITEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_EliteArcherStrongWeapon
	DamagePerRound = Damage:ARCHERELITESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:ARCHERELITESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:ARCHERELITESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:ARCHERELITESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:ARCHERELITESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:ARCHERELITESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:ARCHERELITESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:ARCHERELITESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:ARCHERELITESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:ARCHERELITESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_EliteArcherStrongUpgradedWeapon
	DamagePerRound = Damage:ARCHERELITESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:ARCHERELITESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:ARCHERELITESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:ARCHERELITESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:ARCHERELITESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:ARCHERELITESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:ARCHERELITESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:ARCHERELITESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:ARCHERELITESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:ARCHERELITESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

;----------------------
;----- Basic Infantry
;----------------------

AutoResolveWeapon AutoResolve_BasicInfantryWeakWeapon
	DamagePerRound = Damage:SOLDIERBASICWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:SOLDIERBASICWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:SOLDIERBASICWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:SOLDIERBASICWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:SOLDIERBASICWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:SOLDIERBASICWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:SOLDIERBASICWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:SOLDIERBASICWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:SOLDIERBASICWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:SOLDIERBASICWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_BasicInfantryWeakUpgradedWeapon
	DamagePerRound = Damage:SOLDIERBASICWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:SOLDIERBASICWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:SOLDIERBASICWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:SOLDIERBASICWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:SOLDIERBASICWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:SOLDIERBASICWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:SOLDIERBASICWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:SOLDIERBASICWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:SOLDIERBASICWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:SOLDIERBASICWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_BasicInfantryModerateWeapon
	DamagePerRound = Damage:SOLDIERBASICMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:SOLDIERBASICMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:SOLDIERBASICMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:SOLDIERBASICMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:SOLDIERBASICMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:SOLDIERBASICMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:SOLDIERBASICMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:SOLDIERBASICMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:SOLDIERBASICMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:SOLDIERBASICMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_BasicInfantryModerateUpgradedWeapon
	DamagePerRound = Damage:SOLDIERBASICMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:SOLDIERBASICMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:SOLDIERBASICMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:SOLDIERBASICMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:SOLDIERBASICMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:SOLDIERBASICMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:SOLDIERBASICMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:SOLDIERBASICMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:SOLDIERBASICMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:SOLDIERBASICMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_BasicInfantryStrongWeapon
	DamagePerRound = Damage:SOLDIERBASICSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:SOLDIERBASICSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:SOLDIERBASICSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:SOLDIERBASICSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:SOLDIERBASICSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:SOLDIERBASICSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:SOLDIERBASICSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:SOLDIERBASICSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:SOLDIERBASICSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:SOLDIERBASICSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_BasicInfantryStrongUpgradedWeapon
	DamagePerRound = Damage:SOLDIERBASICSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:SOLDIERBASICSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:SOLDIERBASICSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:SOLDIERBASICSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:SOLDIERBASICSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:SOLDIERBASICSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:SOLDIERBASICSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:SOLDIERBASICSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:SOLDIERBASICSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:SOLDIERBASICSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

;----------------------
;----- Elite Infantry
;----------------------

AutoResolveWeapon AutoResolve_EliteInfantryWeakWeapon
	DamagePerRound = Damage:SOLDIERELITEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:SOLDIERELITEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:SOLDIERELITEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:SOLDIERELITEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:SOLDIERELITEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:SOLDIERELITEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:SOLDIERELITEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:SOLDIERELITEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:SOLDIERELITEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:SOLDIERELITEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_EliteInfantryWeakUpgradedWeapon
	DamagePerRound = Damage:SOLDIERELITEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:SOLDIERELITEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:SOLDIERELITEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:SOLDIERELITEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:SOLDIERELITEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:SOLDIERELITEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:SOLDIERELITEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:SOLDIERELITEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:SOLDIERELITEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:SOLDIERELITEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_EliteInfantryModerateWeapon
	DamagePerRound = Damage:SOLDIERELITEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:SOLDIERELITEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:SOLDIERELITEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:SOLDIERELITEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:SOLDIERELITEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:SOLDIERELITEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:SOLDIERELITEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:SOLDIERELITEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:SOLDIERELITEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:SOLDIERELITEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_EliteInfantryModerateUpgradedWeapon
	DamagePerRound = Damage:SOLDIERELITEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:SOLDIERELITEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:SOLDIERELITEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:SOLDIERELITEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:SOLDIERELITEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:SOLDIERELITEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:SOLDIERELITEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:SOLDIERELITEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:SOLDIERELITEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:SOLDIERELITEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_EliteInfantryStrongWeapon
	DamagePerRound = Damage:SOLDIERELITESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:SOLDIERELITESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:SOLDIERELITESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:SOLDIERELITESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:SOLDIERELITESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:SOLDIERELITESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:SOLDIERELITESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:SOLDIERELITESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:SOLDIERELITESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:SOLDIERELITESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_EliteInfantryStrongUpgradedWeapon
	DamagePerRound = Damage:SOLDIERELITESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:SOLDIERELITESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:SOLDIERELITESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:SOLDIERELITESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:SOLDIERELITESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:SOLDIERELITESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:SOLDIERELITESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:SOLDIERELITESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:SOLDIERELITESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:SOLDIERELITESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_EliteInfantrySingleWeapon
	DamagePerRound = Damage:SOLDIERELITESINGLE_DEFAULT_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:SOLDIERELITESINGLE_DEFAULT_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:SOLDIERELITESINGLE_DEFAULT_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:SOLDIERELITESINGLE_DEFAULT_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:SOLDIERELITESINGLE_DEFAULT_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:SOLDIERELITESINGLE_DEFAULT_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:SOLDIERELITESINGLE_DEFAULT_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:SOLDIERELITESINGLE_DEFAULT_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:SOLDIERELITESINGLE_DEFAULT_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:SOLDIERELITESINGLE_DEFAULT_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

;----------------------
;----- Basic Pikemen
;----------------------

AutoResolveWeapon AutoResolve_BasicPikemanWeakWeapon
	DamagePerRound = Damage:PIKEMANBASICWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:PIKEMANBASICWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:PIKEMANBASICWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:PIKEMANBASICWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:PIKEMANBASICWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:PIKEMANBASICWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:PIKEMANBASICWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:PIKEMANBASICWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:PIKEMANBASICWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:PIKEMANBASICWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_BasicPikemanWeakUpgradedWeapon
	DamagePerRound = Damage:PIKEMANBASICWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:PIKEMANBASICWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:PIKEMANBASICWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:PIKEMANBASICWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:PIKEMANBASICWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:PIKEMANBASICWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:PIKEMANBASICWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:PIKEMANBASICWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:PIKEMANBASICWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:PIKEMANBASICWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_BasicPikemanModerateWeapon
	DamagePerRound = Damage:PIKEMANBASICMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:PIKEMANBASICMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:PIKEMANBASICMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:PIKEMANBASICMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:PIKEMANBASICMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:PIKEMANBASICMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:PIKEMANBASICMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:PIKEMANBASICMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:PIKEMANBASICMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:PIKEMANBASICMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_BasicPikemanModerateUpgradedWeapon
	DamagePerRound = Damage:PIKEMANBASICMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:PIKEMANBASICMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:PIKEMANBASICMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:PIKEMANBASICMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:PIKEMANBASICMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:PIKEMANBASICMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:PIKEMANBASICMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:PIKEMANBASICMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:PIKEMANBASICMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:PIKEMANBASICMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_BasicPikemanStrongWeapon
	DamagePerRound = Damage:PIKEMANBASICSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:PIKEMANBASICSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:PIKEMANBASICSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:PIKEMANBASICSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:PIKEMANBASICSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:PIKEMANBASICSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:PIKEMANBASICSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:PIKEMANBASICSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:PIKEMANBASICSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:PIKEMANBASICSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_BasicPikemanStrongUpgradedWeapon
	DamagePerRound = Damage:PIKEMANBASICSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:PIKEMANBASICSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:PIKEMANBASICSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:PIKEMANBASICSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:PIKEMANBASICSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:PIKEMANBASICSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:PIKEMANBASICSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:PIKEMANBASICSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:PIKEMANBASICSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:PIKEMANBASICSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

;----------------------
;----- Elite Pikemen
;----------------------

AutoResolveWeapon AutoResolve_ElitePikemanWeakWeapon
	DamagePerRound = Damage:PIKEMANELITEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:PIKEMANELITEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:PIKEMANELITEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:PIKEMANELITEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:PIKEMANELITEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:PIKEMANELITEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:PIKEMANELITEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:PIKEMANELITEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:PIKEMANELITEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:PIKEMANELITEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_ElitePikemanWeakUpgradedWeapon
	DamagePerRound = Damage:PIKEMANELITEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:PIKEMANELITEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:PIKEMANELITEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:PIKEMANELITEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:PIKEMANELITEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:PIKEMANELITEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:PIKEMANELITEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:PIKEMANELITEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:PIKEMANELITEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:PIKEMANELITEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_ElitePikemanModerateWeapon
	DamagePerRound = Damage:PIKEMANELITEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:PIKEMANELITEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:PIKEMANELITEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:PIKEMANELITEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:PIKEMANELITEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:PIKEMANELITEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:PIKEMANELITEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:PIKEMANELITEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:PIKEMANELITEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:PIKEMANELITEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_ElitePikemanModerateUpgradedWeapon
	DamagePerRound = Damage:PIKEMANELITEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:PIKEMANELITEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:PIKEMANELITEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:PIKEMANELITEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:PIKEMANELITEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:PIKEMANELITEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:PIKEMANELITEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:PIKEMANELITEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:PIKEMANELITEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:PIKEMANELITEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_ElitePikemanStrongWeapon
	DamagePerRound = Damage:PIKEMANELITESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:PIKEMANELITESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:PIKEMANELITESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:PIKEMANELITESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:PIKEMANELITESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:PIKEMANELITESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:PIKEMANELITESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:PIKEMANELITESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:PIKEMANELITESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:PIKEMANELITESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_ElitePikemanStrongUpgradedWeapon
	DamagePerRound = Damage:PIKEMANELITESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:PIKEMANELITESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:PIKEMANELITESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:PIKEMANELITESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:PIKEMANELITESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:PIKEMANELITESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:PIKEMANELITESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:PIKEMANELITESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:PIKEMANELITESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:PIKEMANELITESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

;----------------------
;----- Basic Cavalry
;----------------------

AutoResolveWeapon AutoResolve_BasicCavalryWeakWeapon
	DamagePerRound = Damage:CAVALRYBASICWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:CAVALRYBASICWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:CAVALRYBASICWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:CAVALRYBASICWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:CAVALRYBASICWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:CAVALRYBASICWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:CAVALRYBASICWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:CAVALRYBASICWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:CAVALRYBASICWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:CAVALRYBASICWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_BasicCavalryWeakUpgradedWeapon
	DamagePerRound = Damage:CAVALRYBASICWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:CAVALRYBASICWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:CAVALRYBASICWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:CAVALRYBASICWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:CAVALRYBASICWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:CAVALRYBASICWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:CAVALRYBASICWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:CAVALRYBASICWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:CAVALRYBASICWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:CAVALRYBASICWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_BasicCavalryModerateWeapon
	DamagePerRound = Damage:CAVALRYBASICMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:CAVALRYBASICMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:CAVALRYBASICMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:CAVALRYBASICMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:CAVALRYBASICMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:CAVALRYBASICMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:CAVALRYBASICMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:CAVALRYBASICMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:CAVALRYBASICMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:CAVALRYBASICMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_BasicCavalryModerateUpgradedWeapon
	DamagePerRound = Damage:CAVALRYBASICMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:CAVALRYBASICMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:CAVALRYBASICMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:CAVALRYBASICMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:CAVALRYBASICMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:CAVALRYBASICMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:CAVALRYBASICMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:CAVALRYBASICMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:CAVALRYBASICMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:CAVALRYBASICMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_BasicCavalryStrongWeapon
	DamagePerRound = Damage:CAVALRYBASICSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:CAVALRYBASICSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:CAVALRYBASICSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:CAVALRYBASICSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:CAVALRYBASICSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:CAVALRYBASICSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:CAVALRYBASICSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:CAVALRYBASICSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:CAVALRYBASICSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:CAVALRYBASICSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_BasicCavalryStrongUpgradedWeapon
	DamagePerRound = Damage:CAVALRYBASICSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:CAVALRYBASICSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:CAVALRYBASICSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:CAVALRYBASICSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:CAVALRYBASICSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:CAVALRYBASICSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:CAVALRYBASICSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:CAVALRYBASICSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:CAVALRYBASICSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:CAVALRYBASICSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_BasicCavalrySingleWeapon
	DamagePerRound = Damage:CAVALRYBASICSINGLE_DEFAULT_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:CAVALRYBASICSINGLE_DEFAULT_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:CAVALRYBASICSINGLE_DEFAULT_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:CAVALRYBASICSINGLE_DEFAULT_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:CAVALRYBASICSINGLE_DEFAULT_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:CAVALRYBASICSINGLE_DEFAULT_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:CAVALRYBASICSINGLE_DEFAULT_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:CAVALRYBASICSINGLE_DEFAULT_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:CAVALRYBASICSINGLE_DEFAULT_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:CAVALRYBASICSINGLE_DEFAULT_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_BasicCavalrySingleUpgradedWeapon
	DamagePerRound = Damage:CAVALRYBASICSINGLE_UPGRADED_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:CAVALRYBASICSINGLE_UPGRADED_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:CAVALRYBASICSINGLE_UPGRADED_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:CAVALRYBASICSINGLE_UPGRADED_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:CAVALRYBASICSINGLE_UPGRADED_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:CAVALRYBASICSINGLE_UPGRADED_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:CAVALRYBASICSINGLE_UPGRADED_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:CAVALRYBASICSINGLE_UPGRADED_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:CAVALRYBASICSINGLE_UPGRADED_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:CAVALRYBASICSINGLE_UPGRADED_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

;----------------------
;----- Elite Cavalry
;----------------------

AutoResolveWeapon AutoResolve_EliteCavalryWeakWeapon
	DamagePerRound = Damage:CAVALRYELITEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:CAVALRYELITEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:CAVALRYELITEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:CAVALRYELITEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:CAVALRYELITEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:CAVALRYELITEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:CAVALRYELITEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:CAVALRYELITEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:CAVALRYELITEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:CAVALRYELITEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_EliteCavalryWeakUpgradedWeapon
	DamagePerRound = Damage:CAVALRYELITEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:CAVALRYELITEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:CAVALRYELITEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:CAVALRYELITEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:CAVALRYELITEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:CAVALRYELITEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:CAVALRYELITEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:CAVALRYELITEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:CAVALRYELITEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:CAVALRYELITEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_EliteCavalryModerateWeapon
	DamagePerRound = Damage:CAVALRYELITEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:CAVALRYELITEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:CAVALRYELITEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:CAVALRYELITEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:CAVALRYELITEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:CAVALRYELITEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:CAVALRYELITEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:CAVALRYELITEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:CAVALRYELITEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:CAVALRYELITEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_EliteCavalryModerateUpgradedWeapon
	DamagePerRound = Damage:CAVALRYELITEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:CAVALRYELITEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:CAVALRYELITEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:CAVALRYELITEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:CAVALRYELITEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:CAVALRYELITEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:CAVALRYELITEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:CAVALRYELITEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:CAVALRYELITEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:CAVALRYELITEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_EliteCavalryStrongWeapon
	DamagePerRound = Damage:CAVALRYELITESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:CAVALRYELITESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:CAVALRYELITESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:CAVALRYELITESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:CAVALRYELITESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:CAVALRYELITESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:CAVALRYELITESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:CAVALRYELITESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:CAVALRYELITESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:CAVALRYELITESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_EliteCavalryStrongUpgradedWeapon
	DamagePerRound = Damage:CAVALRYELITESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:CAVALRYELITESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:CAVALRYELITESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:CAVALRYELITESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:CAVALRYELITESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:CAVALRYELITESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:CAVALRYELITESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:CAVALRYELITESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:CAVALRYELITESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:CAVALRYELITESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_KODAWeapon
	DamagePerRound = Damage:KNIGHTOFDOLAMROTH_DEFAULT_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:KNIGHTOFDOLAMROTH_DEFAULT_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:KNIGHTOFDOLAMROTH_DEFAULT_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:KNIGHTOFDOLAMROTH_DEFAULT_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:KNIGHTOFDOLAMROTH_DEFAULT_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:KNIGHTOFDOLAMROTH_DEFAULT_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:KNIGHTOFDOLAMROTH_DEFAULT_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:KNIGHTOFDOLAMROTH_DEFAULT_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:KNIGHTOFDOLAMROTH_DEFAULT_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:KNIGHTOFDOLAMROTH_DEFAULT_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_EliteCavalrySingleWeapon
	DamagePerRound = Damage:CAVALRYELITESINGLE_DEFAULT_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:CAVALRYELITESINGLE_DEFAULT_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:CAVALRYELITESINGLE_DEFAULT_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:CAVALRYELITESINGLE_DEFAULT_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:CAVALRYELITESINGLE_DEFAULT_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:CAVALRYELITESINGLE_DEFAULT_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:CAVALRYELITESINGLE_DEFAULT_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:CAVALRYELITESINGLE_DEFAULT_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:CAVALRYELITESINGLE_DEFAULT_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:CAVALRYELITESINGLE_DEFAULT_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_EliteCavalrySingleUpgradedWeapon
	DamagePerRound = Damage:CAVALRYELITESINGLE_UPGRADED_DAMAGE Against:AutoResolveUnit_Archer
	DamagePerRound = Damage:CAVALRYELITESINGLE_UPGRADED_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:CAVALRYELITESINGLE_UPGRADED_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:CAVALRYELITESINGLE_UPGRADED_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:CAVALRYELITESINGLE_UPGRADED_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:CAVALRYELITESINGLE_UPGRADED_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:CAVALRYELITESINGLE_UPGRADED_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:CAVALRYELITESINGLE_UPGRADED_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:CAVALRYELITESINGLE_UPGRADED_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:CAVALRYELITESINGLE_UPGRADED_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

;----------------------
;----- Siege
;----------------------

AutoResolveWeapon AutoResolve_SiegeWeakWeapon
	DamagePerRound = Damage:SIEGEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:SIEGEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:SIEGEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:SIEGEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:SIEGEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:SIEGEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:SIEGEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:SIEGEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:SIEGEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:SIEGEWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_SiegeWeakUpgradedWeapon
	DamagePerRound = Damage:SIEGEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:SIEGEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:SIEGEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:SIEGEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:SIEGEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:SIEGEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:SIEGEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:SIEGEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:SIEGEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:SIEGEWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_SiegeModerateWeapon
	DamagePerRound = Damage:SIEGEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:SIEGEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:SIEGEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:SIEGEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:SIEGEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:SIEGEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:SIEGEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:SIEGEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:SIEGEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:SIEGEMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_SiegeModerateUpgradedWeapon
	DamagePerRound = Damage:SIEGEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:SIEGEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:SIEGEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:SIEGEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:SIEGEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:SIEGEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:SIEGEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:SIEGEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:SIEGEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:SIEGEMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_SiegeStrongWeapon
	DamagePerRound = Damage:SIEGESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:SIEGESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:SIEGESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:SIEGESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:SIEGESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:SIEGESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:SIEGESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:SIEGESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:SIEGESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:SIEGESTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_SiegeStrongUpgradedWeapon
	DamagePerRound = Damage:SIEGESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:SIEGESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:SIEGESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:SIEGESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:SIEGESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:SIEGESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:SIEGESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:SIEGESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:SIEGESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Siege
	DamagePerRound = Damage:SIEGESTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

;----------------------
;----- Support
;----------------------

AutoResolveWeapon AutoResolve_SupportWeakWeapon
	DamagePerRound = Damage:SUPPORTWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:SUPPORTWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:SUPPORTWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:SUPPORTWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:SUPPORTWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:SUPPORTWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:SUPPORTWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:SUPPORTWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:SUPPORTWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:SUPPORTWEAK_DEFAULT_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_SupportWeakUpgradedWeapon
	DamagePerRound = Damage:SUPPORTWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:SUPPORTWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:SUPPORTWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:SUPPORTWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:SUPPORTWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:SUPPORTWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:SUPPORTWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:SUPPORTWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:SUPPORTWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:SUPPORTWEAK_UPGRADED_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_SupportModerateWeapon
	DamagePerRound = Damage:SUPPORTMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:SUPPORTMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:SUPPORTMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:SUPPORTMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:SUPPORTMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:SUPPORTMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:SUPPORTMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:SUPPORTMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:SUPPORTMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:SUPPORTMODERATE_DEFAULT_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_SupportModerateUpgradedWeapon
	DamagePerRound = Damage:SUPPORTMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:SUPPORTMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:SUPPORTMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:SUPPORTMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:SUPPORTMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:SUPPORTMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:SUPPORTMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:SUPPORTMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:SUPPORTMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:SUPPORTMODERATE_UPGRADED_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_SupportStrongWeapon
	DamagePerRound = Damage:SUPPORTSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:SUPPORTSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:SUPPORTSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:SUPPORTSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:SUPPORTSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:SUPPORTSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:SUPPORTSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:SUPPORTSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:SUPPORTSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:SUPPORTSTRONG_DEFAULT_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_SupportStrongUpgradedWeapon
	DamagePerRound = Damage:SUPPORTSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:SUPPORTSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Soldier
	DamagePerRound = Damage:SUPPORTSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Pikemen
	DamagePerRound = Damage:SUPPORTSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Cavalry
	DamagePerRound = Damage:SUPPORTSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Hero
	DamagePerRound = Damage:SUPPORTSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Monster
	DamagePerRound = Damage:SUPPORTSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Fortress
	DamagePerRound = Damage:SUPPORTSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:SUPPORTSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_Support
	DamagePerRound = Damage:SUPPORTSTRONG_UPGRADED_DAMAGE Against:AutoResolveUnit_INVALID
	LevelBonus = Level:2 Bonus:10%
	LevelBonus = Level:3 Bonus:15%
	LevelBonus = Level:4 Bonus:20%
	LevelBonus = Level:5 Bonus:25%
	ReduceAttackWhenHurt = Yes
End

AutoResolveWeapon AutoResolve_WotRArmyWeapon
	DamagePerRound = Damage:2000 Against:AutoResolveUnit_Fortress
	LevelBonus = Level:10 Bonus:50%	
	ReduceAttackWhenHurt = No
End

;----------------------
;----------------------
;---- End AOTR Specific stuff
;----------------------
;----------------------