;---------------------------------------------------
;------------------- WOTR BASES --------------------
;---------------------------------------------------
AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - siege base1"
	GameMapToUseOn = "map wor abrakhan.map"
PlayerPositions = 2 3 4 5 6 7 8
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - fortress base1"
	GameMapToUseOn = "map wor abrakhan.map"
PlayerPositions = 1

End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base2"
	GameMapToUseOn = "map wor amathuna.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base3"
	GameMapToUseOn = "map wor amon hen.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base4"
	GameMapToUseOn = "map wor andrast.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base5"
	GameMapToUseOn = "map wor anfalas.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base6"
	GameMapToUseOn = "map wor angmar.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base7"
	GameMapToUseOn = "map wor annuminas.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base8"
	GameMapToUseOn = "map wor anorien.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base9"
	GameMapToUseOn = "map wor barrow downs.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base10"
	GameMapToUseOn = "map wor belfalas.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base11"
	GameMapToUseOn = "map wor black gate.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base12"
	GameMapToUseOn = "map wor borders of khand.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base13"
	GameMapToUseOn = "map wor bree.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base14"
	GameMapToUseOn = "map wor buckland.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base15"
	GameMapToUseOn = "map wor cair andros.map"
End


AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base16"
	GameMapToUseOn = "map wor cape of forlond.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base17"
	GameMapToUseOn = "map wor cape of mardruak.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base18"
	GameMapToUseOn = "map wor caradhras.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base19"
	GameMapToUseOn = "map wor cardolan.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base20"
	GameMapToUseOn = "map wor carn dum.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base21"
	GameMapToUseOn = "map wor carnen.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base22"
	GameMapToUseOn = "map wor central ithilien.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base23"
	GameMapToUseOn = "map wor cirith ungol.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base24"
	GameMapToUseOn = "map wor coldfells.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base25"
	GameMapToUseOn = "map wor crossroads.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base26"
	GameMapToUseOn = "map wor dagorlad.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base27"
	GameMapToUseOn = "map wor dead marshes.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base28"
	GameMapToUseOn = "map wor desert of azkahar.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base29"
	GameMapToUseOn = "map wor desert of lostladen.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base30"
	GameMapToUseOn = "map wor dimrill dale.map"
End


AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - siege base31"
	GameMapToUseOn = "map wor dol amroth.map"
PlayerPositions = 2 3 4 5 6 7 8
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - fortress base31"
	GameMapToUseOn = "map wor dol amroth.map"
PlayerPositions = 1

End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - siege base32"
	GameMapToUseOn = "map wor dol guldur.map"
PlayerPositions = 2 3 4 5 6 7 8
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - fortress base32"
	GameMapToUseOn = "map wor dol guldur.map"
PlayerPositions = 1

End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base33"
	GameMapToUseOn = "map wor dorwinion.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base34"
	GameMapToUseOn = "map wor druadan forest.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base35"
	GameMapToUseOn = "map wor druwaith iaur.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base36"
	GameMapToUseOn = "map wor dunfearn.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base37"
	GameMapToUseOn = "map wor dunharrow.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base38"
	GameMapToUseOn = "map wor dunland.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - siege base39"
	GameMapToUseOn = "map wor durthang.map"
PlayerPositions = 2 3 4 5 6 7 8
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - fortress base39"
	GameMapToUseOn = "map wor durthang.map"
PlayerPositions = 1

End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base40"
	GameMapToUseOn = "map wor dusalan.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base41"
	GameMapToUseOn = "map wor east bight.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base42"
	GameMapToUseOn = "map wor east emnet.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base43"
	GameMapToUseOn = "map wor eastern rohan.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base44"
	GameMapToUseOn = "map wor eastern wastes.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base45"
	GameMapToUseOn = "map wor eastfold.map"
End


AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base46"
	GameMapToUseOn = "map wor eaves of fangorn.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - siege base47"
	GameMapToUseOn = "map wor edoras.map"
PlayerPositions = 2 3 4 5 6 7 8
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - fortress base47"
	GameMapToUseOn = "map wor edoras.map"
PlayerPositions = 1

End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base48"
	GameMapToUseOn = "map wor emyn arnen.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base49"
	GameMapToUseOn = "map wor emyn muil.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base50"
	GameMapToUseOn = "map wor enedwaith.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - siege base51"
	GameMapToUseOn = "map wor erebor.map"
PlayerPositions = 2 3 4 5 6 7 8
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - fortress base51"
	GameMapToUseOn = "map wor erebor.map"
PlayerPositions = 1

End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base52"
	GameMapToUseOn = "map wor erech.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base53"
	GameMapToUseOn = "map wor ered lithui.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - siege base54"
	GameMapToUseOn = "map wor ered luin.map"
PlayerPositions = 2 3 4 5 6 7 8
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - fortress base54"
	GameMapToUseOn = "map wor ered luin.map"
PlayerPositions = 1

End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base55"
	GameMapToUseOn = "map wor ered luin highlands.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base56"
	GameMapToUseOn = "map wor eregion.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - siege base57"
	GameMapToUseOn = "map wor esgaroth.map"
PlayerPositions = 2 3 4 5 6 7 8
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - fortress base57"
	GameMapToUseOn = "map wor esgaroth.map"
PlayerPositions = 1

End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base58"
	GameMapToUseOn = "map wor ethir anduin.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base59"
	GameMapToUseOn = "map wor ettenmoors.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base60"
	GameMapToUseOn = "map wor fangorn.map"
End


AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base61"
	GameMapToUseOn = "map wor far harad.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base62"
	GameMapToUseOn = "map wor field of celebrant.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base63"
	GameMapToUseOn = "map wor fords of bruinen.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base64"
	GameMapToUseOn = "map wor fords of isen.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base65"
	GameMapToUseOn = "map wor forlindon.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base66"
	GameMapToUseOn = "map wor fornost.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base67"
	GameMapToUseOn = "map wor forodwaith.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - siege base68"
	GameMapToUseOn = "map wor framsburg.map"
PlayerPositions = 2 3 4 5 6 7 8
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - fortress base68"
	GameMapToUseOn = "map wor framsburg.map"
PlayerPositions = 1

End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base69"
	GameMapToUseOn = "map wor frecalund.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base70"
	GameMapToUseOn = "map wor gap of rohan.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base71"
	GameMapToUseOn = "map wor gladden fields.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base72"
	GameMapToUseOn = "map wor goblin town.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base73"
	GameMapToUseOn = "map wor grey havens.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base74"
	GameMapToUseOn = "map wor grey mountains.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base75"
	GameMapToUseOn = "map wor greyflood.map"
End


AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base76"
	GameMapToUseOn = "map wor halifirien.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base77"
	GameMapToUseOn = "map wor hall of oak.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - siege base78"
	GameMapToUseOn = "map wor halls of the elvenking.map"
PlayerPositions = 2 3 4 5 6 7 8
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - fortress base78"
	GameMapToUseOn = "map wor halls of the elvenking.map"
PlayerPositions = 1

End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base79"
	GameMapToUseOn = "map wor harad coast.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base80"
	GameMapToUseOn = "map wor harad road.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base81"
	GameMapToUseOn = "map wor harlindon.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base82"
	GameMapToUseOn = "map wor harlond.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base83"
	GameMapToUseOn = "map wor harondor.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base84"
	GameMapToUseOn = "map wor harrowdale.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - siege base85"
	GameMapToUseOn = "map wor helms deep.map"
PlayerPositions = 2 3 4 5 6 7 8
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - fortress base85"
	GameMapToUseOn = "map wor helms deep.map"
PlayerPositions = 1

End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - siege base86"
	GameMapToUseOn = "map wor hidar.map"
PlayerPositions = 2 3 4 5 6 7 8
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - fortress base86"
	GameMapToUseOn = "map wor hidar.map"
PlayerPositions = 1

End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base87"
	GameMapToUseOn = "map wor high pass.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base88"
	GameMapToUseOn = "map wor hills of evendim.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base89"
	GameMapToUseOn = "map wor hollin.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base90"
	GameMapToUseOn = "map wor ice bay of forochel.map"
End


AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base91"
	GameMapToUseOn = "map wor iron foothills.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base92"
	GameMapToUseOn = "map wor iron hills.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - siege base93"
	GameMapToUseOn = "map wor ironfoots halls.map"
PlayerPositions = 2 3 4 5 6 7 8
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - fortress base93"
	GameMapToUseOn = "map wor ironfoots halls.map"
PlayerPositions = 1

End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - siege base94"
	GameMapToUseOn = "map wor isengard.map"
PlayerPositions = 2 3 4 5 6 7 8
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - fortress base94"
	GameMapToUseOn = "map wor isengard.map"
PlayerPositions = 1

End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base95"
	GameMapToUseOn = "map wor ita ma.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base96"
	GameMapToUseOn = "map wor itakh khand.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base97"
	GameMapToUseOn = "map wor jotunstath.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base98"
	GameMapToUseOn = "map wor karna.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base99"
	GameMapToUseOn = "map wor khand.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base100"
	GameMapToUseOn = "map wor kunin.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base101"
	GameMapToUseOn = "map wor lamedon.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base102"
	GameMapToUseOn = "map wor lebennin.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base103"
	GameMapToUseOn = "map wor lossarnach.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - siege base104"
	GameMapToUseOn = "map wor lothlorien.map"
PlayerPositions = 2 3 4 5 6 7 8
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - fortress base104"
	GameMapToUseOn = "map wor lothlorien.map"
PlayerPositions = 1

End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base105"
	GameMapToUseOn = "map wor maros.map"
End


AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - siege base106"
	GameMapToUseOn = "map wor minas morgul.map"
PlayerPositions = 2 3 4 5 6 7 8
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - fortress base106"
	GameMapToUseOn = "map wor minas morgul.map"
PlayerPositions = 1

End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - siege base107"
	GameMapToUseOn = "map wor minas tirith.map"
PlayerPositions = 2 3 4 5 6 7 8
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - fortress base107"
	GameMapToUseOn = "map wor minas tirith.map"
PlayerPositions = 1

End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base108"
	GameMapToUseOn = "map wor minhiriath.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base109"
	GameMapToUseOn = "map wor mirkwood.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base110"
	GameMapToUseOn = "map wor moria.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base111"
	GameMapToUseOn = "map wor mount doom.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base112"
	GameMapToUseOn = "map wor mount gram.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - siege base113"
	GameMapToUseOn = "map wor mount gundabad.map"
PlayerPositions = 2 3 4 5 6 7 8
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - fortress base113"
	GameMapToUseOn = "map wor mount gundabad.map"
PlayerPositions = 1

End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base114"
	GameMapToUseOn = "map wor mouths of entwash.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base115"
	GameMapToUseOn = "map wor nafarat.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base116"
	GameMapToUseOn = "map wor nafarat delta.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base117"
	GameMapToUseOn = "map wor nan celebrant.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base118"
	GameMapToUseOn = "map wor near harad.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base119"
	GameMapToUseOn = "map wor north downs.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base120"
	GameMapToUseOn = "map wor north ithilien.map"
End


AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base121"
	GameMapToUseOn = "map wor northern mirkwood.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base122"
	GameMapToUseOn = "map wor northtarn.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base123"
	GameMapToUseOn = "map wor nurn.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base124"
	GameMapToUseOn = "map wor old brown lands.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base125"
	GameMapToUseOn = "map wor old ford of anduin.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base126"
	GameMapToUseOn = "map wor osgiliath.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base127"
	GameMapToUseOn = "map wor ost in edhil.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - siege base128"
	GameMapToUseOn = "map wor pelargir.map"
PlayerPositions = 2 3 4 5 6 7 8
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - fortress base128"
	GameMapToUseOn = "map wor pelargir.map"
PlayerPositions = 1

End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base129"
	GameMapToUseOn = "map wor plains of gorgoroth.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base130"
	GameMapToUseOn = "map wor regnfells.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base131"
	GameMapToUseOn = "map wor rhudaur.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base132"
	GameMapToUseOn = "map wor rhun.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base133"
	GameMapToUseOn = "map wor ringlo vale.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - siege base134"
	GameMapToUseOn = "map wor rivendell.map"
PlayerPositions = 2 3 4 5 6 7 8
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - fortress base134"
	GameMapToUseOn = "map wor rivendell.map"
PlayerPositions = 1

End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base135"
	GameMapToUseOn = "map wor sarn ford.map"
End


AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base136"
	GameMapToUseOn = "map wor sea of nurnen.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base137"
	GameMapToUseOn = "map wor slavefields of nurn.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base138"
	GameMapToUseOn = "map wor snowbourn.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base139"
	GameMapToUseOn = "map wor south rhun.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base140"
	GameMapToUseOn = "map wor southern ithilien.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base141"
	GameMapToUseOn = "map wor steppes of sarakhax.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base142"
	GameMapToUseOn = "map wor surubeki.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base143"
	GameMapToUseOn = "map wor swanfleet.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base144"
	GameMapToUseOn = "map wor targul.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base145"
	GameMapToUseOn = "map wor taur en morvith.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base146"
	GameMapToUseOn = "map wor taur en ungolath.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base147"
	GameMapToUseOn = "map wor taur hithlin.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base148"
	GameMapToUseOn = "map wor taur na faroth.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base149"
	GameMapToUseOn = "map wor tharbad.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - siege base150"
	GameMapToUseOn = "map wor the angle.map"
PlayerPositions = 2 3 4 5 6 7 8
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - fortress base150"
	GameMapToUseOn = "map wor the angle.map"
PlayerPositions = 1

End


AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base151"
	GameMapToUseOn = "map wor the carrock.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base152"
	GameMapToUseOn = "map wor the folde.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base153"
	GameMapToUseOn = "map wor the forest gate.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base154"
	GameMapToUseOn = "map wor the old forest.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base155"
	GameMapToUseOn = "map wor the shire.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base156"
	GameMapToUseOn = "map wor the wold.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - siege base157"
	GameMapToUseOn = "map wor thorins halls.map"
PlayerPositions = 2 3 4 5 6 7 8
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - fortress base157"
	GameMapToUseOn = "map wor thorins halls.map"
PlayerPositions = 1

End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base158"
	GameMapToUseOn = "map wor tolfalas.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base159"
	GameMapToUseOn = "map wor tombs of abrakhan.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base160"
	GameMapToUseOn = "map wor tower hills.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base161"
	GameMapToUseOn = "map wor trollshaws.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base162"
	GameMapToUseOn = "map wor tuli ma.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base163"
	GameMapToUseOn = "map wor ul tala.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - siege base164"
	GameMapToUseOn = "map wor umbar.map"
PlayerPositions = 2 3 4 5 6 7 8
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - fortress base164"
	GameMapToUseOn = "map wor umbar.map"
PlayerPositions = 1

End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base165"
	GameMapToUseOn = "map wor vale of anduin.map"
End


AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base166"
	GameMapToUseOn = "map wor vales of celduin.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base167"
	GameMapToUseOn = "map wor weather hills.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base168"
	GameMapToUseOn = "map wor weathertop.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base169"
	GameMapToUseOn = "map wor west emnet.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base170"
	GameMapToUseOn = "map wor westfold.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base171"
	GameMapToUseOn = "map wor white pillar.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base172"
	GameMapToUseOn = "map wor withered heath.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - siege base173"
	GameMapToUseOn = "map wor wulfborg.map"
PlayerPositions = 2 3 4 5 6 7 8
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - fortress base173"
	GameMapToUseOn = "map wor wulfborg.map"
PlayerPositions = 1

End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - siege base174"
	GameMapToUseOn = "map worla minas ithil.map"
PlayerPositions = 2 3 4 5 6 7 8
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - fortress base174"
	GameMapToUseOn = "map worla minas ithil.map"
PlayerPositions = 1

End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base175"
	GameMapToUseOn = "map wor foundations of stone.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base176"
	GameMapToUseOn = "map wor silvertine.map"
End


AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base177"
	GameMapToUseOn = "map worla northern greenwood.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base178"
	GameMapToUseOn = "map worla greenwood.map"
End

AIBase RohanBase
	Side = Rohan
	Map = "wotr base - rohan - standard base179"
	GameMapToUseOn = "map worla grey marshes.map"
End