Weather

	HardwareFogColor = R:110 G:130 B:140
	HardwareFogEnable = Yes
	HardwareFogStart = 400
	HardwareFogEnd = 5000

End

WaterTransparency
  ReflectionPlaneZ = 58.0;
  ReflectionOn = Yes
End

FXParticleSystem FogMist;FXParticleSystem CINECampfireEmbers;ground fog

  System
    Priority = VERY_LOW_OR_ABOVE
	Shader = ALPHA
    ParticleName = EXCloud02.tga; EXCineSparks.tga
    Lifetime = 150 150
    SortLevel = 1
    Size = .8 1
    BurstDelay = 10 20; 1 10
    BurstCount = 8 15; 3 5
  End
 
  Color = DefaultColor
    Color1 = R:185 G:185 B:185 0; R:205 G:192 B:168 0; R:255 G:185 B:79 0
    ;Color2 = R:105 G:92 B:68 50; R:0 G:0 B:0 200
    ;ColorScale = 2 -2
  End
    Alpha = DefaultAlpha
    ;Alpha1 = 0 0 50
	Alpha2 = 0.05 0.05 50; 0.1 0.1 50
    Alpha3 = 0 0 120; 150
  End
  Update = DefaultUpdate
    SizeRate = 1 3; 1 3
    SizeRateDamping = 0.9 0.99
    ;AngularRateZ = -0.02 0.02
    ;AngularDamping = 1 1
    ;AngularDampingXY = 1 1
  End
  Physics = DefaultPhysics
    ;Gravity = -0.008
    VelocityDamping = 0.95 0.99
    DriftVelocity = X:0.2 Y:0.-2 Z:0.08; X:0 Y:0 Z:0.64
  End
  EmissionVelocity = OrthoEmissionVelocity
  X = .5 1
  Y = -1 1
  Z = 0 0.1
	End
  EmissionVolume = CylinderEmissionVolume
    Radius = 120
	Length = 2
	Offset = X:0 Y:0 Z:20
  End
  Draw = DefaultDraw
  End
  Wind = DefaultWind
    WindMotion = PingPong

    WindStrength = 0.25; 0.25
    WindFullStrengthDist = 5
    WindZeroStrengthDist = 100
    WindAngleChangeMin = 0.034907
    WindAngleChangeMax = 0.034907
    WindPingPongStartAngleMin = 1.22173
    WindPingPongStartAngleMax = 1.22173
    WindPingPongEndAngleMin = 1.91986
    WindPingPongEndAngleMax = 1.91986
    TurbulenceAmplitude = 0.2
    TurbulenceFrequency = 50
  End
End

Object CINE_ParticleSysProxy2

  ; *** ART Parameters ***
 ReplaceModule ModuleTag_01
  Draw = W3DScriptedModelDraw ModuleTag_01_Override
    DefaultModelConditionState
      Model = NONE
      ParticleSysBone = emberBone LightSunRays
      ParticleSysBone = None None;FireSmokeBig
    End
  
    ModelConditionState = WORLD_BUILDER
	  Model = locator
	End
  End
 End
End


Object CINE_ParticleSysProxy4

  ; *** ART Parameters ***
 ReplaceModule ModuleTag_01
  Draw = W3DScriptedModelDraw ModuleTag_01_Override
    DefaultModelConditionState
      Model = NONE
      ParticleSysBone = emberBone FlowerPollen; campfireEmbers
      ParticleSysBone = None None;FireSmokeBig
    End
  
    ModelConditionState = WORLD_BUILDER
	  Model = locator
	End
  End
 End
End



Object CINEfireMedium ; The name of your object
AddModule ; Tells the game we want to add a 'module' to this object
    Behavior = LifetimeUpdate ModuleTag_LifetimeUpdate ; tells the game what module we want (LifetimeUpdate) and what its called (ModuleTag_LifetimeUpdate)
        MinLifetime        = 6000 ; Minimum timer it can spawn with
        MaxLifetime        = 6000 ; Maximum timer it can spawn with
        DeathType        = FADED ; How the object 'dies' once the timer runs out
    End ; closes code for Behaviour
End ; closes code for AddModule
End ; closes code for Object









;startOfAuto-Generation
;------------------------------------------------------------------------;
;	#################### WAR OF THE RING SETTINGS ####################   ;
;   - Upgrade_WOTRMode is now used to deal with WOTR commandsets         ;
;------------------------------------------------------------------------;
;-------------------
;	GONDOR
;-------------------
PlayerTemplate FactionMen
	StartMoney        				= 0
	SpellBookMp						= MenSpellBook_WOTR
	PurchaseScienceCommandSetMP		= MenSpellStoreCommandSet_WOTR
	InitialUpgrades					= Upgrade_MenFaction Upgrade_WOTRMode
	BuildableHeroesMP				= CreateAHero GondorPippin_WOTR GondorForlong_WOTR GondorBeregond_WOTR GondorImrahil_WOTR GondorDenethor_WOTR GondorFaramir GondorBoromir GondorGandalf_WOTR
End

;-------------------
;	ROHAN
;-------------------
PlayerTemplate FactionRohan
	StartMoney        				= 0
	SpellBookMp						= RohanSpellBook_WOTR
	PurchaseScienceCommandSetMP		= RohanSpellStoreCommandSet_WOTR
	InitialUpgrades					= Upgrade_RohanFaction Upgrade_WOTRMode
	BuildableHeroesMP				= CreateAHero RohanMerry_WOTR RohanEowyn_WOTR RohanElfhelm_WOTR RohanErkenbrand RohanTheodred RohanEomer RohanTheoden
End

;-------------------
;	LOTHLORIEN
;-------------------
PlayerTemplate FactionElves
	StartMoney        				= 0
	SpellBookMp						= ElvesSpellBook_WOTR
	PurchaseScienceCommandSetMP		= ElvesSpellStoreCommandSet_WOTR
	InitialUpgrades					= Upgrade_ElfFaction Upgrade_WOTRMode
	BuildableHeroesMP				= CreateAHero ElvenOrophin_WOTR ElvenRumil ElvenIdrial_WOTR ElvenHaldir ElvenCeleborn ElvenGaladrielLorien_WOTR MirkwoodThranduil_NCS
End

;-------------------
;	RIVENDELL
;-------------------
PlayerTemplate FactionArnor
	StartMoney        				= 0
	SpellBookMp						= ArnorSpellBook_WOTR
	PurchaseScienceCommandSetMP		= ArnorSpellStoreCommandSet_WOTR
	InitialUpgrades					= Upgrade_ArnorFaction Upgrade_WOTRMode	
	BuildableHeroesMP				= CreateAHero ArnorFattyBolger_WOTR ArnorFarmerMaggot_WOTR ElvenArwen_WOTR ElvenGildor ElvenElladan_WOTR ElvenElrohir_WOTR ArnorHalbarad_WOTR ElvenAragorn ElvenGlorfindel_WOTR ElvenElrond_WOTR
End

;-------------------
;	MIRKWOOD
;-------------------
PlayerTemplate FactionMirkwood
	StartMoney        				= 0
	SpellBookMp						= MirkwoodSpellBook_WOTR
	PurchaseScienceCommandSetMP		= MirkwoodSpellStoreCommandSet_WOTR
	InitialUpgrades					= Upgrade_MirkwoodFaction Upgrade_WOTRMode	
	BuildableHeroesMP				= CreateAHero MirkwoodTauriel MirkwoodGalion_WOTR MirkwoodFeren DorwinionFrumgar_WOTR MirkwoodRadagast_WOTR MirkwoodGrimbeorn_WOTR MirkwoodLegolas MirkwoodThranduil
End

;-------------------
;	EREBOR
;-------------------
PlayerTemplate FactionDwarves
	StartMoney        				= 0
	SpellBookMp						= DwarvesSpellBook_WOTR
	PurchaseScienceCommandSetMP		= DwarvesSpellStoreCommandSet_WOTR
	InitialUpgrades					= Upgrade_DwarfFaction Upgrade_WOTRMode	
	BuildableHeroesMP				= CreateAHero DwarvenArcah_WOTR DwarvenGloin_WOTR DwarvenHadhod_WOTR DwarvenBrand_WOTR DwarvenGimli_WOTR DwarvenThorinStonehelm_WOTR DwarvenKingDain_WOTR YoungThorin_WOTR DwarvenThrain_WOTR YoungDain_WOTR YoungDwalin_WOTR YoungBalin_WOTR
End

;-------------------
;	MORDOR
;-------------------
PlayerTemplate FactionMordor
	StartMoney        				= 0
	SpellBookMp						= MordorSpellBook_WOTR
	PurchaseScienceCommandSetMP		= MordorSpellStoreCommandSet_WOTR
	InitialUpgrades					= Upgrade_MordorDualEconomyChoice Upgrade_MordorFaction Upgrade_EvilDualEconomyChoice Upgrade_WOTRMode
	BuildableHeroesMP				= CreateAHero MordorGorbag_WOTR MordorShagrat_WOTR MordorAkhorahil_WOTR MordorUvatha_WOTR  MordorGothmog MordorMouthOfSauron MordorMollok_WOTR MordorWitchKing_WOTR RhunBelokhZa_WOTR RhunKhrenTak_WOTR RhunVahRus_WOTR
End

;-------------------
;	ISENGARD
;-------------------
PlayerTemplate FactionIsengard
	StartMoney        				= 0
	SpellBookMp						= IsengardSpellBook_WOTR
	PurchaseScienceCommandSetMP		= IsengardSpellStoreCommandSet_WOTR
	InitialUpgrades					= Upgrade_IsengardDualEconomyChoice Upgrade_IsengardFaction Upgrade_EvilDualEconomyChoice Upgrade_WOTRMode
	BuildableHeroesMP				= CreateAHero IsengardGrishnakh_WOTR IsengardWormTongue_WOTR IsengardSharku_WOTR IsengardUgluk IsengardLurtz IsengardWulfgar_WOTR IsengardSaruman_WOTR
End

;-------------------
;	MISTY MOUNTAINS
;-------------------
PlayerTemplate FactionWild
	StartMoney        				= 0
	SpellBookMp						= WildSpellBook_WOTR
	PurchaseScienceCommandSetMP		= WildSpellStoreCommandSet_WOTR
	InitialUpgrades					= Upgrade_WildFaction Upgrade_GoblinDualEconomyChoice Upgrade_EvilDualEconomyChoice Upgrade_WOTRMode	
	BuildableHeroesMP				= CreateAHero WildMuzgash WildGolfimbul_WOTR WildUrshak WildLugtheMauled_WOTR WildGreatGoblin WildBolgNew_WOTR WildTrueAzog_WOTR
End

;-------------------
;	DOL GULDUR
;-------------------
PlayerTemplate FactionGuldur
	StartMoney        				= 0
	SpellBookMp						= GuldurSpellBook_WOTR
	PurchaseScienceCommandSetMP		= GuldurSpellStoreCommandSet_WOTR
	InitialUpgrades					= Upgrade_GuldurFaction Upgrade_MordorDualEconomyChoice Upgrade_EvilDualEconomyChoice Upgrade_WOTRMode
	BuildableHeroesMP				= CreateAHero GuldurThrain_WOTR GuldurKrimpul_WOTR GuldurCargast_WOTR GuldurSaenathra_WOTR GuldurKhamul_WOTR GuldurNecromancer_WOTR
End

;-------------------
;	HARADWAITH
;-------------------
PlayerTemplate FactionAngmar
	StartMoney        				= 0
	SpellBookMp						= AngmarSpellBook_WOTR
	PurchaseScienceCommandSetMP		= AngmarSpellStoreCommandSet_WOTR
	InitialUpgrades					= Upgrade_AngmarFaction Upgrade_WOTRMode
	BuildableHeroesMP				= CreateAHero HaradBeruthiel_WOTR HaradSyarRhul_WOTR HaradSuladan HaradBurodapan HaradCassimir HaradCaranLambar_WOTR HaradGoldenKing
End

SkirmishAIData TheSkirmishAIData
    DisableBaseBuilding        = No
    DisableEconomyBuilding    = Yes
    DisableUnitBuilding        = No
    DisableScienceUpgrading = No
    DisableUnitUpgrading    = No
    DisableTacticalAI        = No
    DisableTeamBuilding        = No
    DisableWallBuilding        = Yes ;,; No

    AnyTypeTemplateDisabledSlots = 1
    AnyTypeTemplateDisabledSlots = 2
    AnyTypeTemplateDisabledSlots = 3
    AnyTypeTemplateDisabledSlots = 4
    AnyTypeTemplateDisabledSlots = 5
    AnyTypeTemplateDisabledSlots = 6
End
;------------------------------------------------------------------------;
;	  ENEDWAITH REGION 														 ;
;------------------------------------------------------------------------;
Object Inn
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Enedwaith
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Enedwaith
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Enedwaith
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Enedwaith
		End
	End
End
Object InnDesert
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Enedwaith
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Enedwaith
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Enedwaith
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Enedwaith
		End
	End
End
Object InnSnow
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Enedwaith
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Enedwaith
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Enedwaith
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Enedwaith
		End
	End
End
Object Inn_old
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Enedwaith
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Enedwaith
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Enedwaith
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Enedwaith
		End
	End
End
;endOfAuto-Generation
