PlayerTemplate FactionCivilian
	Side              = Civilian
	PlayableSide      = No
	StartMoney        = 0
	PreferredColor    = R:64 G:64 B:64
	IntrinsicSciences = None
	DisplayName       = INI:FactionCivilian
	ScoreScreenImage  = MutiPlayer_ScoreScreen
	LoadScreenMusic   = Shell2MusicForLoadScreen
	IntrinsicSciences			= SCIENCE_EVIL
	IntrinsicSciencesMP 			= SCIENCE_GULDUR
	SpellBook				= EvilSpellBook
	SpellBookMp				= GuldurSpellBook
	PurchaseScienceCommandSet		= EvilSpellStoreCommandSet
	PurchaseScienceCommandSetMP		= GuldurSpellStoreCommandSet
End


ShadowMap
    MapSize = 2048
    MaxViewDistance = 900.0
    MinShadowedTerrainHeight = 0.0
End

Object UniversalBuildingFoundation
	ReplaceModule ModuleTag_DrawGuldurFloor
	Draw = W3DFloorDraw ModuleTag_DrawGuldurFloor_New
		ModelName		= UBFoundatiotX
		HideIfModelConditions	= USER_1	; Gondor
		HideIfModelConditions	= USER_2	; Rohan
		HideIfModelConditions	= USER_3	; Lothlorien
		HideIfModelConditions	= USER_4	; Dwarves
		HideIfModelConditions	= USER_5	; Mordor
		HideIfModelConditions	= USER_6	; Isengard
		HideIfModelConditions	= USER_7	; Goblins
		HideIfModelConditions	= USER_8	; Rivendell	
		HideIfModelConditions	= USER_10	; Mirkwood		
	End
	End
End	

;--------------------------------------------------------------------------
; Guldur Castle Setup
;--------------------------------------------------------------------------
 
Object GuldurCatapultExpansion
ReplaceModule ModuleTag_04
 	Behavior = GettingBuiltBehavior GetBuiltBehaviorTagX
		SpawnTimer	= DEFAULT_STRUCTURE_HEALDELAY
		RebuildWhenDead = Yes
        SelfBuildingLoop = BuildingConstructionLoop ; Only played if we DON'T spawn a worker
		SelfRepairFromDamageLoop  = NoSound         ; This doesn't cause an animation, so don't bother playing a sound
		SelfRepairFromRubbleLoop  = BuildingConstructionLoop
	End
End
End

 
Object GuldurBarricadeExpansionA
ReplaceModule ModuleTag_04
 	Behavior = GettingBuiltBehavior GetBuiltBehaviorTagX
		SpawnTimer	= DEFAULT_STRUCTURE_HEALDELAY
		RebuildWhenDead = Yes
        SelfBuildingLoop = BuildingConstructionLoop ; Only played if we DON'T spawn a worker
		SelfRepairFromDamageLoop  = NoSound         ; This doesn't cause an animation, so don't bother playing a sound
		SelfRepairFromRubbleLoop  = BuildingConstructionLoop
	End
End
End

ChildObject GuldurBarricadeExpansionB GuldurBarricadeExpansionA
ReplaceModule ModuleTag_04
 	Behavior = GettingBuiltBehavior GetBuiltBehaviorTagX
		SpawnTimer	= DEFAULT_STRUCTURE_HEALDELAY
		RebuildWhenDead = Yes
        SelfBuildingLoop = BuildingConstructionLoop ; Only played if we DON'T spawn a worker
		SelfRepairFromDamageLoop  = NoSound         ; This doesn't cause an animation, so don't bother playing a sound
		SelfRepairFromRubbleLoop  = BuildingConstructionLoop
	End
End
End
 
ChildObject GuldurFountOfCorruptionFoundation GuldurFountOfCorruption
ReplaceModule GetBuiltBehaviorTag
 	Behavior = GettingBuiltBehavior GetBuiltBehaviorTagX
		SpawnTimer	= DEFAULT_STRUCTURE_HEALDELAY
		RebuildWhenDead = Yes
        SelfBuildingLoop = BuildingConstructionLoop ; Only played if we DON'T spawn a worker
		SelfRepairFromDamageLoop  = NoSound         ; This doesn't cause an animation, so don't bother playing a sound
		SelfRepairFromRubbleLoop  = BuildingConstructionLoop
	End
End
End

ChildObject GuldurGaolFoundation GuldurGaol
ReplaceModule ModuleTag_04
 	Behavior = GettingBuiltBehavior GetBuiltBehaviorTagX
		SpawnTimer	= DEFAULT_STRUCTURE_HEALDELAY
		RebuildWhenDead = Yes
        SelfBuildingLoop = BuildingConstructionLoop ; Only played if we DON'T spawn a worker
		SelfRepairFromDamageLoop  = NoSound         ; This doesn't cause an animation, so don't bother playing a sound
		SelfRepairFromRubbleLoop  = BuildingConstructionLoop
	End
End
End

ChildObject GuldurSorceryTowerFoundation GuldurSorceryTower
ReplaceModule GetBuiltBehaviorTag
 	Behavior = GettingBuiltBehavior GetBuiltBehaviorTagX
		SpawnTimer	= DEFAULT_STRUCTURE_HEALDELAY
		RebuildWhenDead = Yes
        SelfBuildingLoop = BuildingConstructionLoop ; Only played if we DON'T spawn a worker
		SelfRepairFromDamageLoop  = NoSound         ; This doesn't cause an animation, so don't bother playing a sound
		SelfRepairFromRubbleLoop  = BuildingConstructionLoop
	End
End
End

ChildObject GuldurSpiderLairFoundation GuldurSpiderLair
ReplaceModule GetBuiltBehaviorTag
 	Behavior = GettingBuiltBehavior GetBuiltBehaviorTagX
		SpawnTimer	= DEFAULT_STRUCTURE_HEALDELAY
		RebuildWhenDead = Yes
        SelfBuildingLoop = BuildingConstructionLoop ; Only played if we DON'T spawn a worker
		SelfRepairFromDamageLoop  = NoSound         ; This doesn't cause an animation, so don't bother playing a sound
		SelfRepairFromRubbleLoop  = BuildingConstructionLoop
	End
End
End

Object GuldurKrimpulGaol
ReplaceModule ModuleTag_04
 	Behavior = GettingBuiltBehavior GetBuiltBehaviorTagX
		SpawnTimer	= DEFAULT_STRUCTURE_HEALDELAY
		RebuildWhenDead = Yes
        SelfBuildingLoop = BuildingConstructionLoop ; Only played if we DON'T spawn a worker
		SelfRepairFromDamageLoop  = NoSound         ; This doesn't cause an animation, so don't bother playing a sound
		SelfRepairFromRubbleLoop  = BuildingConstructionLoop
	End
End
End

ChildObject GuldurRestlessBarrowFoundation GuldurRestlessBarrow
ReplaceModule ModuleTag_04
 	Behavior = GettingBuiltBehavior GetBuiltBehaviorTagX
		SpawnTimer	= DEFAULT_STRUCTURE_HEALDELAY
		RebuildWhenDead = Yes
        SelfBuildingLoop = BuildingConstructionLoop ; Only played if we DON'T spawn a worker
		SelfRepairFromDamageLoop  = NoSound         ; This doesn't cause an animation, so don't bother playing a sound
		SelfRepairFromRubbleLoop  = BuildingConstructionLoop
	End
End
End

ChildObject GuldurRuinousTowerFoundation GuldurRuinousTower
ReplaceModule ModuleTag_04
 	Behavior = GettingBuiltBehavior GetBuiltBehaviorTagX
		SpawnTimer	= DEFAULT_STRUCTURE_HEALDELAY
		RebuildWhenDead = Yes
        SelfBuildingLoop = BuildingConstructionLoop ; Only played if we DON'T spawn a worker
		SelfRepairFromDamageLoop  = NoSound         ; This doesn't cause an animation, so don't bother playing a sound
		SelfRepairFromRubbleLoop  = BuildingConstructionLoop
	End
End
End

ChildObject GuldurSlaveMillFoundation GuldurSlaveMill
ReplaceModule GetBuiltBehaviorTag
 	Behavior = GettingBuiltBehavior GetBuiltBehaviorTagX
		SpawnTimer	= DEFAULT_STRUCTURE_HEALDELAY
		RebuildWhenDead = Yes
        SelfBuildingLoop = BuildingConstructionLoop ; Only played if we DON'T spawn a worker
		SelfRepairFromDamageLoop  = NoSound         ; This doesn't cause an animation, so don't bother playing a sound
		SelfRepairFromRubbleLoop  = BuildingConstructionLoop
	End
End
End

Weather

	HardwareFogColor = R:55 G:85 B:90
	HardwareFogEnable = Yes
	HardwareFogStart = 650
	HardwareFogEnd = 7000
	
End

;startOfAuto-Generation
;------------------------------------------------------------------------;
;	  RHOVANION REGION 														 ;
;------------------------------------------------------------------------;
Object Inn
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Rhovanion
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Rhovanion
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Rhovanion
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Rhovanion
		End
	End
End
Object InnDesert
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Rhovanion
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Rhovanion
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Rhovanion
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Rhovanion
		End
	End
End
Object InnSnow
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Rhovanion
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Rhovanion
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Rhovanion
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Rhovanion
		End
	End
End
Object Inn_old
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Rhovanion
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Rhovanion
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Rhovanion
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Rhovanion
		End
	End
End
;endOfAuto-Generation


;==== Auto Generated AI Fix =====;
SkirmishAIData TheSkirmishAIData
    DisableBaseBuilding        = No
    DisableEconomyBuilding     = No
    DisableUnitBuilding        = No
    DisableScienceUpgrading    = No
    DisableUnitUpgrading       = No
    DisableTacticalAI          = No
    DisableTeamBuilding        = No
    DisableWallBuilding        = Yes ;,; No
End
