MissionObjectiveList
	MissionObjectiveTag = SCRIPT:Objective_E08_01 ; seige riv
	BonusMissionObjectiveTag = SCRIPT:Objective_E08_02 ; kill arwen
	BonusMissionObjectiveTag = SCRIPT:Objective_E08_03 ; kill the heroes
	MissionObjectiveTag = SCRIPT:Objective_E08_04 ; destroy the house
	MissionObjectiveTag = SCRIPT:Objective_E08_05 ; Sauron must live
END
;==========CAMO BLOCK================================
Object ElvenLorienSentryHorde
  RemoveModule ModuleTag_ElvenCamouflage
END

; this guy doesnt have one... but im leaving it in just incase e gets one.
;Object ElvenRivendellLancerHorde
; RemoveModule ModuleTag_CamouflageUpdate
;END

Object ElvenLorienArcherHorde
 RemoveModule ModuleTag_ElvenCamouflage
END

;================================================

Rank 1
    SkillPointsNeededDefault        = 0
    SkillPointsNeededCampaign        = 0 
    SciencePurchasePointsGranted    = 100
End

CommandSet GuldurFortressCommandSetX
	InitialVisible = 8
	//Main Menu
	1   = Command_SpecialAbilityDarkPresence
	2   = Command_ConstructGuldurPorter
	4   = Command_SelectUpgradesGuldurFortress
	5   = Command_SpecialAbilityGuldurPalantir
	;7   = Command_SpecialAbilityGuldurDarkEncroachment
	;8   = Command_SpecialAbilityGuldurSorcery
	7   = Command_SpecialAbilityGuldurEnsnare
	6	= Command_Sell
	//Upgrades Menu
	9   = Command_PurchaseUpgradeGuldurFortressBatCloud
	10  = Command_PurchaseUpgradeGuldurFortressFireArrows
	11  = Command_PurchaseUpgradeGuldurFortressPalantir	
	12  = Command_PurchaseUpgradeGuldurFortressEncroachment
	13  = Command_PurchaseUpgradeGuldurFortressBlight
	14  = Command_PurchaseUpgradeGuldurFortressSorcery
	15	= Command_SpecialAbilityBatCloud
	16	= Command_RadialBack
End

Object GuldurFortress
CommandSet = GuldurFortressCommandSetX
	BuildTime           	= 30
End

Object GuldurFortressCitadel
CommandSet = GuldurFortressCommandSetX
	BuildTime           	= 30
End

CommandSet MordorFortressCommandSetX
	InitialVisible = 9
	//Main Menu
	1	= Command_ConstructMordorPorter
	2   = Command_SpecialAbilityDeadliestServantsPassive
;	4	= Command_FireWeaponMordorFortressSpireFireball 
	4	= Command_SelectUpgradesMordorFortress	
	5	= Command_FireWeaponMordorFortressMagmaCauldrons	
	6	= Command_Sell
	7	= Command_ConstructMordorMorgulOrcHorde
	8	= Command_ConstructMordorBlackRiderHorde
	9	= Command_SpecialAbilityMordorFortressMorgulSpire
		//Upgrades Menu
	10	= Command_PurchaseUpgradeMordorFortressDoomPyres
	11	= Command_PurchaseUpgradeMordorFortressLavaMoat
	12	= Command_PurchaseUpgradeMordorFortressMagmaCauldrons
;	11	= Command_PurchaseUpgradeMordorFortressFireArrows
;	12	= Command_PurchaseUpgradeMordorFortressShelobTerror
	13	= Command_PurchaseUpgradeMordorFortressMorgulSorcery
	14	= Command_PurchaseUpgradeMordorFortressGorgorothSpire
	15	= Command_RadialBack		
End

CommandSet WildFortressCommandSetX
	InitialVisible = 7
	//Main Menu
	1   = Command_ConstructWildPorter
	3   = Command_SelectUpgradesWildFortress
	;4	= Command_ConstructWildGundabadBodyGuardHordeFortress
	4   = Command_SpecialAbilityWildFortressSummonWyrm
	5   = Command_SpecialAbilityDrumsInTheDeep	
	6	= Command_Sell
	//Upgrades Menu
	8   = Command_PurchaseUpgradeWildFortressGoblinTown
	9	= Command_PurchaseUpgradeWildFortressWebCocoon	
	10  = Command_PurchaseUpgradeWildFortressNorthernWastes
	11	= Command_PurchaseUpgradeWildFortressBatCloud
	12	= Command_PurchaseUpgradeWildFortressRazorSpines
	13	= Command_PurchaseUpgradeWildFortressFireArrows
	14	= Command_PurchaseUpgradeWildFortressDrumsInTheDeep	
	15	= Command_SpecialAbilityBatCloud
	16	= Command_RadialBack		 
End

CommandSet GoblinCaveCommandSetX
	1 = Command_ConstructGoblinFighterHorde
	2 = Command_ConstructGoblinArcherHorde
	3 = Command_ConstructMoriaSpearmanHorde
      4 = Command_ConstructMoriaShamanHorde
	5 = Command_Sell
	6 = Command_ConstructHobgoblinPlundererHorde
	7 = Command_PurchaseUpgradeWildCaveLevel2
End
CommandSet GoblinCaveCommandSetLevel2X
	1 = Command_ConstructGoblinFighterHorde
	2 = Command_ConstructGoblinArcherHorde
	3 = Command_ConstructMoriaSpearmanHorde
	4 = Command_ConstructMoriaShamanHorde
      5 = Command_Sell
	6 = Command_ConstructHobgoblinPlundererHorde
	7 = Command_PurchaseUpgradeWildCaveLevel3
End
CommandSet GoblinCaveCommandSetLevel3X
	1 = Command_ConstructGoblinFighterHorde
	2 = Command_ConstructGoblinArcherHorde
	3 = Command_ConstructMoriaSpearmanHorde
	4 = Command_ConstructMoriaShamanHorde
      5 = Command_Sell
	6 = Command_ConstructHobgoblinPlundererHorde
End

Object GoblinCave
CommandSet	= GoblinCaveCommandSetX
	ReplaceModule ModueTag_CaveLevel2CommandSet
	Behavior = CommandSetUpgrade ModueTag_MoriaCaveLevel2CommandSet
		TriggeredBy			= Upgrade_StructureLevel2
		ConflictsWith		= Upgrade_StructureLevel3 Upgrade_WildFortressWebCocoonTrigger
		CommandSet			= GoblinCaveCommandSetLevel2X
	End
	End
	ReplaceModule ModueTag_CaveLevel3CommandSet
	Behavior = CommandSetUpgrade ModueTag_MoriaCaveLevel3CommandSet
		TriggeredBy			= Upgrade_StructureLevel3
		ConflictsWith		= Upgrade_WildFortressWebCocoonTrigger
		CommandSet			= GoblinCaveCommandSetLevel3X
	End
	End
End

Object WildFortress
CommandSet = WildFortressCommandSetX
	BuildTime           	= 30
End

Object WildFortressCitadel
CommandSet = WildFortressCommandSetX
	BuildTime           	= 30
ReplaceModule ModuleTag_DwarvenGuardianHordeBladesCommandSet
Behavior = CommandSetUpgrade ModuleTag_DwarvenGuardianHordeBladesCommandSetX
		TriggeredBy		= Upgrade_WildFortressGoblinTownTrigger
		CommandSet		= WildFortressCommandSetX
	End	
End
End

Object MordorFortress
	BuildTime = 30 
END


Object MordorFortressCitadel
	CommandSet = MordorFortressCommandSetX
ReplaceModule ModuleTag_MorgulCommandSet
Behavior = CommandSetUpgrade ModuleTag_MorgulCommandSetX
		TriggeredBy		= Upgrade_MordorFortressMorgulSorceryTrigger
		ConflictsWith	= Upgrade_WOTRMode		
		CommandSet		= MordorFortressCommandSetX
	End	
End
End

Object RohanOathbreakerHordeSmall
 ReplaceModule ModuleTag_LifetimeUpdate
   Behavior = LifetimeUpdate ModuleTag_LifetimeUpdate_Evil_Riv
		MinLifetime		= 3000000
		MaxLifetime		= 3000000
	End	
 End
END

Object MordorFellBeast
DisplayName      = OBJECT:MordorAkhorahil
End 

;=================================================================================

; WaterTransparency can be overridden per each map to change these values.
WaterTransparency
  ReflectionPlaneZ = 295.0;
  ReflectionOn = Yes
End


Weather

  HardwareFogColor = R:220 G:226 B:235

  HardwareFogEnable = Yes

  HardwareFogStart = 450

  HardwareFogEnd = 3000

End

;-----------------------------------------------------------------

AIData

  LowLodTreeName = TreeLowLODGreyHavens
  MinFlightHeight = 300

END

;-----------------------------------------------------------------

SkirmishAIData TheSkirmishAIData
	CombatChainDefinition ArcherCombatChain
		Unit = ARCHER
		TargetTypes				= STRUCTURE	INFANTRY	CAVALRY	ARCHER	PIKEMAN	WALL	CREEP	HERO
		TargetPriorityModifiers	= -1.0		350.0		0.0		0.0		100.0	-1.0	0.0		0.0
	End
End

;-------------------------------------------------------------------------------------------------------
; BFME 2 SPELLBOOK
;-------------------------------------------------------------------------------------------------------


CommandSet EvilSpellBookCommandSetX
	1 = Command_SpellBookWarChantMordor
	2 = Command_SpellBookCaveBats
	3 = Command_SpellBookChillWind
	
	4 = Command_SpellBookGuldurForestOfFear
	5 = Command_SpellBookGuldurBlackWarg
	6 = Command_SpellBookAOTRScavenger
	7 = Command_SpellBookBarricade
	
	8 = Command_SpellBookWatcherAlly
	9 = Command_SpellBookGuldurDarkness
	10 = Command_SpellBookDragonStrike
	
	11 = Command_SpellBookRainOfFire
	12 = Command_SpellBookEyeofSauronNew
End

CommandSet EvilSpellStoreCommandSetX
	1 = Command_PurchaseSpellWarChantMordor
	2 = Command_PurchaseSpellCaveBats
	3 = Command_PurchaseSpellChillWind
	
	4 = Command_PurchaseSpellGuldurForestOfFear
	5 = Command_PurchaseSpellGuldurBlackWarg
	6 = Command_PurchaseSpellAOTRScavenger
	7 = Command_PurchaseSpellBarricade
	
	8 = Command_PurchaseSpellWatcherAlly
	9 = Command_PurchaseSpellGuldurDarkness
	10 = Command_PurchaseSpellDragonStrike
	
	11 = Command_PurchaseSpellRainOfFire
	12 = Command_PurchaseSpellEyeofSauronNew
End


;-------5 points
Science SCIENCE_WarChantMordor
  PrerequisiteSciences = SCIENCE_MORDOR OR SCIENCE_EVIL
  SciencePurchasePointCost = EVIL_RANK_1_COST
  SciencePurchasePointCostMP = 5
  IsGrantable = Yes
End
Science SCIENCE_CaveBats
  PrerequisiteSciences = SCIENCE_EVIL OR SCIENCE_MORDOR OR SCIENCE_ELVES OR SCIENCE_DWARVES OR SCIENCE_ARNOR
  SciencePurchasePointCost = EVIL_RANK_1_COST
  SciencePurchasePointCostMP = 5
  IsGrantable = Yes
End
Science SCIENCE_ChillWind
  PrerequisiteSciences = SCIENCE_GULDUR OR SCIENCE_EVIL ;SCIENCE_EnshroudingMistSP
  SciencePurchasePointCost = EVIL_RANK_1_COST
  SciencePurchasePointCostMP = 5
  IsGrantable = Yes
End
;-------10 points
Science SCIENCE_GuldurFearForest
  PrerequisiteSciences = SCIENCE_GULDUR OR SCIENCE_EVIL SCIENCE_WarChantMordor
  SciencePurchasePointCost = EVIL_RANK_2_COST
  SciencePurchasePointCostMP = 10
  IsGrantable = Yes
End
Science SCIENCE_GuldurBlackWarg
  PrerequisiteSciences = SCIENCE_EVIL OR SCIENCE_EVIL SCIENCE_WarChantMordor OR SCIENCE_EVIL SCIENCE_CaveBats
  SciencePurchasePointCost = EVIL_RANK_2_COST
  SciencePurchasePointCostMP = 10
  IsGrantable = Yes
End
Science SCIENCE_Scavenger
  PrerequisiteSciences = SCIENCE_GULDUR OR SCIENCE_EVIL SCIENCE_CaveBats OR SCIENCE_ChillWind
  SciencePurchasePointCost = EVIL_RANK_2_COST
  SciencePurchasePointCostMP = 10
  IsGrantable = Yes
End
Science SCIENCE_Barricade
  PrerequisiteSciences = SCIENCE_GULDUR OR SCIENCE_EVIL SCIENCE_ChillWind
  SciencePurchasePointCost = EVIL_RANK_2_COST
  SciencePurchasePointCostMP = 10
  IsGrantable = Yes
End
;-------15 points
Science SCIENCE_WatcherAlly
  PrerequisiteSciences = SCIENCE_GULDUR OR SCIENCE_EVIL SCIENCE_GuldurFearForest OR SCIENCE_GuldurBlackWarg
  SciencePurchasePointCost = EVIL_RANK_3_COST
  SciencePurchasePointCostMP = 15
  IsGrantable = Yes
End
Science SCIENCE_GuldurDarkness
  PrerequisiteSciences = SCIENCE_GULDUR OR SCIENCE_EVIL SCIENCE_GuldurBlackWarg OR SCIENCE_Scavenger
  SciencePurchasePointCost = EVIL_RANK_3_COST
  SciencePurchasePointCostMP = 15
  IsGrantable = Yes
End
Science SCIENCE_DragonStrike
  PrerequisiteSciences = SCIENCE_GULDUR OR SCIENCE_EVIL SCIENCE_Scavenger OR SCIENCE_Barricade
  SciencePurchasePointCost = EVIL_RANK_3_COST
  SciencePurchasePointCostMP = 15
  IsGrantable = Yes
End
;-------25 points
Science SCIENCE_RainOfFire
  PrerequisiteSciences = SCIENCE_GULDUR OR SCIENCE_EVIL SCIENCE_WatcherAlly OR SCIENCE_GuldurDarkness
  SciencePurchasePointCost = EVIL_RANK_4_COST
  SciencePurchasePointCostMP = 25
  IsGrantable = Yes
End
Science SCIENCE_EyeofSauronNew
  PrerequisiteSciences = SCIENCE_GULDUR OR SCIENCE_EVIL SCIENCE_DragonStrike OR SCIENCE_GuldurDarkness
  SciencePurchasePointCost = EVIL_RANK_4_COST
  SciencePurchasePointCostMP = 25
  IsGrantable = Yes
End

Object EvilSpellBook
CommandSet = EvilSpellBookCommandSetX
End


;-------------------------------------------------------------------------------------------------
;BFME 2 PLAYER PORTERS AND SPELLBOOK
;-------------------------------------------------------------------------------------------------

PlayerTemplate FactionCivilian
StartingBuilding = NONE
StartingUnit0 = NONE
StartingUnit1 = NONE
StartingUnit2 =  NONE
StartingUnitOffset2 = X:300 Y:0 Z:0
StartingUnit3 = NONE
StartingUnitOffset3 = X:0 Y:300 Z:0
StartingUnit4 = NONE
StartingUnitOffset4 = X:-300 Y:0 Z:0
StartingUnit7 = NONE
StartingUnitOffset7 = X:0 Y:-300 Z:0
StartMoney = 0
DefaultPlayerAIType		= NONE
	IntrinsicSciences		= SCIENCE_GOOD
	IntrinsicSciencesMP 		= SCIENCE_GOOD
	SpellBook			= GoodSpellBook
	SpellBookMp			= GoodSpellBook
	PurchaseScienceCommandSet	= GoodSpellStoreCommandSetX
	PurchaseScienceCommandSetMP	= GoodSpellStoreCommandSetX
End

PlayerTemplate FactionMen
Side = Fellowship
StartingBuilding = NONE
StartingUnit0 = NONE
StartingUnit1 = NONE
StartingUnit2 =  NONE
StartingUnitOffset2 = X:300 Y:0 Z:0
StartingUnit3 = NONE
StartingUnitOffset3 = X:0 Y:300 Z:0
StartingUnit4 = NONE
StartingUnitOffset4 = X:-300 Y:0 Z:0
StartingUnit7 = NONE
StartingUnitOffset7 = X:0 Y:-300 Z:0
StartMoney = 0
BuildableHeroesMP		= NONE
DefaultPlayerAIType		= NONE
	IntrinsicSciences		= SCIENCE_EVIL
	IntrinsicSciencesMP 		= SCIENCE_EVIL
	SpellBook			= EvilSpellBook
	SpellBookMp			= EvilSpellBook
	PurchaseScienceCommandSet	= EvilSpellStoreCommandSetX
	PurchaseScienceCommandSetMP	= EvilSpellStoreCommandSetX
End

PlayerTemplate FactionDwarves
StartingBuilding = NONE
StartingUnit0 = NONE
StartingUnit1 = NONE
StartingUnit2 =  NONE
StartingUnitOffset2 = X:300 Y:0 Z:0
StartingUnit3 = NONE
StartingUnitOffset3 = X:0 Y:300 Z:0
StartingUnit4 = NONE
StartingUnitOffset4 = X:-300 Y:0 Z:0
StartingUnit7 = NONE
StartingUnitOffset7 = X:0 Y:-300 Z:0
StartMoney = 0
BuildableHeroesMP		= NONE
DefaultPlayerAIType		= NONE
	IntrinsicSciences		= SCIENCE_EVIL
	IntrinsicSciencesMP 		= SCIENCE_EVIL
	SpellBook			= EvilSpellBook
	SpellBookMp			= EvilSpellBook
	PurchaseScienceCommandSet	= EvilSpellStoreCommandSetX
	PurchaseScienceCommandSetMP	= EvilSpellStoreCommandSetX
End

PlayerTemplate FactionElves
StartingBuilding = NONE
StartingUnit0 = NONE
StartingUnit1 = NONE
StartingUnit2 =  NONE
StartingUnitOffset2 = X:300 Y:0 Z:0
StartingUnit3 = NONE
StartingUnitOffset3 = X:0 Y:300 Z:0
StartingUnit4 = NONE
StartingUnitOffset4 = X:-300 Y:0 Z:0
StartingUnit7 = NONE
StartingUnitOffset7 = X:0 Y:-300 Z:0
StartMoney = 0
BuildableHeroesMP		= NONE
DefaultPlayerAIType		= NONE
	IntrinsicSciences		= SCIENCE_EVIL
	IntrinsicSciencesMP 		= SCIENCE_EVIL
	SpellBook			= EvilSpellBook
	SpellBookMp			= EvilSpellBook
	PurchaseScienceCommandSet	= EvilSpellStoreCommandSetX
	PurchaseScienceCommandSetMP	= EvilSpellStoreCommandSetX
End

PlayerTemplate FactionRohan
Side = Fellowship
StartingBuilding = NONE
StartingUnit0 = NONE
StartingUnit1 = NONE
StartingUnit2 =  NONE
StartingUnitOffset2 = X:300 Y:0 Z:0
StartingUnit3 = NONE
StartingUnitOffset3 = X:0 Y:300 Z:0
StartingUnit4 = NONE
StartingUnitOffset4 = X:-300 Y:0 Z:0
StartingUnit7 = NONE
StartingUnitOffset7 = X:0 Y:-300 Z:0
StartMoney = 0
BuildableHeroesMP		= NONE
DefaultPlayerAIType		= NONE
	IntrinsicSciences		= SCIENCE_EVIL
	IntrinsicSciencesMP 		= SCIENCE_EVIL
	SpellBook			= EvilSpellBook
	SpellBookMp			= EvilSpellBook
	PurchaseScienceCommandSet	= EvilSpellStoreCommandSetX
	PurchaseScienceCommandSetMP	= EvilSpellStoreCommandSetX
End

PlayerTemplate FactionGuldur
StartingBuilding = NONE
StartingUnit0 = NONE
StartingUnit1 = NONE
StartingUnit2 =  NONE
StartingUnitOffset2 = X:300 Y:0 Z:0
StartingUnit3 = NONE
StartingUnitOffset3 = X:0 Y:300 Z:0
StartingUnit4 = NONE
StartingUnitOffset4 = X:-300 Y:0 Z:0
StartingUnit7 = NONE
StartingUnitOffset7 = X:0 Y:-300 Z:0
StartMoney = 0
BuildableHeroesMP		= NONE
DefaultPlayerAIType		= NONE
	IntrinsicSciences		= SCIENCE_EVIL
	IntrinsicSciencesMP 		= SCIENCE_EVIL
	SpellBook			= EvilSpellBook
	SpellBookMp			= EvilSpellBook
	PurchaseScienceCommandSet	= EvilSpellStoreCommandSetX
	PurchaseScienceCommandSetMP	= EvilSpellStoreCommandSetX
End

PlayerTemplate FactionWild
StartingBuilding = NONE
StartingUnit0 = NONE
StartingUnit1 = NONE
StartingUnit2 =  NONE
StartingUnitOffset2 = X:300 Y:0 Z:0
StartingUnit3 = NONE
StartingUnitOffset3 = X:0 Y:300 Z:0
StartingUnit4 = NONE
StartingUnitOffset4 = X:-300 Y:0 Z:0
StartingUnit7 = NONE
StartingUnitOffset7 = X:0 Y:-300 Z:0
StartMoney = 0
BuildableHeroesMP		= NONE
DefaultPlayerAIType		= NONE
	IntrinsicSciences		= SCIENCE_EVIL
	IntrinsicSciencesMP 		= SCIENCE_EVIL
	SpellBook			= EvilSpellBook
	SpellBookMp			= EvilSpellBook
	PurchaseScienceCommandSet	= EvilSpellStoreCommandSetX
	PurchaseScienceCommandSetMP	= EvilSpellStoreCommandSetX
End


PlayerTemplate FactionMordor
StartingBuilding = NONE
StartingUnit0 = NONE
StartingUnit1 = NONE
StartingUnit2 =  NONE
StartingUnitOffset2 = X:300 Y:0 Z:0
StartingUnit3 = NONE
StartingUnitOffset3 = X:0 Y:300 Z:0
StartingUnit4 = NONE
StartingUnitOffset4 = X:-300 Y:0 Z:0
StartingUnit7 = NONE
StartingUnitOffset7 = X:0 Y:-300 Z:0
StartMoney = 0
BuildableHeroesMP		= NONE
DefaultPlayerAIType		= NONE
	IntrinsicSciences		= SCIENCE_EVIL
	IntrinsicSciencesMP 		= SCIENCE_EVIL
	SpellBook			= EvilSpellBook
	SpellBookMp			= EvilSpellBook
	PurchaseScienceCommandSet	= EvilSpellStoreCommandSetX
	PurchaseScienceCommandSetMP	= EvilSpellStoreCommandSetX
End


PlayerTemplate FactionIsengard
StartingBuilding = NONE
StartingUnit0 = NONE
StartingUnit1 = NONE
StartingUnit2 =  NONE
StartingUnitOffset2 = X:300 Y:0 Z:0
StartingUnit3 = NONE
StartingUnitOffset3 = X:0 Y:300 Z:0
StartingUnit4 = NONE
StartingUnitOffset4 = X:-300 Y:0 Z:0
StartingUnit7 = NONE
StartingUnitOffset7 = X:0 Y:-300 Z:0
StartMoney = 0
BuildableHeroesMP		= NONE
DefaultPlayerAIType		= NONE
	IntrinsicSciences		= SCIENCE_EVIL
	IntrinsicSciencesMP 		= SCIENCE_EVIL
	SpellBook			= EvilSpellBook
	SpellBookMp			= EvilSpellBook
	PurchaseScienceCommandSet	= EvilSpellStoreCommandSetX
	PurchaseScienceCommandSetMP	= EvilSpellStoreCommandSetX
End


PlayerTemplate FactionArnor
StartingBuilding = NONE
StartingUnit0 = NONE
StartingUnit1 = NONE
StartingUnit2 =  NONE
StartingUnitOffset2 = X:300 Y:0 Z:0
StartingUnit3 = NONE
StartingUnitOffset3 = X:0 Y:300 Z:0
StartingUnit4 = NONE
StartingUnitOffset4 = X:-300 Y:0 Z:0
StartingUnit7 = NONE
StartingUnitOffset7 = X:0 Y:-300 Z:0
StartMoney = 0
BuildableHeroesMP		= NONE
DefaultPlayerAIType		= NONE
	IntrinsicSciences		= SCIENCE_EVIL
	IntrinsicSciencesMP 		= SCIENCE_EVIL
	SpellBook			= EvilSpellBook
	SpellBookMp			= EvilSpellBook
	PurchaseScienceCommandSet	= EvilSpellStoreCommandSetX
	PurchaseScienceCommandSetMP	= EvilSpellStoreCommandSetX
End

;-------------------------------------------------------------------------------------------------