; Object HaradHornofKarna
; KindOf              = LINKED_TO_FLAG PRELOAD STRUCTURE SELECTABLE IMMOBILE SCORE FS_FACTORY AUTO_RALLYPOINT MP_COUNT_FOR_VICTORY NEED_BASE_FOUNDATION ATTACK_NEEDS_LINE_OF_SIGHT CAN_ATTACK MADE_OF_STONE LIVING_WORLD_BUILDING_MIRROR
; END

; ; WaterTransparency can be overridden per each map to change these values.
; WaterTransparency
  ; ReflectionPlaneZ = 98.0;
  ; ReflectionOn = Yes
; End

Weather

	HardwareFogColor = R:110 G:145 B:150; R:130 G:150 B:165
	HardwareFogEnable = Yes
	HardwareFogStart = 370
	HardwareFogEnd = 4000

  	CloudTextureSize = X:4000 Y:4000
	CloudOffsetPerSecond = X:-0 Y:-0
	
End

Object AotRMirkwoodProp06
  Geometry              = BOX
  GeometryMajorRadius   = 0.1
  GeometryMinorRadius   = 0.1
  GeometryHeight        = 0.1
  GeometryIsSmall       = No
End

Object AotRMirkwoodProp15
  Geometry              = BOX
  GeometryMajorRadius   = 0.1
  GeometryMinorRadius   = 0.1
  GeometryHeight        = 0.1
  GeometryIsSmall       = No
End

Object AotRMirkwoodProp23
  Geometry              = BOX
  GeometryMajorRadius   = 0.1
  GeometryMinorRadius   = 0.1
  GeometryHeight        = 0.1
  GeometryIsSmall       = No
End

Object AotRDolGuldurCliffb03
  Geometry              = BOX
  GeometryMajorRadius   = 0.1
  GeometryMinorRadius   = 0.1
  GeometryHeight        = 0.1
  GeometryIsSmall       = No
End

Object AotRDolGuldurCliffb08
  Geometry              = BOX
  GeometryMajorRadius   = 0.1
  GeometryMinorRadius   = 0.1
  GeometryHeight        = 0.1
  GeometryIsSmall       = No
End

Object AotRDolGuldurRock05
  Geometry              = BOX
  GeometryMajorRadius   = 0.1
  GeometryMinorRadius   = 0.1
  GeometryHeight        = 0.1
  GeometryIsSmall       = No
End

Object AotRDolGuldurRock08
  Geometry              = BOX
  GeometryMajorRadius   = 0.1
  GeometryMinorRadius   = 0.1
  GeometryHeight        = 0.1
  GeometryIsSmall       = No
End

Object AotRMoriaCliffTall16
  Geometry              = BOX
  GeometryMajorRadius   = 0.1
  GeometryMinorRadius   = 0.1
  GeometryHeight        = 0.1
  GeometryIsSmall       = No
End

Object AotRAmonHenN02
  Geometry              = BOX
  GeometryMajorRadius   = 0.1
  GeometryMinorRadius   = 0.1
  GeometryHeight        = 0.1
  GeometryIsSmall       = No
End

Object GondorAmonHenB1
  Geometry              = BOX
  GeometryMajorRadius   = 0.1
  GeometryMinorRadius   = 0.1
  GeometryHeight        = 0.1
  GeometryIsSmall       = No
End

Object GondorAmonHenB2
  Geometry              = BOX
  GeometryMajorRadius   = 0.1
  GeometryMinorRadius   = 0.1
  GeometryHeight        = 0.1
  GeometryIsSmall       = No
End

Object GondorAmonHenB3
  Geometry              = BOX
  GeometryMajorRadius   = 0.1
  GeometryMinorRadius   = 0.1
  GeometryHeight        = 0.1
  GeometryIsSmall       = No
End

Object GondorAmonHenB5
  Geometry              = BOX
  GeometryMajorRadius   = 0.1
  GeometryMinorRadius   = 0.1
  GeometryHeight        = 0.1
  GeometryIsSmall       = No
End

Object GondorAmonHenC1
  Geometry              = BOX
  GeometryMajorRadius   = 0.1
  GeometryMinorRadius   = 0.1
  GeometryHeight        = 0.1
  GeometryIsSmall       = No
End

Object GondorAmonHenC5
  Geometry              = BOX
  GeometryMajorRadius   = 0.1
  GeometryMinorRadius   = 0.1
  GeometryHeight        = 0.1
  GeometryIsSmall       = No
End

Object GondorAmonHenW2
  Geometry              = BOX
  GeometryMajorRadius   = 0.1
  GeometryMinorRadius   = 0.1
  GeometryHeight        = 0.1
  GeometryIsSmall       = No
End


Object GondorAmonHenW3
  Geometry              = BOX
  GeometryMajorRadius   = 0.1
  GeometryMinorRadius   = 0.1
  GeometryHeight        = 0.1
  GeometryIsSmall       = No
End

Object GondorAmonHenW5
  Geometry              = BOX
  GeometryMajorRadius   = 0.1
  GeometryMinorRadius   = 0.1
  GeometryHeight        = 0.1
  GeometryIsSmall       = No
End

Object HarlindonRuin08
  Geometry              = BOX
  GeometryMajorRadius   = 0.1
  GeometryMinorRadius   = 0.1
  GeometryHeight        = 0.1
  GeometryIsSmall       = No
End

Object OldForestRock02
  Geometry              = BOX
  GeometryMajorRadius   = 0.1
  GeometryMinorRadius   = 0.1
  GeometryHeight        = 0.1
  GeometryIsSmall       = No
End

Object OldForestRock05
  Geometry              = BOX
  GeometryMajorRadius   = 0.1
  GeometryMinorRadius   = 0.1
  GeometryHeight        = 0.1
  GeometryIsSmall       = No
End

Object OldForestRock07
  Geometry              = BOX
  GeometryMajorRadius   = 0.1
  GeometryMinorRadius   = 0.1
  GeometryHeight        = 0.1
  GeometryIsSmall       = No
End


; FXParticleSystem WhiteDriftingClouds
  ; System
    ; Priority = VERY_LOW_OR_ABOVE
    ; Shader = ALPHA
    ; ParticleName = EXCloud02.tga; exraindrop.tga; EXCloud02.tga
    ; Lifetime = 450 450; 350 350
    ; Size = 0.8 0.8;1 1
    ; BurstDelay = 2 5; 2 5
    ; BurstCount = 1 1; 1 1
    ; IsEmitAboveGroundOnly = No
  ; End
  ; Color = DefaultColor
    ; Color1 = R:255 G:255 B:255 95; R:255 G:255 B:255 75
  ; End
  ; Alpha = DefaultAlpha
    ; Alpha1 = 0.1 0.3 250; 0.1 0.3 50
    ; Alpha2 = 0 0 220; 0 0 350
  ; End
  ; Update = DefaultUpdate
    ; SizeRate = 0.1 0.1; 1 3
    ; SizeRateDamping = 0.5 0.5; 0.9 0.99
    ; AngularRateZ = -0.02 0.02
    ; AngularDamping = 1.5 1.5; 1 1
    ; AngularDampingXY = 1 1
  ; End
  ; Physics = DefaultPhysics
    ; VelocityDamping = 0.5 0.6; 0.7 0.8
    ; DriftVelocity = X:0 Y:-0.1 Z:-0.2; X:0.2 Y:0.2 Z:0.08
  ; End
  ; EmissionVelocity = OrthoEmissionVelocity
    ; X = -0.1 -0.1; -0.4 -0.4
  ; End
  ; EmissionVolume = LineEmissionVolume
    ; IsHollow = Yes
    ; StartPoint = X:0 Y:-80 Z:0
    ; EndPoint = X:0 Y:-90 Z:0
  ; End
  ; Draw = DefaultDraw
  ; End
; End

Object CINE_ParticleSysProxy2

  ; *** ART Parameters ***
 ReplaceModule ModuleTag_01
  Draw = W3DScriptedModelDraw ModuleTag_01_Override
    DefaultModelConditionState
      Model = NONE
      ParticleSysBone = emberBone FloatingDust
      ParticleSysBone = None None;FireSmokeBig
    End
  
    ModelConditionState = WORLD_BUILDER
	  Model = locator
	End
  End
 End
End

FXParticleSystem FloatingDust;falling dust
  System
    Priority = ALWAYS_RENDER
	Shader = ALPHA
    ParticleName = EXCloud02.tga; EXCineSparks.tga
    Lifetime = 150 300; 100 200
    SortLevel = 1
    Size = 0.5 0.8; 0.1 0.2
    BurstDelay = 1 10
    BurstCount = 3 5
  End
 
  Color = DefaultColor
    Color1 = R:205 G:192 B:168 0; R:255 G:185 B:79 0
    Color2 = R:105 G:92 B:68 50; R:0 G:0 B:0 200
    ColorScale = 2 -2
  End
  
    Alpha = DefaultAlpha
    Alpha1 = 50 50 50; 0.1 0.3 50
    Alpha2 = 50 50 300; 0 0 350
  End
  Update = DefaultUpdate
    SizeRate = 0.01 0.07
    SizeRateDamping = 0.65 0.8
    AngleZ = -3 3
    AngularRateZ = -0.3 0.3
    AngularDamping = 0.9 0.99
    AngularDampingXY = 1 1
  End
  Physics = DefaultPhysics
    Gravity = 0.008
    VelocityDamping = 0.95 0.99
    DriftVelocity = X:0.15 Y:0.1 Z:-0.4; X:0 Y:0 Z:0.64
  End
  EmissionVelocity = OrthoEmissionVelocity
  End
  EmissionVolume = CylinderEmissionVolume
    Radius = 155; 7
    Length = 10; 1
  End
  Draw = DefaultDraw
  End
  Wind = DefaultWind
    WindMotion = PingPong

    WindStrength = 0.25; 0.25
    WindFullStrengthDist = 5
    WindZeroStrengthDist = 100
    WindAngleChangeMin = 0.034907
    WindAngleChangeMax = 0.034907
    WindPingPongStartAngleMin = 1.22173
    WindPingPongStartAngleMax = 1.22173
    WindPingPongEndAngleMin = 1.91986
    WindPingPongEndAngleMax = 1.91986
    TurbulenceAmplitude = 0.2
    TurbulenceFrequency = 50
  End
End

Object CINE_ParticleSysProxy3

  ; *** ART Parameters ***
 ReplaceModule ModuleTag_01
  Draw = W3DScriptedModelDraw ModuleTag_01_Override
    DefaultModelConditionState
      Model = NONE
      ParticleSysBone = emberBone DrippingWater; emberBone
      ParticleSysBone = None None;FireSmokeBig
    End
  
    ModelConditionState = WORLD_BUILDER
	  Model = locator
	End
  End
 End
End

; FXParticleSystem DrippingWater; water droplets
  ; System
    ; Priority = HIGH_OR_ABOVE
    ; Shader = ALPHA
    ; ParticleName = EXDirt.tga
    ; ;SlaveSystem = DirtFalling
    ; ;SlavePosOffset = X:0 Y:0 Z:0
    ; Lifetime = 70 70;15 30
    ; Size = 10 10;3 4
    ; BurstDelay = 1 5
    ; BurstCount = 8 8;1 1 decrease for tighter stream
  ; End
  ; Color = DefaultColor
    ; Color1 = R:255 G:255 B:255 0
  ; End
  ; Alpha = DefaultAlpha
    ; Alpha1 = .6 .6 0
	; Alpha2 = 1 1 40
	; Alpha3 = 0 0 70
  ; End
  ; Update = DefaultUpdate
    ; SizeRate = 4 8
    ; SizeRateDamping = 0.5 0.5
    ; AngularRateZ = -0.01 0.01
    ; AngularDamping = 1 1
    ; AngularDampingXY = 1 1
  ; End
  ; Physics = DefaultPhysics
    ; Gravity = -0.06
    ; VelocityDamping = 0.9 0.99
  ; End
  ; EmissionVelocity = SphericalEmissionVelocity
  ; End
  ; EmissionVolume = SphereEmissionVolume
    ; Radius = 30; 1 reduce for tighter stream
  ; End
  ; Draw = DefaultDraw
  ; End
; End

FXParticleSystem FogMist;FXParticleSystem CINECampfireEmbers;ground fog

  System
    Priority = VERY_LOW_OR_ABOVE
	Shader = ALPHA
    ParticleName = EXCloud02.tga; EXCineSparks.tga
    Lifetime = 150 150
    SortLevel = 1
    Size = .8 1
    BurstDelay = 10 20; 1 10
    BurstCount = 8 15; 3 5
  End
 
  Color = DefaultColor
    Color1 = R:145 G:180 B:185 0; R:205 G:192 B:168 0; R:255 G:185 B:79 0
    ;Color2 = R:105 G:92 B:68 50; R:0 G:0 B:0 200
    ;ColorScale = 2 -2
  End
    Alpha = DefaultAlpha
    ;Alpha1 = 0 0 50
	Alpha2 = 0.07 0.07 50; 0.1 0.1 50
    Alpha3 = 0 0 120; 150
  End
  Update = DefaultUpdate
    SizeRate = 1 3; 1 3
    SizeRateDamping = 0.9 0.99
    ;AngularRateZ = -0.02 0.02
    ;AngularDamping = 1 1
    ;AngularDampingXY = 1 1
  End
  Physics = DefaultPhysics
    ;Gravity = -0.008
    VelocityDamping = 0.95 0.99
    DriftVelocity = X:0.2 Y:0.-2 Z:0.08; X:0 Y:0 Z:0.64
  End
  EmissionVelocity = OrthoEmissionVelocity
  X = .5 1
  Y = -1 1
  Z = 0 0.1
	End
  EmissionVolume = CylinderEmissionVolume
    Radius = 120
	Length = 2
	Offset = X:0 Y:0 Z:20
  End
  Draw = DefaultDraw
  End
  Wind = DefaultWind
    WindMotion = PingPong

    WindStrength = 0.25; 0.25
    WindFullStrengthDist = 5
    WindZeroStrengthDist = 100
    WindAngleChangeMin = 0.034907
    WindAngleChangeMax = 0.034907
    WindPingPongStartAngleMin = 1.22173
    WindPingPongStartAngleMax = 1.22173
    WindPingPongEndAngleMin = 1.91986
    WindPingPongEndAngleMax = 1.91986
    TurbulenceAmplitude = 0.2
    TurbulenceFrequency = 50
  End
End



Object Inn
	AddModule ModuleTag_InnKarna
		Behavior = CommandSetUpgrade CommandSetInnMenFactionKarna
			TriggeredBy = Upgrade_AngmarFaction Upgrade_DwarfFaction Upgrade_RohanFaction Upgrade_MenFaction Upgrade_ArnorFaction Upgrade_ElfFaction Upgrade_IsengardFaction Upgrade_MordorFaction Upgrade_WildFaction Upgrade_GuldurFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnMenFaction_Karna
		End
	End
End

; ;startOfAuto-Generation
; ;------------------------------------------------------------------------;
; ;	  HARAD REGION 														 ;
; ;------------------------------------------------------------------------;
; Object Inn
	; ReplaceModule ModuleTag_CommandSetGondor
		; Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Harad
			; TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			; CommandSet	= CommandSetInnGoodFaction_Harad
		; End
	; End
	; ReplaceModule ModuleTag_CommandSetMordor
		; Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Harad
			; TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			; CommandSet	= CommandSetInnEvilFaction_Harad
		; End
	; End	
; End
; Object InnDesert
	; ReplaceModule ModuleTag_CommandSetGondor
		; Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Harad
			; TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			; CommandSet	= CommandSetInnGoodFaction_Harad
		; End
	; End
	; ReplaceModule ModuleTag_CommandSetMordor
		; Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Harad
			; TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			; CommandSet	= CommandSetInnEvilFaction_Harad
		; End
	; End
; End
; Object InnSnow
	; ReplaceModule ModuleTag_CommandSetGondor
		; Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Harad
			; TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			; CommandSet	= CommandSetInnGoodFaction_Harad
		; End
	; End
	; ReplaceModule ModuleTag_CommandSetMordor
		; Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Harad
			; TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			; CommandSet	= CommandSetInnEvilFaction_Harad
		; End
	; End
; End
; Object Inn_old
	; ReplaceModule ModuleTag_CommandSetGondor
		; Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Harad
			; TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			; CommandSet	= CommandSetInnGoodFaction_Harad
		; End
	; End
	; ReplaceModule ModuleTag_CommandSetMordor
		; Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Harad
			; TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			; CommandSet	= CommandSetInnEvilFaction_Harad
		; End
	; End
; End
; ;endOfAuto-Generation


;==== Auto Generated AI Fix =====;
SkirmishAIData TheSkirmishAIData
    DisableBaseBuilding        = No
    DisableEconomyBuilding     = No
    DisableUnitBuilding        = No
    DisableScienceUpgrading    = No
    DisableUnitUpgrading       = No
    DisableTacticalAI          = No
    DisableTeamBuilding        = No
    DisableWallBuilding        = Yes ;,; No
End
