Weather

	HardwareFogColor = R:175 G:190 B:192
	HardwareFogEnable = Yes
	HardwareFogStart = 450
	HardwareFogEnd = 8000
	
End



Object AotRRhunCastleProp1

	ReplaceModule ModuleTag_01
	Draw = W3DScriptedModelDraw ModuleTag_light

    
    RandomTexture = mbNrhun_light.tga 0 mbNrhun.tga
	
		
    DefaultModelConditionState
      Model = prNrhun01_skn
    End
	

End
End 
END



Object AotRRhunCastleProp2

	ReplaceModule ModuleTag_01
	Draw = W3DScriptedModelDraw ModuleTag_light

    
    RandomTexture = mbNrhun_light.tga 0 mbNrhun.tga
	
		
    DefaultModelConditionState
      Model = prNrhun02_skn
    End
	

End
End 
END

Object AotRRhunCastleProp3

	ReplaceModule ModuleTag_01
	Draw = W3DScriptedModelDraw ModuleTag_light

    
    RandomTexture = mbNrhun_light.tga 0 mbNrhun.tga
	
		
    DefaultModelConditionState
      Model = prNrhun03_skn
    End
	

End
End 
END

Object AotRRhunCastleProp4

	ReplaceModule ModuleTag_01
	Draw = W3DScriptedModelDraw ModuleTag_light

    
    RandomTexture = mbNrhun_light.tga 0 mbNrhun.tga
	
		
    DefaultModelConditionState
      Model = prNrhun04_skn
    End
	

End
End 
END

Object AotRRhunCastleProp5

	ReplaceModule ModuleTag_01
	Draw = W3DScriptedModelDraw ModuleTag_light

    
    RandomTexture = mbNrhun_light.tga 0 mbNrhun.tga
	
		
    DefaultModelConditionState
      Model = prNrhun05_skn
    End
	

End
End 
END

Object AotRRhunCastleProp6

	ReplaceModule ModuleTag_01
	Draw = W3DScriptedModelDraw ModuleTag_light

    
    RandomTexture = mbNrhun_light.tga 0 mbNrhun.tga
	
		
    DefaultModelConditionState
      Model = prNrhun06_skn
    End
	

End
End 
END

Object AotRRhunCastleProp7

	ReplaceModule ModuleTag_01
	Draw = W3DScriptedModelDraw ModuleTag_light

    
    RandomTexture = mbNrhun_light.tga 0 mbNrhun.tga
	
		
    DefaultModelConditionState
      Model = prNrhun07_skn
    End
	

End
End 
END

Object AotRRhunCastleProp8

	ReplaceModule ModuleTag_01
	Draw = W3DScriptedModelDraw ModuleTag_light

    
    RandomTexture = mbNrhun_light.tga 0 mbNrhun.tga
	
		
    DefaultModelConditionState
      Model = prNrhun08_skn
    End
	

End
End 
END

Object AotRRhunCastleProp9

	ReplaceModule ModuleTag_01
	Draw = W3DScriptedModelDraw ModuleTag_light

    
    RandomTexture = mbNrhun_light.tga 0 mbNrhun.tga
	
		
    DefaultModelConditionState
      Model = prNrhun09_skn
    End
	

End
End 
END

Object AotRRhunCastleProp10

	ReplaceModule ModuleTag_01
	Draw = W3DScriptedModelDraw ModuleTag_light

    
    RandomTexture = mbNrhun_light.tga 0 mbNrhun.tga
	
		
    DefaultModelConditionState
      Model = prNrhun10_skn
    End
	

End
End 
END

Object AotRRhunCastleProp11

	ReplaceModule ModuleTag_01
	Draw = W3DScriptedModelDraw ModuleTag_light

    
    RandomTexture = mbNrhun_light.tga 0 mbNrhun.tga
	
		
    DefaultModelConditionState
      Model = prNrhun11_skn
    End
	

End
End 
END


;startOfAuto-Generation
;------------------------------------------------------------------------;
;	  RHUN REGION 														 ;
;------------------------------------------------------------------------;
Object Inn
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Rhun
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Rhun
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Rhun
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Rhun
		End
	End
End
Object InnDesert
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Rhun
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Rhun
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Rhun
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Rhun
		End
	End
End
Object InnSnow
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Rhun
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Rhun
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Rhun
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Rhun
		End
	End
End
Object Inn_old
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Rhun
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Rhun
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Rhun
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Rhun
		End
	End
End
;endOfAuto-Generation


;==== Auto Generated AI Fix =====;
SkirmishAIData TheSkirmishAIData
    DisableBaseBuilding        = No
    DisableEconomyBuilding     = No
    DisableUnitBuilding        = No
    DisableScienceUpgrading    = No
    DisableUnitUpgrading       = No
    DisableTacticalAI          = No
    DisableTeamBuilding        = No
    DisableWallBuilding        = Yes ;,; No
End
