Weather 
	HardwareFogColor = R:120 G:166 B:191
	HardwareFogEnable = Yes
	HardwareFogStart = 500
	HardwareFogEnd = 7000
        SnowEnabled = Yes                         ; enable/disable snow on the map. 
        IsSnowing = Yes                         ; is it snowing today? 
        SnowTexture = exraindrop.tga    ; which .tga texture is falling from the sky? 
        SnowBoxHeight = 800                     ; height from which snow falls 
        SnowSpacing = 5                          ; snow spacing -- less means more; 
        NumberTiles = 4 
 
        SnowAmplitude = 3                     ; amount of side-to-side movement.  
        SnowFrequencyScaleX = 0.01       ; speed of side-to-side wave movement. 
        SnowFrequencyScaleY = 0.005     ; speed of side-to-side wave movement.  
 
        SnowPointSize = 22                        ; scale the size of snow particles. 
        SnowMinPointSize =  12              ; min point size 
        SnowMaxPointSize = 19               ; max point size 
 
        SnowPointSprites = No             ; set to "no" for point-sprite emulation. 
        SnowQuadSize = 3                           ; scale the size of snow particles when using point-sprite emulation. 
 
        SnowSpeed = 140                           ; speed at which snow falls 
		
		  ; Lightning stuff
  LightningEnabled = yes          ; enable/disable lightning
  LightningFactor = 0.5 1.0       ; flash amount (0, 1) -- make drops brighter by this much
  LightningDuration = 50          ; how long the lightning lasts
  LightningChance = 0.05          ; chance of lightning (0, 1)
   ;;;SnowXYSpeed = X:40 Y:25 
 
End

WaterTransparency
  ReflectionPlaneZ = 7.0;
  ReflectionOn = Yes
End

;--------------------------------------------------------------------------------------------------------
Object CINE_ParticleSysProxy
 
ReplaceModule ModuleTag_01
  ; *** ART Parameters ***
  Draw = W3DScriptedModelDraw ModuleTag_01_Override
    DefaultModelConditionState
      Model = NONE
      ParticleSysBone = None SmokeIsengardPit
    End
  
    ModelConditionState = WORLD_BUILDER
   Model = locator
 End
  End
End
End
;--------------------------------------------------------------------------------------------------------
Object CINE_ParticleSysProxy2
 
ReplaceModule ModuleTag_01
  ; *** ART Parameters ***
  Draw = W3DScriptedModelDraw ModuleTag_01_Override
    DefaultModelConditionState
      Model = NONE
      ParticleSysBone = None SmokeIsengardPitThin
    End
  
    ModelConditionState = WORLD_BUILDER
   Model = locator
 End
  End
End
End


;--------------------------------------------------------------------------------------------------------
Object CINE_ParticleSysProxy3
 
ReplaceModule ModuleTag_01
  ; *** ART Parameters ***
  Draw = W3DScriptedModelDraw ModuleTag_01_Override
    DefaultModelConditionState
      Model = NONE
      ParticleSysBone = None SmokeIsengardPitupper
    End
  
    ModelConditionState = WORLD_BUILDER
   Model = locator
 End
  End
End
End
;--------------------------------------------------------------------------------------------------------

;startOfAuto-Generation
;------------------------------------------------------------------------;
;	  ROHAN REGION 														 ;
;------------------------------------------------------------------------;
Object Inn
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Rohan
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Rohan
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Rohan
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Rohan
		End
	End
End
Object InnDesert
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Rohan
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Rohan
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Rohan
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Rohan
		End
	End
End
Object InnSnow
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Rohan
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Rohan
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Rohan
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Rohan
		End
	End
End
Object Inn_old
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Rohan
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Rohan
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Rohan
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Rohan
		End
	End
End
;endOfAuto-Generation


;==== Auto Generated AI Fix =====;
SkirmishAIData TheSkirmishAIData
    DisableBaseBuilding        = No
    DisableEconomyBuilding     = No
    DisableUnitBuilding        = No
    DisableScienceUpgrading    = No
    DisableUnitUpgrading       = No
    DisableTacticalAI          = No
    DisableTeamBuilding        = No
    DisableWallBuilding        = Yes ;,; No
End
