;-------------------------------------------------------------------------------------------------
;PLAYER TEMPLATE
;-------------------------------------------------------------------------------------------------

PlayerTemplate FactionNeutral
	IntrinsicSciences		= SCIENCE_GOOD
	IntrinsicSciencesMP 		= SCIENCE_GOOD
	SpellBook			= EvilSpellBook
	SpellBookMp			= EvilSpellBook
	PurchaseScienceCommandSet	= EvilSpellStoreCommandSet
	PurchaseScienceCommandSetMP	= EvilSpellStoreCommandSet
End

PlayerTemplate FactionCivilian
	IntrinsicSciences		= SCIENCE_GOOD
	IntrinsicSciencesMP 		= SCIENCE_GOOD
	SpellBook			= GoodSpellBook
	SpellBookMp			= GoodSpellBook
	PurchaseScienceCommandSet	= GoodSpellStoreCommandSet
	PurchaseScienceCommandSetMP	= GoodSpellStoreCommandSet
End

PlayerTemplate FactionMen
StartingBuilding = NONE
StartingUnit0 = NONE
StartingUnit1 = NONE
StartingUnit2 =  NONE
StartingUnitOffset2 = X:300 Y:0 Z:0
StartingUnit3 = NONE
StartingUnitOffset3 = X:0 Y:300 Z:0
StartingUnit4 = NONE
StartingUnitOffset4 = X:-300 Y:0 Z:0
StartingUnit7 = NONE
StartingUnitOffset7 = X:0 Y:-300 Z:0
StartMoney = 0
BuildableHeroesMP		= NONE
DefaultPlayerAIType		= NONE
	IntrinsicSciences		= SCIENCE_GOOD
	IntrinsicSciencesMP 		= SCIENCE_GOOD
	SpellBook			= GoodSpellBook
	SpellBookMp			= GoodSpellBook
	PurchaseScienceCommandSet	= GoodSpellStoreCommandSet
	PurchaseScienceCommandSetMP	= GoodSpellStoreCommandSet
End

PlayerTemplate FactionDwarves
StartingBuilding = NONE
StartingUnit0 = NONE
StartingUnit1 = NONE
StartingUnit2 =  NONE
StartingUnitOffset2 = X:300 Y:0 Z:0
StartingUnit3 = NONE
StartingUnitOffset3 = X:0 Y:300 Z:0
StartingUnit4 = NONE
StartingUnitOffset4 = X:-300 Y:0 Z:0
StartingUnit7 = NONE
StartingUnitOffset7 = X:0 Y:-300 Z:0
StartMoney = 0
BuildableHeroesMP		= NONE
DefaultPlayerAIType		= NONE
	IntrinsicSciences		= SCIENCE_GOOD
	IntrinsicSciencesMP 		= SCIENCE_GOOD
	SpellBook			= GoodSpellBook
	SpellBookMp			= GoodSpellBook
	PurchaseScienceCommandSet	= GoodSpellStoreCommandSet
	PurchaseScienceCommandSetMP	= GoodSpellStoreCommandSet
End

PlayerTemplate FactionElves
StartingBuilding = NONE
StartingUnit0 = NONE
StartingUnit1 = NONE
StartingUnit2 =  NONE
StartingUnitOffset2 = X:300 Y:0 Z:0
StartingUnit3 = NONE
StartingUnitOffset3 = X:0 Y:300 Z:0
StartingUnit4 = NONE
StartingUnitOffset4 = X:-300 Y:0 Z:0
StartingUnit7 = NONE
StartingUnitOffset7 = X:0 Y:-300 Z:0
StartMoney = 0
BuildableHeroesMP		= NONE
DefaultPlayerAIType		= NONE
	IntrinsicSciences		= SCIENCE_GOOD
	IntrinsicSciencesMP 		= SCIENCE_GOOD
	SpellBook			= GoodSpellBook
	SpellBookMp			= GoodSpellBook
	PurchaseScienceCommandSet	= GoodSpellStoreCommandSet
	PurchaseScienceCommandSetMP	= GoodSpellStoreCommandSet
End


PlayerTemplate FactionWild
StartingBuilding = NONE
StartingUnit0 = NONE
StartingUnit1 = NONE
StartingUnit2 =  NONE
StartingUnitOffset2 = X:300 Y:0 Z:0
StartingUnit3 = NONE
StartingUnitOffset3 = X:0 Y:300 Z:0
StartingUnit4 = NONE
StartingUnitOffset4 = X:-300 Y:0 Z:0
StartingUnit7 = NONE
StartingUnitOffset7 = X:0 Y:-300 Z:0
StartMoney = 0
BuildableHeroesMP		= NONE
DefaultPlayerAIType		= NONE
	IntrinsicSciences		= SCIENCE_GOOD
	IntrinsicSciencesMP 		= SCIENCE_GOOD
	SpellBook			= GoodSpellBook
	SpellBookMp			= GoodSpellBook
	PurchaseScienceCommandSet	= GoodSpellStoreCommandSet
	PurchaseScienceCommandSetMP	= GoodSpellStoreCommandSet
End


PlayerTemplate FactionMordor
StartingBuilding = NONE
StartingUnit0 = NONE
StartingUnit1 = NONE
StartingUnit2 =  NONE
StartingUnitOffset2 = X:300 Y:0 Z:0
StartingUnit3 = NONE
StartingUnitOffset3 = X:0 Y:300 Z:0
StartingUnit4 = NONE
StartingUnitOffset4 = X:-300 Y:0 Z:0
StartingUnit7 = NONE
StartingUnitOffset7 = X:0 Y:-300 Z:0
StartMoney = 0
BuildableHeroesMP		= NONE
DefaultPlayerAIType		= NONE
	IntrinsicSciences		= SCIENCE_GOOD
	IntrinsicSciencesMP 		= SCIENCE_GOOD
	SpellBook			= GoodSpellBook
	SpellBookMp			= GoodSpellBook
	PurchaseScienceCommandSet	= GoodSpellStoreCommandSet
	PurchaseScienceCommandSetMP	= GoodSpellStoreCommandSet
End


PlayerTemplate FactionIsengard
StartingBuilding = NONE
StartingUnit0 = NONE
StartingUnit1 = NONE
StartingUnit2 =  NONE
StartingUnitOffset2 = X:300 Y:0 Z:0
StartingUnit3 = NONE
StartingUnitOffset3 = X:0 Y:300 Z:0
StartingUnit4 = NONE
StartingUnitOffset4 = X:-300 Y:0 Z:0
StartingUnit7 = NONE
StartingUnitOffset7 = X:0 Y:-300 Z:0
StartMoney = 0
BuildableHeroesMP		= NONE
DefaultPlayerAIType		= NONE
	IntrinsicSciences		= SCIENCE_GOOD
	IntrinsicSciencesMP 		= SCIENCE_GOOD
	SpellBook			= GoodSpellBook
	SpellBookMp			= GoodSpellBook
	PurchaseScienceCommandSet	= GoodSpellStoreCommandSet
	PurchaseScienceCommandSetMP	= GoodSpellStoreCommandSet
End

PlayerTemplate FactionArnor
StartingBuilding = NONE
StartingUnit0 = NONE
StartingUnit1 = NONE
StartingUnit2 =  NONE
StartingUnitOffset2 = X:300 Y:0 Z:0
StartingUnit3 = NONE
StartingUnitOffset3 = X:0 Y:300 Z:0
StartingUnit4 = NONE
StartingUnitOffset4 = X:-300 Y:0 Z:0
StartingUnit7 = NONE
StartingUnitOffset7 = X:0 Y:-300 Z:0
StartMoney = 0
BuildableHeroesMP		= NONE
DefaultPlayerAIType		= NONE
	IntrinsicSciences		= SCIENCE_GOOD
	IntrinsicSciencesMP 		= SCIENCE_GOOD
	SpellBook			= GoodSpellBook
	SpellBookMp			= GoodSpellBook
	PurchaseScienceCommandSet	= GoodSpellStoreCommandSet
	PurchaseScienceCommandSetMP	= GoodSpellStoreCommandSet
End

PlayerTemplate FactionRohan
StartingBuilding = NONE
StartingUnit0 = NONE
StartingUnit1 = NONE
StartingUnit2 =  NONE
StartingUnitOffset2 = X:300 Y:0 Z:0
StartingUnit3 = NONE
StartingUnitOffset3 = X:0 Y:300 Z:0
StartingUnit4 = NONE
StartingUnitOffset4 = X:-300 Y:0 Z:0
StartingUnit7 = NONE
StartingUnitOffset7 = X:0 Y:-300 Z:0
StartMoney = 0
BuildableHeroesMP		= NONE
DefaultPlayerAIType		= NONE
	IntrinsicSciences		= SCIENCE_GOOD
	IntrinsicSciencesMP 		= SCIENCE_GOOD
	SpellBook			= GoodSpellBook
	SpellBookMp			= GoodSpellBook
	PurchaseScienceCommandSet	= GoodSpellStoreCommandSet
	PurchaseScienceCommandSetMP	= GoodSpellStoreCommandSet
End

PlayerTemplate FactionGuldur
StartingBuilding = NONE
StartingUnit0 = NONE
StartingUnit1 = NONE
StartingUnit2 =  NONE
StartingUnitOffset2 = X:300 Y:0 Z:0
StartingUnit3 = NONE
StartingUnitOffset3 = X:0 Y:300 Z:0
StartingUnit4 = NONE
StartingUnitOffset4 = X:-300 Y:0 Z:0
StartingUnit7 = NONE
StartingUnitOffset7 = X:0 Y:-300 Z:0
StartMoney = 0
BuildableHeroesMP		= NONE
DefaultPlayerAIType		= NONE
	IntrinsicSciences		= SCIENCE_GOOD
	IntrinsicSciencesMP 		= SCIENCE_GOOD
	SpellBook			= GoodSpellBook
	SpellBookMp			= GoodSpellBook
	PurchaseScienceCommandSet	= GoodSpellStoreCommandSet
	PurchaseScienceCommandSetMP	= GoodSpellStoreCommandSet
End

PlayerTemplate FactionMirkwood
StartingBuilding = NONE
StartingUnit0 = NONE
StartingUnit1 = NONE
StartingUnit2 =  NONE
StartingUnitOffset2 = X:300 Y:0 Z:0
StartingUnit3 = NONE
StartingUnitOffset3 = X:0 Y:300 Z:0
StartingUnit4 = NONE
StartingUnitOffset4 = X:-300 Y:0 Z:0
StartingUnit7 = NONE
StartingUnitOffset7 = X:0 Y:-300 Z:0
StartMoney = 0
BuildableHeroesMP		= NONE
DefaultPlayerAIType		= NONE
	IntrinsicSciences		= SCIENCE_GOOD
	IntrinsicSciencesMP 		= SCIENCE_GOOD
	SpellBook			= GoodSpellBook
	SpellBookMp			= GoodSpellBook
	PurchaseScienceCommandSet	= GoodSpellStoreCommandSet
	PurchaseScienceCommandSetMP	= GoodSpellStoreCommandSet
End

Object UniversalBuildingFoundation
CommandSet = DwarvenFoundationUpgradedCommandSet_Balins
RemoveModule ModueTag_GondorCommandSet
RemoveModule ModueTag_RohanCommandSet
RemoveModule ModueTag_LothlorienCommandSet
RemoveModule ModueTag_RivendellCommandSet
RemoveModule ModuleTag_MirkwoodCommandSet
RemoveModule ModueTag_DwarvesCommandSet
RemoveModule ModueTag_DwarvesCommandSet_WotR
RemoveModule ModueTag_DwarvesCommandSetUpgraded
RemoveModule ModueTag_DwarvesCommandSetUpgraded_WotR
RemoveModule ModueTag_MordorCommandSet
RemoveModule ModueTag_IsengardCommandSet
RemoveModule ModueTag_GoblinsCommandSet
RemoveModule ModueTag_GuldurCommandSet
RemoveModule ModueTag_HaradCommandSet
End

;-------------------------------------------------------------------------------------------------
; BARRACKS
;-------------------------------------------------------------------------------------------------

Object DwarfBarracks
  CommandSet          	= DwarvenBarracksCommandSetX
ReplaceModule ModuleTag_DwarvenBarracksLevel2
	Behavior = CommandSetUpgrade ModuleTag_DwarvenBarracksLevel2X
		TriggeredBy		= Upgrade_DwarvenBarracksLevel2
		ConflictsWith	= Upgrade_GondorBarracksLevel3 Upgrade_WOTRMode
		CommandSet		= DwarvenBarracksCommandSetLevel2X
	End
End
ReplaceModule ModuleTag_DwarvenBarracksLevel3
	Behavior = CommandSetUpgrade ModuleTag_DwarvenBarracksLevel3X
		TriggeredBy		= Upgrade_GondorBarracksLevel3
		ConflictsWith	= Upgrade_WOTRMode		
		CommandSet		= DwarvenBarracksCommandSetLevel3X
	End
End
End

CommandSet DwarvenBarracksCommandSetX
	1 	= Command_ConstructEredLuinTraderHorde
	2 	= Command_ConstructDwarvenGuardianHorde
	3	= Command_ConstructDwarvenPhalanxHorde
	4	= Command_ConstructDwarvenArcherHorde ;DwarvenArcherHorde
	5 	= Command_ConstructDwarvenGrimHammerHorde
	6   = Command_ConstructEredLuinRangerHorde
  	7 	= Command_UpgradeDwarvenBarracksLevel2
  	8 	= Command_Sell
End
CommandSet DwarvenBarracksCommandSetLevel2X
	1 	= Command_ConstructEredLuinTraderHorde
	2 	= Command_ConstructDwarvenGuardianHorde
	3	= Command_ConstructDwarvenPhalanxHorde
	4	= Command_ConstructDwarvenArcherHorde ;DwarvenArcherHorde
	5 	= Command_ConstructDwarvenGrimHammerHorde
	6   = Command_ConstructEredLuinRangerHorde
  	7 	= Command_UpgradeDwarvenBarracksLevel3
  	8 	= Command_Sell
End
CommandSet DwarvenBarracksCommandSetLevel3X
	1 	= Command_ConstructEredLuinTraderHorde
	2 	= Command_ConstructDwarvenGuardianHorde
	3	= Command_ConstructDwarvenPhalanxHorde
	4	= Command_ConstructDwarvenArcherHorde ;DwarvenArcherHorde
	5 	= Command_ConstructDwarvenGrimHammerHorde
	6   = Command_ConstructEredLuinRangerHorde
 	7 	= Command_Sell
End

;-------------------------------------------------------------------------------------------------
;WATERTRANSPARENCY
;-------------------------------------------------------------------------------------------------

WaterTransparency
  ReflectionPlaneZ = 495.0;
  ReflectionOn = Yes
End

;---------------------------------------------------------------------------
;COLONY AND LEADERS
;---------------------------------------------------------------------------

Object DwarvenBalin
VisionRange = 75
ShroudClearingRange = 150
CommandPoints = 1

  VoiceSelect = NoSound
  VoiceMove = NoSound
  VoiceMoveWhileAttacking= NoSound
End

Object DwarvenOin
VisionRange = 75
ShroudClearingRange = 90
CommandPoints = 1

  VoiceSelect = NoSound
  VoiceMove = NoSound
  VoiceMoveWhileAttacking= NoSound
End

Object KhazadGuardHorde_Summoned
RemoveModule ModuleTag_LifetimeUpdate
End

Object KhazadGuard_Summoned

 ReplaceModule ModuleTag_LifetimeUpdate
  Behavior = LifetimeUpdate ModuleTag_Overider
    MinLifetime = 99999999999999999999
    MaxLifetime = 99999999999999999999
  End
 End
End

Object KhazadVetsBanner_Summoned

 ReplaceModule ModuleTag_LifetimeUpdate
  Behavior = LifetimeUpdate ModuleTag_Overider
    MinLifetime = 99999999999999999999
    MaxLifetime = 99999999999999999999
  End
 End
End

Object DwarvenBanner
VisionRange = 75
ShroudClearingRange = 90
PathfindDiameter = 1.0
ReplaceModule ModuleTag_02
	Body = ActiveBody ModuleTag_02X
		CheerRadius 	  = EMOTION_CHEER_RADIUS
		MaxHealth         = 220 ;DWARVEN_AXETHROWER_HEALTH
		MaxHealthDamaged  = 100 ;DWARVEN_AXETHROWER_HEALTH_DAMAGED
		BurningDeathBehavior = Yes
		BurningDeathFX       = FX_InfantryBurningFlame
	End
End
End


Object DwarvenGuardian
PathfindDiameter = 1.0
ReplaceModule ModuleTag_02
	Body = ActiveBody ModuleTag_02X
		CheerRadius 		= EMOTION_CHEER_RADIUS
		MaxHealth			= 220 ;DWARVEN_GUARDIAN_HEALTH
		MaxHealthDamaged	= 100 ;DWARVEN_GUARDIAN_HEALTH_DAMAGED
		BurningDeathBehavior = Yes
		BurningDeathFX       = FX_InfantryBurningFlame
	End
End
End

Object DwarvenArcher
PathfindDiameter = 1.0
ReplaceModule ModuleTag_02
	Body = ActiveBody ModuleTag_02X
		CheerRadius 	  = EMOTION_CHEER_RADIUS
		MaxHealth         = 220 ;DWARVEN_AXETHROWER_HEALTH
		MaxHealthDamaged  = 100 ;DWARVEN_AXETHROWER_HEALTH_DAMAGED
		BurningDeathBehavior = Yes
		BurningDeathFX       = FX_InfantryBurningFlame
	End
End
End

Object DwarvenVWHorde
VisionRange = 75
ShroudClearingRange = 90
	Geometry = BOX
	GeometryMajorRadius = 20.0
	GeometryMinorRadius = 40.0
	GeometryHeight = 20.0
	GeometryIsSmall = No
End

Object DwarvenZerkerHorde
VisionRange = 75
ShroudClearingRange = 90
	Geometry = BOX
	GeometryMajorRadius = 20.0
	GeometryMinorRadius = 40.0
	GeometryHeight = 20.0
	GeometryIsSmall = No
End

Object DwarvenGuardianHorde
VisionRange = 75
ShroudClearingRange = 90
	Geometry = BOX
	GeometryMajorRadius = 20.0
	GeometryMinorRadius = 40.0
	GeometryHeight = 20.0
	GeometryIsSmall = No
End

Object DwarvenArcherHorde
VisionRange = 100
ShroudClearingRange = 110
	Geometry = BOX
	GeometryMajorRadius = 20.0
	GeometryMinorRadius = 40.0
	GeometryHeight = 20.0
	GeometryIsSmall = No
End

Object DwarvenEredLuinRangerHorde
VisionRange = 100
ShroudClearingRange = 110
	Geometry = BOX
	GeometryMajorRadius = 20.0
	GeometryMinorRadius = 40.0
	GeometryHeight = 20.0
	GeometryIsSmall = No
End

Object DwarvenEredLuinTraderHorde
VisionRange = 100
ShroudClearingRange = 110
	Geometry = BOX
	GeometryMajorRadius = 20.0
	GeometryMinorRadius = 40.0
	GeometryHeight = 20.0
	GeometryIsSmall = No
End

Object WildMountainOrcSword
RemoveModule ModuleTag_TerrorOfTheMountainUpgrade
End

;-------------------------------------

Armor WatcherArmorX
  Armor = DEFAULT		  1%
  Armor = PIERCE		1%
  Armor = SIEGE			100%
  Armor = STRUCTURAL		25%
  Armor = FROST          	20%
  Armor = MAGIC			20%
  Armor = HERO			50%
  Armor = UNDEFINED	  	    0% 
End

Object WatcherHead
	ArmorSet
		Conditions      = None
		Armor           = WatcherArmorX
	End
   RemoveModule ModuleTag_LifetimeUpdate
   ReplaceModule ModuleTag_Body
	Body = ActiveBody ModuleTag_Body_Override
		MaxHealth = 32000
	End
  End
End

Object WatcherHittingArm
	RemoveModule ModuleTag_LifetimeUpdate
   ReplaceModule ModuleTag_Body
		Body = ActiveBody ModuleTag_BodyNEW
		MaxHealth = 30000
	End
End
End

Object WatcherCaldera
    RemoveModule ModuleTag_LifetimeUpdate
      ReplaceModule ModuleTag_Draw
	  	Draw = W3DScriptedModelDraw ModuleTag_DrawNEW
        DefaultModelConditionState
            Model = None ;EXCauldera_SKN 
        End
        End
End
End

Weapon WatcherHittingArmWeaponVSMany
ClearNuggets ; Clear all the damage/fx/paralyze etc nuggets so they can be replaced.
	AttackRange = 70 ;150
	AcceptableAimDelta = 25
	PreAttackDelay = 1000
	FiringDuration = 1000
	DelayBetweenShots = Min:3000 Max:5000
	DamageDealtAtSelfPosition = Yes
	DamageNugget
		Damage        = 600
		Radius        = 175
		DamageArc      = 25
		DamageType    = SIEGE
		DamageFXType  = CLUBBING
		DeathType     = NORMAL
	End
	MetaImpactNugget
		HeroResist		= .95
		ShockWaveAmount   = 75.0
		ShockWaveRadius   = 175
		ShockWaveTaperOff = 0.75
		ShockWaveArc      = 25
		ShockWaveZMult    = 1.20
	End
End
Weapon WatcherHittingArmWeaponVSOne
ClearNuggets ; Clear all the damage/fx/paralyze etc nuggets so they can be replaced.
	AttackRange = 70
	AcceptableAimDelta = 25
	PreAttackDelay = 1000
	FiringDuration = 1000
	DelayBetweenShots = Min:3000 Max:5000
	DamageNugget
		Damage        = 700
		Radius        = 25
		DamageType    = SIEGE
		DamageFXType  = CLUBBING
		DeathType     = NORMAL
	End
	MetaImpactNugget
		HeroResist		= .95
		ShockWaveAmount   = 75.0
		ShockWaveRadius   = 25
		ShockWaveTaperOff = 0.75
		ShockWaveZMult    = 1.20
	End
End

;---------------------------------------------------------------------------
;MAP SETTINGS
;---------------------------------------------------------------------------

AIData
    AltCameraZoomOverride = 1.1 ; 1.0 = no change, 0.5 = half height, 0.5 = twice height.
    AltCameraPitchOverride = 0.6 ; 2.0 = no change, 0.0 = looking straight down. 1.0 = looking more towards the horizon (bad)
End

Weather
	CloudTextureSize = X:6000 Y:6000
	CloudOffsetPerSecond = X:-0 Y:-0
End

ShadowMap
	MapSize = 6000
	MaxViewDistance = 6000.0
	MinShadowedTerrainHeight = 0.0
End

Object RivendellWaterfall01
 ReplaceModule 	ModuleTag_01
    Draw = W3DScriptedModelDraw ModuleTag_01_Override
    DefaultModelConditionState
      Model = PMRivFalls01
  End
 End
End
End