

//=====================================================================================================
// This Section contains the RemoveUpgradeUpgrades for Create A Hero Weapons
//=====================================================================================================
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW01
	TriggeredBy		= Upgrade_CHW01 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End
	
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW02
	TriggeredBy		= Upgrade_CHW02 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW03
	TriggeredBy		= Upgrade_CHW03 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW04
	TriggeredBy		= Upgrade_CHW04 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW05
	TriggeredBy		= Upgrade_CHW05 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW06
	TriggeredBy		= Upgrade_CHW06 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW07
	TriggeredBy		= Upgrade_CHW07 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW08
	TriggeredBy		= Upgrade_CHW08 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW09
	TriggeredBy		= Upgrade_CHW09 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW10
	TriggeredBy		= Upgrade_CHW10 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW11
	TriggeredBy		= Upgrade_CHW11 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW12
	TriggeredBy		= Upgrade_CHW12 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW13
	TriggeredBy		= Upgrade_CHW13 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW14
	TriggeredBy		= Upgrade_CHW14 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW15
	TriggeredBy		= Upgrade_CHW15 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW16
	TriggeredBy		= Upgrade_CHW16 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW17
	TriggeredBy		= Upgrade_CHW17 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW18
	TriggeredBy		= Upgrade_CHW18 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW19
	TriggeredBy		= Upgrade_CHW19 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW20
	TriggeredBy		= Upgrade_CHW20 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW21
	TriggeredBy		= Upgrade_CHW21 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW22
	TriggeredBy		= Upgrade_CHW22 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW23
	TriggeredBy		= Upgrade_CHW23 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW24
	TriggeredBy		= Upgrade_CHW24 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW25
	TriggeredBy		= Upgrade_CHW25 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW26
	TriggeredBy		= Upgrade_CHW26 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW27
	TriggeredBy		= Upgrade_CHW27 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW28
	TriggeredBy		= Upgrade_CHW28 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW29
	TriggeredBy		= Upgrade_CHW29 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW30
	TriggeredBy		= Upgrade_CHW30 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW31
	TriggeredBy		= Upgrade_CHW31 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW32
	TriggeredBy		= Upgrade_CHW32
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW33
	TriggeredBy		= Upgrade_CHW33
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW34
	TriggeredBy		= Upgrade_CHW34
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW35
	TriggeredBy		= Upgrade_CHW35 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW36
	TriggeredBy		= Upgrade_CHW36
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW37
	TriggeredBy		= Upgrade_CHW37 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW308
	TriggeredBy		= Upgrade_CHW38 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW39
	TriggeredBy		= Upgrade_CHW39 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW40
	TriggeredBy		= Upgrade_CHW40 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW41
	TriggeredBy		= Upgrade_CHW41 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHW42
	TriggeredBy		= Upgrade_CHW42 
	UpgradeGroupsToRemove = CreateAHero_Weapon
End



//=====================================================================================================
// This section contains the RemoveUpgradeUpgrades for the Create a Hero Bling
//=====================================================================================================
	
//=====================================================================================================
// This section contains the RemoveUpgradeUpgrades for the Create a Hero class
//=====================================================================================================

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_ClassHeroOfTheWest
	TriggeredBy		= Upgrade_CreateAHero_ClassHeroOfTheWest
	UpgradeToRemove	= Upgrade_CreateAHero_ClassWraith Upgrade_CreateAHero_ClassIstariWizard Upgrade_CreateAHero_ClassDwarf Upgrade_CreateAHero_ClassCorruptedMan Upgrade_CreateAHero_ClassServantsOfSauron Upgrade_CreateAHero_ClassArcher Upgrade_CreateAHero_ClassOlogHai
End


Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_ClassIstariWizard
	TriggeredBy		= Upgrade_CreateAHero_ClassIstariWizard
	UpgradeToRemove	= Upgrade_CreateAHero_ClassWraith Upgrade_CreateAHero_ClassHeroOfTheWest Upgrade_CreateAHero_ClassDwarf Upgrade_CreateAHero_ClassCorruptedMan Upgrade_CreateAHero_ClassServantsOfSauron Upgrade_CreateAHero_ClassArcher Upgrade_CreateAHero_ClassOlogHai
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_ClassDwarf
	TriggeredBy		= Upgrade_CreateAHero_ClassDwarf
	UpgradeToRemove	= Upgrade_CreateAHero_ClassWraith Upgrade_CreateAHero_ClassHeroOfTheWest Upgrade_CreateAHero_ClassIstariWizard Upgrade_CreateAHero_ClassCorruptedMan Upgrade_CreateAHero_ClassServantsOfSauron Upgrade_CreateAHero_ClassOlogHai Upgrade_CreateAHero_ClassArcher
End

//	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_ClassHorseman
//		TriggeredBy		= Upgrade_CreateAHero_ClassHorseman
//		UpgradeToRemove	= Upgrade_CreateAHero_ClassWraith Upgrade_CreateAHero_ClassHeroOfTheWest Upgrade_CreateAHero_ClassIstariWizard Upgrade_CreateAHero_ClassDwarf  Upgrade_CreateAHero_ClassCorruptedMan Upgrade_CreateAHero_ClassServantsOfSauron Upgrade_CreateAHero_ClassArcher Upgrade_CreateAHero_ClassOlogHai
//	End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_ClassCorruptedMan
	TriggeredBy		= Upgrade_CreateAHero_ClassCorruptedMan
	UpgradeToRemove	= Upgrade_CreateAHero_ClassWraith Upgrade_CreateAHero_ClassHeroOfTheWest Upgrade_CreateAHero_ClassIstariWizard Upgrade_CreateAHero_ClassDwarf Upgrade_CreateAHero_ClassServantsOfSauron Upgrade_CreateAHero_ClassArcher Upgrade_CreateAHero_ClassOlogHai
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_ClassServantsOfSauron
	TriggeredBy		= Upgrade_CreateAHero_ClassServantsOfSauron
	UpgradeToRemove	= Upgrade_CreateAHero_ClassWraith Upgrade_CreateAHero_ClassHeroOfTheWest Upgrade_CreateAHero_ClassIstariWizard Upgrade_CreateAHero_ClassDwarf Upgrade_CreateAHero_ClassCorruptedMan Upgrade_CreateAHero_ClassArcher Upgrade_CreateAHero_ClassOlogHai
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_ClassArcher
	TriggeredBy		= Upgrade_CreateAHero_ClassArcher
	UpgradeToRemove	= Upgrade_CreateAHero_ClassWraith Upgrade_CreateAHero_ClassHeroOfTheWest Upgrade_CreateAHero_ClassIstariWizard Upgrade_CreateAHero_ClassDwarf Upgrade_CreateAHero_ClassCorruptedMan Upgrade_CreateAHero_ClassServantsOfSauron  Upgrade_CreateAHero_ClassOlogHai
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_ClassOlogHai
	TriggeredBy		= Upgrade_CreateAHero_ClassOlogHai
	UpgradeToRemove	= Upgrade_CreateAHero_ClassWraith Upgrade_CreateAHero_ClassHeroOfTheWest Upgrade_CreateAHero_ClassIstariWizard Upgrade_CreateAHero_ClassDwarf Upgrade_CreateAHero_ClassCorruptedMan Upgrade_CreateAHero_ClassArcher Upgrade_CreateAHero_ClassServantsOfSauron
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_ClassWraith
	TriggeredBy		= Upgrade_CreateAHero_ClassWraith
	UpgradeToRemove	= Upgrade_CreateAHero_ClassHeroOfTheWest Upgrade_CreateAHero_ClassIstariWizard Upgrade_CreateAHero_ClassDwarf Upgrade_CreateAHero_ClassCorruptedMan Upgrade_CreateAHero_ClassServantsOfSauron Upgrade_CreateAHero_ClassArcher Upgrade_CreateAHero_ClassOlogHai
End

//=====================================================================================================
// This section contains the RemoveUpgradeUpgrades for the Create a Hero subclass
//=====================================================================================================

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_SubClass_0
	TriggeredBy		= Upgrade_CreateAHero_SubClass_0
	UpgradeToRemove	= Upgrade_CreateAHero_SubClass_1 Upgrade_CreateAHero_SubClass_2 Upgrade_CreateAHero_SubClass_3 Upgrade_CreateAHero_SubClass_4 Upgrade_CreateAHero_SubClass_5 Upgrade_CreateAHero_SubClass_6
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_SubClass_1
	TriggeredBy		= Upgrade_CreateAHero_SubClass_1
	UpgradeToRemove	= Upgrade_CreateAHero_SubClass_0 Upgrade_CreateAHero_SubClass_2 Upgrade_CreateAHero_SubClass_3 Upgrade_CreateAHero_SubClass_4 Upgrade_CreateAHero_SubClass_5 Upgrade_CreateAHero_SubClass_6
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_SubClass_2
	TriggeredBy		= Upgrade_CreateAHero_SubClass_2
	UpgradeToRemove	= Upgrade_CreateAHero_SubClass_0 Upgrade_CreateAHero_SubClass_1 Upgrade_CreateAHero_SubClass_3 Upgrade_CreateAHero_SubClass_4 Upgrade_CreateAHero_SubClass_5 Upgrade_CreateAHero_SubClass_6
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_SubClass_3
	TriggeredBy		= Upgrade_CreateAHero_SubClass_3
	UpgradeToRemove	= Upgrade_CreateAHero_SubClass_0 Upgrade_CreateAHero_SubClass_1 Upgrade_CreateAHero_SubClass_2  Upgrade_CreateAHero_SubClass_4 Upgrade_CreateAHero_SubClass_5 Upgrade_CreateAHero_SubClass_6
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_SubClass_4
	TriggeredBy		= Upgrade_CreateAHero_SubClass_4
	UpgradeToRemove	= Upgrade_CreateAHero_SubClass_0 Upgrade_CreateAHero_SubClass_1 Upgrade_CreateAHero_SubClass_2 Upgrade_CreateAHero_SubClass_3 Upgrade_CreateAHero_SubClass_5 Upgrade_CreateAHero_SubClass_6
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_SubClass_5
	TriggeredBy		= Upgrade_CreateAHero_SubClass_5
	UpgradeToRemove	= Upgrade_CreateAHero_SubClass_0 Upgrade_CreateAHero_SubClass_1 Upgrade_CreateAHero_SubClass_2 Upgrade_CreateAHero_SubClass_3 Upgrade_CreateAHero_SubClass_4 Upgrade_CreateAHero_SubClass_6
End

Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_SubClass_6
	TriggeredBy		= Upgrade_CreateAHero_SubClass_6
	UpgradeToRemove	= Upgrade_CreateAHero_SubClass_0 Upgrade_CreateAHero_SubClass_1 Upgrade_CreateAHero_SubClass_2 Upgrade_CreateAHero_SubClass_3 Upgrade_CreateAHero_SubClass_4 Upgrade_CreateAHero_SubClass_5 
End


//-------------------------------------------------------
// Generic No Upgrades
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_NoHelmet
	TriggeredBy				= Upgrade_NoHelmet
	UpgradeGroupsToRemove	= CreateAHero_Helmet
End
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_NoShoulderPlates
	TriggeredBy				= Upgrade_NoShoulderPlates
	UpgradeGroupsToRemove	= CreateAHero_ShoulderPlates
End
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_NoGauntlets
	TriggeredBy				= Upgrade_NoGauntlets
	UpgradeGroupsToRemove	= CreateAHero_Gauntlets
End
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_NoShield
	TriggeredBy				= Upgrade_NoShield
	UpgradeGroupsToRemove	= CreateAHero_Shield
End
Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_NoBoots
	TriggeredBy				= Upgrade_NoBoots
	UpgradeGroupsToRemove	= CreateAHero_Boots
End
//-------------------------------------------------------
// Body


// Head Gear
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHH01
		TriggeredBy		= Upgrade_CHH01
		UpgradeGroupsToRemove = CreateAHero_Helmet
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHH02
		TriggeredBy		= Upgrade_CHH02
		UpgradeGroupsToRemove = CreateAHero_Helmet
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHH03
		TriggeredBy		= Upgrade_CHH03
		UpgradeGroupsToRemove = CreateAHero_Helmet
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHH04
		TriggeredBy		= Upgrade_CHH04
		UpgradeGroupsToRemove = CreateAHero_Helmet
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHH05
		TriggeredBy		= Upgrade_CHH05
		UpgradeGroupsToRemove = CreateAHero_Helmet
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHH06
		TriggeredBy		= Upgrade_CHH06
		UpgradeGroupsToRemove = CreateAHero_Helmet
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHH07
		TriggeredBy		= Upgrade_CHH07
		UpgradeGroupsToRemove = CreateAHero_Helmet
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHH08
		TriggeredBy		= Upgrade_CHH08
		UpgradeGroupsToRemove = CreateAHero_Helmet
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHH09
		TriggeredBy		= Upgrade_CHH09
		UpgradeGroupsToRemove = CreateAHero_Helmet
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHH10
		TriggeredBy		= Upgrade_CHH10
		UpgradeGroupsToRemove = CreateAHero_Helmet
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHH11
		TriggeredBy		= Upgrade_CHH11
		UpgradeGroupsToRemove = CreateAHero_Helmet
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHH12
		TriggeredBy		= Upgrade_CHH12
		UpgradeGroupsToRemove = CreateAHero_Helmet
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHH13
		TriggeredBy		= Upgrade_CHH13
		UpgradeGroupsToRemove = CreateAHero_Helmet
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHH14
		TriggeredBy		= Upgrade_CHH14
		UpgradeGroupsToRemove = CreateAHero_Helmet
	End


	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHBOD01
		TriggeredBy		= Upgrade_CHBOD01
		UpgradeGroupsToRemove = CreateAHero_Body
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHBOD02
		TriggeredBy		= Upgrade_CHBOD02
		UpgradeGroupsToRemove = CreateAHero_Body
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHBOD03
		TriggeredBy		= Upgrade_CHBOD03
		UpgradeGroupsToRemove = CreateAHero_Body
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHBOD04
		TriggeredBy		= Upgrade_CHBOD04
		UpgradeGroupsToRemove = CreateAHero_Body
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHBOD05
		TriggeredBy		= Upgrade_CHBOD05
		UpgradeGroupsToRemove = CreateAHero_Body
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHBOD06
		TriggeredBy		= Upgrade_CHBOD06
		UpgradeGroupsToRemove = CreateAHero_Body
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHBOD07
		TriggeredBy		= Upgrade_CHBOD07
		UpgradeGroupsToRemove = CreateAHero_Body
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHBOD08
		TriggeredBy		= Upgrade_CHBOD08
		UpgradeGroupsToRemove = CreateAHero_Body
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHBOD09
		TriggeredBy		= Upgrade_CHBOD09
		UpgradeGroupsToRemove = CreateAHero_Body
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHBOD10
		TriggeredBy		= Upgrade_CHBOD10
		UpgradeGroupsToRemove = CreateAHero_Body
	End


	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHB01
		TriggeredBy		= Upgrade_CHB01
		UpgradeGroupsToRemove = CreateAHero_Boots
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHB02
		TriggeredBy		= Upgrade_CHB02
		UpgradeGroupsToRemove = CreateAHero_Boots
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHB03
		TriggeredBy		= Upgrade_CHB03
		UpgradeGroupsToRemove = CreateAHero_Boots
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHB04
		TriggeredBy		= Upgrade_CHB04
		UpgradeGroupsToRemove = CreateAHero_Boots
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHB05
		TriggeredBy		= Upgrade_CHB05
		UpgradeGroupsToRemove = CreateAHero_Boots
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHB06
		TriggeredBy		= Upgrade_CHB06
		UpgradeGroupsToRemove = CreateAHero_Boots
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHB07
		TriggeredBy		= Upgrade_CHB07
		UpgradeGroupsToRemove = CreateAHero_Boots
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHB08
		TriggeredBy		= Upgrade_CHB08
		UpgradeGroupsToRemove = CreateAHero_Boots
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHB09
		TriggeredBy		= Upgrade_CHB09
		UpgradeGroupsToRemove = CreateAHero_Boots
	End


	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHS01
		TriggeredBy		= Upgrade_CHS01
		UpgradeGroupsToRemove = CreateAHero_Shield
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHS02
		TriggeredBy		= Upgrade_CHS02
		UpgradeGroupsToRemove = CreateAHero_Shield
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHS03
		TriggeredBy		= Upgrade_CHS03
		UpgradeGroupsToRemove = CreateAHero_Shield
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHS04
		TriggeredBy		= Upgrade_CHS04
		UpgradeGroupsToRemove = CreateAHero_Shield
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHS05
		TriggeredBy		= Upgrade_CHS05
		UpgradeGroupsToRemove = CreateAHero_Shield
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHS06
		TriggeredBy		= Upgrade_CHS06
		UpgradeGroupsToRemove = CreateAHero_Shield
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHS07
		TriggeredBy		= Upgrade_CHS07
		UpgradeGroupsToRemove = CreateAHero_Shield
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHS08
		TriggeredBy		= Upgrade_CHS08
		UpgradeGroupsToRemove = CreateAHero_Shield
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHS09
		TriggeredBy		= Upgrade_CHS09
		UpgradeGroupsToRemove = CreateAHero_Shield
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHS10
		TriggeredBy		= Upgrade_CHS10
		UpgradeGroupsToRemove = CreateAHero_Shield
	End

	
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHG01
		TriggeredBy		= Upgrade_CHG01
		UpgradeGroupsToRemove = CreateAHero_Gauntlets
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHG02
		TriggeredBy		= Upgrade_CHG02
		UpgradeGroupsToRemove = CreateAHero_Gauntlets
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHG03
		TriggeredBy		= Upgrade_CHG03
		UpgradeGroupsToRemove = CreateAHero_Gauntlets
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHG04
		TriggeredBy		= Upgrade_CHG04
		UpgradeGroupsToRemove = CreateAHero_Gauntlets
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHG05
		TriggeredBy		= Upgrade_CHG05
		UpgradeGroupsToRemove = CreateAHero_Gauntlets
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHG06
		TriggeredBy		= Upgrade_CHG06
		UpgradeGroupsToRemove = CreateAHero_Gauntlets
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHG07
		TriggeredBy		= Upgrade_CHG07
		UpgradeGroupsToRemove = CreateAHero_Gauntlets
	End


	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHSP01
		TriggeredBy		= Upgrade_CHSP01
		UpgradeGroupsToRemove = CreateAHero_ShoulderPlates
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHSP02
		TriggeredBy		= Upgrade_CHSP02
		UpgradeGroupsToRemove = CreateAHero_ShoulderPlates
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHSP03
		TriggeredBy		= Upgrade_CHSP03
		UpgradeGroupsToRemove = CreateAHero_ShoulderPlates
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHSP04
		TriggeredBy		= Upgrade_CHSP04
		UpgradeGroupsToRemove = CreateAHero_ShoulderPlates
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHSP05
		TriggeredBy		= Upgrade_CHSP05
		UpgradeGroupsToRemove = CreateAHero_ShoulderPlates
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHSP06
		TriggeredBy		= Upgrade_CHSP06
		UpgradeGroupsToRemove = CreateAHero_ShoulderPlates
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHSP07
		TriggeredBy		= Upgrade_CHSP07
		UpgradeGroupsToRemove = CreateAHero_ShoulderPlates
	End
	Behavior = RemoveUpgradeUpgrade Remove_Upgrades_Upgrade_CreateAHero_Upgrade_CHSP08
		TriggeredBy		= Upgrade_CHSP08
		UpgradeGroupsToRemove = CreateAHero_ShoulderPlates
	End
