;-------------------------------------Morgul Wraith fx
FXParticleSystem MorgulWraithShadow
  System
    Priority = ALWAYS_RENDER
    ParticleName = EXdarkGlow2.tga
    Lifetime = 100 100
    SystemLifetime = 520
    Shader = ALPHA
    SortLevel = 1
    Size = 18 18
    BurstDelay = 5 6
    BurstCount = 1 1
  End
  Color = DefaultColor
    Color2 = R:99 G:226 B:196 50
    Color3 = R:6 G:64 B:44 100
  End
  Alpha = DefaultAlpha
    Alpha1 = 0.0 0.0 1
    Alpha2 = 0.095 0.095 20
    Alpha3 = 0.095 0.095 80
    Alpha4 = 0.0 0.0 100
    ;Alpha3 = 0 0 35
  End
  Update = DefaultUpdate
    SizeRate = 0.03 0.05
    ;SizeRateDamping = 0.9 0.93
    ;AngleZ = 0 7
    ;AngularRateZ = -0.05 0.05
    ;AngularDamping = 1 1
    ;AngularDampingXY = 1 1
  End
  Physics = DefaultPhysics
    VelocityDamping = 0.98 0.99
    ;Gravity = 0.1
  End
  EmissionVelocity = OrthoEmissionVelocity
    ;X = 0 0.2
  End
  EmissionVolume = LineEmissionVolume
    StartPoint = X:0 Y:0 Z:20
    EndPoint = X:0 Y:0 Z:4
  End
  Draw = DefaultDraw
  End
End
FXParticleSystem MorgulWraithGlow
  System
    Priority = ALWAYS_RENDER
    ParticleName = EXGlow04.tga
    Lifetime = 100 100
    SystemLifetime = 520
    SortLevel = 2
    Size = 13 16
    BurstDelay = 35 35
    BurstCount = 1 1
  End
  Color = DefaultColor
    Color1 = R:0 G:0 B:0 0
    Color2 = R:48.6 G:110.8 B:95.2 20
    Color3 = R:48.6 G:125.35 B:95.2 80
    Color4 = R:0 G:0 B:0 100
  End
  Update = DefaultUpdate
    SizeRate = 0.3 0.75
    SizeRateDamping = 0.9 0.93
    ;AngleZ = 0 7
    ;AngularRateZ = -0.05 0.05
    ;AngularDamping = 1 1
    ;AngularDampingXY = 1 1
  End
  Physics = DefaultPhysics
    VelocityDamping = 0.98 0.99
  End
  EmissionVelocity = OrthoEmissionVelocity
    X = 0 0.2
  End
  EmissionVolume = LineEmissionVolume
    StartPoint = X:-3.5 Y:0 Z:14
    EndPoint = X:-3.5 Y:0 Z:4
  End
  Draw = DefaultDraw
  End
End

FXParticleSystem MorgulWraithEye_L
  System
    Priority = VERY_LOW_OR_ABOVE
    ParticleName = EXFire01.tga
    Lifetime = 2 2
    SystemLifetime = 507
    Size = 0.25 0.25
    ;StartSizeRate = -0.16 -0.32
    BurstCount = 2 2
  End
  Color = DefaultColor
    Color1 = R:36 G:203 B:149 0
    Color2 = R:0 G:0 B:0 7
  End
  Update = DefaultUpdate
    SizeRate = -0.005 -0.005
    ;SizeRateDamping = 0.99 0.99
    AngleZ = 0 7
    AngularRateZ = -0.01 0.01
    AngularDamping = 1 1
    AngularDampingXY = 1 1
  End
  Physics = DefaultPhysics
    Gravity = 0.16
    VelocityDamping = 1 1
  End
  EmissionVelocity = OrthoEmissionVelocity
  End
  EmissionVolume = LineEmissionVolume
    StartPoint = X:1.92 Y:-0.87 Z:-0.30
    EndPoint = X:1.92 Y:-0.87 Z:-0.30
  End
  Draw = DefaultDraw
  End
End
















Weather

	HardwareFogColor = R:180 G:190 B:200
	HardwareFogEnable = Yes
	HardwareFogStart = 300
	HardwareFogEnd = 1500
	
CloudTextureSize = X:1000 Y:1000		; size in world units that one repetition of the cloud texture spans
CloudOffsetPerSecond = X:0.02 Y:0.0	; offset in texture units that the cloud texture moves per second

End

ShadowMap
	MaxViewDistance = 50
	;MapSize = 2048 ; Use default 1024! Higher numbers cause too much slowdown
End



Object ParticleSysProxy
 
ReplaceModule ModuleTag_01
  ; *** ART Parameters ***
  Draw = W3DScriptedModelDraw ModuleTag_01_Override
    DefaultModelConditionState
      Model = NONE
      ParticleSysBone = None CINEsmokeLarge
      ParticleSysBone = None CHAreaFissureEffect
    End
  
    ModelConditionState = WORLD_BUILDER
   Model = locator
 End
  End
End
End



Object ParticleSysProxy2
 
ReplaceModule ModuleTag_01
  ; *** ART Parameters ***
  Draw = W3DScriptedModelDraw ModuleTag_01_Override
    DefaultModelConditionState
      Model = NONE
      ParticleSysBone = None CHSmoke
    End
  
    ModelConditionState = WORLD_BUILDER
   Model = locator
 End
  End
End
End


Object CINE_ParticleSysProxy4

 ReplaceModule ModuleTag_01
  Draw = W3DScriptedModelDraw ModuleTag_01_Override
    DefaultModelConditionState
      Model = NONE
      ParticleSysBone = emberBone FloatingDust
      ParticleSysBone = None None;FireSmokeBig
    End
  
    ModelConditionState = WORLD_BUILDER
	  Model = locator
	End
  End
 End
End


FXParticleSystem FloatingDust
  System
    Priority = ALWAYS_RENDER
	Shader = ALPHA
    ParticleName = EXCloud02.tga; EXCineSparks.tga
    Lifetime = 150 300; 100 200
    SortLevel = 1
    Size = 0.1 0.2; 0.1 0.2
    BurstDelay = 1 10
    BurstCount = 12 20; 3 5
  End
 
  Color = DefaultColor
    Color1 = R:205 G:192 B:168 0; R:255 G:185 B:79 0
    ;Color2 = R:105 G:92 B:68 100; R:0 G:0 B:0 200
    ;ColorScale = 2 -2
  End
  
    Alpha = DefaultAlpha
    Alpha1 = 1 1 30; 0.1 0.3 50
    ;Alpha2 = .7 .7 150; 0 0 350
	Alpha2 = 0 0 280; 0 0 350
  End
  Update = DefaultUpdate
    SizeRate = 0.01 0.07
    SizeRateDamping = 0.65 0.8
    AngleZ = -3 3
    AngularRateZ = -0.3 0.3
    AngularDamping = 0.9 0.99
    AngularDampingXY = 1 1
  End
  Physics = DefaultPhysics
    Gravity = 0.008
    VelocityDamping = 0.95 0.99
    DriftVelocity = X:0.2 Y:0.15 Z:-0.4; X:0 Y:0 Z:0.64
  End
  EmissionVelocity = OrthoEmissionVelocity
  End
  EmissionVolume = CylinderEmissionVolume
    Radius = 100; 7
    Length = 5; 1
  End
  Draw = DefaultDraw
  End
  Wind = DefaultWind
    WindMotion = PingPong

    WindStrength = 0.25; 0.25
    WindFullStrengthDist = 5
    WindZeroStrengthDist = 100
    WindAngleChangeMin = 0.034907
    WindAngleChangeMax = 0.034907
    WindPingPongStartAngleMin = 1.22173
    WindPingPongStartAngleMax = 1.22173
    WindPingPongEndAngleMin = 1.91986
    WindPingPongEndAngleMax = 1.91986
    TurbulenceAmplitude = 0.2
    TurbulenceFrequency = 50
  End
End



Object TreeLothlorien13
 
 IsGrabbable = No
 IsHarvestable = No

ReplaceModule ModuleTag_01
	Draw = W3DScriptedModelDraw ModuleTag_Draw1

		DefaultModelConditionState
		Model	= PTLoth13
		End

		  StaticSortLevelWhileFading = 2
		AlphaCameraFadeOuterRadius = 200
		AlphaCameraFadeInnerRadius = 100
		AlphaCameraAtInnerRadius = 100%

	End
End 
End

Object TreeLothlorien14
 
 IsGrabbable = No
 IsHarvestable = No

ReplaceModule ModuleTag_01
	Draw = W3DScriptedModelDraw ModuleTag_Draw1

		DefaultModelConditionState
		Model	= PTLoth14
		End

		  StaticSortLevelWhileFading = 2
		AlphaCameraFadeOuterRadius = 200
		AlphaCameraFadeInnerRadius = 100
		AlphaCameraAtInnerRadius = 100%

	End
End 
End


Object CINE_ParticleSysProxy5

  ; *** ART Parameters ***
 ReplaceModule ModuleTag_01
  Draw = W3DScriptedModelDraw ModuleTag_01_Override
    DefaultModelConditionState
      Model = NONE
      ParticleSysBone = emberBone LightSunRays
      ParticleSysBone = None None;FireSmokeBig
    End
  
    ModelConditionState = WORLD_BUILDER
	  Model = locator
	End
  End
 End
End



FXParticleSystem LightSunRays
  System
    Priority = ALWAYS_RENDER
    Shader = W3D_EMISSIVE
    Type = DRAWABLE
    ParticleName = EXCldBrkRays.W3D
    Lifetime = 300 300
 ;   SystemLifetime = 200
    Size = 0.5 0.5; 1.2 1.2;0.1 0.1
    BurstDelay = 180 180;20 90
    BurstCount = 1 1; 0 2
  End
  Color = DefaultColor
    Color1 = R:164 G:140 B:104 0
    Color2 = R:0 G:0 B:0 400
  End
  Alpha = DefaultAlpha
    Alpha2 = 0.05 0.05 120
    Alpha3 = 0.0 0.0 220
	;Alpha4 = 0 0 400
	;Alpha5 = 0 0 400
  End
    Update = DefaultUpdate
    ;SizeRate = 0.04 0.04
    ;SizeRateDamping = 0.95 0.97
    AngleZ = -5.9 -5.9
    ;AngularDamping = 1 1
    Rotation = ROTATE_Y
    ;AngularDampingXY = 1 1
  End
  ; Update = RenderObjectUpdate
    ; StartSizeX = 0.3 0.3
    ; StartSizeY = 0.3 0.3
    ; StartSizeZ = 1 1
    ; SizeRateX = 0.01 0.01
    ; SizeRateY = 0.01 0.01
    ; SizeDampingX = 0.99 0.99
    ; SizeDampingY = 0.99 0.99
    ; SizeDampingZ = 0.98 0.98
    ; AngleZ = 1.6 1.6; -5 5
    ; AngularRateZ = -0.01 0.01
    ; AngularDamping = 0.99 0.99
    ; Rotation = ROTATE_Z
  ; End
  Physics = DefaultPhysics
    VelocityDamping = 1 1
	DriftVelocity = X:0.02 Y:0 Z:0.05;
  End
  EmissionVelocity = OrthoEmissionVelocity
    ; X = 0.5 0.5
    ; Y = 0 0
    ; Z = -0.2 -0.2
  End
   EmissionVolume = PointEmissionVolume;
    ; Radius = 50
    ; Length = 5
   End
  Draw = RenderObjectDraw
  End
End


