Weather
  HardwareFogColor = R:15 G:44 B:31
  HardwareFogEnable = Yes
  HardwareFogStart = 20
  HardwareFogEnd = 500
End




Weather
  ; Cloud control
  CloudTextureSize = X:1000 Y:1000		; size in world units that one repetition of the cloud texture spans
  CloudOffsetPerSecond = X:0.00 Y:0.0	; offset in texture units that the cloud texture moves per second
End


ShadowMap
	MapSize = 4096
	MaxViewDistance = 6000.0
	MinShadowedTerrainHeight = 0.0
End