
WaterTransparency
 ReflectionPlaneZ = 59.0;
 ReflectionOn = Yes
End

Weather

	HardwareFogColor = R:170 G:190 B:195
	HardwareFogEnable = Yes
	HardwareFogStart = 500
	HardwareFogEnd = 9000
	
End


;-------------------------------------------------------------------------------------------------
; PROPS
;-------------------------------------------------------------------------------------------------

Object AotRIronHillsBridge01
  RemoveModule ModuleTag_03
  AddModule
    Body                  = ImmortalBody ModuleTag_B_03
    MaxHealth       = 6000.0
    MaxHealthDamaged = 3000
    MaxHealthReallyDamaged = 1000  
	End
End
  AddModule
	Behavior = InvisibilityUpdate ModuleTag_StealthForEscape
		InvisibilityNugget
			InvisibilityType			= CAMOUFLAGE
			ForbiddenConditions			= FIRING_ANY
			BecomeStealthedFX       	= FX_ElvenCloakOn
			ExitStealthFX           	= FX_ElvenCloakOff
			DetectionRange				= 0
			HintDetectableConditions    = IS_FIRING_WEAPON
		End
		StartsActive					= Yes
		UpdatePeriod					= 2000
	End
End
End

Object AOTRGondorWeaponRack05
  KindOf = PRELOAD STRUCTURE IMMOBILE NOT_AUTOACQUIRABLE SCORE
End

Object IthilienWeapRackSprs
  KindOf = PRELOAD STRUCTURE IMMOBILE NOT_AUTOACQUIRABLE SCORE
End

Object IthilienSupplies01
  KindOf = PRELOAD STRUCTURE IMMOBILE NOT_AUTOACQUIRABLE SCORE
End

Object IthilienSupplies02
  KindOf = PRELOAD STRUCTURE IMMOBILE NOT_AUTOACQUIRABLE SCORE
End

Object Stool01
  KindOf = PRELOAD STRUCTURE IMMOBILE NOT_AUTOACQUIRABLE SCORE
End

Object Table01
  KindOf = PRELOAD STRUCTURE IMMOBILE NOT_AUTOACQUIRABLE SCORE
End

Object TDHDaleCartEmpty
  KindOf = PRELOAD STRUCTURE IMMOBILE NOT_AUTOACQUIRABLE SCORE
End

;-------------------------------------------------------------------------------------------------
;GEOMETRY
;-------------------------------------------------------------------------------------------------

Object AotRGCTable
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End


Object AotRDolGuldurBridgeA
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotRDolGuldurBridgeB01
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotRDolGuldurBridgeB03
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotRDolGuldurBridgeB04
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotRDolGuldurRuinF
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotRDolGuldurWallB01
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotRDolGuldurGateA03
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotRDolGuldurGateA08
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotRDolGuldurCliffB02
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotRDolGuldurCliffb04
  Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotRDolGuldurCliffb07
  Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotRDolGuldurRock01
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotRDolGuldurRock05
  Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotRDolGuldurRock07
  Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object DarkRockGrey02
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotRAmonHenR02
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotRAmonHenR03
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotRAmonHenN08
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotRAmonHenRockCliff07
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotRAmonHenRockCliff08
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotROsgiliathProp01
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotROsgiliathProp06
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotROsgiliathProp09
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotROsgiliathProp10
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotROsgiliathProp13
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotROsgiliathProp19
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotROsgiliathProp20
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotROsgiliathProp25
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotROsgiliathProp28
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotROsgiliathProp33
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotROsgiliathProp36
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotROsgiliathProp37
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotROsgiliathProp40
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotROsgiliathProp42
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotROsgiliathProp47
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotROsgiliathProp52
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotROsgiliathProp53
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotROrthanc05
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object IsengardScaffolding06
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object IsengardScaffolding08
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object IsengardScaffolding09
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object IsengardScaffolding12
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object IsengardScaffolding13
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object IsengardScaffolding16
ReplaceModule ModuleTag_01
  Draw = W3DScriptedModelDraw ModuleTag_01X
    DefaultModelConditionState
      Model = IUScaff09
    End
    
		;--damaged building
	  
		ModelConditionState  = DAMAGED
			Model         = IUScaff09  
		End
		AnimationState = DAMAGED
		End	    
		
		ModelConditionState  = REALLYDAMAGED
			Model         = IUScaff09
		End
		AnimationState = REALLYDAMAGED
		     	EnteringStateFX	= FX_BuildingReallyDamaged
		End
    
		ModelConditionState  = COLLAPSING
			Model         = IUScaff09_D2
		End
		AnimationState = COLLAPSING
      		Animation				=	RubbleAnimation
				AnimationName		=	 IUScaff09_D2.IUScaff09_D2
				AnimationMode		=	ONCE
  			End
		End

		ModelConditionState  = RUBBLE
			Model         = IUScaff09_D3  
		End  

  End
 End
  Geometry				= BOX
  GeometryMajorRadius	= 21.4
  GeometryMinorRadius	= 29.4
  GeometryHeight		= 64.8
  
  GeometryIsSmall		= No
  Shadow				= SHADOW_VOLUME
End

Object IsengardScaffolding17
ReplaceModule ModuleTag_01
  Draw = W3DScriptedModelDraw ModuleTag_01X
    DefaultModelConditionState
      Model = IUScaff05
    End
    
		;--damaged building
	  
		ModelConditionState  = DAMAGED
			Model         = IUScaff05  
		End
		AnimationState = DAMAGED
		End	    
		
		ModelConditionState  = REALLYDAMAGED
			Model         = IUScaff08
		End
		AnimationState = REALLYDAMAGED
		     	EnteringStateFX	= FX_BuildingReallyDamaged
		End
    
		ModelConditionState  = COLLAPSING
			Model         = IUScaff05_D2
		End
		AnimationState = COLLAPSING
      		Animation				=	RubbleAnimation
				AnimationName		=	 IUScaff05_D2.IUScaff05_D2
				AnimationMode		=	ONCE
  			End
		End

		ModelConditionState  = RUBBLE
			Model         = IUScaff05_D3  
		End  

  End
 End
  Geometry				= BOX
  GeometryMajorRadius	= 32.4
  GeometryMinorRadius	= 12.4
  GeometryHeight		= 58.8
  
  GeometryIsSmall		= No
  Shadow				= SHADOW_VOLUME
End

Object SignalFire
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End

Object AotRMoriaHallAWall01a
   Geometry            = BOX
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 0
  GeometryHeight      = 0
  Shadow              = SHADOW_VOLUME
  InstanceScaleFuzziness = 0
End


Object RivendellWaterfall01
ReplaceModule ModuleTag_01
Draw = W3DScriptedModelDraw ModuleTag_01NEW
    DefaultModelConditionState
      Model = PMRivFalls01
      ParticleSysBone = None WaterFallMist Followbone:YES
      ParticleSysBone = None WaterFallSplash Followbone:YES
      ParticleSysBone = None WaterFallSplash Followbone:YES
      ParticleSysBone = None WaterFallSplash Followbone:YES
      ParticleSysBone = None WaterFallSplash Followbone:YES
      ParticleSysBone = None WaterFallSplash Followbone:YES
    End
  End

End
End


;startOfAuto-Generation
;------------------------------------------------------------------------;
;	  ARNOR REGION 														 ;
;------------------------------------------------------------------------;
Object Inn
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Arnor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Arnor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Arnor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Arnor
		End
	End
End
Object InnDesert
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Arnor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Arnor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Arnor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Arnor
		End
	End
End
Object InnSnow
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Arnor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Arnor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Arnor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Arnor
		End
	End
End
Object Inn_old
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Arnor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Arnor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Arnor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Arnor
		End
	End
End
;endOfAuto-Generation


;==== Auto Generated AI Fix =====;
SkirmishAIData TheSkirmishAIData
    DisableBaseBuilding        = No
    DisableEconomyBuilding     = No
    DisableUnitBuilding        = No
    DisableScienceUpgrading    = No
    DisableUnitUpgrading       = No
    DisableTacticalAI          = No
    DisableTeamBuilding        = No
    DisableWallBuilding        = Yes ;,; No
End
