
//-------------------------------------------------------------------------------------------------
// Starting units (heroes and armies) for each faction
//-------------------------------------------------------------------------------------------------

//-------------------------------------------------------------------------------------------------
// Men of the West starting armies
//-------------------------------------------------------------------------------------------------

LivingWorldPlayerArmy
	Name = FaramirPlayerArmy
	DisplayNameTag = LWA:MenHeroArmy
	ArmyEntry
		ThingTemplate = GondorFaramir
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = BoromirPlayerArmy
	DisplayNameTag = LWA:MenHeroArmy	
	ArmyEntry
		ThingTemplate = GondorBoromir
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = ImrahilPlayerArmy
	DisplayNameTag = LWA:MenHeroArmy	
	ArmyEntry
		ThingTemplate = GondorImrahil_WOTR
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = GandalfPlayerArmy
	DisplayNameTag = LWA:MenHeroArmy	
	ArmyEntry
		ThingTemplate = GondorGandalf_WOTR
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = MenOfTheWest_StartingArmy
	DisplayNameTag = LWA:MenOfTheWestGarrison
	ArmyEntry
		ThingTemplate = LamedonClansmenHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = LamedonClansmenHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorLinhirSentryHorde
		Quantity = 1
	End		
	ArmyEntry
		ThingTemplate = BlackrootValeArcherHorde
		Quantity = 1
	End	
End

LivingWorldPlayerArmy
	Name = PelargirNCArmy
	DisplayNameTag = LWA:MenOfTheWestGarrison
	ArmyEntry
		ThingTemplate = GondorLinhirSentryHorde
		Quantity = 1
	End		
	ArmyEntry
		ThingTemplate = BlackrootValeArcherHorde
		Quantity = 1
	End	
End

//-------------------------------------------------------------------------------------------------
// Rohan starting armies
//-------------------------------------------------------------------------------------------------

LivingWorldPlayerArmy
	Name = ErkenbrandPlayerArmy
	DisplayNameTag = LWA:RohanHeroArmy	
	ArmyEntry
		ThingTemplate = RohanErkenbrand
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = TheodredPlayerArmy
	DisplayNameTag = LWA:RohanHeroArmy	
	ArmyEntry
		ThingTemplate = RohanTheodred
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = EomerPlayerArmy
	DisplayNameTag = LWA:RohanHeroArmy	
	ArmyEntry
		ThingTemplate = RohanEomer
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = TheodenPlayerArmy
	DisplayNameTag = LWA:RohanHeroArmy	
	ArmyEntry
		ThingTemplate = RohanTheoden
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = Rohan_StartingArmy
	DisplayNameTag = LWA:MenOfTheWestGarrison
	ArmyEntry
		ThingTemplate = RohanPeasantHorde_Drafted
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanPeasantHorde_Drafted
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanSpearmenHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanArcherNewHorde
		Quantity = 1
	End
End

//-------------------------------------------------------------------------------------------------
// Lothlorien starting armies
//-------------------------------------------------------------------------------------------------

LivingWorldPlayerArmy
	Name = RumilPlayerArmy
	DisplayNameTag = LWA:ElvesHeroArmy
	ArmyEntry
		ThingTemplate = ElvenRumil
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = HaldirPlayerArmy
	DisplayNameTag = LWA:ElvesHeroArmy	
	ArmyEntry
		ThingTemplate = ElvenHaldir
		Quantity = 1
	End	
End

LivingWorldPlayerArmy
	Name = CelebornPlayerArmy
	DisplayNameTag = LWA:ElvesHeroArmy	
	ArmyEntry
		ThingTemplate = ElvenCeleborn
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = GaladrielPlayerArmy
	DisplayNameTag = LWA:ElvesHeroArmy	
	ArmyEntry
		ThingTemplate = ElvenGaladrielLorien_WOTR
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = Elven_StartingArmy
	DisplayNameTag = LWA:ElvesGarrison
	ArmyEntry
		ThingTemplate = ElvenAxeElfHorde_Recruited
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ElvenLorienWarriorHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ElvenLorienArcherHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ElvenLorienArcherHorde
		Quantity = 1
	End
End

//-------------------------------------------------------------------------------------------------
// Rivendell starting armies
//-------------------------------------------------------------------------------------------------

LivingWorldPlayerArmy
	Name = GildorPlayerArmy
	DisplayNameTag = LWA:RivendellHeroArmy
	ArmyEntry
		ThingTemplate = ElvenGildor
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = StriderPlayerArmy
	DisplayNameTag = LWA:RivendellHeroArmy
	ArmyEntry
		ThingTemplate = ElvenAragorn
		Quantity = 1
	End	
End

LivingWorldPlayerArmy
	Name = GlorfindelPlayerArmy
	DisplayNameTag = LWA:RivendellHeroArmy	
	ArmyEntry
		ThingTemplate = ElvenGlorfindel_WOTR
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = ElrondPlayerArmy
	DisplayNameTag = LWA:RivendellHeroArmy
	ArmyEntry
		ThingTemplate = ElvenElrond_WOTR
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = Rivendell_StartingArmy
	DisplayNameTag = LWA:RivendellGarrison
	ArmyEntry
		ThingTemplate = ArnorRangerHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ArnorRangerHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ArnorRangerHorde
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = Rivendell_DunadanArmy
	DisplayNameTag = LWA:RivendellGarrison
	ArmyEntry
		ThingTemplate = ArnorRangerHorde
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = Noldor_StartingArmy
	DisplayNameTag = LWA:RivendellGarrison
	ArmyEntry
		ThingTemplate = ElvenRivendellKnightHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RivendellHobbitFriendsHordeLWM
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RivendellHobbitFriendsHordeLWM
		Quantity = 1
	End
End

//-------------------------------------------------------------------------------------------------
// Woodland Realm starting armies
//-------------------------------------------------------------------------------------------------

LivingWorldPlayerArmy
	Name = TaurielPlayerArmy
	DisplayNameTag = LWA:MirkwoodHeroArmy
	ArmyEntry
		ThingTemplate = MirkwoodTauriel
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = FerenPlayerArmy
	DisplayNameTag = LWA:MirkwoodHeroArmy
	ArmyEntry
		ThingTemplate = MirkwoodFeren
		Quantity = 1
	End	
End

LivingWorldPlayerArmy
	Name = LegolasPlayerArmy
	DisplayNameTag = LWA:MirkwoodHeroArmy
	ArmyEntry
		ThingTemplate = MirkwoodLegolas
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = ThranduilPlayerArmy
	DisplayNameTag = LWA:MirkwoodHeroArmy
	ArmyEntry
		ThingTemplate = MirkwoodThranduil
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = Mirkwood_StartingArmy
	DisplayNameTag = LWA:MirkwoodGarrison
	ArmyEntry
		ThingTemplate = MirkwoodRangerHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MirkwoodRangerHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MirkwoodWardenHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MirkwoodSpearHorde
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = Greenwood_StartingArmy
	DisplayNameTag = LWA:MirkwoodGarrison
	ArmyEntry
		ThingTemplate = MirkwoodWarriorHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MirkwoodPalaceGuardHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GreenwoodArcherHorde
		Quantity = 1
	End
End

//-------------------------------------------------------------------------------------------------
// Dwarven starting armies
//-------------------------------------------------------------------------------------------------

LivingWorldPlayerArmy
	Name = BalinPlayerArmy
	DisplayNameTag = LWA:DwarvesHeroArmy
	ArmyEntry
		ThingTemplate = DwarvenBalin
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = DainPlayerArmy
	DisplayNameTag = LWA:DwarvesHeroArmy	
	ArmyEntry
		ThingTemplate = DwarvenDain_WOTR
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = CaptainofDalePlayerArmy
	DisplayNameTag = LWA:DwarvesHeroArmy	
	ArmyEntry
		ThingTemplate = DwarvenCaptainofDale
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = ThorinPlayerArmy
	DisplayNameTag = LWA:DwarvesHeroArmy	
	ArmyEntry
		ThingTemplate = DwarvenThorin_WOTR
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = BrandPlayerArmy
	DisplayNameTag = LWA:DwarvesHeroArmy	
	ArmyEntry
		ThingTemplate = DwarvenBrand_WOTR
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = GimliPlayerArmy
	DisplayNameTag = LWA:DwarvesHeroArmy	
	ArmyEntry
		ThingTemplate = DwarvenGimli_WOTR
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = StonehelmPlayerArmy
	DisplayNameTag = LWA:DwarvesHeroArmy	
	ArmyEntry
		ThingTemplate = DwarvenThorinStonehelm_WOTR
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = Dwarven_StartingArmy
	DisplayNameTag = LWA:DwarvesGarrison
	ArmyEntry
		ThingTemplate = DwarvenGuardianHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = DwarvenGuardianHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = DwarvenPhalanxHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = DwarvenArcherHorde
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = Dale_StartingArmy
	DisplayNameTag = LWA:DwarvesGarrison
	ArmyEntry
		ThingTemplate = MenofDaleSwordsmanHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = DwarvenMenOfDaleHorde
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = IH_StartingArmy
	DisplayNameTag = LWA:DwarvesGarrison
	ArmyEntry
		ThingTemplate = IronHillsWarriorHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IronHillsWarriorHorde
		Quantity = 1
	End
End

//-------------------------------------------------------------------------------------------------
// Corrupted Wild starting armies
//-------------------------------------------------------------------------------------------------

LivingWorldPlayerArmy
	Name = MuzgashPlayerArmy
	DisplayNameTag = LWA:WildHeroArmy
	ArmyEntry
		ThingTemplate = WildMuzgash
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = UrshakPlayerArmy
	DisplayNameTag = LWA:WildHeroArmy
	ArmyEntry
		ThingTemplate = WildUrshak
		Quantity = 1
	End
End	

LivingWorldPlayerArmy
	Name = GreatGoblinPlayerArmy
	DisplayNameTag = LWA:WildHeroArmy
	ArmyEntry
		ThingTemplate = WildGreatGoblin
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = AzogPlayerArmy
	DisplayNameTag = LWA:WildHeroArmy
	ArmyEntry
		ThingTemplate = WildAzog_WOTR
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = CorruptedWild_StartingArmy
	DisplayNameTag = LWA:WildGarrison
	ArmyEntry
		ThingTemplate = GoblinFighterHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinFighterHorde
		Quantity = 1
	End	
	ArmyEntry
		ThingTemplate = GoblinFighterHorde
		Quantity = 1
	End	
	ArmyEntry
		ThingTemplate = GoblinArcherHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildMountainOrcBruteHorde
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = Moria_StartingArmy
	DisplayNameTag = LWA:WildGarrison
	ArmyEntry
		ThingTemplate = GoblinFighterHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinFighterHorde
		Quantity = 1
	End	
	ArmyEntry
		ThingTemplate = GoblinArcherHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinArcherHorde
		Quantity = 1
	End
End	

LivingWorldPlayerArmy
	Name = Gundabad_StartingArmy
	DisplayNameTag = LWA:WildGarrison
	ArmyEntry
		ThingTemplate = WildGundabadBerserkerHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = WildGundabadBerserkerHorde
		Quantity = 1
	End	
End

//-------------------------------------------------------------------------------------------------
// Mordor starting armies
//-------------------------------------------------------------------------------------------------

LivingWorldPlayerArmy
	Name = GothmogPlayerArmy
	DisplayNameTag = LWA:MordorHeroArmy
	ArmyEntry
		ThingTemplate = MordorGothmog
		Quantity = 1
	End	
End

LivingWorldPlayerArmy
	Name = MouthOfSauronArmy
	DisplayNameTag = LWA:MordorHeroArmy
	ArmyEntry
		ThingTemplate = MordorMouthOfSauron
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = UvathaPlayerArmy
	DisplayNameTag = LWA:MordorHeroArmy
	ArmyEntry
		ThingTemplate = MordorUvatha_WOTR
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = WitchKingPlayerArmy
	DisplayNameTag = LWA:MordorHeroArmy
	ArmyEntry
		ThingTemplate = MordorWitchKing_WOTR
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = Mordor_StartingArmy
	DisplayNameTag = LWA:MordorGarrison
	ArmyEntry
		ThingTemplate = MordorFighterHorde_WOTR
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorFighterHorde_WOTR
		Quantity = 1
	End	
	ArmyEntry
		ThingTemplate = MordorArcherHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorPikemanHorde
		Quantity = 1
	End
End	

LivingWorldPlayerArmy
	Name = Serf_StartingArmy
	DisplayNameTag = LWA:MordorGarrison
	ArmyEntry
		ThingTemplate = MordorVariagHorde
		Quantity = 1
	End	
	ArmyEntry
		ThingTemplate = TribalAuxillaryHorde_WOTR
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = AuxillaryArcherHorde
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = Easterling_StartingArmy
	DisplayNameTag = LWA:MordorGarrison
	ArmyEntry
		ThingTemplate = MordorEasterlingHorde
		Quantity = 1
	End	
	ArmyEntry
		ThingTemplate = MordorEasterlingHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingArcherHorde
		Quantity = 1
	End
End	

//-------------------------------------------------------------------------------------------------
// Isengard starting armies
//-------------------------------------------------------------------------------------------------

LivingWorldPlayerArmy
	Name = UglukPlayerArmy
	DisplayNameTag = LWA:IsengardHeroArmy
	ArmyEntry
		ThingTemplate = IsengardUgluk
		Quantity = 1
	End	
End

LivingWorldPlayerArmy
	Name = LurtzPlayerArmy
	DisplayNameTag = LWA:IsengardHeroArmy
	ArmyEntry
		ThingTemplate = IsengardLurtz
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = WulfgarPlayerArmy
	DisplayNameTag = LWA:IsengardHeroArmy
	ArmyEntry
		ThingTemplate = IsengardWulfgar_WOTR
		Quantity = 1
	End
End	

LivingWorldPlayerArmy
	Name = SarumanPlayerArmy
	DisplayNameTag = LWA:IsengardHeroArmy
	ArmyEntry
		ThingTemplate = IsengardSaruman_WOTR
		Quantity = 1
	End	
End	

LivingWorldPlayerArmy
	Name = Isengard_StartingArmy
	DisplayNameTag = LWA:IsengardGarrison
	ArmyEntry
		ThingTemplate = IsengardFighterHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardUrukCrossbowHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardPikemanHorde
		Quantity = 1
	End
End 

//-------------------------------------------------------------------------------------------------
// Dol Guldur starting armies
//-------------------------------------------------------------------------------------------------

LivingWorldPlayerArmy
	Name = KrimpulPlayerArmy
	DisplayNameTag = LWA:GuldurHeroArmy
	ArmyEntry
		ThingTemplate = GuldurKrimpul_WOTR
		Quantity = 1
	End	
End

LivingWorldPlayerArmy
	Name = SaenathraPlayerArmy
	DisplayNameTag = LWA:GuldurHeroArmy
	ArmyEntry
		ThingTemplate = GuldurSaenathra_WOTR
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = GuldurKhamulPlayerArmy
	DisplayNameTag = LWA:GuldurHeroArmy
	ArmyEntry
		ThingTemplate = GuldurKhamul_WOTR
		Quantity = 1
	End
End	

LivingWorldPlayerArmy
	Name = NecromancerPlayerArmy
	DisplayNameTag = LWA:GuldurHeroArmy
	ArmyEntry
		ThingTemplate = GuldurNecromancer_WOTR
		Quantity = 1
	End
End	

LivingWorldPlayerArmy
	Name = Guldur_StartingArmy
	DisplayNameTag = LWA:GuldurGarrison
	ArmyEntry
		ThingTemplate = GuldurOrcPikemanHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GuldurOrcArcherHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GuldurOrcArcherHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GuldurBrokenRabbleHorde_WOTR
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GuldurBrokenRabbleHorde_WOTR
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = Spider_StartingArmy
	DisplayNameTag = LWA:GuldurGarrison
	ArmyEntry
		ThingTemplate = GuldurFellBroodHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GuldurFellBroodHorde
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = EliteGuldur_StartingArmy
	DisplayNameTag = LWA:GuldurGarrison
	ArmyEntry
		ThingTemplate = GuldurOrcRavagerHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GuldurTombGuardHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GuldurWoodsmenHorde
		Quantity = 1
	End
End

//-------------------------------------------------------------------------------------------------
// Angmar starting armies
//-------------------------------------------------------------------------------------------------

;LivingWorldPlayerArmy
;	Name = RogashPlayerArmy
;	DisplayNameTag = LWA:AngmarHeroArmy
;	ArmyEntry
;		ThingTemplate = AngmarRogash
;		Quantity = 1
;	End
;End
;
;LivingWorldPlayerArmy
;	Name = MorgramirPlayerArmy
;	DisplayNameTag = LWA:AngmarHeroArmy
;	ArmyEntry
;		ThingTemplate = AngmarMorgramir
;		Quantity = 1
;	End
;End
;
;LivingWorldPlayerArmy
;	Name = WitchKingArmy
;	DisplayNameTag = LWA:AngmarHeroArmy
;	ArmyEntry
;		ThingTemplate = AngmarWitchking
;		Quantity = 1
;	End
;End
;
;LivingWorldPlayerArmy
;	Name = HwaldarPlayerArmy
;	DisplayNameTag = LWA:AngmarHeroArmy
;	ArmyEntry
;		ThingTemplate = AngmarHwaldar
;		Quantity = 1
;	End
;End
;
;
;LivingWorldPlayerArmy
;	Name = Angmar_StartingArmy
;	DisplayNameTag = LWA:AngmarGarrison
;	ArmyEntry
;		ThingTemplate = AngmarDarkDunedainHorde 
;		Quantity = 1
;	End
;	ArmyEntry
;		ThingTemplate = AngmarDarkRangerHorde 
;		Quantity = 1
;	End
;        ArmyEntry
;                ThingTemplate = AngmarThrallMaster
;                Quantity = 1
;        End
;End    

//-------------------------------------------------------------------------------------------------
// Haradwaith starting armies
//-------------------------------------------------------------------------------------------------

LivingWorldPlayerArmy
	Name = SuladanPlayerArmy
	DisplayNameTag = LWA:HaradwaithHeroArmy
	ArmyEntry
		ThingTemplate = HaradSuladan
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = CassimirPlayerArmy
	DisplayNameTag = LWA:HaradwaithHeroArmy
	ArmyEntry
		ThingTemplate = HaradCassimir
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = BurodapanPlayerArmy
	DisplayNameTag = LWA:HaradwaithHeroArmy
	ArmyEntry
		ThingTemplate = HaradBurodapan
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = GoldenKingPlayerArmy
	DisplayNameTag = LWA:HaradwaithHeroArmy
	ArmyEntry
		ThingTemplate = HaradGoldenKing
		Quantity = 1
	End
End


LivingWorldPlayerArmy
	Name = Angmar_StartingArmy
	DisplayNameTag = LWA:HaradwaithGarrison
	ArmyEntry
		ThingTemplate = HaradWarlord 
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradWarlord 
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradWarlord
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = HaradWarlord
		Quantity = 1
	End
End    


//-------------------------------------------------------------------------------------------------
// Custom armies for the tutorial
//-------------------------------------------------------------------------------------------------

LivingWorldPlayerArmy
	Name = TheodenPlayerArmy_Tutorial
	DisplayNameTag = LWA:MenHeroArmy
	ArmyEntry
		ThingTemplate = RohanTheoden
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanRohirrimHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanRohirrimHorde
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = AragornPlayerArmy_Tutorial		// Aragorn needs to beat the FellBeast1, so make sure this army is stronger
	DisplayNameTag = LWA:MenHeroArmy	
	ArmyEntry
		ThingTemplate = GondorAragornMP
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorRangerHorde
		Quantity = 2
	End
	ArmyEntry
		ThingTemplate = RohanRohirrimHorde
		Quantity = 2
	End
End

LivingWorldPlayerArmy
	Name = BoromirPlayerArmy_Tutorial		// Boromir needs to lose to the WitchKing, so make sure this army is weaker
	DisplayNameTag = LWA:MenHeroArmy	
	ArmyEntry
		ThingTemplate = GondorBoromir
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorFighterHorde
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = MenOfTheWest_Garrison1_Tutorial
	DisplayNameTag = LWA:MenOfTheWestGarrison
	ArmyEntry
		ThingTemplate = GondorArcherHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorTowerShieldGuardHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorTowerShieldGuardHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorKnightHorde
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = WitchKingPlayerArmy_Tutorial
	DisplayNameTag = LWA:MordorHeroArmy
	ArmyEntry
		ThingTemplate = MordorWitchKingOnFellBeast
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorFighterHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHorde
		Quantity = 2
	End
	ArmyEntry
		ThingTemplate = MordorAttackTroll
		Quantity = 2
	End
End

LivingWorldPlayerArmy
	Name = FellBeast1PlayerArmy_Tutorial
	DisplayNameTag = LWA:MordorHeroArmy
	ArmyEntry
		ThingTemplate = MordorFellBeast
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorFighterHorde
		Quantity = 2
	End
End	

LivingWorldPlayerArmy
	Name = FellBeast2PlayerArmy_Tutorial
	DisplayNameTag = LWA:MordorHeroArmy
	ArmyEntry
		ThingTemplate = MordorFellBeast
		Quantity = 1
	End	
	ArmyEntry
		ThingTemplate = MordorAttackTroll
		Quantity = 2
	End
	ArmyEntry
		ThingTemplate = MordorCorsairsOfUmbarHorde
		Quantity = 2
	End
End

LivingWorldPlayerArmy
	Name = Mordor_Garrison1_Tutorial
	DisplayNameTag = LWA:MordorGarrison
	ArmyEntry
		ThingTemplate = MordorFighterHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMountainTroll
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorDrummerTroll
		Quantity = 1
	End
End	


////////////////////////////////////////////////
// Custom armies for the Historical Scenario  //
////////////////////////////////////////////////

//-------------------------------------------------------------------------------------------------
// Elves
//-------------------------------------------------------------------------------------------------

LivingWorldPlayerArmy
	Name = ElvenThranduilArmy_Historical
	DisplayNameTag = LWA:ElvesHeroArmy
	ArmyEntry
		ThingTemplate = ElvenThranduil
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ElvenMirkwoodArcherHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ElvenMirkwoodArcherHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ElvenMirkwoodArcherHorde
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = ElvenElrondArmy_Historical
	DisplayNameTag = LWA:ElvesHeroArmy	
	ArmyEntry
		ThingTemplate = ElvenElrond
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ElvenLorienWarriorHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ElvenRivendellLancerHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ElvenRivendellLancerHorde
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = ElvenHaldirArmy_Historical
	DisplayNameTag = LWA:ElvesHeroArmy	
	ArmyEntry
		ThingTemplate = ElvenHaldir
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ElvenLorienWarriorHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ElvenLorienWarriorHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ElvenLorienArcherHorde
		Quantity = 1
	End
End

LivingWorldPlayerArmy ;;,;; Added for 2.1
	Name = ElvenGlorfindelArmy_Historical
	DisplayNameTag = LWA:ElvesHeroArmy	
	ArmyEntry
		ThingTemplate = ElvenGlorfindel
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = NoldorWarriorHorde
		Quantity = 1
	End
End



//-------------------------------------------------------------------------------------------------
// Men of the West
//-------------------------------------------------------------------------------------------------

LivingWorldPlayerArmy
	Name = MenEomerArmy_Historical ;;,;; MenTheodenArmy_Historical
	DisplayNameTag = LWA:MenHeroArmy
	ArmyEntry
		ThingTemplate = RohanEomer ;;,;; RohanTheoden
		Quantity = 1
        End
	ArmyEntry
		ThingTemplate = RohanRohirrimHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanRohirrimHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanRohirrimHorde
		Quantity = 1
	End
End


LivingWorldPlayerArmy
	Name =  MenAragornArmy_Historical
	DisplayNameTag = LWA:MenHeroArmy
	ArmyEntry
		ThingTemplate = GondorAragornMP
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = MenBoromirArmy_Historical
	DisplayNameTag = LWA:MenHeroArmy
	ArmyEntry
		ThingTemplate = GondorBoromir
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorKnightHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorRangerHorde
		Quantity = 1
	End
	ArmyEntry ;;,;; Added for 2.1
		ThingTemplate = GondorRangerHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorTowerShieldGuardHorde
		Quantity = 1
	End
	ArmyEntry ;;,;; Added for 2.1
		ThingTemplate = GondorTowerShieldGuardHorde
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = MenGarrisonArmy_Historical
	DisplayNameTag = LWA:MenOfTheWestGarrison
	ArmyEntry
		ThingTemplate = GondorArcherHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorFighterHorde
		Quantity = 1
	End
End

//-------------------------------------------------------------------------------------------------
// Dwarves - just use default armies
//-------------------------------------------------------------------------------------------------

//-------------------------------------------------------------------------------------------------
// Isengard
//-------------------------------------------------------------------------------------------------

LivingWorldPlayerArmy
	Name = IsengardSarumanArmy_Historical
	DisplayNameTag = LWA:IsengardHeroArmy
	ArmyEntry
		ThingTemplate = IsengardSaruman
		Quantity = 1
        End
	ArmyEntry
		ThingTemplate = IsengardFighterHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardUrukCrossbowHorde
		Quantity = 1
	End
End


LivingWorldPlayerArmy
	Name = IsengardSharkuArmy_Historical
	DisplayNameTag = LWA:IsengardHeroArmy
	ArmyEntry
		ThingTemplate = IsengardSharku
		Quantity = 1
        End
	ArmyEntry
		ThingTemplate = IsengardWargRiderHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardWargRiderHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardWargRiderHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardWargRiderHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardWargRiderHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardWargRiderHorde
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = IsengardLurtzArmy_Historical
	DisplayNameTag = LWA:IsengardHeroArmy
	ArmyEntry
		ThingTemplate = IsengardLurtz
		Quantity = 1
        End
	ArmyEntry
		ThingTemplate = IsengardFighterHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardFighterHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardFighterHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardUrukCrossbowHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardUrukCrossbowHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardUrukCrossbowHorde
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = IsengardGarrisonArmy_Historical
	DisplayNameTag = LWA:IsengardGarrison
	ArmyEntry
		ThingTemplate = IsengardFighterHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardUrukCrossbowHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardWargRiderHorde
		Quantity = 1
	End
End

//-------------------------------------------------------------------------------------------------
// Mordor starting armies
//-------------------------------------------------------------------------------------------------

LivingWorldPlayerArmy
	Name = MordorWitchKingArmy_Historical
	DisplayNameTag = LWA:MordorHeroArmy
	ArmyEntry
		ThingTemplate = MordorWitchKingOnFellBeast
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorFighterHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMountainTroll
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorAttackTroll
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorDrummerTroll
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = MordorFellBeast1Army_Historical
	DisplayNameTag = LWA:MordorHeroArmy
	ArmyEntry
		ThingTemplate = KhamulFellBeast
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorCorsairsOfUmbarHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorHaradrimArcherHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorHaradrimArcherHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMumakilOld
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMumakilOld
		Quantity = 1
	End
End	

LivingWorldPlayerArmy
	Name = MordorFellBeast2Army_Historical
	DisplayNameTag = LWA:MordorHeroArmy
	ArmyEntry
		ThingTemplate = MordorFellBeast
		Quantity = 1
	End	
	ArmyEntry
		ThingTemplate = MordorFighterHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMountainTroll
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = MordorGarrisonArmy_Historical
	DisplayNameTag = LWA:MordorGarrison
	ArmyEntry
		ThingTemplate = MordorEasterlingHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorEasterlingHorde
		Quantity = 1
	End
End

//-------------------------------------------------------------------------------------------------
// Goblins
//-------------------------------------------------------------------------------------------------
LivingWorldPlayerArmy
	Name = WildDrogothArmy_Historical
	DisplayNameTag = LWA:WildHeroArmy
	ArmyEntry
		ThingTemplate = Drogoth
		Quantity = 1
	End	
	ArmyEntry
		ThingTemplate = GoblinFighterHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinFighterHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinArcherHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinArcherHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinCaveTroll
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinCaveTroll
		Quantity = 1
	End
End	

LivingWorldPlayerArmy
	Name = WildGorkilArmy_Historical
	DisplayNameTag = LWA:WildHeroArmy
	ArmyEntry
		ThingTemplate = WildGoblinKing
		Quantity = 1
	End	
	ArmyEntry
		ThingTemplate = GoblinFighterHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinFighterHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinArcherHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinArcherHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinCaveTroll
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinCaveTroll
		Quantity = 1
	End
End

//-------------------------------------------------------------------------------------------------
// Angmar (for Fall of Arnor scenario)
//-------------------------------------------------------------------------------------------------
LivingWorldPlayerArmy
	Name = AngmarRogashArmy_Historical
	DisplayNameTag = LWA:AngmarHeroArmy
	ArmyEntry
		ThingTemplate = AngmarRogash
		Quantity = 1
	End	
	ArmyEntry
		ThingTemplate = AngmarThrallMaster
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = AngmarDarkDunedainHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = AngmarDarkRangerHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = AngmarHillTrollHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = AngmarSnowTrollHorde
		Quantity = 1
	End
End	

LivingWorldPlayerArmy
	Name = AngmarMorgramirArmy_Historical
	DisplayNameTag = LWA:AngmarHeroArmy
	ArmyEntry
		ThingTemplate = AngmarMorgramir
		Quantity = 1
	End	
	ArmyEntry
		ThingTemplate = AngmarThrallMaster
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = AngmarDarkDunedainHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = AngmarDarkRangerHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = AngmarHillTrollHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = AngmarSnowTrollHorde
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = AngmarWitchKingArmy_Historical
	DisplayNameTag = LWA:AngmarHeroArmy
	ArmyEntry
		ThingTemplate = AngmarWitchking
		Quantity = 1
	End	
	ArmyEntry
		ThingTemplate = AngmarThrallMaster
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = AngmarDarkDunedainHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = AngmarDarkRangerHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = AngmarHillTrollHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = AngmarSnowTrollHorde
		Quantity = 1
	End
End

//-------------------------------------------------------------------------------------------------
// Rohan (for Assault on Rohan scenario - AOTR001)
//-------------------------------------------------------------------------------------------------
LivingWorldPlayerArmy
	Name = RohanTheodenArmy_AOTR001
	DisplayNameTag = LWA:RohanHeroArmy
	ArmyEntry
		ThingTemplate = RohanTheoden
		Quantity = 1
	End	
	ArmyEntry
		ThingTemplate = RohanEowyn_WOTR
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanPeasantHorde
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = RohanEomerArmy_AOTR001
	DisplayNameTag = LWA:RohanHeroArmy
	ArmyEntry
		ThingTemplate = RohanEomer
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanRohirrimHorde
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = RohanTheodredArmy_AOTR001
	DisplayNameTag = LWA:RohanHeroArmy
	ArmyEntry
		ThingTemplate = RohanTheodred
		Quantity = 1
	End	
	ArmyEntry
		ThingTemplate = RohanElfhelm_WOTR
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanRohirrimHorde
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = RohanHelmsDeepArmy_AOTR001
	DisplayNameTag = LWA:RohanGarrison
	ArmyEntry
		ThingTemplate = RohanHelmingasWardenHorde
		Quantity = 1
	End
End

//-------------------------------------------------------------------------------------------------
// Isengard (for Assault on Rohan scenario - AOTR001)
//-------------------------------------------------------------------------------------------------
LivingWorldPlayerArmy
	Name = SarumanPlayerArmy_AOTR001
	DisplayNameTag = LWA:IsengardHeroArmy
	ArmyEntry
		ThingTemplate = IsengardSaruman_WOTR
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardWormTongue_WOTR
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardFighterHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardPikemanHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardUrukCrossbowHorde
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = UglukPlayerArmy_AOTR001
	DisplayNameTag = LWA:IsengardHeroArmy
	ArmyEntry
		ThingTemplate = IsengardUgluk
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardScoutHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardScoutHorde
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = LurtzPlayerArmy_AOTR001
	DisplayNameTag = LWA:IsengardHeroArmy
	ArmyEntry
		ThingTemplate = IsengardLurtz
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardScoutHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardScoutHorde
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = WulfgarPlayerArmy_AOTR001
	DisplayNameTag = LWA:IsengardHeroArmy
	ArmyEntry
		ThingTemplate = IsengardWulfgar_WOTR
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardWildmanHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardWildmanSpearHorde
		Quantity = 1
	End
End

//-------------------------------------------------------------------------------------------------
// Gondor (for Siege of Gondor scenario - AOTR002)
//-------------------------------------------------------------------------------------------------

LivingWorldPlayerArmy
	Name = FaramirPlayerArmy_AOTR002
	DisplayNameTag = LWA:MenHeroArmy
	ArmyEntry
		ThingTemplate = GondorFaramir
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorRangerHorde
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = BoromirPlayerArmy_AOTR002
	DisplayNameTag = LWA:MenHeroArmy
	ArmyEntry
		ThingTemplate = GondorBoromir
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorFighterHorde
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = MinasTirith_StartingArmy_AOTR002
	DisplayNameTag = LWA:MenOfTheWestGarrison
	ArmyEntry
		ThingTemplate = GondorDenethor_WOTR
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorBeregond_WOTR
		Quantity = 1
	End	
End

//-------------------------------------------------------------------------------------------------
// Mordor (for Siege of Gondor scenario - AOTR002)
//-------------------------------------------------------------------------------------------------

LivingWorldPlayerArmy
	Name = GothmogPlayerArmy_AOTR002
	DisplayNameTag = LWA:MordorHeroArmy
	ArmyEntry
		ThingTemplate = MordorGothmog
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorFighterHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHorde
		Quantity = 1
	End	
End

LivingWorldPlayerArmy
	Name = MouthOfSauronArmy_AOTR002
	DisplayNameTag = LWA:MordorHeroArmy
	ArmyEntry
		ThingTemplate = MordorMouthOfSauron
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorFighterHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHorde
		Quantity = 1
	End	
End

LivingWorldPlayerArmy
	Name = WitchKingArmy_AOTR002
	DisplayNameTag = LWA:MordorHeroArmy
	ArmyEntry
		ThingTemplate = MordorWitchKing_WOTR
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = Mordor_StartingArmy_AOTR002
	DisplayNameTag = LWA:MordorGarrison
	ArmyEntry
		ThingTemplate = MordorFighterHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorFighterHorde
		Quantity = 1
	End	
End

//-------------------------------------------------------------------------------------------------
// Good (for AOTR - BFME2 Campaign)
//-------------------------------------------------------------------------------------------------
LivingWorldPlayerArmy
	Name = WotRGoodArmy1
	DisplayNameTag = LWA:WotrGoodArmy1
	ArmyEntry
		ThingTemplate = WotRGoodArmy1
		Quantity = 1
	End	
End

//-------------------------------------------------------------------------------------------------
// Evil (for AOTR - BFME2 Campaign)
//-------------------------------------------------------------------------------------------------
LivingWorldPlayerArmy
	Name = WotREvilArmy1
	DisplayNameTag = LWA:WotrEvilArmy1
	ArmyEntry
		ThingTemplate = WotREvilArmy1
		Quantity = 1
	End	
End

//-------------------------------------------------------------------------------------------------
// Dorwinion starting armies
//-------------------------------------------------------------------------------------------------
LivingWorldPlayerArmy
	Name = DorwinionMorinehtarPlayerArmy
	DisplayNameTag = LWA:DorwinionArmy
	ArmyEntry
		ThingTemplate = Morinehtar
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = Romestamo
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = DorwinionBrandPlayerArmy
	DisplayNameTag = LWA:DorwinionArmy
	ArmyEntry
		ThingTemplate = DwarvenBrand
		Quantity = 1
	End
End