//-------------------------------------------------------------------------------------------------
//	Default settings for RTS battle in WOTR
//-------------------------------------------------------------------------------------------------


SecondsPerReinforcement	= 240		; In RTS: After the first army, each reinforcement army comes into battle 15 minutes later
StartingCashRTS		= 500 ;6000
StartingCashRTSWithFort	= 500 ;3000 ;6000 ;,; 2500 ;;,;; 1500
InitialRevivalCostMultiplier = 1.0 ;;,;; 2.0
InitialRevivalTimeMultiplier = 1.0

#include "LivingWorldVictoryTypes.inc"
