Weather
;; ---------------------------------
;;              SNOW
;; ---------------------------------

SnowEnabled = yes               ; enable/disable snow on the map.
IsSnowing = yes			; is it snowing today?

SnowTexture = EXSnowFlake2.tga	;EXMask.tga	;EXRainDrop.tga

SnowBoxHeight = 500             ; height from which snow falls
SnowSpacing = 60                ; snow spacing -- less means more
NumberTiles = 4

SnowAmplitude = 6             ; amount of side-to-side movement. 
SnowFrequencyScaleX = 0.02         ; speed of side-to-side wave movement.
SnowFrequencyScaleY = 0.02         ; speed of side-to-side wave movement. 

SnowPointSize = 2               ; scale the size of snow particles.
SnowMinPointSize = 5           ; min point size
SnowMaxPointSize = 15           ; max point size

SnowPointSprites = no           ; set to "no" for point-sprite emulation.
SnowQuadSize = 2.5               ; scale the size of snow particles when using point-sprite emulation.
    

SnowSpeed = 90.0               ; speed at which snow falls




HardwareFogColor = R:170 G:185 B:195
	HardwareFogEnable = Yes
	HardwareFogStart = 350
	HardwareFogEnd = 7000
	
	
End


WaterTransparency
  ReflectionPlaneZ = 98.0;
  ReflectionOn = Yes
End


Object Bear
  ReplaceModule ModuleTag_01
  Draw = W3DScriptedModelDraw ModuleTag_Polar
    DefaultModelConditionState
		Model               = CUBear_SKN
    End
    RandomTexture = cupolarbear.tga 0 cubear.tga
   	IdleAnimationState
		StateName					=   STATE_Idle
		Animation = IdleA
			AnimationName       = CUBear_SKL.CUBear_IDLA
			AnimationPriority	= 10
			AnimationMode       = ONCE
			AnimationBlendTime	=	10
		End
		Animation = IdleB
			AnimationName       = CUBear_SKL.CUBear_IDLB
			AnimationPriority	= 10
			AnimationMode       = ONCE
			AnimationBlendTime	=	10
		End
		BeginScript
			Prev = CurDrawablePrevAnimationState()
			if Prev == "STATE_Alert" then CurDrawableSetTransitionAnimState("TRANS_AlertToIdle") end
		EndScript
    End
	AnimationState				= MOVING PANICKING
		Animation				= RUNA
			AnimationName		= CUBear_SKL.CUBear_RUNA
			AnimationMode		= LOOP
		End
		Flags					= RANDOMSTART
	End        	
	AnimationState			=	MOVING
		StateName			=	STATE_moving
		Animation			=	Moving
			AnimationName	=	CUBear_SKL.CUBear_WALKA
			AnimationBlendTime	=	10
			AnimationMustCompleteBlend = yes
		End
		
		BeginScript
			Prev = CurDrawablePrevAnimationState()
			if Prev == "STATE_Alert" then CurDrawableSetTransitionAnimState("TRANS_AlertToIdle") end
		EndScript
		
	End
	TransitionState					=	TRANS_AlertToIdle
		Animation					=   IDLE
			AnimationName			=	CUBear_SKL.CUBear_IDLE
			AnimationMode			=	ONCE
		End
	End		
	TransitionState					=	TRANS_IdleToAlert
		Animation					=   IDLC
			AnimationName			=	CUBear_SKL.CUBear_IDLC
			AnimationMode			=	ONCE
		End
	End			
	AnimationState        = DYING DEATH_1
		Animation           = CUBear_DIEA
  			AnimationName     = CUBear_SKL.CUBear_IDLA
			AnimationMode     = LOOP
		End
	End		
	AnimationState        = DYING
		Animation           = CUBear_DIEA
  			AnimationName     = CUBear_SKL.CUBear_DIEA
			AnimationMode     = ONCE
		End
	End			
 End
 End
 End



	
;startOfAuto-Generation
;------------------------------------------------------------------------;
;	  ARNOR REGION 														 ;
;------------------------------------------------------------------------;
Object Inn
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Arnor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Arnor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Arnor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Arnor
		End
	End
End
Object InnDesert
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Arnor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Arnor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Arnor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Arnor
		End
	End
End
Object InnSnow
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Arnor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Arnor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Arnor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Arnor
		End
	End
End
Object Inn_old
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Arnor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Arnor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Arnor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Arnor
		End
	End
End
;endOfAuto-Generation


;==== Auto Generated AI Fix =====;
SkirmishAIData TheSkirmishAIData
    DisableBaseBuilding        = No
    DisableEconomyBuilding     = No
    DisableUnitBuilding        = No
    DisableScienceUpgrading    = No
    DisableUnitUpgrading       = No
    DisableTacticalAI          = No
    DisableTeamBuilding        = No
    DisableWallBuilding        = Yes ;,; No
End
