;;,;; 2.02e Drake Broodling Drake DoT Breath

;------------------------------------------------------------------------------
 	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BABYDRAKE_FLAME_DAMAGE .143 )
		Radius			= BABYDRAKE_FLAME_RADIUS	; HitStoredTarget means we hurt the person we launched at.  And nobody else.  So a miss hurts nobody.
		DelayTime		= BABYDRAKE_FLAME_DELAY
		DamageType		= FLAME
		DamageFXType		= FLAME
		DeathType		= BURNED
		DamageMaxHeight = 20 ;50	;;,;; 2.3 fix
	End

;------------------------------------------------------------------------------
  	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BABYDRAKE_FLAME_DAMAGE .143 )
		Radius			= BABYDRAKE_FLAME_RADIUS	; HitStoredTarget means we hurt the person we launched at.  And nobody else.  So a miss hurts nobody.
		DelayTime		= 200
		DamageType		= FLAME
		DamageFXType		= FLAME
		DeathType		= BURNED
		DamageMaxHeight = 20 ;50	;;,;; 2.3 fix
	End

;------------------------------------------------------------------------------
  	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BABYDRAKE_FLAME_DAMAGE .143 )
		Radius			= BABYDRAKE_FLAME_RADIUS	; HitStoredTarget means we hurt the person we launched at.  And nobody else.  So a miss hurts nobody.
		DelayTime		= 400
		DamageType		= FLAME
		DamageFXType		= FLAME
		DeathType		= BURNED
		DamageMaxHeight = 20 ;50	;;,;; 2.3 fix
	End

;------------------------------------------------------------------------------
  	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BABYDRAKE_FLAME_DAMAGE .143 )
		Radius			= BABYDRAKE_FLAME_RADIUS	; HitStoredTarget means we hurt the person we launched at.  And nobody else.  So a miss hurts nobody.
		DelayTime		= 600
		DamageType		= FLAME
		DamageFXType		= FLAME
		DeathType		= BURNED
		DamageMaxHeight = 20 ;50	;;,;; 2.3 fix
	End

;------------------------------------------------------------------------------
  	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BABYDRAKE_FLAME_DAMAGE .143 )
		Radius			= BABYDRAKE_FLAME_RADIUS	; HitStoredTarget means we hurt the person we launched at.  And nobody else.  So a miss hurts nobody.
		DelayTime		= 800
		DamageType		= FLAME
		DamageFXType		= FLAME
		DeathType		= BURNED
		DamageMaxHeight = 20 ;50	;;,;; 2.3 fix
	End

;------------------------------------------------------------------------------
  	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BABYDRAKE_FLAME_DAMAGE .143 )
		Radius			= BABYDRAKE_FLAME_RADIUS	; HitStoredTarget means we hurt the person we launched at.  And nobody else.  So a miss hurts nobody.
		DelayTime		= 1000
		DamageType		= FLAME
		DamageFXType		= FLAME
		DeathType		= BURNED
		DamageMaxHeight = 20 ;50	;;,;; 2.3 fix
	End

;------------------------------------------------------------------------------
  	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BABYDRAKE_FLAME_DAMAGE .143 )
		Radius			= BABYDRAKE_FLAME_RADIUS	; HitStoredTarget means we hurt the person we launched at.  And nobody else.  So a miss hurts nobody.
		DelayTime		= 1200
		DamageType		= FLAME
		DamageFXType		= FLAME
		DeathType		= BURNED
		DamageMaxHeight = 20 ;50	;;,;; 2.3 fix
	End