;;,;; 2.02e Balrog DoT Breath

;------------------------------------------------------------------------------
	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BALROG_BREATH_DAMAGE .048 )
		Radius			= BALROG_BREATH_RADIUS
		DamageScalar  = 25% NONE +COMMANDCENTER -GuldurNecromancer -IsengardSaruman -AngmarWitchking -MoriaDurinsBane -HeroBilboBotfa -RohanDraftTower
		DelayTime		= 1000
		DamageType		= FLAME
		DamageFXType		= FLAME
		DeathType		= BURNED
		DamageArc		= 90
		DamageMaxHeight = 20 ;;,;; 50 ;We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
	End

	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BALROG_BREATH_DAMAGE .048 )
		Radius			= BALROG_BREATH_RADIUS
		DamageScalar  = 20% NONE +COMMANDCENTER -GuldurNecromancer -IsengardSaruman -AngmarWitchking -MoriaDurinsBane -HeroBilboBotfa -RohanDraftTower
		DelayTime		= 1000
		DamageType		= MAGIC
		DamageArc		= 90
		DamageMaxHeight = 20 ;;,;; 50 ;We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
    		DamageScalar  = 25000% NONE +MinisGateDoor
	End

;------------------------------------------------------------------------------
	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BALROG_BREATH_DAMAGE .048 )
		Radius			= BALROG_BREATH_RADIUS
		DamageScalar  = 25% NONE +COMMANDCENTER -GuldurNecromancer -IsengardSaruman -AngmarWitchking -MoriaDurinsBane -HeroBilboBotfa -RohanDraftTower
		DelayTime		= 1200
		DamageType		= FLAME
		DamageFXType		= FLAME
		DeathType		= BURNED
		DamageArc		= 90
		DamageMaxHeight = 20 ;;,;; 50 ;We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
	End

	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BALROG_BREATH_DAMAGE .048 )
		Radius			= BALROG_BREATH_RADIUS
		DamageScalar  = 20% NONE +COMMANDCENTER -GuldurNecromancer -IsengardSaruman -AngmarWitchking -MoriaDurinsBane -HeroBilboBotfa -RohanDraftTower
		DelayTime		= 1200
		DamageType		= MAGIC
		DamageArc		= 90
		DamageMaxHeight = 20 ;;,;; 50 ;We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
    		DamageScalar  = 25000% NONE +MinisGateDoor
	End

;------------------------------------------------------------------------------
	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BALROG_BREATH_DAMAGE .048 )
		Radius			= BALROG_BREATH_RADIUS
		DamageScalar  = 25% NONE +COMMANDCENTER -GuldurNecromancer -IsengardSaruman -AngmarWitchking -MoriaDurinsBane -HeroBilboBotfa -RohanDraftTower
		DelayTime		= 1400
		DamageType		= FLAME
		DamageFXType		= FLAME
		DeathType		= BURNED
		DamageArc		= 90
		DamageMaxHeight = 20 ;;,;; 50 ;We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
	End

	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BALROG_BREATH_DAMAGE .048 )
		Radius			= BALROG_BREATH_RADIUS
		DamageScalar  = 20% NONE +COMMANDCENTER -GuldurNecromancer -IsengardSaruman -AngmarWitchking -MoriaDurinsBane -HeroBilboBotfa -RohanDraftTower
		DelayTime		= 1400
		DamageType		= MAGIC
		DamageArc		= 90
		DamageMaxHeight = 20 ;;,;; 50 ;We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
    		DamageScalar  = 25000% NONE +MinisGateDoor
	End

;------------------------------------------------------------------------------
	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BALROG_BREATH_DAMAGE .048 )
		Radius			= BALROG_BREATH_RADIUS
		DamageScalar  = 25% NONE +COMMANDCENTER -GuldurNecromancer -IsengardSaruman -AngmarWitchking -MoriaDurinsBane -HeroBilboBotfa -RohanDraftTower
		DelayTime		= 1600
		DamageType		= FLAME
		DamageFXType		= FLAME
		DeathType		= BURNED
		DamageArc		= 90
		DamageMaxHeight = 20 ;;,;; 50 ;We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
	End

	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BALROG_BREATH_DAMAGE .048 )
		Radius			= BALROG_BREATH_RADIUS
		DamageScalar  = 20% NONE +COMMANDCENTER -GuldurNecromancer -IsengardSaruman -AngmarWitchking -MoriaDurinsBane -HeroBilboBotfa -RohanDraftTower
		DelayTime		= 1600
		DamageType		= MAGIC
		DamageArc		= 90
		DamageMaxHeight = 20 ;;,;; 50 ;We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
    		DamageScalar  = 25000% NONE +MinisGateDoor
	End

;------------------------------------------------------------------------------
	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BALROG_BREATH_DAMAGE .048 )
		Radius			= BALROG_BREATH_RADIUS
		DamageScalar  = 25% NONE +COMMANDCENTER -GuldurNecromancer -IsengardSaruman -AngmarWitchking -MoriaDurinsBane -HeroBilboBotfa -RohanDraftTower
		DelayTime		= 1800
		DamageType		= FLAME
		DamageFXType		= FLAME
		DeathType		= BURNED
		DamageArc		= 90
		DamageMaxHeight = 20 ;;,;; 50 ;We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
	End

	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BALROG_BREATH_DAMAGE .048 )
		Radius			= BALROG_BREATH_RADIUS
		DamageScalar  = 20% NONE +COMMANDCENTER -GuldurNecromancer -IsengardSaruman -AngmarWitchking -MoriaDurinsBane -HeroBilboBotfa -RohanDraftTower
		DelayTime		= 1800
		DamageType		= MAGIC
		DamageArc		= 90
		DamageMaxHeight = 20 ;;,;; 50 ;We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
    		DamageScalar  = 25000% NONE +MinisGateDoor
	End

;------------------------------------------------------------------------------
	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BALROG_BREATH_DAMAGE .048 )
		Radius			= BALROG_BREATH_RADIUS
		DamageScalar  = 25% NONE +COMMANDCENTER -GuldurNecromancer -IsengardSaruman -AngmarWitchking -MoriaDurinsBane -HeroBilboBotfa -RohanDraftTower
		DelayTime		= 2000
		DamageType		= FLAME
		DamageFXType		= FLAME
		DeathType		= BURNED
		DamageArc		= 90
		DamageMaxHeight = 20 ;;,;; 50 ;We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
	End

	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BALROG_BREATH_DAMAGE .048 )
		Radius			= BALROG_BREATH_RADIUS
		DamageScalar  = 20% NONE +COMMANDCENTER -GuldurNecromancer -IsengardSaruman -AngmarWitchking -MoriaDurinsBane -HeroBilboBotfa -RohanDraftTower
		DelayTime		= 2000
		DamageType		= MAGIC
		DamageArc		= 90
		DamageMaxHeight = 20 ;;,;; 50 ;We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
    		DamageScalar  = 25000% NONE +MinisGateDoor
	End

;------------------------------------------------------------------------------
	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BALROG_BREATH_DAMAGE .048 )
		Radius			= BALROG_BREATH_RADIUS
		DamageScalar  = 25% NONE +COMMANDCENTER -GuldurNecromancer -IsengardSaruman -AngmarWitchking -MoriaDurinsBane -HeroBilboBotfa -RohanDraftTower
		DelayTime		= 2200
		DamageType		= FLAME
		DamageFXType		= FLAME
		DeathType		= BURNED
		DamageArc		= 90
		DamageMaxHeight = 20 ;;,;; 50 ;We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
	End

	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BALROG_BREATH_DAMAGE .048 )
		Radius			= BALROG_BREATH_RADIUS
		DamageScalar  = 20% NONE +COMMANDCENTER -GuldurNecromancer -IsengardSaruman -AngmarWitchking -MoriaDurinsBane -HeroBilboBotfa -RohanDraftTower
		DelayTime		= 2200
		DamageType		= MAGIC
		DamageArc		= 90
		DamageMaxHeight = 20 ;;,;; 50 ;We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
    		DamageScalar  = 25000% NONE +MinisGateDoor
	End

;------------------------------------------------------------------------------
	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BALROG_BREATH_DAMAGE .048 )
		Radius			= BALROG_BREATH_RADIUS
		DamageScalar  = 25% NONE +COMMANDCENTER -GuldurNecromancer -IsengardSaruman -AngmarWitchking -MoriaDurinsBane -HeroBilboBotfa -RohanDraftTower
		DelayTime		= 2400
		DamageType		= FLAME
		DamageFXType		= FLAME
		DeathType		= BURNED
		DamageArc		= 90
		DamageMaxHeight = 20 ;;,;; 50 ;We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
	End

	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BALROG_BREATH_DAMAGE .048 )
		Radius			= BALROG_BREATH_RADIUS
		DamageScalar  = 20% NONE +COMMANDCENTER -GuldurNecromancer -IsengardSaruman -AngmarWitchking -MoriaDurinsBane -HeroBilboBotfa -RohanDraftTower
		DelayTime		= 2400
		DamageType		= MAGIC
		DamageArc		= 90
		DamageMaxHeight = 20 ;;,;; 50 ;We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
    		DamageScalar  = 25000% NONE +MinisGateDoor
	End

;------------------------------------------------------------------------------
	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BALROG_BREATH_DAMAGE .048 )
		Radius			= BALROG_BREATH_RADIUS
		DamageScalar  = 25% NONE +COMMANDCENTER -GuldurNecromancer -IsengardSaruman -AngmarWitchking -MoriaDurinsBane -HeroBilboBotfa -RohanDraftTower
		DelayTime		= 2600
		DamageType		= FLAME
		DamageFXType		= FLAME
		DeathType		= BURNED
		DamageArc		= 90
		DamageMaxHeight = 20 ;;,;; 50 ;We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
	End

	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BALROG_BREATH_DAMAGE .048 )
		Radius			= BALROG_BREATH_RADIUS
		DamageScalar  = 20% NONE +COMMANDCENTER -GuldurNecromancer -IsengardSaruman -AngmarWitchking -MoriaDurinsBane -HeroBilboBotfa -RohanDraftTower
		DelayTime		= 2600
		DamageType		= MAGIC
		DamageArc		= 90
		DamageMaxHeight = 20 ;;,;; 50 ;We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
    		DamageScalar  = 25000% NONE +MinisGateDoor
	End

;------------------------------------------------------------------------------
	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BALROG_BREATH_DAMAGE .048 )
		Radius			= BALROG_BREATH_RADIUS
		DamageScalar  = 25% NONE +COMMANDCENTER -GuldurNecromancer -IsengardSaruman -AngmarWitchking -MoriaDurinsBane -HeroBilboBotfa -RohanDraftTower
		DelayTime		= 2800
		DamageType		= FLAME
		DamageFXType		= FLAME
		DeathType		= BURNED
		DamageArc		= 90
		DamageMaxHeight = 20 ;;,;; 50 ;We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
	End

	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BALROG_BREATH_DAMAGE .048 )
		Radius			= BALROG_BREATH_RADIUS
		DamageScalar  = 20% NONE +COMMANDCENTER -GuldurNecromancer -IsengardSaruman -AngmarWitchking -MoriaDurinsBane -HeroBilboBotfa -RohanDraftTower
		DelayTime		= 2800
		DamageType		= MAGIC
		DamageArc		= 90
		DamageMaxHeight = 20 ;;,;; 50 ;We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
    		DamageScalar  = 25000% NONE +MinisGateDoor
	End

;------------------------------------------------------------------------------
	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BALROG_BREATH_DAMAGE .048 )
		Radius			= BALROG_BREATH_RADIUS
		DamageScalar  = 25% NONE +COMMANDCENTER -GuldurNecromancer -IsengardSaruman -AngmarWitchking -MoriaDurinsBane -HeroBilboBotfa -RohanDraftTower
		DelayTime		= 3000
		DamageType		= FLAME
		DamageFXType		= FLAME
		DeathType		= BURNED
		DamageArc		= 90
		DamageMaxHeight = 20 ;;,;; 50 ;We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
	End

	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BALROG_BREATH_DAMAGE .048 )
		Radius			= BALROG_BREATH_RADIUS
		DamageScalar  = 20% NONE +COMMANDCENTER -GuldurNecromancer -IsengardSaruman -AngmarWitchking -MoriaDurinsBane -HeroBilboBotfa -RohanDraftTower
		DelayTime		= 3000
		DamageType		= MAGIC
		DamageArc		= 90
		DamageMaxHeight = 20 ;;,;; 50 ;We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
    		DamageScalar  = 25000% NONE +MinisGateDoor
	End

;------------------------------------------------------------------------------
	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BALROG_BREATH_DAMAGE .048 )
		Radius			= BALROG_BREATH_RADIUS
		DamageScalar  = 25% NONE +COMMANDCENTER -GuldurNecromancer -IsengardSaruman -AngmarWitchking -MoriaDurinsBane -HeroBilboBotfa -RohanDraftTower
		DelayTime		= 3200
		DamageType		= FLAME
		DamageFXType		= FLAME
		DeathType		= BURNED
		DamageArc		= 90
		DamageMaxHeight = 20 ;;,;; 50 ;We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
	End

	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BALROG_BREATH_DAMAGE .048 )
		Radius			= BALROG_BREATH_RADIUS
		DamageScalar  = 20% NONE +COMMANDCENTER -GuldurNecromancer -IsengardSaruman -AngmarWitchking -MoriaDurinsBane -HeroBilboBotfa -RohanDraftTower
		DelayTime		= 3200
		DamageType		= MAGIC
		DamageArc		= 90
		DamageMaxHeight = 20 ;;,;; 50 ;We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
    		DamageScalar  = 25000% NONE +MinisGateDoor
	End

;------------------------------------------------------------------------------
	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BALROG_BREATH_DAMAGE .048 )
		Radius			= BALROG_BREATH_RADIUS
		DamageScalar  = 25% NONE +COMMANDCENTER -GuldurNecromancer -IsengardSaruman -AngmarWitchking -MoriaDurinsBane -HeroBilboBotfa -RohanDraftTower
		DelayTime		= 3400
		DamageType		= FLAME
		DamageFXType		= FLAME
		DeathType		= BURNED
		DamageArc		= 90
		DamageMaxHeight = 20 ;;,;; 50 ;We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
	End

	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BALROG_BREATH_DAMAGE .048 )
		Radius			= BALROG_BREATH_RADIUS
		DamageScalar  = 20% NONE +COMMANDCENTER -GuldurNecromancer -IsengardSaruman -AngmarWitchking -MoriaDurinsBane -HeroBilboBotfa -RohanDraftTower
		DelayTime		= 3400
		DamageType		= MAGIC
		DamageArc		= 90
		DamageMaxHeight = 20 ;;,;; 50 ;We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
    		DamageScalar  = 25000% NONE +MinisGateDoor
	End

;------------------------------------------------------------------------------
	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BALROG_BREATH_DAMAGE .048 )
		Radius			= BALROG_BREATH_RADIUS
		DamageScalar  = 25% NONE +COMMANDCENTER -GuldurNecromancer -IsengardSaruman -AngmarWitchking -MoriaDurinsBane -HeroBilboBotfa -RohanDraftTower
		DelayTime		= 3600
		DamageType		= FLAME
		DamageFXType		= FLAME
		DeathType		= BURNED
		DamageArc		= 90
		DamageMaxHeight = 20 ;;,;; 50 ;We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
	End

	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BALROG_BREATH_DAMAGE .048 )
		Radius			= BALROG_BREATH_RADIUS
		DamageScalar  = 20% NONE +COMMANDCENTER -GuldurNecromancer -IsengardSaruman -AngmarWitchking -MoriaDurinsBane -HeroBilboBotfa -RohanDraftTower
		DelayTime		= 3600
		DamageType		= MAGIC
		DamageArc		= 90
		DamageMaxHeight = 20 ;;,;; 50 ;We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
    		DamageScalar  = 25000% NONE +MinisGateDoor
	End

;------------------------------------------------------------------------------
	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BALROG_BREATH_DAMAGE .048 )
		Radius			= BALROG_BREATH_RADIUS
		DamageScalar  = 25% NONE +COMMANDCENTER -GuldurNecromancer -IsengardSaruman -AngmarWitchking -MoriaDurinsBane -HeroBilboBotfa -RohanDraftTower
		DelayTime		= 3800
		DamageType		= FLAME
		DamageFXType		= FLAME
		DeathType		= BURNED
		DamageArc		= 90
		DamageMaxHeight = 20 ;;,;; 50 ;We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
	End

	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BALROG_BREATH_DAMAGE .048 )
		Radius			= BALROG_BREATH_RADIUS
		DamageScalar  = 20% NONE +COMMANDCENTER -GuldurNecromancer -IsengardSaruman -AngmarWitchking -MoriaDurinsBane -HeroBilboBotfa -RohanDraftTower
		DelayTime		= 3800
		DamageType		= MAGIC
		DamageArc		= 90
		DamageMaxHeight = 20 ;;,;; 50 ;We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
    		DamageScalar  = 25000% NONE +MinisGateDoor
	End

;------------------------------------------------------------------------------
	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BALROG_BREATH_DAMAGE .048 )
		Radius			= BALROG_BREATH_RADIUS
		DamageScalar  = 25% NONE +COMMANDCENTER -GuldurNecromancer -IsengardSaruman -AngmarWitchking -MoriaDurinsBane -HeroBilboBotfa -RohanDraftTower
		DelayTime		= 4000
		DamageType		= FLAME
		DamageFXType		= FLAME
		DeathType		= BURNED
		DamageArc		= 90
		DamageMaxHeight = 20 ;;,;; 50 ;We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
	End

	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BALROG_BREATH_DAMAGE .048 )
		Radius			= BALROG_BREATH_RADIUS
		DamageScalar  = 20% NONE +COMMANDCENTER -GuldurNecromancer -IsengardSaruman -AngmarWitchking -MoriaDurinsBane -HeroBilboBotfa -RohanDraftTower
		DelayTime		= 4000
		DamageType		= MAGIC
		DamageArc		= 90
		DamageMaxHeight = 20 ;;,;; 50 ;We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
    		DamageScalar  = 25000% NONE +MinisGateDoor
	End

;------------------------------------------------------------------------------
	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BALROG_BREATH_DAMAGE .048 )
		Radius			= BALROG_BREATH_RADIUS
		DamageScalar  = 25% NONE +COMMANDCENTER -GuldurNecromancer -IsengardSaruman -AngmarWitchking -MoriaDurinsBane -HeroBilboBotfa -RohanDraftTower
		DelayTime		= 4200
		DamageType		= FLAME
		DamageFXType		= FLAME
		DeathType		= BURNED
		DamageArc		= 90
		DamageMaxHeight = 20 ;;,;; 50 ;We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
	End

	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BALROG_BREATH_DAMAGE .048 )
		Radius			= BALROG_BREATH_RADIUS
		DamageScalar  = 20% NONE +COMMANDCENTER -GuldurNecromancer -IsengardSaruman -AngmarWitchking -MoriaDurinsBane -HeroBilboBotfa -RohanDraftTower
		DelayTime		= 4200
		DamageType		= MAGIC
		DamageArc		= 90
		DamageMaxHeight = 20 ;;,;; 50 ;We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
    		DamageScalar  = 25000% NONE +MinisGateDoor
	End

;------------------------------------------------------------------------------
	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BALROG_BREATH_DAMAGE .048 )
		Radius			= BALROG_BREATH_RADIUS
		DamageScalar  = 25% NONE +COMMANDCENTER -GuldurNecromancer -IsengardSaruman -AngmarWitchking -MoriaDurinsBane -HeroBilboBotfa -RohanDraftTower
		DelayTime		= 4400
		DamageType		= FLAME
		DamageFXType		= FLAME
		DeathType		= BURNED
		DamageArc		= 90
		DamageMaxHeight = 20 ;;,;; 50 ;We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
	End

	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BALROG_BREATH_DAMAGE .048 )
		Radius			= BALROG_BREATH_RADIUS
		DamageScalar  = 20% NONE +COMMANDCENTER -GuldurNecromancer -IsengardSaruman -AngmarWitchking -MoriaDurinsBane -HeroBilboBotfa -RohanDraftTower
		DelayTime		= 4400
		DamageType		= MAGIC
		DamageArc		= 90
		DamageMaxHeight = 20 ;;,;; 50 ;We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
    		DamageScalar  = 25000% NONE +MinisGateDoor
	End

;------------------------------------------------------------------------------
	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BALROG_BREATH_DAMAGE .048 )
		Radius			= BALROG_BREATH_RADIUS
		DamageScalar  = 25% NONE +COMMANDCENTER -GuldurNecromancer -IsengardSaruman -AngmarWitchking -MoriaDurinsBane -HeroBilboBotfa -RohanDraftTower
		DelayTime		= 4600
		DamageType		= FLAME
		DamageFXType		= FLAME
		DeathType		= BURNED
		DamageArc		= 90
		DamageMaxHeight = 20 ;;,;; 50 ;We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
	End

	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BALROG_BREATH_DAMAGE .048 )
		Radius			= BALROG_BREATH_RADIUS
		DamageScalar  = 20% NONE +COMMANDCENTER -GuldurNecromancer -IsengardSaruman -AngmarWitchking -MoriaDurinsBane -HeroBilboBotfa -RohanDraftTower
		DelayTime		= 4600
		DamageType		= MAGIC
		DamageArc		= 90
		DamageMaxHeight = 20 ;;,;; 50 ;We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
    		DamageScalar  = 25000% NONE +MinisGateDoor
	End

;------------------------------------------------------------------------------
	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BALROG_BREATH_DAMAGE .048 )
		Radius			= BALROG_BREATH_RADIUS
		DamageScalar  = 25% NONE +COMMANDCENTER -GuldurNecromancer -IsengardSaruman -AngmarWitchking -MoriaDurinsBane -HeroBilboBotfa -RohanDraftTower
		DelayTime		= 4800
		DamageType		= FLAME
		DamageFXType		= FLAME
		DeathType		= BURNED
		DamageArc		= 90
		DamageMaxHeight = 20 ;;,;; 50 ;We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
	End

	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BALROG_BREATH_DAMAGE .048 )
		Radius			= BALROG_BREATH_RADIUS
		DamageScalar  = 20% NONE +COMMANDCENTER -GuldurNecromancer -IsengardSaruman -AngmarWitchking -MoriaDurinsBane -HeroBilboBotfa -RohanDraftTower
		DelayTime		= 4800
		DamageType		= MAGIC
		DamageArc		= 90
		DamageMaxHeight = 20 ;;,;; 50 ;We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
    		DamageScalar  = 25000% NONE +MinisGateDoor
	End

;------------------------------------------------------------------------------
	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BALROG_BREATH_DAMAGE .048 )
		Radius			= BALROG_BREATH_RADIUS
		DamageScalar  = 25% NONE +COMMANDCENTER -GuldurNecromancer -IsengardSaruman -AngmarWitchking -MoriaDurinsBane -HeroBilboBotfa -RohanDraftTower
		DelayTime		= 5000
		DamageType		= FLAME
		DamageFXType		= FLAME
		DeathType		= BURNED
		DamageArc		= 90
		DamageMaxHeight = 20 ;;,;; 50 ;We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
	End

	DamageNugget                        ; A basic Nugget that just does damage
		Damage			= #MULTIPLY( BALROG_BREATH_DAMAGE .048 )
		Radius			= BALROG_BREATH_RADIUS
		DamageScalar  = 20% NONE +COMMANDCENTER -GuldurNecromancer -IsengardSaruman -AngmarWitchking -MoriaDurinsBane -HeroBilboBotfa -RohanDraftTower
		DelayTime		= 5000
		DamageType		= MAGIC
		DamageArc		= 90
		DamageMaxHeight = 20 ;;,;; 50 ;We won't hurt something far above us.  Birds fly at around 100
		DamageSpeed		= 400
    		DamageScalar  = 25000% NONE +MinisGateDoor
	End
