Weather

	HardwareFogColor = R:165 G:180 B:180
	HardwareFogEnable = Yes
	HardwareFogStart = 500
	HardwareFogEnd = 6000
	
End


WaterTransparency
  ReflectionPlaneZ = 88.0;
  ReflectionOn = Yes
End

Object CINE_ParticleSysProxy3

  ; *** ART Parameters ***
 ReplaceModule ModuleTag_01
  Draw = W3DScriptedModelDraw ModuleTag_01_Override
    DefaultModelConditionState
      Model = NONE
      ParticleSysBone = emberBone LeavesFalling
      ParticleSysBone = None None;FireSmokeBig
    End
  
    ModelConditionState = WORLD_BUILDER
	  Model = locator
	End
  End
 End
End

FXParticleSystem LeavesFalling
  System
    Priority = ALWAYS_RENDER
	Shader = ALPHA
    ParticleName = EXLeaf01.tga
    Lifetime = 150 300; 100 200
    SortLevel = 1
    Size = 1.5 2.5; 0.1 0.2
    BurstDelay = 80 140
    BurstCount = 5 30; 3 5
  End
 
  Color = DefaultColor
    Color1 = R:230 G:135 B:45 0; R:255 G:185 B:79 0
    ;Color2 = R:105 G:92 B:68 100; R:0 G:0 B:0 200
    ColorScale = 2 -2
  End
  
    Alpha = DefaultAlpha
    Alpha1 = 0 0 10; 0.1 0.3 50
    Alpha2 = 1 1 50; 0 0 350
	Alpha3 = 1 1 300; 0 0 350
	Alpha4 = 0 0 180; 0 0 350
  End
  Update = DefaultUpdate
    SizeRate = 0 0
    SizeRateDamping = 0 0
    AngleZ = 0 360
    AngularRateZ = 50 300
    AngularDamping = 0.8 0.9
    AngularDampingXY = .7 .9
  End
  Physics = DefaultPhysics
    Gravity = -0.3
    VelocityDamping = 0.6 0.8
    DriftVelocity = X:0.2 Y:0.15 Z:-0.2; X:0 Y:0 Z:0.64
  End
  EmissionVelocity = OutwardEmissionVelocity
  Speed = 2 4
     ; X = 0 0
     ; Y = 0 0
    ; Z = -1 -0.5
  End
  EmissionVolume = CylinderEmissionVolume
    Radius = 75; 7
    Length = 5; 1
  End
  Draw = DefaultDraw
  End
  Wind = DefaultWind
    WindMotion = PingPong

    WindStrength = 0.55; 0.25
    WindFullStrengthDist = 5
    WindZeroStrengthDist = 100
    WindAngleChangeMin = 0.034907
    WindAngleChangeMax = 0.034907
    WindPingPongStartAngleMin = 1.22173
    WindPingPongStartAngleMax = 1.22173
    WindPingPongEndAngleMin = 1.91986
    WindPingPongEndAngleMax = 1.91986
    TurbulenceAmplitude = 0.5
    TurbulenceFrequency = 10
  End
End

Object CINE_ParticleSysProxy2

  ; *** ART Parameters ***
 ReplaceModule ModuleTag_01
  Draw = W3DScriptedModelDraw ModuleTag_01_Override
    DefaultModelConditionState
      Model = NONE
      ParticleSysBone = emberBone LightSunRays
      ParticleSysBone = None None;FireSmokeBig
    End
  
    ModelConditionState = WORLD_BUILDER
	  Model = locator
	End
  End
 End
End

;startOfAuto-Generation
;------------------------------------------------------------------------;
;	  ERIADOR REGION 														 ;
;------------------------------------------------------------------------;
Object Inn
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Eriador
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Eriador
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Eriador
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Eriador
		End
	End
End
Object InnDesert
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Eriador
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Eriador
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Eriador
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Eriador
		End
	End
End
Object InnSnow
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Eriador
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Eriador
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Eriador
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Eriador
		End
	End
End
Object Inn_old
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Eriador
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Eriador
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Eriador
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Eriador
		End
	End
End
;endOfAuto-Generation



;==== Auto Generated AI Fix =====;
SkirmishAIData TheSkirmishAIData
    DisableBaseBuilding        = No
    DisableEconomyBuilding     = No
    DisableUnitBuilding        = No
    DisableScienceUpgrading    = No
    DisableUnitUpgrading       = No
    DisableTacticalAI          = No
    DisableTeamBuilding        = No
    DisableWallBuilding        = Yes ;,; No
End
