WaterTransparency
  ReflectionPlaneZ = 12.0;
  ReflectionOn = Yes
End

;------------------------------------------------------------------------------

Weather
  HardwareFogColor = R:216 G:198 B:161
  HardwareFogEnable = Yes
  HardwareFogStart = 800
  HardwareFogEnd = 12000
End

;------------------------------------------------------------------------------

Object AotRHaradCliffB01
 
  Geometry              = BOX
  GeometryMajorRadius   = 0.001
  GeometryMinorRadius   = 0.001
  GeometryHeight        = 0.001
  GeometryIsSmall       = No
  Shadow                = SHADOW_VOLUME
  BuildCompletion     = PLACED_BY_PLAYER
End

;------------------------------------------------------------------------------

Object AotRHaradCliffB02
  Geometry              = BOX
  GeometryMajorRadius   = 0.001
  GeometryMinorRadius   = 0.001
  GeometryHeight        = 0.001
  GeometryIsSmall       = No
  Shadow                = SHADOW_VOLUME
  BuildCompletion     = PLACED_BY_PLAYER
End

;------------------------------------------------------------------------------

Object AotRHaradCliffB03
  Geometry              = BOX
  GeometryMajorRadius   = 0.001
  GeometryMinorRadius   = 0.001
  GeometryHeight        = 0.001
  GeometryIsSmall       = No
  Shadow                = SHADOW_VOLUME
  BuildCompletion     = PLACED_BY_PLAYER
End

;------------------------------------------------------------------------------

Object AotRHaradCliffB04
  Geometry              = BOX
  GeometryMajorRadius   = 0.001
  GeometryMinorRadius   = 0.001
  GeometryHeight        = 0.001
  GeometryIsSmall       = No
  Shadow                = SHADOW_VOLUME
  BuildCompletion     = PLACED_BY_PLAYER
End

;------------------------------------------------------------------------------

Object AotRHaradCliffB05
  Geometry              = BOX
  GeometryMajorRadius   = 0.001
  GeometryMinorRadius   = 0.001
  GeometryHeight        = 0.001
  GeometryIsSmall       = No
  Shadow                = SHADOW_VOLUME
  BuildCompletion     = PLACED_BY_PLAYER
End

;------------------------------------------------------------------------------

Object AotRHaradCliffB06
  Geometry              = BOX
  GeometryMajorRadius   = 0.001
  GeometryMinorRadius   = 0.001
  GeometryHeight        = 0.001
  GeometryIsSmall       = No
  Shadow                = SHADOW_VOLUME
  BuildCompletion     = PLACED_BY_PLAYER
End

;------------------------------------------------------------------------------

Object AotRHaradCliffB07
  Geometry              = BOX
  GeometryMajorRadius   = 0.001
  GeometryMinorRadius   = 0.001
  GeometryHeight        = 0.001
  GeometryIsSmall       = No
  Shadow                = SHADOW_VOLUME
  BuildCompletion     = PLACED_BY_PLAYER
End

;------------------------------------------------------------------------------

Object AotRHaradCliffB08
  Geometry              = BOX
  GeometryMajorRadius   = 0.001
  GeometryMinorRadius   = 0.001
  GeometryHeight        = 0.001
  GeometryIsSmall       = No
  Shadow                = SHADOW_VOLUME
  BuildCompletion     = PLACED_BY_PLAYER
End

;------------------------------------------------------------------------------

Object AotRHaradCliffB09
  Geometry              = BOX
  GeometryMajorRadius   = 0.001
  GeometryMinorRadius   = 0.001
  GeometryHeight        = 0.001
  GeometryIsSmall       = No
  Shadow                = SHADOW_VOLUME
  BuildCompletion     = PLACED_BY_PLAYER
End

;------------------------------------------------------------------------------

Object AotRHaradCliffB10
  Geometry              = BOX
  GeometryMajorRadius   = 0.001
  GeometryMinorRadius   = 0.001
  GeometryHeight        = 0.001
  GeometryIsSmall       = No
  Shadow                = SHADOW_VOLUME
  BuildCompletion     = PLACED_BY_PLAYER
End

;------------------------------------------------------------------------------



  ObjectReskin HorseGrazing3 HorseGrazing
  ; *** ART Parameters ***

	ReplaceModule ModuleTag_01
	Draw = W3DScriptedModelDraw ModuleTag_Desert

		RandomTexture = nuhorse03desert.tga 0 nuhorse03.tga 

	;RandomTexture = NUHorse01.tga 0 cuhorse_bnwta.tga
	;RandomTexture = NUHorse02.tga 0 cuhorse_bnwta.tga
	;RandomTexture = NUHorse03.tga 0 cuhorse_bnwta.tga
	;RandomTexture = NUHorse04.tga 0 cuhorse_bnwta.tga
	;RandomTexture = NUHorse05.tga 0 cuhorse_bnwta.tga
	;RandomTexture = NUHorse06.tga 0 cuhorse_bnwta.tga
  
    DefaultModelConditionState
		Model               = NuHorse3_SKN
    End
   	IdleAnimationState
		StateName					=   STATE_Idle
		Animation = IdleA
			AnimationName       = NUHorse_SKL.NUHorse_GRZA
			AnimationPriority	= 10
			AnimationMode       = ONCE
		End
		Animation = IdleB
			AnimationName       = NUHorse_SKL.NUHorse_GRZB
			AnimationPriority	= 10
			AnimationMode       = ONCE
		End
		BeginScript
			Prev = CurDrawablePrevAnimationState()
			if Prev == "STATE_moving" then CurDrawableSetTransitionAnimState("TRANS_MovingToIdle") end
		EndScript
    End

; REMOVED - Ugly      
;	AnimationState			=	MOVING TURN_LEFT
;		StateName			=	STATE_moving
;		Animation
;			AnimationName	=	NUHorse_SKL.NUHorse_TRNL
;			AnimationMode   =	LOOP		
;			AnimationBlendTime	=	15	
;			AnimationMustCompleteBlend = yes
;		End
;		BeginScript
;			Prev = CurDrawablePrevAnimationState()
;			if Prev == "STATE_Idle" then CurDrawableSetTransitionAnimState("TRANS_IdletoMoving") end
;		EndScript
;	End

;	AnimationState			=	MOVING TURN_RIGHT
;		StateName			=	STATE_moving
;		Animation
;			AnimationName	=	NUHorse_SKL.NUHorse_TRNR
;			AnimationMode   =	LOOP	
;			AnimationBlendTime	=	15	
;			AnimationMustCompleteBlend = yes		
;		End
;		BeginScript
;			Prev = CurDrawablePrevAnimationState()
;			if Prev == "STATE_Idle" then CurDrawableSetTransitionAnimState("TRANS_IdletoMoving") end
;		EndScript
;	End	

; REMOVED - Not Used	
;	AnimationState			=	MOVING WANDER
;		StateName			=	STATE_moving
;		Animation			=	Moving
;			AnimationName	=	NUHorse_SKL.NUHorse_WLKA
;			AnimationBlendTime	=	20
;			AnimationMustCompleteBlend = yes
;		End
;		BeginScript
;			Prev = CurDrawablePrevAnimationState()
;			if Prev == "STATE_Idle" then CurDrawableSetTransitionAnimState("TRANS_IdletoMoving") end
;		EndScript
;	End

	AnimationState				= MOVING PANICKING
		Animation				= RUNA
			AnimationName		= NUHorse_SKL.NUHorse_RUNA
			AnimationMode		= LOOP
		End
		Flags					= RANDOMSTART
	End    
		
	AnimationState			=	MOVING
		StateName			=	STATE_moving
		Animation			=	Moving
			AnimationName	=	NUHorse_SKL.NUHorse_WLKA
			AnimationBlendTime	=	10
			AnimationMustCompleteBlend = yes
		End
		BeginScript
			Prev = CurDrawablePrevAnimationState()
			if Prev == "STATE_Idle" then CurDrawableSetTransitionAnimState("TRANS_IdletoMoving") end
		EndScript
	End
	
	TransitionState					=	TRANS_MovingToIdle
		Animation					=   DWNA
			AnimationName			=	NUHorse_SKL.NUHorse_DWNA
			AnimationMode			=	ONCE
		End
	End	
	
	TransitionState					=	TRANS_IdletoMoving
		Animation					=   UPA
			AnimationName			=	NUHorse_SKL.NUHorse_UPA
			AnimationMode			=	ONCE
		End
	End
	
	AnimationState        = DYING
		Animation           = DIEA
  			AnimationName     = NUHorse_SKL.NUHorse_DIEA
			AnimationMode     = ONCE
		End
	End	
 End
 End
End








;startOfAuto-Generation
;------------------------------------------------------------------------;
;	#################### WAR OF THE RING SETTINGS ####################   ;
;   - Upgrade_WOTRMode is now used to deal with WOTR commandsets         ;
;------------------------------------------------------------------------;
;-------------------
;	GONDOR
;-------------------
PlayerTemplate FactionMen
	StartMoney        				= 0
	SpellBookMp						= MenSpellBook_WOTR
	PurchaseScienceCommandSetMP		= MenSpellStoreCommandSet_WOTR
	InitialUpgrades					= Upgrade_MenFaction Upgrade_WOTRMode
	BuildableHeroesMP				= CreateAHero GondorPippin_WOTR GondorForlong_WOTR GondorBeregond_WOTR GondorImrahil_WOTR GondorDenethor_WOTR GondorFaramir GondorBoromir GondorGandalf_WOTR
End

;-------------------
;	ROHAN
;-------------------
PlayerTemplate FactionRohan
	StartMoney        				= 0
	SpellBookMp						= RohanSpellBook_WOTR
	PurchaseScienceCommandSetMP		= RohanSpellStoreCommandSet_WOTR
	InitialUpgrades					= Upgrade_RohanFaction Upgrade_WOTRMode
	BuildableHeroesMP				= CreateAHero RohanMerry_WOTR RohanEowyn_WOTR RohanElfhelm_WOTR RohanErkenbrand RohanTheodred RohanEomer RohanTheoden
End

;-------------------
;	LOTHLORIEN
;-------------------
PlayerTemplate FactionElves
	StartMoney        				= 0
	SpellBookMp						= ElvesSpellBook_WOTR
	PurchaseScienceCommandSetMP		= ElvesSpellStoreCommandSet_WOTR
	InitialUpgrades					= Upgrade_ElfFaction Upgrade_WOTRMode
	BuildableHeroesMP				= CreateAHero ElvenOrophin_WOTR ElvenRumil ElvenIdrial_WOTR ElvenHaldir ElvenCeleborn ElvenGaladrielLorien_WOTR MirkwoodThranduil_NCS
End

;-------------------
;	RIVENDELL
;-------------------
PlayerTemplate FactionArnor
	StartMoney        				= 0
	SpellBookMp						= ArnorSpellBook_WOTR
	PurchaseScienceCommandSetMP		= ArnorSpellStoreCommandSet_WOTR
	InitialUpgrades					= Upgrade_ArnorFaction Upgrade_WOTRMode	
	BuildableHeroesMP				= CreateAHero ArnorFattyBolger_WOTR ArnorFarmerMaggot_WOTR ElvenArwen_WOTR ElvenGildor ElvenElladan_WOTR ElvenElrohir_WOTR ArnorHalbarad_WOTR ElvenAragorn ElvenGlorfindel_WOTR ElvenElrond_WOTR
End

;-------------------
;	MIRKWOOD
;-------------------
PlayerTemplate FactionMirkwood
	StartMoney        				= 0
	SpellBookMp						= MirkwoodSpellBook_WOTR
	PurchaseScienceCommandSetMP		= MirkwoodSpellStoreCommandSet_WOTR
	InitialUpgrades					= Upgrade_MirkwoodFaction Upgrade_WOTRMode	
	BuildableHeroesMP				= CreateAHero MirkwoodTauriel MirkwoodGalion_WOTR MirkwoodFeren DorwinionFrumgar_WOTR MirkwoodRadagast_WOTR MirkwoodGrimbeorn_WOTR MirkwoodLegolas MirkwoodThranduil
End

;-------------------
;	EREBOR
;-------------------
PlayerTemplate FactionDwarves
	StartMoney        				= 0
	SpellBookMp						= DwarvesSpellBook_WOTR
	PurchaseScienceCommandSetMP		= DwarvesSpellStoreCommandSet_WOTR
	InitialUpgrades					= Upgrade_DwarfFaction Upgrade_WOTRMode	
	BuildableHeroesMP				= CreateAHero DwarvenArcah_WOTR DwarvenGloin_WOTR DwarvenHadhod_WOTR DwarvenBrand_WOTR DwarvenGimli_WOTR DwarvenThorinStonehelm_WOTR DwarvenKingDain_WOTR YoungThorin_WOTR DwarvenThrain_WOTR YoungDain_WOTR YoungDwalin_WOTR YoungBalin_WOTR
End

;-------------------
;	MORDOR
;-------------------
PlayerTemplate FactionMordor
	StartMoney        				= 0
	SpellBookMp						= MordorSpellBook_WOTR
	PurchaseScienceCommandSetMP		= MordorSpellStoreCommandSet_WOTR
	InitialUpgrades					= Upgrade_MordorDualEconomyChoice Upgrade_MordorFaction Upgrade_EvilDualEconomyChoice Upgrade_WOTRMode
	BuildableHeroesMP				= CreateAHero MordorGorbag_WOTR MordorShagrat_WOTR MordorAkhorahil_WOTR MordorUvatha_WOTR  MordorGothmog MordorMouthOfSauron MordorMollok_WOTR MordorWitchKing_WOTR RhunBelokhZa_WOTR RhunKhrenTak_WOTR RhunVahRus_WOTR
End

;-------------------
;	ISENGARD
;-------------------
PlayerTemplate FactionIsengard
	StartMoney        				= 0
	SpellBookMp						= IsengardSpellBook_WOTR
	PurchaseScienceCommandSetMP		= IsengardSpellStoreCommandSet_WOTR
	InitialUpgrades					= Upgrade_IsengardDualEconomyChoice Upgrade_IsengardFaction Upgrade_EvilDualEconomyChoice Upgrade_WOTRMode
	BuildableHeroesMP				= CreateAHero IsengardGrishnakh_WOTR IsengardWormTongue_WOTR IsengardSharku_WOTR IsengardUgluk IsengardLurtz IsengardWulfgar_WOTR IsengardSaruman_WOTR
End

;-------------------
;	MISTY MOUNTAINS
;-------------------
PlayerTemplate FactionWild
	StartMoney        				= 0
	SpellBookMp						= WildSpellBook_WOTR
	PurchaseScienceCommandSetMP		= WildSpellStoreCommandSet_WOTR
	InitialUpgrades					= Upgrade_WildFaction Upgrade_GoblinDualEconomyChoice Upgrade_EvilDualEconomyChoice Upgrade_WOTRMode	
	BuildableHeroesMP				= CreateAHero WildMuzgash WildGolfimbul_WOTR WildUrshak WildLugtheMauled_WOTR WildGreatGoblin WildBolgNew_WOTR WildTrueAzog_WOTR
End

;-------------------
;	DOL GULDUR
;-------------------
PlayerTemplate FactionGuldur
	StartMoney        				= 0
	SpellBookMp						= GuldurSpellBook_WOTR
	PurchaseScienceCommandSetMP		= GuldurSpellStoreCommandSet_WOTR
	InitialUpgrades					= Upgrade_GuldurFaction Upgrade_MordorDualEconomyChoice Upgrade_EvilDualEconomyChoice Upgrade_WOTRMode
	BuildableHeroesMP				= CreateAHero GuldurThrain_WOTR GuldurKrimpul_WOTR GuldurCargast_WOTR GuldurSaenathra_WOTR GuldurKhamul_WOTR GuldurNecromancer_WOTR
End

;-------------------
;	HARADWAITH
;-------------------
PlayerTemplate FactionAngmar
	StartMoney        				= 0
	SpellBookMp						= AngmarSpellBook_WOTR
	PurchaseScienceCommandSetMP		= AngmarSpellStoreCommandSet_WOTR
	InitialUpgrades					= Upgrade_AngmarFaction Upgrade_WOTRMode
	BuildableHeroesMP				= CreateAHero HaradBeruthiel_WOTR HaradSyarRhul_WOTR HaradSuladan HaradBurodapan HaradCassimir HaradCaranLambar_WOTR HaradGoldenKing
End

SkirmishAIData TheSkirmishAIData
    DisableBaseBuilding        = No
    DisableEconomyBuilding    = Yes
    DisableUnitBuilding        = No
    DisableScienceUpgrading = No
    DisableUnitUpgrading    = No
    DisableTacticalAI        = No
    DisableTeamBuilding        = No
    DisableWallBuilding        = Yes ;,; No

    AnyTypeTemplateDisabledSlots = 1
    AnyTypeTemplateDisabledSlots = 2
    AnyTypeTemplateDisabledSlots = 3
    AnyTypeTemplateDisabledSlots = 4
    AnyTypeTemplateDisabledSlots = 5
    AnyTypeTemplateDisabledSlots = 6
End
;------------------------------------------------------------------------;
;	  HARAD REGION 														 ;
;------------------------------------------------------------------------;
Object Inn
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Harad
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Harad
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Harad
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Harad
		End
	End	
End
Object InnDesert
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Harad
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Harad
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Harad
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Harad
		End
	End
End
Object InnSnow
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Harad
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Harad
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Harad
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Harad
		End
	End
End
Object Inn_old
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Harad
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Harad
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Harad
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Harad
		End
	End
End
;endOfAuto-Generation
