WaterTransparency
  ReflectionPlaneZ = 98.0;
  ReflectionOn = Yes
End


Object CINE_ParticleSysProxy4

  ; *** ART Parameters ***
 ReplaceModule ModuleTag_01
  Draw = W3DScriptedModelDraw ModuleTag_01_Override
    DefaultModelConditionState
      Model = NONE
      ParticleSysBone = emberBone FlowerPollen; campfireEmbers
      ParticleSysBone = None None;FireSmokeBig
    End
  
    ModelConditionState = WORLD_BUILDER
	  Model = locator
	End
  End
 End
End


FXParticleSystem FogMist;FXParticleSystem CINECampfireEmbers;ground fog

  System
    Priority = VERY_LOW_OR_ABOVE
	Shader = ALPHA
    ParticleName = EXCloud02.tga; EXCineSparks.tga
    Lifetime = 150 150
    SortLevel = 1
    Size = .8 1
    BurstDelay = 10 20; 1 10
    BurstCount = 8 15; 3 5
  End
 
  Color = DefaultColor
    Color1 = R:185 G:185 B:185 0; R:205 G:192 B:168 0; R:255 G:185 B:79 0
    ;Color2 = R:105 G:92 B:68 50; R:0 G:0 B:0 200
    ;ColorScale = 2 -2
  End
    Alpha = DefaultAlpha
    ;Alpha1 = 0 0 50
	Alpha2 = 0.05 0.05 50; 0.1 0.1 50
    Alpha3 = 0 0 120; 150
  End
  Update = DefaultUpdate
    SizeRate = 1 3; 1 3
    SizeRateDamping = 0.9 0.99
    ;AngularRateZ = -0.02 0.02
    ;AngularDamping = 1 1
    ;AngularDampingXY = 1 1
  End
  Physics = DefaultPhysics
    ;Gravity = -0.008
    VelocityDamping = 0.95 0.99
    DriftVelocity = X:0.2 Y:0.-2 Z:0.08; X:0 Y:0 Z:0.64
  End
  EmissionVelocity = OrthoEmissionVelocity
  X = .5 1
  Y = -1 1
  Z = 0 0.1
	End
  EmissionVolume = CylinderEmissionVolume
    Radius = 120
	Length = 2
	Offset = X:0 Y:0 Z:20
  End
  Draw = DefaultDraw
  End
  Wind = DefaultWind
    WindMotion = PingPong

    WindStrength = 0.25; 0.25
    WindFullStrengthDist = 5
    WindZeroStrengthDist = 100
    WindAngleChangeMin = 0.034907
    WindAngleChangeMax = 0.034907
    WindPingPongStartAngleMin = 1.22173
    WindPingPongStartAngleMax = 1.22173
    WindPingPongEndAngleMin = 1.91986
    WindPingPongEndAngleMax = 1.91986
    TurbulenceAmplitude = 0.2
    TurbulenceFrequency = 50
  End
End


;startOfAuto-Generation
;------------------------------------------------------------------------;
;	  ARNOR REGION 														 ;
;------------------------------------------------------------------------;
Object Inn
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Arnor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Arnor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Arnor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Arnor
		End
	End
End
Object InnDesert
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Arnor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Arnor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Arnor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Arnor
		End
	End
End
Object InnSnow
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Arnor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Arnor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Arnor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Arnor
		End
	End
End
Object Inn_old
	ReplaceModule ModuleTag_CommandSetGondor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetGondor_Arnor
			TriggeredBy	= Upgrade_MenFaction Upgrade_RohanFaction Upgrade_DwarfFaction Upgrade_ElfFaction Upgrade_ArnorFaction Upgrade_MirkwoodFaction
			CommandSet	= CommandSetInnGoodFaction_Arnor
		End
	End
	ReplaceModule ModuleTag_CommandSetMordor
		Behavior = CommandSetUpgrade ModuleTag_CommandSetMordor_Arnor
			TriggeredBy	= Upgrade_MordorFaction Upgrade_AngmarFaction Upgrade_GuldurFaction Upgrade_WildFaction Upgrade_IsengardFaction
			CommandSet	= CommandSetInnEvilFaction_Arnor
		End
	End
End
;endOfAuto-Generation




;==== Auto Generated AI Fix =====;
SkirmishAIData TheSkirmishAIData
    DisableBaseBuilding        = No
    DisableEconomyBuilding     = No
    DisableUnitBuilding        = No
    DisableScienceUpgrading    = No
    DisableUnitUpgrading       = No
    DisableTacticalAI          = No
    DisableTeamBuilding        = No
    DisableWallBuilding        = Yes ;,; No
End
